### ISSUE TITLE
Organizational Discussion

### ISSUE THREAD

**Issue by rschroll** [pdfpc/pdfpc#1]
Hi all,

Over in davvil/pdfpc#86, we discussed forking pdfpc in order to try to get it back into shape.  This is that effort.  Right now, we are @davvil, @andybarry, and myself.  But I'd love for others to join the process.  If you're interested in joining "officially" (whatever that means), please comment here.  Or feel free to create pull requests.

I've never tried to set up a community like this, so I don't know exactly what needs to be done.  I'll create a few umbrella bugs to cover the big tasks that we're interested in attacking.  Please comment there if you have any ideas, and feel free to create your own bugs.

There are a few more administrative type things that need discussion.  I list them below, along with my opinions on them.  This is intended to start a discussion, not lay down the law, so if you disagree, please say so!

Pull Requests
-----------------
I live in fear of committing stupid mistakes to public repos, so I like to have someone else look over my code first.  I recommend that we all make pull requests and have them approved by another devel before merging our work in.  Not only does this prevent silly mistakes, it also helps us all understand how the code's changing.

I don't want this to become a bureaucratic mess, though.  Reviewers don't have to go through all the code with a fine-toothed comb -- just check that the general outline seems reasonable.  There's no need to create a pull request for small, obviously correct bug fixes, either.  There's a danger of this slowing things down too much, so I'd say that two days of silence from everyone else should count as an "approve" vote.

(And to reiterate my point above, this is just my prejudice -- if this seems bad to you, please say so!)

Revision History
--------------------
I'm a big fan of keeping "logical history", as opposed to "actual history", in git.  That is, I like to squash WIP commits together and then rebase them on top of master before merging them in.  I feel it's more useful to have changes grouped by function than to know exactly what the state of a bunch of branches was on a particular date.

However, the other projects I've worked on collaboratively have had a strong central repository and generally worked with patches, not branches.  So I'm not sure that this model will work with Github's pull request system.  I'd like to hear what others think about this.

Code Architecture
-----------------------
The pdfpc code base is, in my opinion, somewhat over-engineered.  There are a lot of namespaces, interfaces, base classes, and signal passing.  When I first worked on the code, I thought this was how Vala was done, but having worked on another Vala project, that's not generally the case.  (Now I expect that the original author was exposed to too much Java.)

In implementing the movie code, I started to remove some of these layers.  I would encourage this to continue, in general.  That said, what's here does work, so I'm not suggesting we go in and rip out code just to rip out code.  But if you're working on something and think, "This would be easier if I removed that indirection", go for it!

Code Style
--------------
There is no consistent code style using in pdfpc.  In general, I follow the make-it-look-like-the-surrounding-code coding style, but that's hard to do here.  I've worked on another Vala project with Yorba, and I generally agree with their [coding style](https://wiki.gnome.org/Apps/Geary/CodingConventions).  My recommendation would be to use that for new code and gradually fix the existing code as the spirit moves us.

There are a few places where I might want to break from Yorba's conventions, though:

* Yorba forbids `this` unless it is needed for disambiguation.  The current code uses `this` pretty extensively, and I think it helps you understand at a glance what's internal and external.  I'd be happy to make `this` mandatory.  But let's be sure to go one way or the other.

* Yorba forbids using `using`.  I'd allow it only for internal namespaces, since pdfpc uses them so much.  But Vala's implicit namespace rules may allow us to avoid this most of the time.

----

I hope this wall of text hasn't scared anyone off.  I don't mean to turn this into a whole mess of bureaucracy; I'm just hoping to get everyone on the same page.  I'm also not dogmatic about any of these points.  If I'm wrong, tell me!

**Comment by andybarry** [comment]
Awesome, sounds great.  Overall I agree with everything you've written.  A few things will be new for me (squashing commits, vala style) but they are things I should catch up on anyway.  My research group works with the same pull request model you've outline here and it's great.  I'll plan to work in my own fork and pull request here.

Thank you for taking the lead on this part!  I was about to go file some bugs as we discussed, but I see you've already done it!  I'll take a look and comment on some so we can get started coding.

Lastly -- as @rschroll said, any and all welcome to join us!

**Comment by davvil** [comment]
Hi! I'm still alive! @rschroll, great idea founding the community, as I certainly was not able to maintain pdfpc properly :(

I'm afraid I won't be able to contribute much (as has become apparent). Having moved away from academia I hardly use pdfpc any more, and "real life" doesn't allow me to have too many side projects. But I will certainly follow the development and see if I can somehow help.

I agree with nearly all the points listed above, although as this was my only project with vala, I cannot give much feedback on code style. Wrt. to merging vs rebasing, I personally prefer the "real history", as it indirectly groups related commits in separate branches in the history (and with few developers it's easy to follow). But that is a matter of taste.

What I'm a bit more afraid of is rewriting the history when rebasing: can I commit my work in progress to my local github repo (e.g. for working at different computers) and afterwards do the rebase in order to prepare the pull request? Or the modification of the history when rebasing will do my local repo and my github repo incompatible?

**Comment by andybarry** [comment]
@davvil great to hear from you!  Happy to have your support for this and any help you can provide!  I'll let @rschroll answer the rebasing question since I also have worked mostly with full history.

**Comment by Beuh** [comment]
Hi guys,

As I said already, I love this software so I'd be happy to participate as well. I'm quite at ease with programming in general, but not really accustomed to collaborative projects and details of use of git, so I might do a few mistakes in the beginning ..

**Comment by rschroll** [comment]
@davvil: Good to hear that you're doing okay.  I added you to the group 
since I thought you might be interested in seeing where this goes.  But 
we don't expect anything from you, so contribute as much or as little 
as you like.  And if this leads to too many emails, you can remove 
yourself without making the rest of us feel bad.

@Beuh: I've added you to the team.  If you're not feeling confident at 
git right now, maybe don't make any commits to the shared repository 
right away.  But please participate in all other ways.  We're all happy 
to merge your pull requests, and after one or two, I'm sure you'll pick 
up how the process works.

Re history format:
The way I do "logical history" is to keep a WIP branch.  This can be on 
your own machine, in your own github, or a branch in the org's repo.  
Commit onto that, merge master in, etc.  When it's ready, I rebase the 
branch onto master and squash the commits into several logical commits. 
 Then I do a fast-forward merge into master.  Note that the rebasing 
should only happen on a private branch -- don't (force) push it to any 
public branch.

The obvious problem with this is it leaves any public WIP branches 
unmerged.  If you do the rebasing in a branch linked to a public 
branch, you end up with a divergence.  The benefit is that you can get 
one idea per commit, instead of having that idea spread out between 
several commits, where you happened to notice the bits of it.  It gives 
you a chance to rewrite commit messages once everything's complete and 
you have a better grasp of what's important.  You also get a better 
chance of having the tree compile and run at every commit, which helps 
in bisection.

I prefer this in part because I've done a bit of work through bugzilla 
via patches.  Since patches may get modified and applied in different 
orders, rebasing my local branch to stay on top of the remote one is 
natural.  But it seems like both @davvil and @andybarry aren't used to 
this style, and it's not such a great fit for Github's pull requests, 
so I'm willing to be outvoted here.  Let me know.

Re coding style:
I'm leaning towards breaking with the Yorba style and requiring the 
explicit "this" keyword.  Any thoughts?

**Comment by rschroll** [comment]
Two other style decisions to make:

1) Commit messages

I like starting with a single line (< 80 chars) stating an overview of 
the change.  Start with a capital letter, no period at the end.  
Imperative voice ("Fix the frobitzer").  This is followed by as many 
paragraphs as necessary (perhaps 0) to explain why the change was done 
this way.  The what should be apparent from the diff, although you may 
need to clarify tricky points.

This is the style my existing commits use, but there's no consistency 
among the other commits.  If you prefer a different style, we can use 
that.

2) White space

There should be no tabs.  There should be no trailing whitespace, 
except perhaps in white-space-only lines.  I actually can never decide 
on this point.  On the one hand, I like being able to just place my 
cursor on a blank line and start typing at the proper indent.  On the 
other, I like to be able to just strip all trailing white space and 
call it a day.  What do you guys think?

However we decide, one of the first things we should do is fix the 
existing white space errors, so we don't have to worry about them in 
when we fix other code.

Let me know your preferences.

**Comment by andybarry** [comment]
Commit message style sounds good.  I'll try to work on that as I move forward.

I'm a big fan of no extra whitespace.  That way I can set my editor to zap things on save and be done with it.  Otherwise I end up with lines with the wrong amount of whitespace and it's annoying and we have to worry about it.

And most editors will do the right thing pretty fast when you start typing, so that doesn't bother me too much (although I agree is occationally annoying too.)

No tabs :)

**Comment by AndreasBilke** [comment]
I also would like to join the team.

For the coding style I have no particular opinion except that I like whitespaces for indention and trailing whitespaces are terrible.

I would prefer the "logical history" since I like the idea behind it. But I have never used such collaborative style before, but I am willing to learn something new.

**Comment by rschroll** [comment]
Welcome!

I think the jury is still out on whether the logical history will work 
for us or not, but we'll give it a bit longer before we make a change.

**Comment by AndreasBilke** [comment]
I have a organizational question regarding to pull requests. @rschroll pushed his gtk3 branch (with rebase magic) to the pdfpc master. But what happens with his pull request? Shall this be closed if the commits are on master?

**Comment by rschroll** [comment]
Yeah, I guess I messed this up slightly.  I did a little rebasing of 
the gtk3 branch, and rather than push that branch and then merge it 
into master, I just did the merge locally and pushed only the new 
master.  I didn't consider that this wouldn't close the pull request 
automatically.

Actually, that leads to another point: I like doing fast-forward merges 
where possible, but github avoids them completely.  Do you guys like to 
see the explicit merge commit in the tree, or do you like the simple 
tree generated by fast-forwarding?  (Or do you just not care?)

**Comment by AndreasBilke** [comment]
I like the way you did it with the gtk3 branch. These "Merge pull request"
commit messages get on my nerves. I just wondered why the gtk3 pull request
is still open but the commits are on master.

**Comment by andybarry** [comment]
I personally like the "merge pull request" commits because they let me easily go back to the pull request if I'm wondering what happened at that point.  Often the pull request has lots of useful discussion to explain why we did what.

**Comment by andybarry** [comment]
I just created two labels:
- waiting for review
- waiting for changes

I'm thinking we can use these to track where pull requests are.  So for example, I just updated #10, so it's "waiting for review" from one of you guys.  When that label is there, it means, "take a look and if you're happy, merge it."

If there are changes you'd like made on the request, then swap to the "waiting for changes" label, so it's clear that we're not going to merge the request until something has changed.  Seems like it's a useful thing, but if we don't end up liking it, no worries.

**Comment by davvil** [comment]
One thing I should do is point from my repo to the new one. Any recommendations about the best way to do that? I expect I would update my README.rst to point to the new repo and similarly with the webpage. Is the webpage of the pdfpc organization already available?

**Comment by AndreasBilke** [comment]
@davvil no, but if it's okay for you, we can copy your page and modify everything we need.

**Comment by rschroll** [comment]
@davvil: One thing you could do is modify your repository's description 
to point to the organization's repository.

But yeah, we should get a quick webpage for the org up, and change our 
README to point to that.

**Comment by davvil** [comment]
Done, my description now points to this repo.

**Comment by AndreasBilke** [comment]
I think we finished creating a new maintainer team for pdfpc. If there are new things to discuss, we can create new issues.
