### ISSUE TITLE
Add minimized control & maximized presentation

### ISSUE THREAD

**Issue by susobaco** [pdfpc/pdfpc#100]
Hi, I want to know if you can do this: start a presentation with the -w. The control window is too small. The display window goes maximized by the secondary monitor. For me it is fundamental, and I do a presentation and at the same time want to control the lights with Q Light Controler Plus. Thank you

**Comment by AndreasBilke** [comment]
Actually I don't understand your problem/use case. Why do you need to run
in windowed mode? This window mode is more or less a debug mode. If you
need to control other programs during presentation, you can use your window
manager features to switch applications and bring others to foreground.

**Comment by susobaco** [comment]
Thanks for your reply. I think I have explained wrong. I use LXDE Trisquel pdfpc and when I run the expanded desktop monitors the two running full screen and no windows. On the secondary monitor, the display is full screen. Right, but in the control monitor, I can not do more because pdfpc small window is full, I have buttons maximize window minimize, out, etc.

**Comment by andybarry** [comment]
I'm not quite sure if this will help, but you could try the ````-Z```` (--size) option.  Otherwise, could you post a screenshot with some annotations describing what you are trying to do?

**Comment by susobaco** [comment]
![2015-11-19-091826_2560x1024_scrot](https://cloud.githubusercontent.com/assets/5635692/11265691/bdda108e-8e9e-11e5-85aa-6202999356e9.png)

This is the screenshot when the presentation begins. Both the main screen and in high school, the program is maximized. I can not access the other running programs. What interests me is that the secondary display is maximized (presentation) and the main no. As the screenshot with LibreOffice.

![2015-11-19-092405_2560x1024_scrot](https://cloud.githubusercontent.com/assets/5635692/11265777/56340d6c-8e9f-11e5-8273-bff5f12ae881.png)

**Comment by rschroll** [comment]
If I'm understanding correctly, you'd like the presenter window (on the 
left) running in windowed mode and the presentation window (on the 
right) running full screen.  This would be feasible to implement as an 
option, but I already worry about the number we have.


Unfortunately, the current architecture locks the window size from the 
start.  It'd be nice if this could be changed while pdfpc is running.  
This would allow us to implement a real-time switch from windowed to 
full-screen mode, which strikes me as a better solution than yet 
another command-line switch.  #22 started playing with this.

In the meantime, I'll second Andreas's suggestion: Use your window 
manager to switch between the presenter window and whatever other tools 
you need.  In Gnome Shell, for example, I can Alt-Tab or use the 
overview to switch windows on my main screen while leaving the 
presentation undisturbed on the external monitor.  If your window 
manager doesn't support this, get a better one. :)

**Comment by susobaco** [comment]
I am using openbox. I realized that the name of the windows (obxprop | grep _OB_APP *) is the same for the primary and secondary window. If they had different name, I could set openbox that will maximize the monitor 2 etc, etc, would be a possible solution (I do well on VLC). Can you do that, rename windows? - Thanks

**Comment by AndreasBilke** [comment]
Both windows already have a different title. Do you mean that?

**Comment by susobaco** [comment]
Attached a picture of the output of the command.
![2015-12-01-095901_2560x1024_scrot](https://cloud.githubusercontent.com/assets/5635692/11496495/97d970aa-9812-11e5-8967-dc394c3be6ca.png)

**Comment by AndreasBilke** [comment]
What is the output of?:

pdfpc --version

pdfpc should have different titles and different roles starting at v4.0.

**Comment by einhander** [comment]
xprop should give different role for pdfpc 3+

**Comment by susobaco** [comment]
the program does not have this option,
sudo dpkg -s pdf-presenter-console | grep  'Version'
Version: 3.1.1-2
should I build higher, or there is a PPA?

**Comment by AndreasBilke** [comment]
You can try build it on your own. Just to check that everything works.
