### ISSUE TITLE
Custom layout of the presenter screen

### ISSUE THREAD

**Issue by fhgd** [pdfpc/pdfpc#101]
Ideally my presenter screen should look like follows:
- the note page from latex beamer should be the main window (upper left)
- instead of the overlay thumbnails (I don't use them) I want use the field for manually typed notes (pdfpc notes) in order to remember of a interesting  discussion during or after the talk
- the real actual slide should be in the upper right
- the next slide should be below in the lower right

Is this possible to implement, maybe with a css style file or so?

**Comment by rschroll** [comment]
On Fri, Nov 20, 2015 at 1:20 PM, fhgd <notifications@github.com> wrote:
> Is this possible to implement, maybe with a css style file or so?

Possible?  Yes.  Easy?  Not really.

All the elements in the presenter are separate GTK widgets, and they 
are laid out as specified in presenter.vala.  Rearranging them will 
take more than a CSS fix.  If we wanted this to be user-modifiable, the 
best approach would probably be to define the interface in a GTKBuilder 
XML file and let the user replace that at run time.  But that would 
open up a whole other can of worms.

**Comment by cristobaltapia** [comment]
I would also like something like this. But if this super-user-modifiable option is to complex, it would help at least to be able to see on the right side the current slide instead of the next one, when using beamer notes. This really confuses me when using the beamer notes and maybe it wouldn't be so hard to implement.

**Comment by AndreasBilke** [comment]
#268 tackles some configuration options. A freely configurable layout is (for me) out of scope.
