### ISSUE TITLE
Move some command line options to a config file

### ISSUE THREAD

**Issue by AndreasBilke** [pdfpc/pdfpc#103]
We are at a point, where it gets really difficult to find names/shortcuts for new command line switches. Some of these switches are per-pc permanent. For example current-size, current-height, next-height, overview-min-size, size are not changed with every pdfpc startup. Even disable-cache, disable-compression, black-on-end are not changed very often. With #102 there might be a need for even more command line switches.

To save shortcut-namespace, we can move these permanent pdfpc config options to the pdfpcrc file.

**Comment by andybarry** [comment]
I was just thinking about this -- it might be nice to do some of them as a per-pdf thing.  Perhaps we could encode something in the PDF metadata?  For example,

````-l, --last-minutes=N          Time in minutes, from which on the timer changes its color. (Default 5 minutes)````

is really a per-presentation thing.  Perhaps we can add a simple latex command that would encode that into the PDF.

Thoughts?

**Comment by AndreasBilke** [comment]
I think this is what the .pdfpc file is for. But yes, some options are per
pdf and some are permanent user changes.

The only thing I am worried about is the workflow for per-pdf settings. The
user has to specify some per-pdf settings via command line in the first
place, then we could save that setting in the pdfpc file. But for end users
this behaviour might not be transparent enough.

The permanent changes are no problems I think. The user opens his config
file, save his changes and go on. He is permanently aware what his actions
do.

Some auto-saving magic for per-pdf changes are not that clear.

**Comment by rschroll** [comment]
We already save some command line options into the pdfpc file.  
Duration is the one I happen to know about offhand; I haven't checked 
for others.  This is a rather weird behavior, IMO.  We generally don't 
expect command line options to result in permanent behavior changes.  
It's also not clear how to undo those changes from the command line.

Re embedding options in PDF metadata: It could be interesting to bring 
pdfpc-latex-notes into the project and add commands that could set 
other options in the pdfpc file.  Perhaps we could even find a way to 
store the pdfpc file within the PDF file as metadata.  This of course 
leads to a greater problem of integrating all the places where options 
can be set.

**Comment by AndreasBilke** [comment]
But saving permanent options (like next-view-size) into a config file is
okay for you?

This could be some easy change and it would be clear for the user what
happens (and how to undo it).

**Comment by andybarry** [comment]
Merged to master.
