### ISSUE TITLE
Looping movies with stop set is broken

### ISSUE THREAD

**Issue by andybarry** [pdfpc/pdfpc#104]
As described in #42, looping when a stop time is set does not work.

I worked on this for a while today but wasn't able to come up with a perfect fix.  

Attempt 1: I can tell gstreamer to loop the segment, which works correctly.  But, that means we can't let the user seek past the ````stoptime```` (gstreamer treats that as EOS).

Attempt 2: Attach a gstreamer pad and probe to the stream, read the time, and then seek from in there.  The result broken in a similar to what we already have, except it does throw fewer nasty looking things when GST_DEBUG=4 is set (environment variable).

I don't understand why what we're already doing, or what the pad/probe solution is doing fails to cause the stream to seek correctly.  If @AndreasBilke also doesn't know, it might be time to ask the gstreamer mailing list.

Alternatively, if folks are OK giving up being able to seek in parts other than between the start/stop times, that's pretty easy to do.

**Comment by AndreasBilke** [comment]
I don't know how gstreamer works at all, I think @rschroll is the one with
most of the gstreamer experience.

**Comment by rschroll** [comment]
Yeah, I'm the one to blame for the gstreamer stuff.  That doesn't mean 
that I understand it any more than anyone else.  Do you have your work 
in branches?  I can take a look and see if I see anything obvious.  
Don't get your hopes up, though....

**Comment by andybarry** [comment]
Attempt 2 is here, but please forgive the ridiculous debug print statements :)

https://github.com/andybarry/pdfpc/tree/end_time_loop_fix

I didn't save Attempt 1, but it would be easy to get back if we decide that's what we want to do.
