### ISSUE TITLE
Notes in .tex are not displayed in pdfpc

### ISSUE THREAD

**Issue by Eisenbarth** [pdfpc/pdfpc#105]
Hello,

the notes that I have in a .tex file are not displayed in the notes area of pdfpc. Is there a way to have this feature working ? Is it a bug ? Or maybe I'm doing something wrong ... 

Here is an example file : 
```latex
\documentclass{beamer}

\begin{document}

    \begin{frame}
        I am an example
        \note{Note 1}
        
    \end{frame}
    
    \begin{frame}
        I am an example (bis)
        \note{Note 2}
    \end{frame}
    
\end{document}
```

Thank you in advance

**Comment by einhander** [comment]
Have you tried to add to preamble
````
\usepackage{pgfpages}
\setbeameroption{show notes on second screen=bottom} % 
````
And start pdfpc with option:
pdfpc -n bottom your.pdf

**Comment by Eisenbarth** [comment]
I tried and it makes something strange.

Here is a screenshot : https://www.anony.ws/image/JZdV

The important slide is on bottom while the notes are on top. I expected more something like the notes we can add by typing 'n' in pdfpc.

**Comment by AndreasBilke** [comment]
Your screenshot shows exaclty what --notes should do.

> I expected more something like the notes we can add by typing 'n' in pdfpc.

This is not easy. pdfpc can't (or don't) parse the pdf to filter out notes
from pdf pages.

Maybe you are interessted in https://github.com/cebe/pdfpc-latex-notes .
This package creates a .pdfpc compliant file during your latex run. This
can than be used as a notes source.

**Comment by Eisenbarth** [comment]
Yes, pdfpc-latex-notes is exactly what I was looking for !

Thank you very much.
