### ISSUE TITLE
Clicking in the space below the "next slide" view does not advance the slide

### ISSUE THREAD

**Issue by andybarry** [pdfpc/pdfpc#107]
Does this happen to anyone else?  Seems like clicking everywhere else is working correctly for me.

**Comment by AndreasBilke** [comment]
This should be the space where notes appear? So if you type 'n' you can
type in this area.

**Comment by rschroll** [comment]
I'm seeing it, too.  I does seem to be related to the text area, as my 
cursor changes to the text caret.  This shouldn't happen -- we don't 
want mouse control to break because the cursor happened to move over an 
invisible control.  There's probably some mouse sensitivity setting on 
the text we can toggle.

**Comment by andybarry** [comment]
...and @rschroll saves me from feeling like a complete idiot :)

**Comment by AndreasBilke** [comment]
as @rschroll mentioned, my cursor also changes to the text caret, but I can still click in this area and the slide changes to the next.

**Comment by simonnagl** [comment]
I am using pdfpc on a laptop with tochscreen. When I use the touchscreen in the area of the notes nothing happens. At the rest of the screen the next slide appears. When using the mouse I do not have that issue.

**Comment by AndreasBilke** [comment]
Do you still have this problem? Maybe it vanished with newer gtk?

**Comment by AndreasBilke** [comment]
I can't reproduce it on different systems. If this problem still occurs, please re-open the issue.

**Comment by simonnagl** [comment]
I am not using a touch screen anymore. I cannot reproduce it now.
