### ISSUE TITLE
Crashes and problems using the [skip] option

### ISSUE THREAD

**Issue by endzone** [pdfpc/pdfpc#108]
Hi,

I am experimenting with the [skip] option in the settings file.

CRASH: I experience crashes when adding

     [skip]
     1,2

and then start the slides, move forward some slides and returning back to the first slide. I get an 'segmentation fauilt' there.

PROBLEM: Adding an empty section (to disable overlay grouping) works only once, i.e., I add

     [skip]

and nothing below. Starting the presentation, the overlays are not grouped. Leaving the presentation, the empty [skip] section is removed. Thus starting the presentation again, overlay grouping is turned on again. There is currently no way to disable it permanently.

**Comment by endzone** [comment]
I suspect the problem is here
https://github.com/pdfpc/pdfpc/blob/2aee348fbfcee375a82bb313db7edc6a5588a60f/src/classes/window/presenter.vala#L399

If the user adds slide 1 (or possibly also the last slide) in the [skip] section manually, the increment and decrement of the slide counter results in an invalid value (i.e. 0 or a number > the total number of slides)

**Comment by endzone** [comment]
The saving problem originates from here
https://github.com/pdfpc/pdfpc/blob/2aee348fbfcee375a82bb313db7edc6a5588a60f/src/classes/metadata/pdf.vala#L227

One of the conditions for saving is violated if no slides are skipped.

**Comment by AndreasBilke** [comment]
So could you reproduce the problem without manipulating things in the pdfpc
file which are usally modified by the program itself?

Or: does this problem arise if you let pdfpc do the [skip] formating?

**Comment by endzone** [comment]
The non-crash problem is possible to achieve with "regular" pdfpc usage. I.e. I press the "o" key on all slides (except the first, as it does not work there). The result is a complete ungrouping of the overlays. Exiting and restarting pdfpc drops this change, as the [skip] section is not stores when it is empty.
