### ISSUE TITLE
Feature request: disable overlay grouping

### ISSUE THREAD

**Issue by einhander** [pdfpc/pdfpc#109]
Due some bug in how pdfpc work with handout and overlay together I need an option to disable overlay grouping.
My slides full of overlay and I also use handout so it's really painful.

**Comment by AndreasBilke** [comment]
By handout, do you mean "\note" in your tex file?

pdfpc detects overlays by using the pagelabel for each page in the pdf.
latex beamer (more precisely pgfpages) destroys the labels if overlays and
notes are used simultaneously. so pdfpc can't (and never will with the
current way to detect overlays) do grouping correctly.

But I agree, disabling grouping is some useful option to workaround this
beamer/pgfpages issue.

**Comment by einhander** [comment]
Yes, I mean \note command. I know that overlay+handout issue is "won't fix"
So workaround is really needed. I mean in pdfpc as an option, not in .pdfpc file.

**Comment by endzone** [comment]
This is my workaround (for current pdfpc master):

     echo "[skip]" >> talk.pdfpc && pdfpc talk.pdf

What it does is that is disables grouping for all slides in the config file and then runs pdfpc.

Currently, pdfpc does not save this setting, see issue #108 .
Thus, the echo is needed every time you start pdfpc. I put this in a wrapper shell script, and it does the job nicely.

**Comment by einhander** [comment]
Thank you. This is really a hack)) I'll try to use this.

**Comment by endzone** [comment]
Its not really a "hack". It is equivalent to pressing the "o" key to ungroup on every single slide...

**Comment by AndreasBilke** [comment]
@einhander Could you test #112 if it fulfil your request?

**Comment by einhander** [comment]
Thank you, it works.

**Comment by andybarry** [comment]
This feature is now in master.

**Comment by einhander** [comment]
Thank you!
