### ISSUE TITLE
Cut-off clock

### ISSUE THREAD

**Issue by gdetrez** [pdfpc/pdfpc#117]
On a  1280x800 monitor, the clock is cut-off when using the default configuration althought there seems to be enough space above...

![workspace 1_011](https://cloud.githubusercontent.com/assets/38019/12326137/283399b2-bacf-11e5-8806-b4c822932d07.png)

Using the new `-h` option, I can make it fit by reducing the height by one percent (`-h 79`):

![workspace 1_010](https://cloud.githubusercontent.com/assets/38019/12326130/1d3ff910-bacf-11e5-93cb-b1819ed3f674.png)

**Comment by AndreasBilke** [comment]
It does not fit even with the latest master code?

**Comment by gdetrez** [comment]
Yes (tested with the latest master, f83ed9c)

**Comment by andybarry** [comment]
I was able to reproduce by setting my resolution to 1280x800.  I think the problem is that the default font size is too large for 90% of 800 pixels.  I started to look into how to fix that, but haven't figured it out yet.

**Comment by AndreasBilke** [comment]
In the pdfpc.css file, one can reduce the font-size of the bottom texts. Currently, it is set to 5 em. I can live with some smaller default value.

**Comment by andybarry** [comment]
We used to automatically scale the text to fill the bottom space.  In commit 7313d01aff48ce4959c39df691baedc981537d40, we swapped that out for CSS styling.  I don't quite understand why we'd rather a fixed-point font than one that automatically scales.  In #95 @rschroll discussed that we might want a CSS trick to set the font based on widget size, but I haven't been able to figure out a way to do that so far.

**Comment by AndreasBilke** [comment]
There were two reasons why I implemented it:

- some users wanted to have bigger/smaller text at the bottom
- I had problems with cut-off previews

Maybe my problem at that time was not fully related to text size but to
this progressbar set_ellipsize thing @andybarry implemented a few days ago.
