### ISSUE TITLE
Screen confusion in help text

### ISSUE THREAD

**Issue by gdetrez** [pdfpc/pdfpc#119]
with pdfpc --help, I read this

      -Z, --size                    Size of the presenter console in width:height format (forces windowed mode)

but it seems that the option changes the size of the *presentation* screen (the one that should go on the beamer), not the *presenter* screen.

**Comment by AndreasBilke** [comment]
You are right, the behaviour and the help text differ. Does someone know if the help text is wrong or the behaviour? And, why do we have this option anyway? I tought windowed mode is more a debug feature?

**Comment by andybarry** [comment]
This one is me.  I added that option for myself way back when to support a presentation where I had a split screen slides and videos.  So on the left I had slides (which needed to be a particular size) and on the right I had videos  that played continuously in a different media player.

The help text is wrong, but there's also an argument that exposing this option isn't worth the added complexity to the user.  Thoughts?

**Comment by gdetrez** [comment]
I think the windowed mode can be useful for user who want to get an idea of how pdfpc works and you don't have a second screen at hand. I'm not sure about the `-z` options thought. (It would probably be easier to be able to scale the windows with the mouse.)

**Comment by AndreasBilke** [comment]
How should this be done? If we have --windowed in the Options, it is
always visible to the user.

But I agree, the end user should be aware of windowed mode.
