### ISSUE TITLE
Prerendering slows down the GUI

### ISSUE THREAD

**Issue by andybarry** [pdfpc/pdfpc#12]
Right now prerendering causes the entire GUI to lock occasionally.  I expect this is because prerendering is done in the UI thread instead of its own thread, but I haven't actually looked into it.

We should move the rendering into its own thread or figure out why the GUI locks up.

**Comment by andybarry** [comment]
I took a first pass at implementing multi-threaded rendering, but didn't have much luck.  Whenever I run two rendering operations at the same time, I get a segfault inside poppler.  See here: https://github.com/andybarry/pdfpc/tree/threading

Poppler is [supposed to be thread-safe now](https://bugs.freedesktop.org/show_bug.cgi?id=50992), so maybe it's my fault somewhere up the chain.

**Comment by miasma** [comment]
The rendering should use background threads and a thread pool. For instance my laptop has relatively low power cores but 4 of them with HT.  The rendering speed would multiply by at least 4, maybe close to 8. This would be a significant improvement. Currently the pre-render speed for a set of slides for a 2 hour presentation is 8 to 20 seconds. This adds some delay because I need to configure the projectors/displays before launching pdfpc.

**Comment by AndreasBilke** [comment]
We are currently using `GdkPixbuf` for creating PNGs in the PNG cache. If I get it correctly, access to `GdkPixbuf` must be locked, i.e. only one thread (from the gdk main thread) can render a slide at a time.
This totally destroys the whole idea of a multi threading prerendering.

**Comment by fnevgeny** [comment]
> only one thread (from the gdk main thread) can render a slide at a time

But different threads can render _different_ slides in parallel, which would give the needed speed-up for multi-slide presentations, right?

**Comment by AndreasBilke** [comment]
My knowledge is that poppler is not thread safe. But one could out source the rendering to a unique thread (non GUI) which would make pdfpc reactive to user input (since the blocking code is no longer in the GUI thread).

**Comment by andybarry** [comment]
That's correct.  A few years ago I took a pass at this and poppler seg
faults if you try to use it in multiple threads.  Moving rendering to its
own thread would be great.

**Comment by fnevgeny** [comment]
Thanks for the clarifications, I see.

About the issue itself: it looks to me rather a feature request (important, yes), but not a bug. In my experience, there is never a real lock, but of course the GUI is rather laggish during the prerendering.

**Comment by AndreasBilke** [comment]
This should no longer be an issue with #447
