### ISSUE TITLE
Timer not showing.

### ISSUE THREAD

**Issue by TheGrandmother** [pdfpc/pdfpc#121]
Hello!

The timer is not showing for me.

I'm running `pdfpc -d 10  press.pdf` but i do not see any timer :/

**Comment by AndreasBilke** [comment]
Do you see no timer in general or just with "-d"?

**Comment by TheGrandmother** [comment]
I see no timer and no icons on the bottom at all.

**Comment by TheGrandmother** [comment]
Hmm i realized that i just see them on one of the screens. If i run `pdfpc -s -d 10 press.pdf ` i can see it.

Maybe there is something odd with the resolution.

**Comment by AndreasBilke** [comment]
Could you try pull request #120? Maybe commit ce56cbd do the trick for you.

**Comment by TheGrandmother** [comment]
:heart: It is working!

Thanks!
