### ISSUE TITLE
Per-PDF metadata for pdfpc options

### ISSUE THREAD

**Issue by andybarry** [pdfpc/pdfpc#125]
In #103 we discussed somehow using PDF metadata to set options for pdfpc.  The idea would be to set some options, like using overlays, timer duration, etc. using these options.  I think this could be a really nice way to handle presentation-specific options.

**Comment by AndreasBilke** [comment]
One can embedd XMP into the pdf to add some meta data. I googled around and found xmpincl and hyperxmp as latex packages to add XMP data.

The problem with xmpincl is, that you have to write your own XMP file (xml stuff) and this file is embedded into the pdf.

Hyperxmp lets you add some predefined meta data (like author etc).

So ether it is quite complicated to add something to the pdf or you can't add custom meta data.

I think this would be an enhancement, but it is really not user friendly and maybe to command line switches in pdfpc are way better.

**Comment by einhander** [comment]
Hi, I think I found a solution for this.
According to http://www.lancoude.com/adding-custom-metadata-values-to-a-pdf-file/ you could use hyperref package with pdfinfo option to add some custom key fields.

**Comment by AndreasBilke** [comment]
Great, I looked into the poppler api on how to get this data.
Unfortunately, I didn't found a way to get this with the poppler-glib api
(which we have to use).

The poppler-qt5 api provies a way to read this
(http://people.freedesktop.org/~aacid/docs/qt5/classPoppler_1_1Document.html#a00c581e1103955cc3cf00908fac5ce53).

Any help is welcome to find a way for fetching this kind of meta data.

**Comment by andybarry** [comment]
I agree -- I tried to get at the data with gtk / poppler and had no luck.  I think we should put this on hold until there is good API support.
