### ISSUE TITLE
Problem to install on Ubuntu 15.10

### ISSUE THREAD

**Issue by dragonxtek** [pdfpc/pdfpc#127]
~/pdfpc/build$ cmake ..
-- checking for module 'poppler-glib'
--   package 'poppler-glib' not found
CMake Error at /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:344 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:506 (_pkg_check_modules_internal)
  src/CMakeLists.txt:5 (pkg_check_modules)

~/pdfpc/build$ sudo apt-get install libpoppler-glib-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpoppler-glib-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.

What is the problem? I missed some library? Also, I install poppler tarball, but I got the same result

**Comment by andybarry** [comment]
Can you post the output of:
````pkg-config --modversion poppler-glib````

and 
````pkg-config --list-all |grep poppler````

**Comment by dragonxtek** [comment]
~$ pkg-config --modversion poppler-glib
0.33.0

~$ pkg-config --list-all |grep poppler
poppler-qt5                         poppler-qt5 - Qt5 bindings for poppler
poppler                             poppler - PDF rendering library
poppler-cairo                       poppler-cairo - Cairo backend for Poppler PDF rendering library
poppler-splash                      poppler-splash - Splash backend for Poppler PDF rendering library
poppler-glib                        poppler-glib - GLib wrapper for poppler
poppler-data                        poppler-data - Encoding files for use with poppler
poppler-cpp                         poppler-cpp - cpp backend for Poppler PDF rendering library
poppler-qt4                         poppler-qt4 - Qt4 bindings for poppler

**Comment by andybarry** [comment]
You definitely have it, probably cmake isn't finding it.

Did you make sure to init the submodules?

````
cd pdfpc
git submodule init
git submodule update
mkdir build
cd build
cmake ../
make -j8
sudo make install
````

See: http://abarry.org/the-new-complete-guide-to-embedded-videos-in-beamer-under-linux/

**Comment by andybarry** [comment]
actually I think we zapped those... hmm.

**Comment by dragonxtek** [comment]
I got the same error :(

**Comment by andybarry** [comment]
That's really odd.  If you don't need the latest version, you can install from apt:
````sudo apt-get install pdf-presenter-console````

other than that, I'm not quite sure what's wrong.

**Comment by dragonxtek** [comment]
Yes, it's really weird, but at least apt-get works fine. Thanks!
