### ISSUE TITLE
Ready for a new release?

### ISSUE THREAD

**Issue by andybarry** [pdfpc/pdfpc#129]
I'm pretty happy with the number of bugs we've knocked out in the last month!  How do you guys feel about a new release?  In particular, it would be great to get the Debian / Ubuntu package updated so we can start advertising that as a fast way to get pdfpc.

**Comment by AndreasBilke** [comment]
If we hurry up, we could hit the ubuntu 16.04 lts feature freeze. So, lets
go for it! (https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule)

For Debian there is the deadline in december.

**Comment by andybarry** [comment]
Awesome!  @barak, if we tag a new release, would you have time to package it and get us into 16.04?

**Comment by AndreasBilke** [comment]
There are a few things to do:

- update version string in pdfpc.vala (we forgot it last time with 4.0.1)
- version string in man page (pdfpc.in)
- update copyright notice in source files (@rschroll did it the last times)

**Comment by andybarry** [comment]
Also compile a changelog.  I'll start working on that.

**Comment by andybarry** [comment]
OK check out #130, which adds the copyrights, updates the version strings, and adds to the changelog.  Definitely double-check to see if I missed anything.

Props to @rschroll for the sweet copyright script.

**Comment by andybarry** [comment]
Tagged and released!  @barak, let us know what we need to do to help you get a .deb package done.  I'm going to leave this issue open until we've handled that.

**Comment by rschroll** [comment]
Way to go, everyone!

I'm busy starting a new job, so I haven't had the time to think about 
pdfpc at all.  But I appreciate all the work you're doing to keep it 
going.  Thanks!

Robert

**Comment by barak** [comment]
dput.
