### ISSUE TITLE
Use GLib.Actions in PresentationController

### ISSUE THREAD

**Issue by rschroll** [pdfpc/pdfpc#13]
There's a custom Action class defined in presentation_controller.vala.  To use it, callbacks need to be passed in to handle the action activation.  The leads to a warning, "copying delegates is not supported".  It also contributes to funkiness in the keystroke handling.

I think we'd be better off moving to a signal-based mechanism based on GLib.Actions.

**Comment by andybarry** [comment]
Fixed from #18.
