### ISSUE TITLE
Shortcut key to jump to last overlay

### ISSUE THREAD

**Issue by t-brink** [pdfpc/pdfpc#135]
This is related to issue #102, but instead of switching to a linear progression through overlays, I would like a key to jump to the last overlay of a slide. My reasoning is, that during the normal course of the presentation I will move strictly forward through the slides. At the end, there is usually a question session, where I use `TAB` or `g<number>` to jump to a specific slide. The same as fhgd in issue #102, I would then like to show the complete (final) slide. This can be awkward if there are many overlays (I sometimes add curves to graphs one after another to make the data easier to understand). A simple key to jump to the final overlay of a slide would be good enough for me and would not change the way things work currently. It also does not involve complicated mental models one would have to keep in mind.

Alternatively, the overview could always show and jump to the final overlay, but that may be confusing.

Simply disabling the overlays does not work for me, as it makes the overview useless.

As an aside, I was very happy to see that this project got revived, thank you for keeping this excellent tool working!

**Comment by AndreasBilke** [comment]
@t-brink could you test the pull request?

**Comment by t-brink** [comment]
Works for me, thanks for the quick response! Do you think a standard keybinding should be added? I used L (as in Last overlay). I'm equally happy just putting it in my local config file, too.

**Comment by AndreasBilke** [comment]
Actually, I have no opinion about the shortcut. I just needed something to
test it :).

I will wait for some response from the others and change it to whatsoever.
