### ISSUE TITLE
Href does not open external video

### ISSUE THREAD

**Issue by diegit** [pdfpc/pdfpc#138]
New issue from https://github.com/pdfpc/pdfpc/issues/72

Hi,

I found this program a few days ago and tried to use it with one of my existing presentations. I want to open external videos with href. Okular and the internal texstudio viewer open the video with vlc. Pdfpc prints only "Vorgang wird nicht unterstützt" (operation not supported). Embedded videos (with \href{run:..}) work fine.

minimal example:
```
\documentclass[11pt,a4paper]{beamer}
\usepackage{hyperref}

\begin{document}
\begin{frame}
\href{NC_CIL.mov}{
\includegraphics[width=1.0\linewidth]{NC_CIL_grafik.png}\\
{\tiny Invasion assays, Carmona-Fontaine et al. Nature 2008} }
\end{frame}
\end{document}
```
OS: Linux Mint 17.3
/usr/local/bin/pdfpc -v
pdfpc v4.0.2

thank you!

Link to .tex and .pdf:
https://tubcloud.tu-berlin.de/index.php/s/VUWBFhQJoYBnvTO

**Comment by AndreasBilke** [comment]
If you use hyperref this way, pdfpc thinks `NC_CIL.mov` is some link (and it can't find a way to open it). You have two (or three) choices to get your video running in pdfpc.

Option 1:
Change `\href{NC_CIL.mov}...`  to `\href{run:NC_CIL.mov}`

Option 2:
Use the `multimedia` package from beamer. Than you have something like `\movie{\includegraphics[width=1.0\linewidth]{NC_CIL_grafik.png}}{NC_CIL.mov}`

**Comment by diegit** [comment]
Hi,

I tried that already, but pdfpc plays the video embedded in the pdf for both options. It be great if pdfpc could open the video in whatever is the standard program for these files. Just like okular and evince handle this.

Maybe as backround:
I've often got things like \href{NC_CIL.mov}{click me!}. With the multimedia package and \href{run:..} the movies are embedded with the size of the text.

**Comment by AndreasBilke** [comment]
Maybe I missunderstood you. The movie should be opened with an external
player and not as a embedded video in pdfpc?

**Comment by diegit** [comment]
yes exactly!

**Comment by AndreasBilke** [comment]
Okay, then, you need to specify your file with the `file://` syntax. You
have something like `\href{file:///home/user/file.mov}` .

This is a valid url. Note, that you can't use relativ paths.

**Comment by AndreasBilke** [comment]
More user friendly would be to call xdg-open directly within our code. So
I let this issue open so that we can discuss this further.

**Comment by diegit** [comment]
awesome thank you!
I tried absolute paths, but only without the file:// in front of it.

If someone else has the same problem and doesn't want to write the absolute path everywhere, you can use:
`
\usepackage{xstring}
\newcommand\myPth{file://*AbsPathToPresentation*}
`
and then
`
\href{\myPth *relativePath*}
`

**Comment by dbitouze** [comment]
> If someone else has the same problem and doesn't want to write the absolute path everywhere, you can use:
> `\usepackage{xstring}`

Thanks for sharing. AFAICS, `\usepackage{xstring}` isn't necessary.
