### ISSUE TITLE
Use xdg-open for correct application in links

### ISSUE THREAD

**Issue by AndreasBilke** [pdfpc/pdfpc#139]
If a user specify a `\href` in his document, use `xdg-open` to find an application for opening the link. This way, someone can write `\href{file.mov}` instead of using the `file://` syntax.

**Comment by AndreasBilke** [comment]
xdg-open is not available on systems like windows or mac os x. The code should be system independed, so therefore xdg-open is not an option.

**Comment by farseerfc** [comment]
macOS has the general `open` command which works even better than `xdg-open` in Linux. Windows can usually `explorer <filename.ext>` to do the same thing.

**Comment by AndreasBilke** [comment]
Of course, but you need to distinguish between mac os, windows, linux. and
what is with openbsd, freebsd etc? The current approach is platform
independent in a sense, that you have a common API.

**Comment by dbitouze** [comment]
> Of course, but you need to distinguish between mac os, windows, linux. and what is with openbsd, freebsd etc?

Other PDF viewers, e.g. Evince which is working , make use of `xdg-open` or similar to find an application for opening a link.

> The current approach is platform independent in a sense, that you have a common API.

Maybe the current feature could be an exception to this approach...

**Comment by mgkuhn** [comment]
What is the “current approach” for firing up an application (such as an audio-file player) when clicking on a relative URL to an application file in the same folder?

**Comment by mgkuhn** [comment]
Would the GTK functions [show_uri_on_window()](https://valadoc.org/gtk+-3.0/Gtk.show_uri_on_window.htm) or [show_uri()](https://valadoc.org/gtk+-3.0/Gtk.show_uri.htm) not be a suitable portable API for calling the default applications for a file type?
