### ISSUE TITLE
Auto-grouping behave strangely when used with Beamer notes option

### ISSUE THREAD

**Issue by perror** [pdfpc/pdfpc#148]
I do not know if it is a feature or a bug, but it seems that the structure of the presentation is much more difficult to understand for pdfpc when the slides are compiled with beamer notes, then the auto-group behave extremely strangely (grouping slides together when they seems to have no links together and, even, forgetting some links when there is one).

I guess that the auto-grouping algorithm has not been designed to cope with the Beamer-notes PDF split "hack" for dual-display presentation.

Note that, the same document compiled with "hide notes" behave well in pdfpc!

So, my question is simply: Is there hope to get this fixed or this is simply so much a mess in the structure of the document when coping with Beamer-notes that there is no hope?

**Comment by AndreasBilke** [comment]
The problem is that beamer (or in detail pgfpages) does not produce correct pdf page labels if you have notes + overlays.

pdfpc uses these pdf page labels for auto grouping and so it does not work if they are broken. This is a very long standing problem in pgfpages and personally I think this will never be fixed. **but** we implemented a function to disable-auto grouping if you want.

Maybe there is some other way to the grouping right, but we didn't find some other way.

**Comment by andybarry** [comment]
Is it possible to detect when this is broken and automatically disable the grouping?

**Comment by perror** [comment]
@AndreasBilke : but we implemented a function to disable-auto grouping if you want.

Yes, I was using it (`-g` option) for now. But, I better understand the problem. In fact, I was not really expecting that this kind of behavior could be fixed nor detected but I was asking just in case.

Thanks.

**Comment by perror** [comment]
Ah, I was just thinking... Would it be okay to consider that the option `--notes` automatically implies the `--disable-auto-grouping` option? Or, are they cases where using `--notes` can be done with auto-grouping and work nicely ? (I am asking just in case)

**Comment by AndreasBilke** [comment]
It could be possible that a user creates his slides without latex beamer.
And maybe this software does not break pdf page labels, then it is useful
to keep the auto grouping feature.

I don't know some software which do this, but just focusing on latex beamer
slides is not the best way.

**Comment by AndreasBilke** [comment]
I re-tested why we can't auto detect this. I tested the following:

A pdf with 2 (logical) slides with 3 itemize items per page page. Each item
is a beamer overlay.

This is the mapping from real page index to logical index (aka pdf page
label) for the version without notes

0 -> 1
1 -> 1
2 -> 1
3 -> 2
4 -> 2
5 -> 2

As you can see, the first three slides have the same page label and the
next three also have the right label. Now I show the the mapping for the
same slide set, but with notes enabled:

0 -> 1
1 -> 1
2 -> 1
3 -> 2
4 -> 1
5 -> 3

And if you have more slides and a more "complicated" setup it get even
worse.

So I think we have no chance to auto-detect this.

**Comment by perror** [comment]
Thanks for trying but I guess that fixing `pgfpages` would the right way. After all, the real bug is coming from there! :-)

**Comment by AndreasBilke** [comment]
Of course ;) I submitted a bug report in 2012
https://bitbucket.org/rivanvx/beamer/issues/228/wrong-pdf-labels-per-page-when-using-notes
(and I think this bug is alive even longer).

As you can see, nothing changed.

**Comment by fnevgeny** [comment]
Just updating the beamer bug report link: josephwright/beamer#228
