### ISSUE TITLE
Bad aliasing of slides

### ISSUE THREAD

**Issue by perror** [pdfpc/pdfpc#149]
I am using the `pdfpc` 4.0.2 Debian (unstable) package on a MacBook laptop with a HiDPI Retina screen (2560x1600) together with a "normal" video-projector (1280x800).

I noticed that when using `pdfpc` on several slides, there is an extra aliasing step that render the slides as if they were in the wrong definition on the video-projector. It gives a very bad visual effect on the slides (some of them are really difficult to read which ruin about all the effort).

I first though it was an `xrandr` problem but, the resolution is correct. And, I tried with Evince alone and the rendering is much better. So, the last in raw is `pdfpc` itself... 

I am looking a bit at the code to see where this extra aliasing is added but could not locate it until now.

Is it an intended feature, and, if yes, could there be an option to disable it (or just fix it)?

**Comment by perror** [comment]
I have tested with a non-HiDPI laptop and it behaved nicely. So, I am more and more suspecting the HiDPI to be responsible for this strange behavior.

I also found another strange behavior that might be linked to this bug. When displaying a video, the movie is played in a window which is shifted and reduced in size. See, the following pictures to see what is displayed on the laptop (first image), what is displayed on both (the black rectangle in the middle is a bug of the screenshot software, just ignore it) for full-screen and embedded video:

![screenshot from 2016-04-14 17-14-17](https://cloud.githubusercontent.com/assets/1612326/14533956/79f8c63e-0267-11e6-9a3f-8451ed9d585d.png)
![screenshot from 2016-04-14 17-23-19](https://cloud.githubusercontent.com/assets/1612326/14533969/8556d3a4-0267-11e6-9ed7-ef3b66f90343.png)
![screenshot from 2016-04-14 17-23-31](https://cloud.githubusercontent.com/assets/1612326/14533976/8ddb81be-0267-11e6-87bc-23c9f5a388a5.png)

Then, here are an example of the blurred display (again, the black rectangle should be ignored):
![screenshot from 2016-04-14 17-33-17](https://cloud.githubusercontent.com/assets/1612326/14534000/a25a593a-0267-11e6-91df-b17ec3eab353.png)

This last image is just a sample of what does display Evince:
![screenshot from 2016-04-14 17-33-42](https://cloud.githubusercontent.com/assets/1612326/14534007/a620d486-0267-11e6-9e24-5081c65ca86f.png)

**Comment by jakobwenzel** [comment]
I also experience this issue. If I turn off Scaling in gnome-tweak-tools, pdfpc displays fine.

**Comment by perror** [comment]
I do not see how to turn off the Scaling in gnome-tweak-tools, but I can set it to '0' (zero), '1' (one) and '2' (two). I tried with '0' with no real improvement (unfortunately).

But, I am ready to try.

**Comment by perror** [comment]
I did a few experiments to better understand the bug and it seems that when the video-projector is plugged, the system select the mode 1024x768@70Hz where the native resolution is in fact 1600x1200@60Hz. Then, when I change it to the native resolution the display is much better.

So, could it be that all the pre-processing of the images is based on the native resolution of the display and, then, mapped on the current display even if it does not fit?

**Comment by perror** [comment]
Ok, I am more and more confident in the fact that the bug is coming from a wrong resolution settings. `pdfpc` seems to get the native resolution of the display and send an image computed for this native resolution without noticing that it is not exactly the same.

I checked out the current git master and did a few test on it. And, it just behave as the current stable version (except that I needed to fix a few things such as 'adding a "new"' and get the fullscreen to work again). So, the bug must be still around, but I am not yet acquainted to Vala, so I have some problem to find it in the code.

**Comment by andybarry** [comment]
I can confirm this is an issue on my new HDPI screen as well.  Must be something with the scaling messing up our resolution detection.

**Comment by perror** [comment]
I you need, I can test patches (I have a github clone that compiles fine on my HiDPI laptop and 4 or 5 types of video-projectors to test the thing if needed). So, feel free to ask me.

**Comment by diraimondo** [comment]
Any hope for a fix or a bad workaround in order to get a proper aliasing on the second screen using an HiDPI main screen? I can confirm the problem (3200x1800 with scaling factor 2 on main screen and 1280x1024 on the second screen) and also that switching the system on scaling factor 1 (using gnome-tweak-tools) apparently fix the problem but make unusable all the rest of applications.

Please!!!

**Comment by AndreasBilke** [comment]
Any external help would be welcome.

**Comment by skadge** [comment]
I confirm the issue and the (easy enough) workaround consisting in setting `GDK_SCALE=1`.
After a bit of debugging, Poppler's `get_link_mapping` returns the wrong area for the videos.
Basically, the area is divided by `GDK_SCALE` (try to set it to 3 to see the effect).

**Comment by AndreasBilke** [comment]
@perror could you try this patch and post the result: https://pub.bilke.org/2017-01-01-Z3daO9W71eQ/screen-geometry.patch ?

It is just a debug statement to figure out what are the scaling factors for each screen. We are doing pixel sized rendering and maybe we are rendering for too small sizes.

**Comment by perror** [comment]
@AndreasBilke I will. I imagine that I will have to write down the actual scaling and compare it with the desired one. I'll try to make it in the next days.

**Comment by diraimondo** [comment]
@AndreasBilke , I tested your debug patch.
I'm using the internal 3200x1800 display jointly with an external 3840x2160 one.
My scaling factor is set on 2:
```
$ gsettings get org.gnome.desktop.interface scaling-factor
uint32 2
```

This is the output without the GDK_SCALE specification and with the aliasing problem:
```
$ ./pdfpc ~/presentation.pdf
0> width 1920 height 1080, scaling 2
1> width 1600 height 900, scaling 2
```

This is the output with the GDK_SCALE hack and with a proper aspect:
```
$ GDK_SCALE=1 ./pdfpc ~/presentation.pdf
0> width 3840 height 2160, scaling 1
1> width 3200 height 1800, scaling 1
```

**Comment by perror** [comment]
I also tested your debug patch, I have a primary display at 2560x1600 and a secondary display (video-projector) at 1024x768.

When setting the 
```
$ pdfpc slides.pdf 
Screensaver inhibited
0> width 1280 height 800, scaling 2
1> width 512 height 384, scaling 2
Screensaver reactivated
```
And, I noticed exactly the same effect than diraimondo when forcing the `GDK_SCALE` to 1.
Note that, I need the `GDK_SCALE` to be set to 2 for other displays.

So, after all, it seems that the `GDK_SCALE` value is just ignored when displaying the video. It's just that.

**Comment by AndreasBilke** [comment]
@perror @diraimondo can you try my branch at https://github.com/AndreasBilke/pdfpc/tree/issue-149 ? I tried GDK_SCALE=2 at my non-hidpi monitor and I got blurred slides as well. With this fix, the slides looking good with GDK_SCALE=2

There are some things which are not working in the branch (like nice overview images, pause images etc) but lets see if this goes in the right direction.

**Comment by diraimondo** [comment]
@AndreasBilke you branch works well with the scaling/aliasing problem here. It looks the right direction! :-)

**Comment by AndreasBilke** [comment]
@perror  if your problem still exist in master, please reopen this issue.

**Comment by perror** [comment]
@AndreasBilke : No, the bug was removed by the fork. I did not have anything new to add to what has been already said, so I got silent. Sorry, I should have tell that it was solved for me too!
