### ISSUE TITLE
Make uninstall

### ISSUE THREAD

**Issue by madoar** [pdfpc/pdfpc#150]
Hello,
I just found pdfpc on github and I like it a lot.
After discovering that the version in the ubuntu repositories is quite old, I downloaded the current version from here and built it myself. Afterwards I discovered that the current version of pdfpc won't start in fullscreen mode for me (like described in issue #64), so I tried to uninstall it and to go back to the version in the ubuntu repositories, but I couldn't find an make option to uninstall pdfpc.

Which brings me to my feature request: please add a make option to uninstall pdfpc previously installed with make.

Greetings 
Marc

**Comment by AndreasBilke** [comment]
https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F
the last command should do the job.
