### ISSUE TITLE
How to change the default options for the movie?

### ISSUE THREAD

**Issue by murpholinox** [pdfpc/pdfpc#153]
Hi I just found out pdfpc. Very nice. Thanks
The provided movie example works great in chapeau OS.
But how can I change the default behavior of the movie in the presentation? I want to be able to play it with a click (or any key)...and after it ends play it again...(only if needed). That means...removing the loop and autostart defaults.  I suppose I have to change some lines in the sty file but my latex knowledge is very limited. 
Thanks again for your time

**Comment by AndreasBilke** [comment]
You can use the "standard" way and use hyperref directly. The code can be
found in the man page

    \usepackage{hyperref}
    \href{run:<movie file>}{<placeholder content>}

**Comment by murpholinox** [comment]
Thanks for the tip. I did not see that.
