### ISSUE TITLE
Incorrect next slide show when using `--notes`, and some weird behaviour when moving back through slides

### ISSUE THREAD

**Issue by lckarssen** [pdfpc/pdfpc#159]
I've made a presentation using LaTeX Beamer in which I use notes. When I use `pdfpc -n right`, the main slide (on the external display) shows correctly and the notes can be seen correctly on the secondary screen. However, the slide shown on the right of the notes is not the next slide, it's the one after that. The actual next slide is shown as a small slide below the notes and the (incorrect) next slide. Even stranger: in some cases the 'next slide' is not updated when moving to the following slide. 

Added to this, moving back between slides is erratic, sometimes `pdfpc` jumps two slides back.

For example:

- I am on slide 1, the title page (show on the external display). The top left viewport (on the secondary screen) shows the notes and the top right viewport shows slide 3. Below the two top previews slide 2 is shown in the centre. 
- I move to slide 2 (on the primary screen): on the secondary screen the title slide is moved down and on the left; the top right viewport still contains slide 3; the notes are displayed correctly in the top left viewport.
- I move to slide 3, now slide 4 is small, centred below the two main previews and the top right preview contains slide 5.
- I hit the left arrow key and instead of going one slide back (from slide 3 to slide 2) I end up on the title slide.

This is on Ubuntu 16.04, pdfpc v4.0.2.

**Comment by AndreasBilke** [comment]
Do you use also overlays with latex notes? If this is the case, this is a
latex beamer (or more specific pgfpages) bug and probably will never be
fixed.

**Comment by lckarssen** [comment]
Nope, this also shows up in a quick example without overlays.

**Comment by AndreasBilke** [comment]
Could you provide an example where this happens?

**Comment by lckarssen** [comment]
Here's a simple MWE. 

```LaTeX
\documentclass[]{beamer}
\usepackage{pgfpages}
\setbeameroption{show notes on second screen}


\title{My presentation}
\author{Yours Truely}

\begin{document}
\maketitle
\begin{frame}
  \frametitle{A frame with notes}
  This is a list
  \begin{itemize}
  \item An item
  \item Another item
  \end{itemize}
  \note{Don't forget to mention something here.}
\end{frame}

\begin{frame}
  \frametitle{A slide with a table}
  \begin{tabular}{rll}
    Header 1& Header 2 & Header 3\\
    \hline
    10 & item & item \\
    20 & item & item \\
    \hline
  \end{tabular}
  \note{A note for the table}
\end{frame}

\begin{frame}
  \frametitle{Another slide}
  Some text
\end{frame}

\begin{frame}
  \frametitle{Yet another slide}
  This means nothing
\end{frame}

\begin{frame}
  \frametitle{The last slide}
  This is the end.
\end{frame}

\end{document}
```

I tried both pdflatex and XeLaTeX and the issue was present in both cases.

**Comment by AndreasBilke** [comment]
Okay, I can reproduce this. I will have a look why this happens. I think this worked some time ago. Let's see...

**Comment by lckarssen** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Thanks! Let me know if I need to test something.

Andreas Bilke <notifications@github.com> schreef op 23 mei 2016 09:59:28 CEST:
>Okay, I can reproduce this. I will have a look why this happens. I
>think this worked some time ago. Let's see...
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pdfpc/pdfpc/issues/159#issuecomment-220911771

- --
L.C. Karssen
Utrecht
The Netherlands
lennart@karssen.org
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iIcEAREKAEcFAldCzcdAHEwuQy4gS2Fyc3NlbiAoR1BHIGtleSBmb3IgcGVyc29u
YWwgc3R1ZmYpIDxsZW5uYXJ0QGthcnNzZW4ub3JnPgAKCRC/Av9aqI9VSg9xAJ0U
iLnJwtcC2CDVCgd8sm3o8thMxQCfSjD1TvOpOmxg9JscPE/1gqn8h9s=
=PG0X
-----END PGP SIGNATURE-----

**Comment by AndreasBilke** [comment]
I looked into the pdf page labels for this example and with my texlive+beamer they are totally screwed. Actually, I have no idea why. I will look into this more deeply.

Until then, you can use (with pdfpc/master) the `disable-auto-grouping` function.

**Comment by AndreasBilke** [comment]
I created pr #176 . I think we cannot fix this in the near future.

**Comment by cdown** [comment]
Was a bug also filed upstream with pgfpages? Is pgfpages abandoned, as it seems?

**Comment by lckarssen** [comment]
No, sorry, I didn't take the time to file a bug upstream.
