### ISSUE TITLE
separate notes file

### ISSUE THREAD

**Issue by rpglover64** [pdfpc/pdfpc#162]
https://github.com/cebe/pdfpc-latex-notes does what I want more than embedding the notes in the pdf, but it [erases the pdfpc file](https://github.com/cebe/pdfpc-latex-notes/issues/10). Would it be possible to split the pdfpc file into things that should be overwritten on each build (e.g. notes, overlay specifications, etc) and configuration options (e.g. font size)?

**Comment by AndreasBilke** [comment]
Could you explain your idea in more detail? I don't get it.

**Comment by rpglover64** [comment]
The simplest implementation would be supporting an `include` directive in the `pdfpc` file.

That way, I could have a `main.pdfpc` file which `include`s a `main.notes` file and modify the `pdfpc-latex-notes` sty file to output to the `main.notes` file.

Does that make sense?

**Comment by AndreasBilke** [comment]
Oh okay. yes this would be nice. Are you able to implement this?

**Comment by rpglover64** [comment]
Unfortunately not. Sorry.

**Comment by AndreasBilke** [comment]
@rpglover64 I created a PR #296 . Is this what you wanted? Did it works for you?

**Comment by rpglover64** [comment]
Unfortunately, I haven't used `pdfpc` since I filed the issue, so I'm not sure.

**Comment by AndreasBilke** [comment]
@rpglover64 Are you interested in testing this PR?

**Comment by AndreasBilke** [comment]
Closed with #296
