### ISSUE TITLE
Allow more options in config files

### ISSUE THREAD

**Issue by nplatis** [pdfpc/pdfpc#163]
I believe it would be useful to set some more defaults in config files, such as those corresponding to options:
- last-minutes
- time-of-day
- switch-screens
- disable-cache
- disable-compression
- single-screen
- windowed
- size
- notes

The reason is that one may be having a more or less constant environment for presentations, and this would save some typing of command-line options.

For example, I use my presentations as lecture notes, and of all the timing options, the most useful to me would be to have the current time displayed on screen. Now I can't set it globally, I have to (remember and) type -C always.

**Comment by AndreasBilke** [comment]
@nplatis Is this was you expected?

**Comment by nplatis** [comment]
Yes, that's it. Thanks!
