### ISSUE TITLE
pdfpc with multiple options 

### ISSUE THREAD

**Issue by mfouda** [pdfpc/pdfpc#164]
Hello,
Can we use pdfpc with multiple options. For example 
pdfpc -s, -d 45 pdfFile.pdf

Thank you

**Comment by AndreasBilke** [comment]
You want switch-screens and duration at the same time? This actually should
work. There are just some options which are mutually exclusive, but not
these both.

**Comment by andybarry** [comment]
Yes, that will work, just don't use a comma between arguments (just a space):

pdfpc -s -d 45 pdfFile.pdf

**Comment by mfouda** [comment]
Thank you all :)
