### ISSUE TITLE
Black screen without showing content of the pdf file

### ISSUE THREAD

**Issue by mfouda** [pdfpc/pdfpc#165]
Hello,
I am wondering when I try to launch pdf file (slides) with pdfpc. The XQuartz is launching in the same time, but I only get a **black screen without the content of the pdf file**. 
I have installed all the packages gtk+3, gee, vala, etc ... all.
Example: **pdfpc -s -w pdfpc-demo.pdf**, I got the following in this image 
![blackscreenpdfpc](https://cloud.githubusercontent.com/assets/18485676/16175308/2f0eeb3a-35e8-11e6-86d0-65ca60432a5a.png)

Please some one help me !!!
Best

**Comment by AndreasBilke** [comment]
You fixed it by your self?
