### ISSUE TITLE
[Organization] Search for Contributors

### ISSUE THREAD

**Issue by AndreasBilke** [pdfpc/pdfpc#166]
I think we need to actively search for new contributors. Currently, we get new features requests and so on, but for the most cases the authors of the issues are no developers, so they can't help us (they just want things).

If I see it correctly, every pdfpc maintainer (including me) has not enough time to shorten the issue list :)

Are there any ideas how to improve this? Should we "disallow" every feature request, except those were the author can actively help?

**Comment by cebe** [comment]
who are the "pdfpc maintainers" right now?

**Comment by AndreasBilke** [comment]
Oh right, there is no "we are the maintainer" file :) I meant the people
from the pdfpc organization https://github.com/pdfpc/

**Comment by cebe** [comment]
> I meant the people from the pdfpc organization https://github.com/pdfpc/

There is only you shown in public all other members seem to have only hidden membership :)

**Comment by AndreasBilke** [comment]
Hm, right :) Each member have to make themself a public memer. But, we are
5 in total.

**Comment by AndreasBilke** [comment]
I think with philippberndt we have now 2 active members :)
