### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by slardiere** [pdfpc/pdfpc#167]
Commit 35ee0deb448ebf506b459e8d965a38bdd3feb19d breaks full screen mode on Debian/GnomeShell : 
gnome-shell                   3.14.4-1~deb8u1     amd64

pdfpc open the presentation in windowed mode, and I'unable to switch to full screen

**Comment by ennob** [comment]
I had this problem as well. I have sent a pull request with a fix though, so hopefully it will get included soon.

**Comment by AndreasBilke** [comment]
@slardiere Is your problem resolved with #173?

**Comment by slardiere** [comment]
Yes, problem fixed !
