### ISSUE TITLE
Current release 4.0.2 does not compile on Open Suse Tumbleweed

### ISSUE THREAD

**Issue by diegit** [pdfpc/pdfpc#168]
Hi,

the latest release v4.0.2 does not compile on Tumbleweed due to vala 0.32.0, this was fixed by this PR https://github.com/pdfpc/pdfpc/pull/152 
Would it be possible to release an updated version so pdfpc can be included in Tumbleweed?

thank you!

**Comment by AndreasBilke** [comment]
We have a new release.
