### ISSUE TITLE
Add option to start presentation at a given page

### ISSUE THREAD

**Issue by logological** [pdfpc/pdfpc#170]
Many PDF viewers have a command-line option (often `--page` or `-p`) that takes a page number as an argument.  Using this option causes the document to be opened at a particular page.

It would be useful if pdfpc had a similar command-line option, because there are cases in which you need to start a presentation somewhere other than the beginning.

**Comment by AndreasBilke** [comment]
@logological could you check pr #196?

**Comment by AndreasBilke** [comment]
I merged #196. If this was not the changes you had in mind, please reopen this issue.

**Comment by logological** [comment]
> @logological could you check pr #196?

From reading the source code, it seems to be what I was asking for.  Thanks!
