### ISSUE TITLE
Persistent prerendering cache

### ISSUE THREAD

**Issue by anntzer** [pdfpc/pdfpc#171]
Would it be possible to add an option to dump the (compressed) prerendering cache to disk, in order to trade startup against disk usage?

**Comment by AndreasBilke** [comment]
Everything is possible if someone want to implement it.

Actually, I think implementing multi-threading pre-rendering is more useful
compared to some complex logic for dumping and loading (and keeping track
of different binary formats, if we change something in the caching).

**Comment by miasma** [comment]
I commented the multi-threaded rendering on issue #12. IMO this proposal has very little practical value unless the set of slides has a huge number of pages or you're using pdfpc as a viewer when creating new slides with LaTeX. In the former case it might be better to split the file with e.g. pdftk. If you think about normal presentations, around 100 slides will render in 2-5 seconds using a multi-threaded renderer. Typical presentations are much shorter. If the response time of the GUI is a problem, a separate render thread should solve that even on single-core machines. A work queue approach could also prioritize the rendering of frames if you browse the slides in a non-linear fashion before the pre-rendering is done.

**Comment by anntzer** [comment]
Sounds fair.  Feel free to close this.

**Comment by miasma** [comment]
BTW, the command line option -z may speed up things quite a bit compared to default settings if you have enough memory (4+ GB). Nowadays, even older machines tend to have enough RAM for 100 uncompressed slides.

If someone wants to micro-optimize, compressing with LZ4 might result in a better speed/storage ration than PNG. There's also Zstandard (http://facebook.github.io/zstd/), which is 3x faster than PNG and even has a better compression ratio.

For instance, -z combined with a thread pool implementation would make the pre-rendering almost instant in many cases. I just tested on an "old" Haswell notebook and it took around 1.5 seconds to render 60 slides with mostly textual content. With 4 threads (and/or HT), probably more than 100 slides per second would be possible. I can imagine that persistent caching would mostly benefit really old hardware.
