### ISSUE TITLE
Allow setting of (some) options in pdfpc files

### ISSUE THREAD

**Issue by jspitz** [pdfpc/pdfpc#172]
This is somewhat related to #163, but it concerns local `*.pdfpc` files, not global config files.

IMHO it would be good if some presentation-related options could be set in the local `.pdfpc` file, allowing to preset how a given presentation is done if not otherwise specified via the command line options.

Candidates:
- duration
- end−time
- last−minutes
- start−time
- time−of−day
- notes

and maybe others.

This would help to assure that a given presentation is displayed in a given way.

**Comment by AndreasBilke** [comment]
Actually,

* notes
* duration

are already read from pdfpc file. But the others seem reasonable.

**Comment by jspitz** [comment]
> * notes
> * duration
> 
> are already read from pdfpc file. 

I see, thanks. But this is not documented on the man page, is it?

**Comment by AndreasBilke** [comment]
No. Shame on us! :)

**Comment by AndreasBilke** [comment]
@jspitz  Is #205 what you expect?

**Comment by jspitz** [comment]
Yes, thank you!
