### ISSUE TITLE
cannot see embedded videos

### ISSUE THREAD

**Issue by asartori86** [pdfpc/pdfpc#180]
hi,

I cannot see the embedded videos. I tried with the `video-example.pdf` provided in the readme. I get this warning/error

```
** (pdfpc:21498): WARNING **: movie.vala:531: Error creating control pipeline: Could not make element overlay of type cairooverlay.
```

I am running on gentoo with openbox. I am missing any gstreamer plugin? which one?

thanks

**Comment by AndreasBilke** [comment]
The video in the demo example uses the theora video codec IIRC. So you
should be fine with gstreamer + gstreamer-good plugins.

You can see the dependency list for debian here:

https://packages.debian.org/stretch/pdf-presenter-console

or for arch linux here:

https://www.archlinux.org/packages/community/x86_64/pdfpc/

So could you try on your own a litte bit? Maybe we forgot some depencies in
the cmake file.

**Comment by asartori86** [comment]
actually I have all of them installed..

**Comment by a123qwertz567** [comment]
If it is an overlay thing, have you tried to supress the overlays:

```
pdfpc --help
[...]
-g, --disable-auto-grouping     Disable auto detection and grouping of overlayed slides
[...]
```

**Comment by asartori86** [comment]
Thanks @a123qwertz567, but it didn't help

```
$ pdfpc -g video-example.pdf 

** (pdfpc:10526): WARNING **: movie.vala:531: Error creating control pipeline: Could not make element overlay of type cairooverlay.
```

**Comment by AndreasBilke** [comment]
`cairooverlay` is in `gst-plugins-good` and it seems that your gentoo installation is not working properly. So I would say it is not a pdfpc issue.

**Comment by fnevgeny** [comment]
The upstream bug tracker: [https://bugs.gentoo.org/291150](https://bugs.gentoo.org/291150)
