### ISSUE TITLE
Not displaying presentation window on secondary display in DWM

### ISSUE THREAD

**Issue by amarala** [pdfpc/pdfpc#181]
pdfpc shows only the overview window on the primary monitor (the presentation window does not appear anywhere) when run on the dwm window manager (http://dwm.suckless.org/). I've tested it under versions dwm 6.0, 6.1 and the latest git revision, with pdfpc v3.1.1 and v4.0.2 on Ubuntu 15.04 and 16.04, and the same behaviour was observed. 

Any ideas?

**Comment by cdown** [comment]
You can do something like this: https://github.com/cdown/dwm/commit/74bc69e4a88255207353b4d904ffedda81ed5d32

**Comment by dev-zero** [comment]
same issue with i3

**Comment by dev-zero** [comment]
Ok, i3 got a fix this very same problem with LibreOffice's Impress [in 4.13](https://i3wm.org/downloads/RELEASE-NOTES-4.13.txt). Unfortunately, this does not solve the issue with the pdfpc presentation window. The reason for this might be, that pdfpc does not set the necessary properties on the presentation window. If you look at [how i3 detects the presenter for Impress](https://github.com/i3/i3/blob/f58dde28504cd78267439ec232be9689ff82d47c/src/manage.c#L360), you notice, that it looks for the `_NET_WM_STATE_FULLSCREEN` property in the `_NET_WM_STATE` atom. And indeed, comparing the `xprop` output for Libreoffice's Impress:

```
_NET_WM_ICON_GEOMETRY(CARDINAL) = 2284, 1048, 401, 32
XdndAware(ATOM) = BITMAP
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 7
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_FULLSCREEN
WM_CLIENT_LEADER(WINDOW): window id # 0x4800020
_NET_WM_PID(CARDINAL) = 2517
WM_CLIENT_MACHINE(STRING) = "scarlet.int.dev-zero.ch"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 1920 by 1200
		program specified maximum size: 2020 by 1300
		window gravity: Static
WM_CLASS(STRING) = "libreoffice", "LibreOffice 5.2"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		bitmap id # to use for icon: 0x48017c2
		bitmap id # of mask for icon: 0x48017c3
		window id # of group leader: 0x48017b4
_NET_WM_USER_TIME(CARDINAL) = 1906349
```

with the one for the pdpc presentation screen window:

```
_NET_WM_STATE(ATOM) = 
_NET_WM_ICON_GEOMETRY(CARDINAL) = 2254, 1048, 401, 32
_NET_WM_DESKTOP(CARDINAL) = 2
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x4000001
_GTK_THEME_VARIANT(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
_NET_WM_OPAQUE_REGION(CARDINAL) = 3, 0, 954, 3, 0, 3, 960, 1045
WM_WINDOW_ROLE(STRING) = "presentation"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 67108869, 67108870
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x4000004
WM_CLIENT_LEADER(WINDOW): window id # 0x4000001
_NET_WM_PID(CARDINAL) = 2256
WM_LOCALE_NAME(STRING) = "de_CH.utf8"
WM_CLIENT_MACHINE(STRING) = "scarlet.int.dev-zero.ch"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 1920 by 1080
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "pdfpc", "Pdfpc"
[...]
```

shows that `_NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_FULLSCREEN` is missing.

**Comment by dev-zero** [comment]
see also https://bz.apache.org/ooo/show_bug.cgi?id=110881

**Comment by AndreasBilke** [comment]
Okay, I use xmonad with arch linux and both windows have these x window
properties set. If one could find out how to explicitly set up this with
the code, I would be happy to merge this!

**Comment by dev-zero** [comment]
Ok, I checked the Gtk+ source code and they actually set the property when going into `fullscreen()` (actually `gdk_window_fullscreen`). Coming back to pdfpc and how you obtain the fullscreen with multiple move/unfullscreen/fullscreen calls in the `on_size_allocate` I guess that we are losing the property somewhere.

That gave me the idea to try and help pdfpc by setting the pdfpc windows to floating, which solved the issue :)
So, you need the following configuration for i3 to avoid tiling and then the window placement and fullscreen works with i3 4.13:

```
for_window [ title="^pdfpc - present" ] border none floating enable
```

**Comment by dev-zero** [comment]
... and to confirm, then I also get the following on the presentation window using `xprop`:

```
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN
_NET_WM_ICON_GEOMETRY(CARDINAL) = 2655, 1048, 401, 32
_NET_WM_DESKTOP(CARDINAL) = 6
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
I3_FLOATING_WINDOW(CARDINAL) = 1
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x4000001
_GTK_THEME_VARIANT(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 1920, 1200
WM_WINDOW_ROLE(STRING) = "presentation"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 67108869, 67108870
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x4000004
WM_CLIENT_LEADER(WINDOW): window id # 0x4000001
_NET_WM_PID(CARDINAL) = 4278
WM_LOCALE_NAME(STRING) = "de_CH.utf8"
WM_CLIENT_MACHINE(STRING) = "scarlet.int.dev-zero.ch"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 1920 by 1200
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "pdfpc", "Pdfpc"
[...]
```
