### ISSUE TITLE
`prev` command respects pdf labels when it should not

### ISSUE THREAD

**Issue by cdown** [pdfpc/pdfpc#182]
I was affected by #159, but even so, I should have been able to use `next` and `prev` without grouping, I believe. `next` operates as expected, but `prev` skips based on the page labels. I'm under the impression that only `prevOverlay` should do that.

**Comment by AndreasBilke** [comment]
Could you provide a MWE? I can not follow your issue.

**Comment by phillipberndt** [comment]
I think that this issue is what I've addressed in #186, right?

**Comment by cdown** [comment]
Yes, that sounds exactly the same. I'll confirm that it fixes it at some point soon.
