### ISSUE TITLE
Video is not framed properly

### ISSUE THREAD

**Issue by a123qwertz567** [pdfpc/pdfpc#184]
I successfully included a video in my presentation. When the video is started, the left bottom corner of the video appears in the top right corner of the frame/slide again. This fractal is visible in the presenter/note-preview, too.
I made some screenshots:

[http://imgur.com/a/MuDLS](http://imgur.com/a/MuDLS)
This happens in full screen and windowed mode. The Screenshots are from windowed mode.

I included the video with this latex code:
```
\subsection{Arbeitsweise mit dem Informationssystem}
\begin{frame}{Arbeitsweise mit dem Informationssystem}
\begin{figure}

\centering
\href{run:./video/weldtool_60_fss_qsub.ogv}{\includegraphics[width=1\textwidth]{video/vlcsnap-2016-11-26-15h05m40s084}}
	
\end{figure}
\end{frame}
```
It is not really a problem, just looks not right.

**Comment by AndreasBilke** [comment]
Could you provide a MWE?

**Comment by AndreasBilke** [comment]
Did this happen for every video and every time? I had a similar issue a few days ago. I had a presentation with a video and used the overview function. When I snapped back to the normal view I got very similar distortions.

**Comment by a123qwertz567** [comment]
I try to remember how I fixed it. Maybe I changed the codec or reinstalled another version of gstreamer.

Occured the error again since the last post? Quite a long time ago....
