### ISSUE TITLE
Allow change of font size for clock

### ISSUE THREAD

**Issue by oudou** [pdfpc/pdfpc#189]
Just like I can change the size of the notes, I'd like to be able to make the clock a little bigger since I'm not always right in front of my laptop when presenting.

**Comment by AndreasBilke** [comment]
You can use the css file (see rc/pdfpc.css) for this.

**Comment by oudou** [comment]
Perfect, just what I was looking for. I see there is mention of this in the man page, but I had just searched for "font" and did not see it at first. Thanks.
