### ISSUE TITLE
Reduce number of renderers and caches

### ISSUE THREAD

**Issue by rschroll** [pdfpc/pdfpc#19]
I was looking at the caching code and realized that in the typical case (two windows, no PDF notes), we have five separate renderers and caches all with the same content!  This may have been necessary when we were working with pixmaps, but now we're drawing with Cairo and can scale images easily.  So I think we should only render things once, at the highest resolution we might need, and then scale those as needed for the various views.

Because we want to handle PDF notes, we can't just make a single simple renderer and use it everywhere.  Instead, we'll either need two, one for the content and one for the notes, or one that does both.  I'm not sure which is better -- it's just a choice of where to hide the complexity.

This may alleviate #12 to a certain extent.

**Comment by AndreasBilke** [comment]
As long as we have a PNG cache for a small memory footprint, I see no chance to get rid of multiple renderers/caches. I did some experiments, and even the scall down from current_slide to next_slide (in presenter window) leads to ugly results. The simple cache (which just stores the ImageSurfaces) has no such problems.

We could reuse the cache for the strict views (the overlay ones). The user would not notice the ugly rendering. But the memory consumption for the small views is mostly not noticeable and therefor not worth the coding.

**Comment by phillipberndt** [comment]
That is weird. PNG is a lossless format, and Cairo's image surfaces are memory buffers for the rastered data, not containers for vector graphics instructions that are applied on the fly upon drawing to an actual device. Both methods should yield similar results.

Do results improve if you [use a different filter](https://www.cairographics.org/manual/cairo-cairo-pattern-t.html#cairo-pattern-set-filter) for downscaling?

**Comment by AndreasBilke** [comment]
Maybe I did not get the concept, but I tried in `View.Pdf.draw` the following
```
cr.scale(scale_factor_width, scale_factor_height);
cr.set_source_surface(this.current_slide, 0, 0);
var cairo_pattern = cr.get_source();
cairo_pattern.set_filter(Cairo.Filter.BEST);
cr.rectangle(0, 0, this.current_slide.get_width(), this.current_slide.get_height());
cr.fill();
```
The `current_slide` was at some size and I tried to scale it down a little. This resulted in a quite blurry rendering.

**Comment by phillipberndt** [comment]
I expected that the results would be blurry - after all, this is about replacing flexible resolution vector graphics with interpolated, rescaled versions of a single, large rasterized image. What puzzles me is that you get better results with the simple cache.

I've hacked together [a quick implementation to test this where you can toggle the feature](https://github.com/phillipberndt/pdfpc/commit/23ad4ea65e0ad3f89ad467d1d0e4e913805fbf5f). (When you start this version of pdfpc the first views are always rendered directly, so in order to see the rescaled, blurred versions, navigate away from the first slide and back. Note that I didn't bother about notes on slides, all renderers use the same cache.) I don't see any difference between the PNG cache and the simple cache.

**Comment by AndreasBilke** [comment]
Okay, but we use `ImageSurface` at every point anyway (which is a rastered graphic). Is there some vector drawing area in cairo?

**Comment by phillipberndt** [comment]
Even if there was, I doubt that it'd still be a speed improvement vs. no cache at all: The PDF/poppler document is a vector representation of the presentation, after all. The entire idea of the cache is to cache the rasterized variant to spare the vector drawing commands. I don't think that you can have a single cache without introducing some amount of blur to some of the views.

**Comment by AndreasBilke** [comment]
Then we can close this issue because the alternatives (with a cleaner
design) are worse than the current approach?

**Comment by phillipberndt** [comment]
One possibility is to make this a command line flag like in my hack. This
would give all users a choice regarding to which trade-off they prefer. (I
don't know how we could do an implementation which is less of a hack yet
simple though..)

**Comment by AndreasBilke** [comment]
Actually I am not a fan of this super-configurable stuff, it just increases the code complexity. I even dislike that we have a PNG cache, a ImageSurface cache and no cache at all :)

**Comment by phillipberndt** [comment]
Alright. In this case I concur that we can close this as unfixable.
