### ISSUE TITLE
Videos playing sound but not images

### ISSUE THREAD

**Issue by severin-lemaignan** [pdfpc/pdfpc#197]
I'm encountering an issue that puzzles me a little: presentations embedding video play the sound as expected, but no image.

It was previously working well, and stopped working without changing PDFPC version. This hints to a personal system environment issue, but I have investigated it carefully (cf below) without being able to isolate the culprit. Maybe someone might have an idea?

My configuration: Ubuntu 16.04, HiDPI laptop screen, gnome-shell, Intel HD5500 video card. The issue arise with the Ubuntu packaged version as well as with a fresh compilation from sources.

**What does not work:**
When the slides have videos, the sound starts playing as it should, but no image. Tested with several PDF, several video format, including the 'official' sample [video PDF](https://pdfpc.github.io/demo/pdfpc-video-example.zip). I get no warning/error on the command line (ie, no complains from `gstreamer`).

**What I've tested:**
- running the video directly with gstreamer (`gst-launch-1.0 filesrc location=<your video> ! decodebin ! autovideosink`): it works well (ie, the video is correctly played, both image and sound)
- creating a new user account (to make absolutely sure there is nothing dodgy in the environment) and starting `pdfpc` from there. Still doesn't work.
- tried in full-screen or windowed mode: no difference
- tried without grouping the overlays: no difference
- tried in a wayland session instead of X11: no differences with respect to the videos
- tried xfce instead of gnome-shell: no difference
- running `pdfpc` in a debugger does not help as everything works well from `pdfpc`'s perspective (ie, the video is handed over to `gstreamer` which starts playing it -- we hear the sound). Only the video does not appear.
- contrary to #224, compiling with `pdflatex`, `lualatex` or `xelatex` make no difference.

At that stage, my best guess is something goes wrong between `gstreamer`, `X11` and the Intel driver [except that it works if I call directly `gst-launch`). But I'm not sure how to investigate that. Any idea?

**Comment by AndreasBilke** [comment]
Are you having problems with every video or just some specific? Do you know
if there were some significant updates to pdfpc dependencies (like
gstreamer) in the meantime?

**Comment by severin-lemaignan** [comment]
Thanks @AndreasBilke for your quick answer.
The problem occurs with every videos.

The last time I am sure it worked was on December 1st. I've quickly checked the changelog of gstreamer-1.0 on packages.ubuntu.com, and no new release occured since that time...

**Comment by severin-lemaignan** [comment]
For the sake of completeness, I've tried with both `libgstreamer-1.8.0` (`xenial` repository on Ubuntu) and `libgstreamer-1.8.2` (`xenial-updates` on Ubuntu), with no success.

I should as well note that the same presentation works well on a different computer with Ubuntu 16.04 as well. This really hints at an issue with my environment/system. As described above, I've tried quite a few things I could think of, without much success :-/

**Comment by severin-lemaignan** [comment]
I'm still puzzled by this issue.

I've pasted here http://pastebin.com/SVF0dKX4 the output of `pdfpc` when displaying the `video-example.pdf` example, with `GST_DEBUG=*:INFO` to see exactly what happen on gstreamer's side.

At first sight, nothing particular stands out. The debug stream contains only 4 `WARN`, 2 related to sound (which works), 2 that say `basesrc gstbasesrc.c:3489:gst_base_src_start_complete:<source> pad not activated yet`. Does not sound to scary.

Could someone get the same log (cf below) and post it somewhere, to compare the two?

To get the log:
```bash
$ export GST_DEBUG=*:INFO
$ cd pdfpc/pdfpc-video-example
$ pdfpc video-example.pdf
# and then, skip to the second page with the right arrow, let the video play for 2-3 seconds, and quit
```

**Comment by severin-lemaignan** [comment]
I've as well tested using mesa's `llvmpipe` instead of the Intel OpenGL driver: no difference

**Comment by AndreasBilke** [comment]
Sorry that my log contains also the console control characters, but here it is: https://pub.bilke.org/2017-02-02-Gxm2KJYbRWo/pdfpc-video-example-debug.txt

**Comment by severin-lemaignan** [comment]
Thanks @AndreasBilke! I've diff'ed them, nothing stands out.

The interesting bit, though, is that neither the video stream *nor the cairo canvas* with the seek bar are drawn. Yet *the overlay is physically present*: the mouse interactions work for instance (if I click on different locations on the (invisible) seek bar, the sound correctly jumps to the corresponding point in the video).  It is really like the gstreamer rendering pipeline (maybe, the sink of the pipeline?) does not display the pixels.

I've tried to replace the `xvimagesink` [here](https://github.com/pdfpc/pdfpc/blob/master/src/classes/action/movie.vala#L297) by a `ximagesink`, same issue :-/

**Comment by severin-lemaignan** [comment]
Ok, if I now replace `xvimagesink` by `autovideosink`, the video opens in a new window, and plays correctly! Let's investigate other video sinks...

**Comment by severin-lemaignan** [comment]
Alright, I might have a lead:
`pdfpc` tells `gstreamer` were to display the video by [passing the X id of the window](https://github.com/pdfpc/pdfpc/blob/master/src/classes/action/movie.vala#L306). Using `gdb`, it appears that this `xid` value does not match any existing X window (as listed with `wmctrl -l`), and in particular, it does not match the ID of the `pdfpc` window. @AndreasBilke could you check with `gdb` that in a 'working' situation, the `xid` value [here](https://github.com/pdfpc/pdfpc/blob/master/src/classes/action/movie.vala#L306) does match the `pdfpc` window X ID?

**Comment by severin-lemaignan** [comment]
Using `xdotool windowmove <gstreamer subwindow xid> <x> <y>`, I'm able to move around the 'movie' window (which is just the static poster image). So this sub-window is indeed visible. It just does not render the gstreamer pipeline... (to be 100% that the poster is not displayed on top of the video, I've replace the poster by a transparent PNG, same result)...

What a nice, painful bug! :-)

**Comment by AndreasBilke** [comment]
Just to be sure: the `xvimagesink` does not work for you, but with `autovideosink` you get a video? Lets see if I can reproduce it on my machine (with ubuntu).

**Comment by severin-lemaignan** [comment]
Well, its is a bit more complicated: `xvimagesink`, by default, creates a new floating window, except if we pass a XWindow ID using the `Overlay` interface and `set_window_handle` ([as documented here](https://valadoc.org/gstreamer-video-1.0/Gst.Video.Overlay.html)). `autovideosink` chooses automatically a backend -- as a matter of fact I'm pretty sure gstreamer selects `xvimagesink` as well in my case. But, as `autovideosink` does not receive a XWindow ID, it simply creates its own window, and consequently, draws and renders correctly the video.

As such, this issue really seem to be: the attachment of a XWindow via `set_window_handle` leads to gstreamer not rendering anything.

**Comment by AndreasBilke** [comment]
I was able to test it on a ubuntu 16.04 machine. Unfortunately it worked properly there so I can't really help here.

**Comment by AndreasBilke** [comment]
Oh, I overlooked that you are using gnome under ubuntu. So my test setup was not the same as yours.

**Comment by severin-lemaignan** [comment]
Alright, I've eventually found something: videos play as expected when using KDE instead of Gnome/xfce. It works as well if I do not use any desktop environment, and instead I directly launch `pdfpc` in a X server.

As a matter of fact, from a gnome session, changing the compositor from `mutter` to `kwin` by running `kwin --replace` suffice to get the video working again...

**Comment by severin-lemaignan** [comment]
Good, after chatting with `gstreamer` developer, the issue comes from client side decorations and as a consequence, a mismatch between the X11 visuals of the mutter window and what gstreamer's `xvimagesink` is providing.

https://bugzilla.gnome.org/show_bug.cgi?id=721148

An easy workaround is to [disable client side decorations](http://www.webupd8.org/2014/08/how-to-disable-gtk3-client-side.html) or to use `glimagesink` in pdfpc (drop-in replacement for `xvimagesink`).

Using `glimagesink` seems the best option to me (obviously, it requires opengl, but I guess it is ok). I'll open a PR.

**Comment by phillipberndt** [comment]
If the window manager is part of the problem, then issuing [Gdk.Window.set_override_redirect](https://valadoc.org/gdk-3.0/Gdk.Window.set_override_redirect.html) on pdfpc's windows might help as well. (We'd need to *disable* redirects, and of course only do it if pdfpc doesn't run in windowed mode.) Changing [the decoration status](https://valadoc.org/gtk+-3.0/Gtk.Window.decorated.html) might have an influence as well.

I think the correct place to do that would be in [fullscreen.vala, function `on_mapped`](https://github.com/pdfpc/pdfpc/blob/master/src/classes/window/fullscreen.vala#L138). Just add `this.get_window().set_override_redirect(true)` somewhere.

**Comment by severin-lemaignan** [comment]
For reference, a copy-paste of the suggestions by the gstreamer dev:
```
ndufresne:  skadge, one way is to disable client side decoration
                   the other way is to use gtk_widget_set_visual()
                   Which require listing the visual from the GdkScreen
                   and pick one that has no alpha
                   the third option is to fix xvimagesink, to properly query the parent window rather then hardcoding a visual
                   skadge, there is more option, you could use gtksink, gtkglsink
skadge       ok! Thanks a lot! I'll try first with nocsd, and if it solves the issue, I'll investigate set_visual
ndufresne   or glimagesink
skadge       Yep, I've played a little with gtksink, but it would involve quite a bit of change to pdfpc...
ndufresne    skadge, what you would gain, is that it's no longer X11 specific
skadge        Would be an option, I guess, but I'll try first the others :-)
ndufresne    skadge, maybe give glimagsink a try, that binds you to GL though * glimagesink this one at least is a drop-in replacement
```

**Comment by severin-lemaignan** [comment]
@phillipberndt Yes, I was hoping to instruct pdfpc to bypass the compositor. However I tried your suggestion without success. I also tried setting `set_composited(false)`, but it does not solve the issue either.

**Comment by phillipberndt** [comment]
Thanks for testing, and also for pasting the chat log - it's interesting to know why xvimagesink fails. Since (I think?) pdfpc currently renders the video directly onto the presentation I doubt that it'd be a good idea to drop alpha support, so exchanging the gstreamer sink indeed seems to be the best option. (I'd still add the fallback and keep the dependency optional, but let's wait for @AndreasBilke's opinion for that..)

**Comment by AndreasBilke** [comment]
In would prefer the fallback solution (to have it only as an optional
dependency).
