### ISSUE TITLE
key binding increaseFontSize font size actually decreases font size

### ISSUE THREAD

**Issue by jfnk** [pdfpc/pdfpc#199]
Hi, 

using pdfpc on Fedora 25 Workstation, the keys to increase font size, e.g. + decrease the font size within notes. 

I changed the keybindings in pdfpcrc to other keys. The keys change but the effect stays the same: decreasing font size. Other changes to the pdfpcrc file work just fine. 

Since in F25, pdfpc V. 4.0.1 is available in the repositories, I compiled the latest release (4.0.5) from source. Still the same problem. The only way to increase font size for me is manually in the .pdfpc file. 

I am not using wayland. 

It seems like increaseFontSize and decreaseFontSize are internally mapped to the same value. 

Would be glad if somone could look into this issue. 
Joe

**Comment by AndreasBilke** [comment]
I can't reproduce this on my machine. Did you tried some other default key
mappings like bracketleft/right? On my keyboard, I trigger them with
`AltGr+8` which leads to `[` respectively.

**Comment by jfnk** [comment]
Yes, I also tried other key mappings like '[' and bound even simple lowercase letters to increaseFontSize but font size keeps on decreasing.

**Comment by AndreasBilke** [comment]
Could you do some debugging on your own? As I said, I can't reproduce it.
You have `public bool key_press(Gdk.EventKey key);` in
presentation_controller.vala . There you can trace which keys are handled
and to which action they lead.

**Comment by jfnk** [comment]
I will try, when I have some time...

**Comment by AndreasBilke** [comment]
Please re-open the issue when you debugged it. I tried several different platforms and I was never able to reproduce it with a standard installation.
