### ISSUE TITLE
Compile with modern vala

### ISSUE THREAD

**Issue by rschroll** [pdfpc/pdfpc#2]
pdfpc will not compile with any vala newer than 0.20 (see davvil/pdfpc#88).   We should get that fixed.

Unfortunately, it looks like the show-stopper is that the Gdk2 vapi is broken in valac 0.22 and higher.  Perhaps there's a way to correct that ourselves?  The real solution will be to move to Gtk3, which will be better supported (#3).

**Comment by andybarry** [comment]
We should also look at davvil/pdfpc#73 where some work has been done.

**Comment by rschroll** [comment]
With the changes from #3, pdfpc now compiles with valac 0.26.
