### ISSUE TITLE
Square Brackets in Notes lead to deletion in pdfpc-file when closing pdfpc

### ISSUE THREAD

**Issue by cmcx** [pdfpc/pdfpc#200]
When writing some notes in the presenter console I made the mistake to insert a word with square brackets: [word-in-brackets]
After closing pdfpc with the q command and reopening it, all notes after this entry including the [word-in-brackets] were gone, deleted from the .pdfpc file.

I now understand (after the fact) that this might be covered by the manual saying that the note section must be the last one in the file, but it would have saved me two hours of work if the manual had explicitly stated that using square brackets in the notes will violate this requirement and lead to unwanted consequences (in my case: deletion)

*Suggestion:* Put a note in the manual saying that using square brackets in the notes is not a good idea.

**Comment by AndreasBilke** [comment]
Could you check PR #201 if this fix your problem? Square brackets are now allowed and are escaped properly in the pdfpc file.

**Comment by cmcx** [comment]
That seems like a very good solution to me. Thank you! (Closing this now.)
