### ISSUE TITLE
Full screen notes for current slide?

### ISSUE THREAD

**Issue by cdown** [pdfpc/pdfpc#208]
How can one get full screen notes? I thought this could be achieved by setting `current-height` to 100 and `next-height` to 0, but that still results in this:

![2017-02-04_151144_231709237](https://cloud.githubusercontent.com/assets/660663/22619418/3f96ed54-eaec-11e6-9bbc-26c4e0d1750d.png)

Setting `next-height` to 1 *does* result in the next slide getting smaller, but the current slide notes don't get any bigger:

![2017-02-04_151032_764277851](https://cloud.githubusercontent.com/assets/660663/22619411/1b1fff2e-eaec-11e6-88fa-05405dc36839.png)

My ultimate goal is to have *only* the current slide's notes take up the full screen.

This is with `pdfpc -S -n right foo.pdf`, on version 4.0.5. All that's in my config is this:

```
option current-height 100
option next-height 0
```

Thanks!

**Comment by AndreasBilke** [comment]
This sizing stuff seems a little buggy to me and I think it was never intended
to "hide" the next screen.

The best you can get is with

option current-size 99
option current-height 100

Note that current-size should not be 100, otherwise you might get more
buggy results :)

**Comment by cdown** [comment]
Thanks! That works pretty good for now. Maybe I'll put up a PR some time to support single slide notes.
