### ISSUE TITLE
Refactor caching

### ISSUE THREAD

**Issue by phillipberndt** [pdfpc/pdfpc#211]
This is a potential solution for #12, and, in reply to @AndreasBilke's comment in #19, an idea that would reduce code complexity of the caches significantly. I'd like to put the following proposition up for discussion:

* Remove the current cache implementations (PNG, persistent, simple) entirely
* Move prerendering and cache functionality completely into the renderer
* Always prerender into a Cairo ImageSurface (which can be done from a separate thread without blocking, I do that in pqiv as well)
* Support two variants of the renderer:
  * One prerenders all slides and maintains them in an array of image surfaces. We'll use this one for the overview page, which renders to very small buffers, so the memory footprint should remain small.
  * The other prerenders slides that are reachable from the current slide, e.g. the next/previous user/real slides. This means that per navigation request by the user, one new slide must be prerendered for every view. The advantage is that this can be initiated *after* displaying the new slide, because the new one has already been prerendered - so it won't be noticeable by users unless they skim very fast through the slides. *Only* the four mentioned slides plus the current one are maintained in a cache; ones not directly reachable are purged. This should keep the memory footprint low, while still allowing fast navigation between slides.

Disadvantages:
* Breaks backwards compatibility (since this will remove three command line parameters). This could be mitigated by maintaining support for the flags for a while and printing a warning when they are used.
* Navigation via the overview page is slow, because the target slide is likely not currently cached. Since the overview page is normally only used after a talk during discussion, this shouldn't be a big issue.
* Skimming through slides can become slow, which admittedly is a use case that might happen during presentations. We need to keep in mind that rendering the pages is very fast, it's the PNG compression that takes much time / processing power. So this might be acceptable.

What do you think? I'd prepare an implementation if you think that this is a good idea.

**Comment by AndreasBilke** [comment]
So just to get you correct: each view has still its own rendering functionality (and "cache") and each view is rendering in its native resolution? And to make slide switching less laggy a view has some kind of sliding window of already rendered slides? I like that idea!
To the disadvantages:
- I personally don't care much for this. We can increase the version to something like 4.1 or even 5.0 to show that something bigger happend.
- We could prerender all the overview slides anyway. Since the resolution is small there is no high memory footprint. This way one could use the overview like now.
- Instead of having just one slide prerendered ahead, we might have a window of +- 3 slides. This would indeed be more complex than just one slide but we could mitigate the problem of fast slide switching.

**But** could you please wait some time with this implementation? I currently rewrite the the sizing logic for pdfpc completely. With this, I throw away a lot of filthy cluttered code in all windows and the pdf view. I don't know when I'm finished but there is still some work to do.

**Comment by phillipberndt** [comment]
> And to make slide switching less laggy a view has some kind of sliding window of already rendered slides? 

Those, and the slides that are most likely to come up next.

> But could you please wait some time with this implementation? I currently rewrite the the sizing logic for pdfpc completely. With this, I throw away a lot of filthy cluttered code in all windows and the pdf view. I don't know when I'm finished but there is still some work to do.


Will do.

**Comment by AndreasBilke** [comment]
I postponed the rewrite. I did not get it to work without some fixed size calculations at some point. If you like, you can work on here.

**Comment by phillipberndt** [comment]
Early steps: https://github.com/phillipberndt/pdfpc/tree/cache-reimplementation

The code already has one common cache per render resolution, but I'm not sure whether I'm happy with the interface yet. It's definitively too early to talk about details, I mainly wanted to share this to show where this could be going & to leave a note that I haven't forgotten about this :-)

**Comment by AndreasBilke** [comment]
Maybe I get the code wrong, but: The views are cached for the whole time and are not purged after some slides? So in the end, we have all slides in memory?

**Comment by phillipberndt** [comment]
That's the part of the interface I'm unhappy about.. the `invalidate_caches` calls are currently used to invalidate the caches explicitly.

**Comment by fnevgeny** [comment]
OK, I suggest the following structural changes:

- there is just one `Renderer`
- the `Renderer` keeps a number of `Cache`'s; these are private objects
- each "user" (`View`) just calls `Renderer.render_to_surface()` as needed
- the responsibility of prerendering/clearing/updating/etc of the caches lies exclusively with `Renderer`
- the support for the persistent (on-disk) cache is removed. With good caching algorithms it should not be needed.

I believe by keeping the entire logic inside a single object, it will be easier to implement smart/robust caching algorithms. What do you think?

**Comment by AndreasBilke** [comment]
> the `Renderer` keeps a number of `Cache`'s; these are private objects

One cache per resolution? So the presenter view has 3 caches, the
presentation view one?

> the support for the persistent (on-disk) cache is removed. With good
> caching algorithms it should not be needed.

There is also an open issue for background threaded rendering. That should
also reduce the need for disk-caching.

> What do you think?

Sounds good! It reduces the complexity which is always a good idea.

**Comment by fnevgeny** [comment]
> One cache per resolution? So the presenter view has 3 caches, the presentation view one?

In the simplest case, yes. But recall that now the fullscreen/windowed mode can be switched during the presentation, and in the windowed mode, the size is not fixed. Add to that support for the monitor plug-and-play which is on the horizon (#408) and possibly auxiliary screens (#396)...

> There is also an open issue for background threaded rendering. That should also reduce the need for disk-caching.

Yes, of course.

**Comment by fnevgeny** [comment]
> Add to that support for the monitor plug-and-play which is on the horizon (#408) and possibly auxiliary screens (#396)...

As well as #414 and #421...

**Comment by fnevgeny** [comment]
One more comment. What to do with the cache status/progress widget? If the cache is (re)built asynchronously, this indicator will be shown at unpredictable times as well. It may be good as a debugging aid for developers :), but for users, it will likely be distracting. So I suggest to get rid of it. OK?

**Comment by AndreasBilke** [comment]
@fnevgeny yes, you are right

**Comment by AndreasBilke** [comment]
Implemented with #447
