### ISSUE TITLE
Feature Request: Reload from file

### ISSUE THREAD

**Issue by ber532k** [pdfpc/pdfpc#212]
Would it be possible to add an action to reload the pdf from disk while staying on the same slide? Something similar to vim's ``:e`` command. This could be usefull if one wants to use a slide for brainstorming or summarizing a discussion during some interactive part of the presentation.  Sort of like you sometimes do with a blackboard.

**Comment by AndreasBilke** [comment]
I mean, technically, it would be possible but I think it is out of scope
for a presentation tool to allow such things. There are many pure PDF
viewers which allows reloading if the file changed.

**Comment by ByteHamster** [comment]
I don't think this is out of scope. I create my presentations using LaTeX, sometimes there is an error on the slides. So I alt+tab to the editor, change the slide, compile ... and then I need to restart pdfpc and try to find the current slide again.

**Comment by mgkuhn** [comment]
Fixed in https://github.com/pdfpc/pdfpc/issues/409
