### ISSUE TITLE
Additional pdfpcrc options for default font size and cursor size

### ISSUE THREAD

**Issue by Drup** [pdfpc/pdfpc#219]
Those two are quite too small for me, I would like to make them bigger for all my presentations. An option in the configuration file would be convenient.

**Comment by AndreasBilke** [comment]
You can configure some things in the pdfpc.css file. Did you tried it? I would not increase default font sizes since everybody has some other opinion about "nice defaults" and if you can change it with your own css it is fine this way.

**Comment by Drup** [comment]
I haven't tried modifying the css. I can try that.

I was not asking for a change of the default, just an option in pdfpcrc. ;)

**Comment by AndreasBilke** [comment]
Yes, I was to quick when reading your issue. But still, changing it in the css file is as good as having a config file option :)
