### ISSUE TITLE
Support for beamer notes: show both notes, next slide and current slide!

### ISSUE THREAD

**Issue by jbaum98** [pdfpc/pdfpc#220]
I wanted to link to this issue: davvil/pdfpc#45. 
It is a feature request suggesting that when beamer notes are being displayed, the notes slide be displayed alongside the actual slide in the presenter view rather than in its place.
Was this ever implemented in this fork?

**Comment by AndreasBilke** [comment]
No it wasn't and I don't like this feature at all. It would result in changing layouts based on some conditions. And what would be the correct way if you have conflicting options (like text notes and latex beamer notes)?

**Comment by mbanck** [comment]
The documentation already states that
```
These [internal] notes take precedence over the native PDF annotations, i.e., if a user-proveded note exists for a given slide, any PDF annotations on that page will be silently ignored.
```
Using e.g. http://www.pdfill.com/example/pdf_commenting_new.pdf I see that the annotations in there are presented like pdfpc notes. And the quote from the documentation makes it clear that pdfpc notes take precedence, so why not treat latex-beamer notes like pdf annotations? This sounds like the most natural approach to me.

An alternative would be to have an extra mode where both the previous and the next slide are shown along with the current slide (some presenter consoles do this I think), and have the latex-beamer notes be either the previous slide or the current slide.

**Comment by AndreasBilke** [comment]
> [...] so why not treat latex-beamer notes like pdf annotations?
> This sounds like the most natural approach to me.

Because latex-beamer notes are just "a bigger slide" and we cut off
one half of the page. There is no way to parse the latex-beamer notes and
make them behave like all other types of notes.

**Comment by mbanck** [comment]
Right, I came across the same conclusion.

So how about a key binding or option where the user can switch the notes slides between the current and next slide? That way, you could decide for yourself which is more important right now, and it should be pretty easy to implement.

**Comment by AndreasBilke** [comment]
> So how about a key binding or option where the user can switch the notes
> slides between the current and next slide? That way, you could decide for
> yourself which is more important right now, and it should be pretty easy
> to implement.

Your PR is very welcome! :)

**Comment by mbanck** [comment]
For the record, I managed to hack pdfpc (4.0.5, which is in Debian stable) to my liking, but this is a WIP as it does this unconditionally:

```
--- pdf-presenter-console-4.0.5.orig/src/classes/window/presenter.vala
+++ pdf-presenter-console-4.0.5/src/classes/window/presenter.vala
@@ -163,7 +163,7 @@ namespace pdfpc.Window {
                 metadata,
                 current_allocated_width,
                 (int) Math.floor(Options.current_height * bottom_position / (double) 100),
-                Metadata.Area.NOTES,
+                Metadata.Area.CONTENT,
                 Options.black_on_end,
                 true,
                 this.presentation_controller,
@@ -183,7 +183,7 @@ namespace pdfpc.Window {
                 metadata,
                 next_allocated_width,
                 (int) Math.floor(Options.next_height * bottom_position / (double)100 ),
-                Metadata.Area.CONTENT,
+                Metadata.Area.NOTES,
                 true,
                 false,
                 this.presentation_controller,
@@ -423,9 +423,9 @@ namespace pdfpc.Window {
             try {
                 this.current_view.display(current_slide_number);
                 this.next_view.display(this.metadata.user_slide_to_real_slide(
-                    current_user_slide_number + 1));
+                    current_user_slide_number));
                 if (this.presentation_controller.skip_next()) {
-                    this.strict_next_view.display(current_slide_number + 1, true);
+                    this.strict_next_view.display(current_slide_number, true);
                 } else {
                     this.strict_next_view.fade_to_black();
                 }
@@ -461,7 +461,7 @@ namespace pdfpc.Window {
         public void goto_page(int page_number) {
             try {
                 this.current_view.display(page_number);
-                this.next_view.display(page_number + 1);
+                this.next_view.display(page_number);
             } catch( Renderer.RenderError e ) {
                 error("The pdf page %d could not be rendered: %s", page_number, e.message);
             }
```

I will see about a proper PR eventually

**Comment by AndreasBilke** [comment]
Your PR is very welcome!

**Comment by nikonikolov** [comment]
@mbanck Thanks for your code, saved my life!

**Comment by cristobaltapia** [comment]
@mbanck Thanks for the patch! This was the only reason I was still using `dspdfviewer`. I also changed the sizes of the page for the notes (larger) and of the content (a bit smaller), by editing the file `src/classes/options.vala`.
Regarding the swap of the "content" and "notes" areas in the patch, I think that this should be the normal behavior when using beamer notes, since otherwise the use of the pointer and drawing functions is done on the "notes" area, where one cannot see the content.

@AndreasBilke thanks a lot for this software! It is really great! My presentations really shine now :P

**Comment by cristobaltapia** [comment]
The only problem with this fix is that the overview shows the notes page and not the slides. How can I change that?

**Comment by memeplex** [comment]
I think a limitation of this approach would be https://github.com/pdfpc/pdfpc/issues/443.

It's better to toggle the main view between current slide and notes using a shortcut.

**Comment by fnevgeny** [comment]
See #479.
