### ISSUE TITLE
non-primary screen no longer shows

### ISSUE THREAD

**Issue by emacsomancer** [pdfpc/pdfpc#221]
Apparently as of the latest update I am no longer getting the "audience"-view output on the non-primary/external display. (So, I'm only getting the "presenter" view on my screen and no pdfpc display on the other screen.)

**Comment by napseis** [comment]
hi,
I'm on Ubuntu Linux, and I discovered the same issue was introduced for me by commit f19307bf0c404ce8a5b3876ced3a324ffc294426
Maube try to build from the one before as a workaround ?

**Comment by AndreasBilke** [comment]
Could you give some information about your distribution, window manager and so on?

**Comment by napseis** [comment]
hi,
As for me, Ubuntu 16.04 with KDE plasma desktop.

**Comment by emacsomancer** [comment]
I'm using Arch Linux w/ kernel 4.9 w/ AwesomeWM as my window manager (no DE).

**Comment by AndreasBilke** [comment]
@emacsomancer Sorry for the very late response. Did you read the README? There is a section about tiling window managers and moving of windows to the correct screen.

We removed the trial and error approach for moving stuff in favor of a more clean solution for widely used WMs.

**Comment by napseis** [comment]
hi,
Does someone have a solution for Kwin please ?

**Comment by AndreasBilke** [comment]
Please fill out a proper issue form

Am 10. November 2017 11:56:33 MEZ schrieb Napseis <notifications@github.com>:
>hi,
>Does someone have a solution for Kwin please ?
