### ISSUE TITLE
make error with vala-0.36 on Mac OSX

### ISSUE THREAD

**Issue by hayneswa** [pdfpc/pdfpc#223]
When compiling from source on Mac OSX with vala-0.36, I would get the following error:

`/Users/hayneswa/Downloads/pdfpc-pdfpc-77c2c01/src/classes/window/overview.vala:302.32-302.35: error: Argument 1: Cannot pass value to reference or output parameter
            this.slides.remove(iter);`

Reverting to vala-0.32.1 resolved this error. Might be helpful to indicate this issue in documentation.

**Comment by PeterJackNaylor** [comment]
Hi,

Thanks for the reporting, I was also having diffculties. 
However I have only one window (only presenter view or only presentation view)
Do you have the same problem? (i am asking because I have just compiled from source and encoutered the same vala problem)

**Comment by AndreasBilke** [comment]
Oh nice, they changed the API in a non compatible way!

**Comment by AndreasBilke** [comment]
@hayneswa are you able to fix the problem by yourself? I have no access to vala 0.36 currently. Otherwise it has to wait until 0.36 hits arch linux.

**Comment by hayneswa** [comment]
I end up with the same issue that @PeterJackNaylor described, where I only get one window that is either presenter view or presentation view. This was my first time using pdfpc on mac (used it for a long time without problem on ubuntu), so I don't know if this was an issue on mac before.

**Comment by AndreasBilke** [comment]
Fixed with the latest commit.

**Comment by hayneswa** [comment]
Confirmed that this fix works on my machine. Thanks!
