### ISSUE TITLE
xelatex  : video only plays sound

### ISSUE THREAD

**Issue by dcherian** [pdfpc/pdfpc#224]
Xubuntu 16.04, pdfpc git master

When compiling video-example.tex with pdflatex, everything works as it should.

When compiling with xelatex, I hear sound but get no video.

Have you seen this issue before?

**Comment by dcherian** [comment]
Same problem with pdfpc 4.0.2 from apt

**Comment by phillipberndt** [comment]
Might be related to #197. Which of the different embedding methods do you use? If it is not too inconvenient, could you attach an example to this bug?

**Comment by dcherian** [comment]
I can reproduce by compiling https://pdfpc.github.io/demo/pdfpc-video-example.zip with xelatex. With pdflatex all slides work perfectly. With xelatex none of the embedding methods show video (only play audio)

**Comment by severin-lemaignan** [comment]
Now this is interesting! As reported in #197, I'm encountering the same issue, and, like you, I do not usually compile with `pdflatex` (I normally use `lualatex`).

**Comment by severin-lemaignan** [comment]
For reference, I attach the PDFs generated by `pdflatex`, `lualatex` and `xelatex` for this minimal example:
```tex
\documentclass{beamer}
\usepackage[english]{babel}
\newcommand\video[2]{\href{run:#2}{\resizebox{#1}{#1}{Click me}}}

\begin{document}
\begin{frame}{Video playback}
    \centering
    \video{7cm}{figs/videoclip.webm}
\end{frame}
\end{document}
```
[presentation.xelatex.pdf](https://github.com/pdfpc/pdfpc/files/952128/presentation.xelatex.pdf)
[presentation.pdflatex.pdf](https://github.com/pdfpc/pdfpc/files/952127/presentation.pdflatex.pdf)
[presentation.lualatex.pdf](https://github.com/pdfpc/pdfpc/files/952126/presentation.lualatex.pdf)

**Comment by phillipberndt** [comment]
Closing this in favour of #197, I'll reply there with a detailled answer.

**Comment by phillipberndt** [comment]
Never mind - it's two different bugs after all.

@severin-lemaignan Your three example files *all* display fine here. But I've tried to compile the example myself as @dcherian suggested, and that is indeed broken.

However, this is due to a bug xelatex, not in pdfpc: The resulting PDF reports that the action mapping should be drawn in a zero pixel square. pdfpc attempts to comply and of course fails, because you can't render a video in a zero pixel square. Acrobat Reader even displays an error message if trying to view the page with the embedded video - if I instead open the presentation as created by pdflatex in Acrobat, I see the overlay image and a hyperlink, as expected.

**Comment by severin-lemaignan** [comment]
Yes, after further testing tonight, I confirm these are 2 different bugs. I still encounter bug #197 be it with `pdflatex`, `lualatex` or `xelatex`.

**Comment by dcherian** [comment]
@phillipberndt Can you file an upstream bug with xelatex? I don't know enough to file a useful bug report, I don't think.

**Comment by dajuno** [comment]
Hi, has there been any progress on this issue?
Thanks

**Comment by AndreasBilke** [comment]
@dajuno This issue was closed since it's not a pdfpc bug but a xelatex.

**Comment by dajuno** [comment]
@AndreasBilke Ok, do you know if the bug was reported on the xelatex side?

**Comment by AndreasBilke** [comment]
Sorry I don't know that

Am 9. September 2018 11:17:01 MESZ schrieb David <notifications@github.com>:
>@AndreasBilke Ok, do you know if the bug was reported on the xelatex
>side?

**Comment by fnevgeny** [comment]
@dajuno If **you** do not report it, it will not be reported.
