### ISSUE TITLE
Automatically advancing slides

### ISSUE THREAD

**Issue by gunnarx** [pdfpc/pdfpc#229]
Is there a way to automatically advance slides based on a second timer?  I didn't see it in the man page and if there isn't such a feature, let's consider this a feature request.

**Comment by gunnarx** [comment]
Found the program "impressive" that has this feature and I can use it for the moment.  I'll leave it here anyway because it seems like a good feature.

**Comment by fnevgeny** [comment]
Please note that pdfpc allows for controlling it via DBus, so it's fairly trivial to script the auto advancing. Something like

```shell
#!/bin/sh

PERIOD=60

INTERFACE_NAME=io.github.pdfpc
INTERFACE_PATH=/io/github/pdfpc

while :
do
    sleep ${PERIOD}
    dbus-send --type=method_call --session --dest=${INTERFACE_NAME} \
        ${INTERFACE_PATH} ${INTERFACE_NAME}.TriggerAction string:next
done
```

Run this script in the background (or from another terminal), and then start pdfpc. Voila!

**Comment by AndreasBilke** [comment]
Very nice. So I prefer to close this since there exists a good solution.
