### ISSUE TITLE
Feature Request : Ability to save and reload current page

### ISSUE THREAD

**Issue by pantale** [pdfpc/pdfpc#230]
Hi,

I discovered this wonderfull application and found it very usefull for me. There is only one thing for me that will make it better, is the ability to save and reload the current slide for a next session. 

I'm professor and would like to use this for my courses, what I would like is the ability to press a key at the end of a session (for example 'X') and this will save the current page number of my slideshow in a file (for example the associated local file .pdfpc.

Then some days later, I reload the same pdf file to continue my class and by pressing for example key 'R', pdfpc will read the last displayed page number from the file and jump to this one.
So I can continue my presentation from the last slide I stopped last time.

I hope that this can be included in one of the next versions of pdfpc.

Kindly Regards,

Olivier Pantalé

**Comment by pantale** [comment]
Hi,

I have done the implementation myself, but I don't know how to give you back the source if you are interested in merging my modifications.
[pdfpc_modified.tar.gz](https://github.com/pdfpc/pdfpc/files/978248/pdfpc_modified.tar.gz)


Olivier Pantale

**Comment by AndreasBilke** [comment]
I took your changes and edited some small parts. See #231.
