### ISSUE TITLE
High CPU usage after video has finished playing (H264 in MP4 container)

### ISSUE THREAD

**Issue by tilman2** [pdfpc/pdfpc#235]
I have embedded a 4 MB MP4 file with a H264 (and AAC) payload in a Latex beamer presentation via the multimedia's package \movie command. The clip is configured to play on click.

While the clip is playing, a single pdfpc thread is running at about 30% CPU usage (the others are sitting at about 8%). Once the clip has finished playing, a bunch of threads named multiqueue1:src are jumping to about 50% CPU usage, and are staying there. According to perf, the CPU time is spent inside libavcodec-ffmpeg.so.

I cannot reproduce this problem with the sample AVI file that's part of the pdfpc video demo, so I guess it depends on the kind of codec used. OTOH it seems that pdfpc isn't properly stopping video playback...

I'm running pdfpc 4.0.2 on an (up to date) Ubuntu 16.04. system.

**Comment by AndreasBilke** [comment]
Could you post the video for further analysis?

**Comment by phillipberndt** [comment]
No need, I can reproduce the issue. The problem seems to be the way the "pause" function is implemented: It seeks to the current stream position every 50ms, which is expensive for some videos. Simply removing `start_refresh` reduces CPU usage to 0, but hides the controls overlay as well.

I'm currently investigating alternatives.

**Comment by phillipberndt** [comment]
I've pushed a solution to [@phillioberndt/pdfpc/bug235](https://github.com/phillipberndt/pdfpc/tree/bug235). I didn't find a way to redraw the controls without seeking either, but at least it's possible to reduce the number of redraws by redrawing only upon mouse movement rather than every 50ms.

**Comment by tilman2** [comment]
I can confirm that your patch fixes the problem. Thank you.

**Comment by phillipberndt** [comment]
I just found [an expose method in the GstVideoOverlay interface](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/GstVideoOverlay.html#gst-video-overlay-expose). That'd probably be a better solution.

**Comment by phillipberndt** [comment]
..but calling it doesn't retrigger the cairo overlay, and the cairo overlay doesn't have its own expose method. So we'll have to stick with the solution we already have.
