### ISSUE TITLE
Hangs on startup (Linux, tiling WM, no screensaver installed)

### ISSUE THREAD

**Issue by tomszilagyi** [pdfpc/pdfpc#236]
I am trying to use pdfpc on Linux. I am using the `i3` window manager (a tiling WM) with no screensaver installed on the system.

When I start pdfpc (compiled from latest git master), it hangs for about 27 seconds. This happens all the time, and there is no CPU activity during this period. It is just sitting there, waiting for a timeout (according to `strace`, it's waiting in a poll). If I wait patiently, the program eventually starts up and displays the two screens. However, this is a show-stopper to using pdfpc live, because I can only start it when the external (presenter) screen is already connected (to detect and size correctly), and then I don't have time to wait.

I have been looking at the source to see what is going on at startup and found that the following piece of code is what makes the startup hang. In src/classes/presentation_controller.vala, constructor of PresentationController, line 278:
```
            try {
                this.screensaver = Bus.get_proxy_sync(BusType.SESSION, "org.freedesktop.ScreenSaver",
                    "/org/freedesktop/ScreenSaver");
                this.screensaver_cookie = this.screensaver.inhibit("pdfpc",
                    "Showing a presentation");
                GLib.print("Screensaver inhibited\n");
            } catch (Error error) {
                // pass
            }
```

If I remove this part and recompile, pdfpc starts up instantly, just as it should. Is there a better way to fix this problem?

I am happy to provide additional diagnostics if you tell me what to do or look at.

**Comment by phillipberndt** [comment]
Maybe it suffices not to use the synchronous API - the timeout remains the same, but it won't block pdfpc anymore. Could you test whether https://github.com/phillipberndt/pdfpc/tree/bug236 works as expected?

**Comment by tomszilagyi** [comment]
@phillipberndt Thanks! Unfortunately the issue does not go away with your change. It is different though: the presenter and presentation windows are created right away, but then they remain black for the same amount of time.

Isn't there a way to ask the system whether there is a screensaver running in the first place, and not bother inhibiting it unless there is? (sorry, naive question)

**Comment by phillipberndt** [comment]
That should happen automatically. You're running into some timeout, either while connecting to Dbus (if you're not running a session dbus daemon) of while attempting to connect to the `org.freedesktop.ScreenSaver` interface. Since you're still experiencing issues with my commit, I'd guess that the latter is the case. I've updated the branch to call inhibit asynchronously as well - how about now?

**Comment by tomszilagyi** [comment]
@phillipberndt That did the trick, thanks a lot!

NB.: I got this warning when compiling, it's new as far as I remember:

```
warning: unhandled error `GLib.IOError'
                        this.screensaver_cookie = this.screensaver.inhibit.end(res);
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Target still built and seems to work as expected.
