### ISSUE TITLE
Support notes per overlay

### ISSUE THREAD

**Issue by Tamriel** [pdfpc/pdfpc#239]
In Latex it is possible to show a note starting from a specific overlay with `\note[item]<2->{my note}`.
It would be nice to edit the notes per overlay, not per frame.
This could be done with this syntax:

````
### 2.1
note for the second slide
### 2.2
note for the first overlay of the second slide
````

**Comment by AndreasBilke** [comment]
But some people like to have the same notes on every overlay page. Do you have any idea how to handle both types of notes?

**Comment by Tamriel** [comment]
I create the notes with [pdfpc-latex-notes](https://github.com/cebe/pdfpc-latex-notes). Therefore notes which are visible on every overlay page would be in each subsection:
````
\note[item]{visible on all overlays}
\note[item]<2-3>{visible on 2 and 3}
\note[item]<3>{visible on 3}
````
would create
````
### 2.1
visible on all overlays
### 2.2
visible on all overlays
visible on 2 and 3
### 2.3
visible on all overlays
visible on 2 and 3
visible on 3
````
Editing from the pdfpc view would edit the note per subsection, so to have a note on every overlay page one would have to insert that note on every subsection.
I think users with that wish are the minority. What do you think?

**Comment by AndreasBilke** [comment]
I would say users with "per overlay notes" are the minority, but in general
I support both ways of having notes.

I'm just searching for a convenient behaviour to support both ways
simultaneously.

**Comment by ChasNelson1990** [comment]
I realise this is already tagged as a low priority enhancement but I would just like to second that this would be a really useful feature.

Case example:
In my teaching slides I have a bullet list in a lefthand column and then overlays with a image or diagram representing each item in a righthand column. My notes normally describe what the image is and where it's from, lots of technical details that don't need to be on the slides (although often end up in my article-mode copy).
Currently I can add `\pnotes{}` to each `\only<>{}` statement but I only see the final set of notes for that slide and get passed the error "Found conflicting notes for slide X". If I disable grouping though my notes and slides go completely out of order.
My current fix is to add all the notes outside of my `\only<>{}` commands but manually adding the overlay number at the start of each note. But this can end up being a lot of text that it's easy to get lost in.

Possible Solution:
This might be naive but following @Tamriel's suggested syntax of:
```
### 2.1
note for overlay 1
```
The way to combine both options would be to take the following syntax(es):
```
### 2
note for all overlays
### 2.
note for all overlays
### 2.0
note for all overlays
### 2.1
note for first overlay
```
This would require some adjustment to [pdfpc-latex-notes](https://github.com/cebe/pdfpc-latex-notes), which I also use, but I think would simplify the needed modifications and prevent failure of previously compiled presentations?

**Comment by fnevgeny** [comment]
I also want this.

My suggestion would be to have it as a config option - either notes are per-slide (aka overlay) or per-user_slide. People who want per-slide are LaTeX folks (i.e., those who use LaTeX to produce both slides and notes). Or maybe there will be a support in OO for this in the future. On the other hand, defining per-slide notes using the built-in pdfpc editor would be a tedious process (imagine what headache would cause attempt to get the same functionality as beamer's \only<> etc). What I hint here at, is that users who use the built-in notes editor will never want this. I believe it's not a coincidence that, so far, everyone voting for this functionality are LaTeX users.

So with this option flag, all we need is to save it in the .pdfpc file. The rest of the syntax could remain the same, but the page numbers (### N) would be interpreted differently - as either slide_number or user_slide_number. A .pdfpc file with this flag absent would be treated in the backward-compatible way. 

And, I can't help but mention that probably [.pdfpc files are not needed when using LaTeX for presentations.](https://github.com/pdfpc/pdfpc/issues/300) :)

**Comment by merlinthered** [comment]
I'd like to add my support for this. I think adding per-overlay notes on top of the existing ones like @ChasNelson1990 suggests would be a good solution. It is especially useful if you have a complex animation with overlays that needs a lot of notes. They may not fit inside the notes window, but you can't easily split the animation up into multiple slides.
