### ISSUE TITLE
Overlay preview size

### ISSUE THREAD

**Issue by kakila** [pdfpc/pdfpc#244]
Hi all,

I was trying to make the preview of the overlay bigger, but couldn't.
I tried changing the values of 

option current-size

and 

option current-height

In the rc file, but none of them affect the relative size of current slide and next overlay.

Thanks!

**Comment by AndreasBilke** [comment]
Which version do you use? For me, `current-size` changes the size of the current slide and therefor also for the overlay previews. The change is size is not that big but I think it is intended that the overlay preview is just a small hint and not a good visible preview for the overlays.

**Comment by kakila** [comment]
> $ pdfpc --version
> pdfpc v4.0.2
> (C) 2015-2016 Robert Schroll, Andreas Bilke, Andy Barry and others
> (C) 2012 David Vilar
> (C) 2009-2011 Jakob Westhoff
> 
> License GPLv2: GNU GPL version 2 <http://gnu.org/licenses/gpl-2.0.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law
I would like to see the next overlay big enough to read from it. Note that the next slide is shown big enough, but once it is as overlay you cannot see it. Another option would be to disable the mini preview completely.

**Comment by AndreasBilke** [comment]
You mean `overview-min-size`? You should increase this in your `pdfpcrc`
