### ISSUE TITLE
Unable to get fullscreen rendering, and stuck on first slide

### ISSUE THREAD

**Issue by Djoop** [pdfpc/pdfpc#245]
Hi,

I'm running pdfpc v4.0.6 on Fedora 25, using Awesome window manager. The second screen has a higher resolution than the laptop (primary screen), and is configured using xrandr. What happens is the following:
- if I use windowed mode "-w", then I can freely move the desired window on the external screen, but I cannot get if fullscreen (the window can be maximized, but the rendered part stays the same, so is quite small compared to the size of the screen). I can change the slides as expected, though.
- if I don't use any option, the second screen is recognized correctly and the slides displayed at the desired resolution on the external screen, but the rendered area is cropped (I guess to the resolution of the first screen, which is smaller ?), so that I can see only the upper-left part of the slides, and the rest of the screen is black. Moreover, if I try to change the current slide, it does change on the primary screen (preview mode), but not on the external screen.

Does anyone has an idea how to fix this ? Is the problem coming from awesome WM ?
Please ask me if you need any further information.

Thanks!

**Comment by AndreasBilke** [comment]
Did you read the part
https://github.com/pdfpc/pdfpc/#windows-do-not-appear-on-the-correct-screen
? Maybe you can configure your awesone WM to move the window on the right
screen.

**Comment by Djoop** [comment]
Thank you for the suggestion. Unfortunately, I don't think that this solves the problem. I am able to freely resize the window and move it to the right screen, but the problem is still the same: the resolution is fixed, and does not vary when I move/resize the window. Is there a way, once the window is placed on the desired screen and has the desired size, to force pdfpc to recalculate the resolution?

**Comment by AndreasBilke** [comment]
@Djoop pdfpc fetches the screen resolution for both screens and calculate the layout according to this size. There is no mechanism to resize/recalculate this later (I now this is not nice).
Are you able to debug this issue a little bit further? You can have a look at the fullscreen class (both presenter and presentation derive from it) and investigate if pdfpc recognize the correct resolution and correct hidpi settings (if you have it).

Do you have X or wayland as display server?

**Comment by AndreasBilke** [comment]
@Djoop did you tried to tell your awesome wm to move the windows (like in the FAQ proposed)?

**Comment by AndreasBilke** [comment]
If you still have the issue (even with awesome specific configuration on your site), please reopen the issue.
