### ISSUE TITLE
New release with Vala 0.36 support 

### ISSUE THREAD

**Issue by SWW13** [pdfpc/pdfpc#246]
I've submitted a pull request for a `pdfpc` formula in Homebrew, this will make `brew install pdfpc` possible on OS X.

To add a new a core formula one of the requirements is a patch free build, the currently newest version 4.0.6 does not contain d9673035b8ce6863fac23a40397a2b642a4778eb. (see https://github.com/Homebrew/homebrew-core/pull/14906#pullrequestreview-46138886)

**Comment by AndreasBilke** [comment]
See latest release.
