### ISSUE TITLE
i3-wm presentation screen not moved to 2nd screen

### ISSUE THREAD

**Issue by Stunkymonkey** [pdfpc/pdfpc#252]
if you use pdfpc with [i3-wm](https://i3wm.org/) you first have to exit fullscreen in i3
then manually move the screen to the other screen
and enter full screen again

i think it's not supposed to be like this.
i started looking for a solution and found others having this problem before:
https://github.com/dannyedel/dspdfviewer/blob/master/runtimeconfiguration.cpp#L40
so via i3-msg it is possible to move the screen

**Comment by AndreasBilke** [comment]
For i3 you can use the following config:

for_window [ title="^pdfpc - present" ] border none floating enable

We figured out that there is no general solution for moving a window (AND
fullscreening) is available for different WMs. Our current approach works
for the big WMs (like gnome based) but not for tilling WMs (since they
ignore some window hints).

So this is a won't fix.

**Comment by phillipberndt** [comment]
If you use an old version of GTK (older than 3.18), then updating it might help as well. GTK introduced an API that lets the programmer choose which screen to use in that release. For older versions, pdfpc moves the window to the top left position of the target screen and optimistically calls fullscreen.

Btw, I *guess* that this is related to the way GTK processes move requests (..namely, asynchronously) and to the fact that i3 does something different than most other WMs. I have seen [similar problems in another project](https://github.com/phillipberndt/pqiv/issues/92) lately.

An alternative fix in the i3 config that doesn't require to switch to floating is

    for_window [ title="^pdfpc.*" window_role="presentation" ] move to output right, fullscreen

**Comment by AndreasBilke** [comment]
New gtk versions do not help.

**Comment by phillipberndt** [comment]
Indeed, [i3 does not support fullscreen monitor hints](https://github.com/i3/i3/issues/2116), and, [apparently](https://github.com/GNOME/gtk/blob/caacab13e96f3d79a197ad93195b5b30f6775c9e/gdk/x11/gdkwindow-x11.c#L3543), GTK does not implement a workaround.

**Comment by AndreasBilke** [comment]
And i3 has not the same (like gnome) concept of "other screen". It maps
workspaces to screens but that is kind of fluid.
