### ISSUE TITLE
slides do not advance correctly in pointer mode

### ISSUE THREAD

**Issue by dnarnold** [pdfpc/pdfpc#255]
I have installed pdfpc through the pdf-presenter-console 4.0.6-1 package of Ubuntu 17.04.  I am having trouble with pointer mode (the red dot that follows the cursor, invoked with the 8 key). When pointer mode is on, and the mouse is still, slides do not advance.

For example, I start a presentation.  If I hit the right cursor key, the slide does not advance, so I hit it again, and the slide doesn't advance.  Then I move the mouse and the presentation jumps two slides ahead.  I don't always see this behavior, but usually do.

Any ideas?  Thanks for a great program.

**Comment by AndreasBilke** [comment]
Hi, I can't reproduce it.

**Comment by dnarnold** [comment]
OK, I've explored this further and produced a minimal reproducible example.  It seems this also involves included movies: the problem arises when there is an included movie on the slide, pdfpc is in pointer mode, and you try to advance to the next slide.  I attach a zipfile with a simple latex file and mp4 file that illustrates the problem.  Please let me know if you can reproduce the problem with these files.  Thanks.
[pdfpctest.zip](https://github.com/pdfpc/pdfpc/files/1183930/pdfpctest.zip)

**Comment by phillipberndt** [comment]
I just tried to reproduce this and found that pointer mode does not work for me at all: Pressing `8` gives me a black screen with the red dot, and *hides* the presentation.

**Comment by AndreasBilke** [comment]
@dnarnold thank you for your example. I experience now the same as you describe.

**Comment by AndreasBilke** [comment]
@phillipberndt interesting :) What do you think about using the `gtksink` instead of this hacky thing with different types of sinks which work on own windows etc? It is in gst-plugins-bad and it seems more integrated into the GTK world. (we have no problems catching events etc).

**Comment by phillipberndt** [comment]
I had ruled that out earlier because we'd have to add a new widget per video with that backend, but given that we now do that anyway, I don't see why not :+1

**Comment by dnarnold** [comment]
Here is another minimal example which illustrates another problem with displaying movies which may, or may not, be related to the bug above.  While a movie is normally displayed as link text until it is started, if you page forward to a movie, then page back and forward to it again, the second time the link text does not appear, but instead the first frame of the movie does.  Also, if a \pause command is used to place a movie on the second overlay of a slide, the first frame of the movie (not the link text) is displayed already on the first overlay of the slide.  This seems wrong in two ways: the movie should not display at all on the first overlay, and it should display as the link text on the second overlay until the movie is started.

I attach the latex file and a sample movie file to illustrate all this.

[pdfpctest2.zip](https://github.com/pdfpc/pdfpc/files/1202463/pdfpctest2.zip)

**Comment by AndreasBilke** [comment]
@dnarnold could you test pr #263 if it works for you now?

**Comment by dnarnold** [comment]
I tried it out on my file and it seems to work perfectly.  Thanks!
