### ISSUE TITLE
pdfpc stops playing videos after few frames

### ISSUE THREAD

**Issue by sergiud** [pdfpc/pdfpc#259]
I'm on Arch Linux. pdfpc stops playing videos after few frames. A workaround is to uninstall `libva-intel-driver`.

**Comment by AndreasBilke** [comment]
Could you gibe an example? I have a very similar setup like you, so maybe I can see this also?

**Comment by sergiud** [comment]
I'll see what I can do.

**Comment by AndreasBilke** [comment]
@sergiud  Could you try the latest master? We did some work in how videos are played.

**Comment by sergiud** [comment]
@AndreasBilke I did. Unfortunately the problem remains. 

As for the problem. In one slide I have tree small frame videos. The first two stop playing completely, whereas the third continues with some kind of macroblocking. Again, without `libva-intel-driver`there are no issues whatsoever.

I can try record a video of what happens.

**Comment by AndreasBilke** [comment]
> I can try record a video of what happens.

Please

**Comment by AndreasBilke** [comment]
As it seems this problems is caused by other libraries I close this issue.
