### ISSUE TITLE
Fatal IO error on X server when playing back videos

### ISSUE THREAD

**Issue by mhoff** [pdfpc/pdfpc#260]
I'm using the pdfpc-video-example from the official website to demonstrate this problem.
`pdfpc` fails with the following output when attempting to switch to the second slide (the video slide).
```
[~/Test/pdfpc-video-example]> pdfpc video-example.pdf    
Unknown option gstreamer-pipeline in pdfpcrc
Screensaver inhibited
Gdk-Message: pdfpc: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
```
As you can see, I already tried to set option `gstreamer-pipeline` to `glimagesink`, however, gstreamer does not understand the option.

My operating system is Arch Linux and I'm currently using the Gnome desktop.
Installed software:

```
[~/Test/pdfpc-video-example]> pacman -Qs gst
local/clutter-gst 3.0.24-1
    GStreamer bindings for clutter
local/gst-libav 1.12.2-1
    GStreamer Multimedia Framework ffmpeg Plugin
local/gst-plugins-bad 1.12.2-1
    GStreamer Multimedia Framework Bad Plugins
local/gst-plugins-base 1.12.2-1
    GStreamer Multimedia Framework Base Plugins
local/gst-plugins-base-libs 1.12.2-1
    GStreamer Multimedia Framework Base Plugin libraries
local/gst-plugins-good 1.12.2-1
    GStreamer Multimedia Framework Good Plugins
local/gst-plugins-ugly 1.12.2-1
    GStreamer Multimedia Framework Ugly Plugins
local/gstreamer 1.12.2-1
    GStreamer open-source multimedia framework core library
local/totem 3.24.0-1 (gnome)
    Movie player for the GNOME desktop based on GStreamer
```
Issue https://github.com/pdfpc/pdfpc/issues/259 does not apply, `libva-intel-driver` is not installed.

**Comment by AndreasBilke** [comment]
Could you try #263 ? We changed how videos are rendered.

**Comment by mhoff** [comment]
Sorry, I forgot to give this issue an update. After restarting the system, suddenly everything worked.

(However, videos are always displayed fullscreen, which means `width` and `height` are not respected, and the rendering quality is bad, but that should be another issue I guess.)
