### ISSUE TITLE
Using pdfpc with Xming on Windows

### ISSUE THREAD

**Issue by sgraf812** [pdfpc/pdfpc#262]
I installed pdfpc through the `nix` package manager within my Ubuntu Subsystem on my windows machine.

So far, everything seems to work fine on a single display, but I can't really open the presentation-only view at all. Any ideas on how I have to setup Xming? So far I'm using the arguments  `:0 -clipboard -multiwindow -dpi 144` and set `export DISPLAY=:0.0` in my .bashrc. Maybe this is the culprit? I have no idea how these X window servers work, really...

Currently, if I connect a second monitor, the whole window is stretched over the 2 monitors.

**Comment by sgraf812** [comment]
For the record: I managed to spawn an Xming instance at :0, where there is a fullscreen window on display 0 on my first monitor and a fullscreen window on display 1 on my second monitor, but pdfpc doesn't seem to recognise this.

```
"C:\Program Files (x86)\Xming\Xming.exe" :0 -screen 0 @1 -screen 1 @2 -engine 1
```

**Comment by einhander** [comment]
In xserver  world :0.0 represents first monitor, and 0.1 second. Screen is xserver abstraction, nothing do with real monitor.
I don't familiar with Xming, you have to  create additional outputs to your main.

**Comment by AndreasBilke** [comment]
This is not a bug of pdfpc but a configuration issue with windows/ubuntu. If you find something to run pdfpc on this setup I would be happy to include it into the README.
