### ISSUE TITLE
Slide Freeze does not work with video slides

### ISSUE THREAD

**Issue by AndreasBilke** [pdfpc/pdfpc#264]
When a user has video slides the freeze function does not work correctly.

Instead of just changing the presenter slides (and not the presentation) the videos appear on the presentation view regardless of the freezing states. I.e. the video is displayed on top of the (freezed) slide.

It seems this bug is here since we have video support.

**Comment by complanar** [comment]
Can confirm that bug. Seems to have been there since ever and in every version.

**Comment by axtimwalde** [comment]
Can confirm this bug.

**Comment by fnevgeny** [comment]
OK, this is clearly a bug, but what should the correct behavior be? Say, one hits "f" while a video is playing, and then switches to another slide in the presenter interface. Should the video in the "frozen" presentation slide continue playing or be paused?

**Comment by AndreasBilke** [comment]
For my understanding, the semantics for a slide freeze is that just the synchronous slide switch is disabled. The rest should work normally.

I think you use the freeze feature to search for another side while the audience should look at the other one. And they should see the playing video not a paused one.

**Comment by fnevgeny** [comment]
Well, I use the overview mode (Tab) for that. Is there some extra functionality in the freeze mode? Perhaps only if one wants to jump right to a specific transition inside a slide.

In any case, it seems implementing this functionality (keeping the movie alive on only the presentation screen) would require a rather substantial rewrite of the video subsystem (_and_ not only that). Currently, each video is effectively a single object with two sinks but API methods operating on both. Splitting this (while keeping everything in sync in the normal, non-frozen mode), would be a lot of work.

On the other hand, the current situation makes freezing entirely unusable with presentations containing videos. So I suggest, as a lesser evil, to give up on the ideal semantics but deal with the overlaying videos issue, which seems to me easier to fix.

**Comment by AndreasBilke** [comment]
@fnevgeny if you use the tab mode then the video plays normally (of it's that what you ment)

I totally agree with you that the video system has to be rewritten for that. But I think that even for the "simple" version all of that had to be done.
