### ISSUE TITLE
For grouped overlays, (have an option to) show final slide of group in the 'next slide' position of presenter view

### ISSUE THREAD

**Issue by emacsomancer** [pdfpc/pdfpc#268]
Rather than showing the next overlay group slide in the 'next slide' preview on the right hand side of the presenter view, would it be possible to (have an option to) show instead the final slide of the current overlay group (until the current slide is the final slide of the overlay group, at which point it would switch to the next overlay group)?

**Comment by HermannDppes** [comment]
I would be in favour of even stronger customization options. So far, I had no need for the notes so I replaced them by the final slide of the current group, showing it *in addition* to the final slide of the next group. (To do this, [I forked the project](https://github.com/HermannDppes/pdfpc) and butchered it horrible until it worked.<sup>[TM](http://tvtropes.org/pmwiki/pmwiki.php/Main/TradeSnark)</sup>)

**Comment by AndreasBilke** [comment]
@HermannDppes Why you didn't put effort in sharing your work here (and make it configurable)?

**Comment by emacsomancer** [comment]
@HermannDppes It would be great if this were configurable.   I had exactly the same thought - about using the notes space for additional preview, as I essentially never use notes. But it would be nice to have the option to use notes (the reason I don't use notes is at least in part because I've never had presenter software which allowed me to).

Also, @HermannDppes , I built your fork and ran it, but I don't see how to get these features to activate. Is there a runtime flag that's needed?

**Comment by phillipberndt** [comment]
Should be related to 7cbd71d.

**Comment by emacsomancer** [comment]
@phillipberndt Is there a way to activate this?  Tried the 'git' version of pdfpc, but it is still showing the next slide in the preview.

**Comment by HermannDppes** [comment]
@emacsomancer No, nothing special needed. Are you sure you got the right branch? It should have multiple occurrences of `futureViews` and `future_allocated_width` in `presenter.vala`.

@AndreasBilke I did neither feel like the achievement was big enough nor like the code was sane enough to share it unprovoked. After I got it working for me, other things got more important than cleaning up the code or figuring out what the reasonable way to configure this would be.

Are there currently any options to customize the layout of pdfpc? Are there any preferences how this should work? I can’t promise anything but if there is enough other stuff I desperately want to procrastinate, I might get around to fiddling with it again.

**Comment by AndreasBilke** [comment]
> @AndreasBilke I did neither feel like the achievement was big enough nor
> like the code was sane enough to share it unprovoked. After I got it
> working for me, other things got more important than cleaning up the code
> or figuring out what the reasonable way to configure this would be.

This request occurred already here so there is obviously a need for this
kind of layout (which makes it big enough :)).

> Are there currently any options to customize the layout of pdfpc? Are
> there any preferences how this should work? I can’t promise anything but
> if there is enough other stuff I desperately want to procrastinate, I
> might get around to fiddling with it again.

There are some flags for setting the size of current view, next view and
this small overlay widgets.

I would say that keeping the note text area still in memory (to allow notes
setting without any modification) and just do not add this notes_view to
the layout. @phillipberndt what do you think?

**Comment by emacsomancer** [comment]
@HermannDppes Yes, it looks like I was building the wrong branch. Got it working (for some reason I had expected the position of the two preview frames to be reversed though). Thanks.  I'd vote for pushing your changes if you happen to be ranking your future (structured) procrastination venues.

**Comment by AndreasBilke** [comment]
Fixed with #429
