### ISSUE TITLE
Fullscreen display broken

### ISSUE THREAD

**Issue by severin-lemaignan** [pdfpc/pdfpc#269]
Commit 14a865fa035b2a1e962ecee4fabaafbb0febdd8a (introduced in PR #263) breaks the fullscreen rendering of the `pdfpc` window: 

![screenshot](https://user-images.githubusercontent.com/385379/29386370-cfd8e1b0-82db-11e7-81df-bfd5ab35ad3e.jpg)

(original resolution: 2560x1440)

- the window does not start at 0x0
- the window is much larger than the screen, causing the many UI element to become invisible (in particular, the next slide window)

Note that this issue is a HIDPI-related issue. I'm using by default a GDK_SCALE=2. Using

```
GDK_SCALE=1 pdfpc test.pdf
```

effectively fixes the window placement and size.

The faulty commit has been identified with (`git bisect`)

**Comment by AndreasBilke** [comment]
Do you use wayland?

**Comment by severin-lemaignan** [comment]
Sorry, forgot the mention: I'm running gnome-shell 3.18 on a X.org session.

**Comment by AndreasBilke** [comment]
Is the window size twice as large as the screen resolution?

Does it work for you if you use GDK_SCALE=2?

**Comment by severin-lemaignan** [comment]
Using `GDK_SCALE=2` does exhibit the issue.

It is not exactly 2 times bigger:
Output of `xwininfo`:
```
xwininfo: Window id: 0x2c0000c "pdfpc - presenter ()"

  Absolute upper-left X:  78
  Absolute upper-left Y:  50
  Relative upper-left X:  78
  Relative upper-left Y:  50
  Width: 3784
  Height: 2530
  Depth: 32
  Visual: 0x8f
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x2c0000b (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +78+50  --1302+50  --1302--1140  +78--1140
  -geometry 1892x1265+78+50
```
(my resolution is 2560x1440)

**Comment by HermannDppes** [comment]
I have a 1920 by 1080 pixel screen, can reproduce:
* `GDK_SCALE=2`
> Absolute upper-left X:> 0
> Absolute upper-left Y:> 27
> Relative upper-left X:> 0
> Relative upper-left Y:> 0
> Width: 2836
> Height: 1840
> Depth: 24
> Visual: 0xd4
> Visual Class: TrueColor
> Border width: 0
> Class: InputOutput
> Colormap: 0x460000b (installed)
> Bit Gravity State: NorthWestGravity
> Window Gravity State: NorthWestGravity
> Backing Store State: NotUseful
> Save Under State: no
> Map State: IsViewable
> Override Redirect State: no
> Corners:> +0+27> --916+27> --916--787> +0--787
> -geometry 1418x920+0+27
* `GDK_SCALE=3`
> Absolute upper-left X:> 0
> Absolute upper-left Y:> 27
> Relative upper-left X:> 0
> Relative upper-left Y:> 0
> Width: 3873
> Height: 2616
> Depth: 24
> Visual: 0xd4
> Visual Class: TrueColor
> Border width: 0
> Class: InputOutput
> Colormap: 0x460000b (installed)
> Bit Gravity State: NorthWestGravity
> Window Gravity State: NorthWestGravity
> Backing Store State: NotUseful
> Save Under State: no
> Map State: IsViewable
> Override Redirect State: no
> Corners:> +0+27> --1953+27> --1953--1563> +0--1563
> -geometry 1291x872+0+27
* `GDK_SCALE=4`
> Absolute upper-left X:> 0
> Absolute upper-left Y:> 27
> Relative upper-left X:> 0
> Relative upper-left Y:> 0
> Width: 4896
> Height: 3408
> Depth: 24
> Visual: 0xd4
> Visual Class: TrueColor
> Border width: 0
> Class: InputOutput
> Colormap: 0x460000b (installed)
> Bit Gravity State: NorthWestGravity
> Window Gravity State: NorthWestGravity
> Backing Store State: NotUseful
> Save Under State: no
> Map State: IsViewable
> Override Redirect State: no
> Corners:> +0+27> --2976+27> --2976--2355> +0--2355
> -geometry 1224x852+0+27

All of these were done without a second monitor.

I noticed that the 27 pixel offset pretty closely matches the height of my (task? os? applet? start?) bar, but changing its size did not influence that offset, so this seems purely coincidental.

I’m using a Linux Mint 18 “Sarah” with Cinnamon.

**Comment by AndreasBilke** [comment]
@severin-lemaignan , @HermannDppes Could you try the following patch? https://pub.bilke.org/2017-08-18-YxotEik9qE0/0001-Fix-regression-introduced-in-263.patch

**Comment by severin-lemaignan** [comment]
@AndreasBilke yes, this seems to fix the issue for me, for both the presentation and the presenter. Excellent!

**Comment by HermannDppes** [comment]
@AndreasBilke #271 works for me.
