### ISSUE TITLE
inlineMovie is not working in the current arch package.

### ISSUE THREAD

**Issue by fhaust** [pdfpc/pdfpc#272]
Not sure if you guys are packaging for Arch Linux or if it is somebody else.

For me `inlineMovie` displays the movie in fullscreen mode regardless of size options when using the current Arch Linux package. I just compiled `pdfpc` from revision c42823636c114450753c4c3fee9fc7f89a5eacfc and it works fine there. 

Don't know what changed in between, but you might consider a new build for Arch Linux.

**Comment by AndreasBilke** [comment]
These problems are fixed on `master`, v4.0.7 is still affected of this issue. You might ask the arch linux maintainer for applying patches or you have to wait until we release a new version.

**Comment by AndreasBilke** [comment]
@fhaust We pushed a new release. You might contact the arch linux maintainer to create an update.

**Comment by fhaust** [comment]
done
