### ISSUE TITLE
Interaction with other tools

### ISSUE THREAD

**Issue by cversari** [pdfpc/pdfpc#28]
Hi all,
  thanks for bringing pdfpc back to life.

I would have a feature request: would it be possible to output somewhere (stdout or file or whatever) in real time the number of the current slide being shown?
This would be the minimal output information to let pdfpc interact with other tools, I am thinking for example to anyremote http://anyremote.sourceforge.net/ or similar.

Of course it is already possible to use pdfpc with anyremote (I do it on a regular basis), but one very cool thing would be to show in the cell phone screen some info like the note of the current slide or a preview of the next. To do this, one needs to know at least the number of the current slide being shown, otherwise it is quite complicated to guess it given the many possible ways allowed by pdfpc to jump backward and forward in the presentation.

**Comment by rschroll** [comment]
It's certainly possible.  I've been wondering privately if we should have debug statements throughout the code that could be turned on by a command line switch.  Page changes would be an obvious place to start.

Is there any particular format that anyremote wants?  I looked over the website briefly, but I couldn't understand how it interacts with programs on the computer.

**Comment by andybarry** [comment]
We should also think about if dbus might be the right way of doing this.  Cleaner than  to stdout

**Comment by rschroll** [comment]
That's true.  And writing a dbus server with vala is criminally easy.

**Comment by cversari** [comment]
Apparently anyremote supports Dbus ( http://anyremote.sourceforge.net/dbus.html ), so that may be the most clean and general solution.

Depending on how criminally easy it is, it may be interesting to  publish on Dbus info such as:
- the currently opened pdf file
- the number of the current slide
- the note of the slide
- ...
It would be even cooler if all the actions available via keyboard were also available as methods on Dbus, so that anyremote (or any other application) may control pdfpc directly without using keyboard/mouse emulation.

**Comment by rschroll** [comment]
We could make the presentation controller into a dbus server.  Then all 
of our action handlers would be available as dbus methods.  But it 
might be better to make a separate server with a method that takes the 
action name.  This would insulate it against changes to the controller, 
as well as letting us use the same names we use in the keybindings.

**Comment by rschroll** [comment]
I've pushed a sample implementation to the dbus branch of 
rschroll/pdfpc.  It's pretty basic, but you can do quite a lot already. 
 We might want to expose a few more properties.  Should we go this way, 
we also ought to think about:
- What our DBus namespace should be.  Right now, I've chosen 
io.github.pdfpc, but do we want to have github in there?
- Our terminology for "pages" and "user pages", as we call them 
internally.  I think this is a bad name to expose to the user.  Right 
now I'm using "slide" for "user page" and "overlay" for page.  But this 
sort of clashes with "nextOverlay" and "prevOverlay", which move in 
user pages, not standard pages.

@cversari: If you could test this with anyremote, it'd be great to know 
if this actually works.  And if you can come up with a configuration 
file we can ship with pdfpc, that'd be even greater!

**Comment by cversari** [comment]
@rschroll: many thanks. Since I am not an expert of anyremote, I will first try the DBus implementation with a simple anyremote configuration, just to test that it works: I will let you know the outcome as soon as I can. Thereafter, I would be glad to contribute to the development of a full anyremote config for pdfpc.

**Comment by AndreasBilke** [comment]
@cversari did you had some time playing on the anyremote integration?

**Comment by AndreasBilke** [comment]
@rschroll could you make a pr for your dbus implementation?

**Comment by rschroll** [comment]
I've created PR #132 with my branch from way back when.  As I say 
there, it doesn't merge cleanly.  I can try to rebase it over the 
weekend.

**Comment by andybarry** [comment]
Merged in #133.
