### ISSUE TITLE
Wrong presentation ratio when removing notes

### ISSUE THREAD

**Issue by diegit** [pdfpc/pdfpc#280]
### Expected Behaviour
Show presentation with correct ratio:
![withnotes](https://user-images.githubusercontent.com/5353192/29968184-c36aad0a-8f1a-11e7-92f3-0dcef06b2be0.png)

### Actual Behaviour
presentation has wrong ratio:
![nonotes](https://user-images.githubusercontent.com/5353192/29968188-cac45a7e-8f1a-11e7-9d39-9bff894f6037.png)

### If it's a bug: Steps to reproduce the behaviour (e.g. a minimal working example for the PDF)
1. Create a presentation with notes (`\setbeameroption{show notes on second screen=right}`) and display them with `pdfpc --notes=right a.pdf`
2. Remove notes and compile again
3. Presentation has wrong ratio with `pdfpc a.pdf`
4. Rename to b.pdf
5. Presentation has correct ratio with `pdfpc b.pdf`

-This happens in windowed and normal mode
-A disabled cache does not change anything

#### pdfpc version
4.0.8

#### Used Distribution (GTK version, vala version)
Opensuse Tumbleweed
Vala 0.36.4
Gnome Version 3.24.2

#### Display Server (X/Wayland)
X

#### HiDPI Setting (yes/no)
no

**Comment by AndreasBilke** [comment]
Actually, it is more or less expected behaviour. The `--notes=right` is saved in the `a.pdfpc` file for later usage. As expected this setting is reloaded for the next time.
I might be nice that pdfpc is detecting your changed note setting but I see no way in how this could be done.

**Comment by HermannDppes** [comment]
@AndreasBilke Well, you could do the following:

Szenario: pdfpc is called with a 8 to 3 presentation and --notes=right

Current behaviour: pdfpc remembers “Left half of presentation is presi, right half of presentation is notes”

Alternative behaviour: pdfpc remebers “Leftmost 4 by 3 is presi, rest is notes”

But that sure seems like a disproportionate amount of effort for solving a single corner case while leaving others off worse.

**Comment by diegit** [comment]
I was not aware that pdfpc remembers that there are notes included, and I was under the impression that some old cache files were used by accident

I'll close this issue!
