### ISSUE TITLE
If the font size is set to 0, it can't be increased

### ISSUE THREAD

**Issue by dzamlo** [pdfpc/pdfpc#281]
If you decrease the font size to 0, you can't increase the font size.

In the `increase_font_size()` function in `src/classes/window/presenter.vala`, the font size is multiplied. But if the font size is set to 0, it will not be increased.

**Comment by AndreasBilke** [comment]
@dzamlo Could you try PR #282 ?

**Comment by dzamlo** [comment]
After a quick test, #282 seems to work and fixes this issues.

Thanks for your work on this amazing project.

**Comment by AndreasBilke** [comment]
Fixed with #282 .
