### ISSUE TITLE
pdfpc doesn't render any Chinese characters

### ISSUE THREAD

**Issue by amosbird** [pdfpc/pdfpc#288]
### Expected Behaviour
render Chinese characters correctly

### Actual Behaviour
doesn't render them

### If it's a bug: Steps to reproduce the behaviour (e.g. a minimal working example for the PDF)
any pdf with Chinese characters, `你好`

#### pdfpc version
pdfpc v4.0.8

#### Used Distribution (GTK version, vala version)
Vala 0.36.4
Gtk 3.22.1

#### Display Server (X/Wayland)
X

#### HiDPI Setting (yes/no)
no

**Comment by fnevgeny** [comment]
Works fine here with a few PDF's randomly downloaded from Internet, e.g. <http://www2.ed.gov/about/offices/list/ocr/docs/howto-chinese.pdf>. Do other viewers (e.g., evince) render Chinese OK?

**Comment by amosbird** [comment]
hmm, ok it may be related to certain fonts. Yeah, zathura works fine. Could you try this one https://la.wentropy.com/Gn8c.pdf

**Comment by fnevgeny** [comment]
Renders fine here (three Chinese glyphs on the title page). Do you say evince and pdfpc render this file differently in your case? As far as I know, zathura has more than one renderer plugin for PDF.

**Comment by amosbird** [comment]
oh, evince doesn't render those characters either. So what plugin does pdfpc using and how can I fix this ?

**Comment by fnevgeny** [comment]
pdfpc uses poppler. zathura has either poppler of mupdf (https://pwmt.org/projects/zathura/plugins/). I bet yours is configured for mupdf. Try poppler and it should likely show off the same problem. If so, try asking on the poppler (or evince) forums. Look at the config (probably /usr/share/poppler/*), you might see something obvious there. Which OS are you using, BTW?

**Comment by amosbird** [comment]
I'm using archlinux. Ok, I'll ask in #popper then. Thanks.

**Comment by fnevgeny** [comment]
You're welcome. In fact, #archlinux might be even a better option to get help in your case. Under Ubuntu and Gentoo, I don't have this issue.

**Comment by amosbird** [comment]
Ah, I fixed this by installing poppler-data.

**Comment by fnevgeny** [comment]
If archlinux indeed allows to install poppler without poppler-data, I'd consider it a packaging bug and file a report. Since absence of poppler-data renders (sic!) poppler half-usable, as you saw.
