### ISSUE TITLE
Point to specific .pdfpc file from command line

### ISSUE THREAD

**Issue by ChasNelson1990** [pdfpc/pdfpc#289]
I've only been using pdfpc for a little while and it's great, thanks for all your work.

The current presentation I'm preparing has notes, so I have chosen to use pdfpc-latex-notes (https://github.com/cebe/pdfpc-latex-notes) as they work the way I want.

However, when I compile through atom (https://www.atom.io), my latexmk puts all compiled files in a ./build/ folder, keeping the final pdf in the root folder. I can't change the settings in the atom plug-in (https://atom.io/packages/latex) to also keep the .pdfpc file in the root folder.

So, I wondered whether it would be useful to have a -f, --file option to point to, in my case, './build/main.pdfpc'. I could see this having further use if you had multiple .pdfpc files, e.g. one with custom notes and one without, or things like that.

**Comment by AndreasBilke** [comment]
Sounds logic. Can you implement it?

**Comment by ChasNelson1990** [comment]
I will have a look today/tomorrow. It may well be beyond me but we'll see. I shall update later this weekend.

P.S. Sorry for the delay in reply

**Comment by ChasNelson1990** [comment]
Sorry but I'm having trouble initialising a new command line option successfully. I have added:
`{ "config-location", 'R', 0, OptionArg.STRING, ref Options.config_location, "Full path location to a pdfrc file (e.g. ./build/withnotes.pdfpc).", "LOCATION"},`
inside `const OptionEntry[] options = {}` of pdfpc.vala and also:
`public static string? config_location = null;`
inside `public class Options: GLib.Object {}` of options.vala.

The make is without error but when I try to use `--config-location="./build/withnotes.pdfpc"` I  the contents of the file printed as attempted command line options (I get `Warning: Unknown command line "[notes]"`  etc.), same when I use, `-R "./build/withnotes.pdfpc"`. The same is true without quotations marks.

**Comment by AndreasBilke** [comment]
Could you track your effor in a branch so that we can see exactly what you
did?

**Comment by ChasNelson1990** [comment]
Sorry for the absurd delay in replying, again.

I have pushed a commit on my fork at: https://github.com/ChasNelson1990/pdfpc/commit/803f052b4c3b5d4904e721d8c2ca3059e9e26398

**Comment by AndreasBilke** [comment]
I think you mixed the concept of `pdfpcrc`(which has pdfpc global config options like mouse binding) and the `pdfpc` file which stores per-presentation stuff like notes etc. You tried to load the `pdfpc` file with the `pdfpcrc` config file parser and (correctly) receive error messages about unknown options.

I added the custom `pdfpc` parsing and pushed it to a new PR. can you try it?

**Comment by ChasNelson1990** [comment]
Thanks @AndreasBilke,

Yes this works I can now point to a .pdfpc file in another folder and I see notes from that file that don't appear without the -R flag. Exactly what I wanted.
