### ISSUE TITLE
PDF annotations as notes

### ISSUE THREAD

**Issue by fnevgeny** [pdfpc/pdfpc#291]
Hello,

I noticed there is a rudimentary support for native PDF annotations: they are automatically imported & shown as usual pdfpc notes. However:

1. They are also rendered in the standard poppler way (as "note" icons and/or highlighted text) on both presenter and presentation screens - which is likely not what one ever wants.

2. These notes can be edited and will then saved to the .pdfpc file, however, upon the next invocation they will be silently overwritten.

3. Well, everything above is not documented, it seems.

Point (1) is the simplest - replacing render() with render_for_printing() seems sufficient (and I couldn't see any negative side effects). In the  worst case, once imported, the annotations can be programmatically removed using the Poppler API.

About (2), we can either (i) load annotations only for pages with no pdfpc notes or (ii) disallow modifications of "imported" notes. What do you think?

**Comment by AndreasBilke** [comment]
This seems to be a very nice feature!
1. `render_for_printing()` seems to be fine
2. I would say, if pdfpc encounters PDF annotations, they should be read-only. No fancy `.pdfpc` synchronization. I would also say PDF annotations/pdfpc notes should be mutually exclusive. No mixing of ways on how to do notes stuff.
3. As usual :)

**Comment by fnevgeny** [comment]
OK, will do it in a few days.
