### ISSUE TITLE
Video on Note Frame

### ISSUE THREAD

**Issue by cxkoda** [pdfpc/pdfpc#292]
Version: pdfpc v4.0.8

I am working on a presentation with notes (double screen width) and videos.

In dual screen mode
`pdfpc --notes=right video-example.pdf`
pdfpc displays the movie not only in the presentation frame but also in the note frame.

A presentation containing the issue can be generated by adding
`\usepackage{pgfpages}`
`\setbeameroption{show notes on second screen=right}`
to the preamble of the [video-example](https://github.com/pdfpc/pdfpc.github.io/blob/master/demo/pdfpc-video-example/video-example.tex) and displaying the newly compiled pdf using the above command.

**Comment by AndreasBilke** [comment]
This is for sure not intended. But I am not sure about a good solution. Currently, the video controls are only accessible via the presenter screen. If we hide the video on the presenter, where should the video be controlled?

**Comment by cxkoda** [comment]
Usually I show only short videos, which are played just once or in a loop. Hence most of the time I do not need explicit video controls.
You are right that putting the video on the presenter screen is probably the best solution for controlling. 
Would it be possible to leave the choice to the user whether the control video is displayed or not? Maybe by setting an additional flag in the Latex hyperlink to hide the video?

**Comment by AndreasBilke** [comment]
I mean, one can implement a lot of things :) But but hiding/disabling the video control when notes are used is a very limited use case.
@phillipberndt What do you think about having an extra control widget (somewhere in the UI) if we have videos AND latex notes?

**Comment by AndreasBilke** [comment]
@phillipberndt @fnevgeny What about having video controls on the presenter and presentation screen? We then could simply hide/disable the video on the presenter screen (without further control ui).

**Comment by phillipberndt** [comment]
Tricky. Since in this mode LaTeX outputs a double-width page and all pdfpc is supposed to do is to display either half on one of the screens, it'd make sense to only display the video at the position where it is placed in the PDF - that is either on the presenter or presentation window.

On the other hand, having video controls in the presenter window is something most users will like to have. I believe that @cxkoda's suggestion makes sense: In `--notes=` mode, hide the video from the presenter view unless a new flag in the video URL, `controls` (?), is set to `false` and/or(?) `autoplay` is on.

**Comment by fnevgeny** [comment]
I don't feel strongly about this, it isn't my personal way of using videos in presentations. In the relatively rare cases I do, I embed video in the slide (**and** don't use the `--notes` switch).

**Comment by diegit** [comment]
I just tested the changes. 
The video is not on top of the notes anymore and I can start videos from the presenter but not the presentation screen. Once the video is started it plays on top of the notes and there is no way to get rid of it. However, there are no video controls (eg progress bar) visible and there is also no indicator (changed cursor) that the area is clickable.
This is the case for X11 and wayland.

With an older version (v4.0.6 on X11) the progress bar is also invisible but functional. In addition, the cursor indicates that there is a clickable area to start the video.

I get the following error message in the console, I'm not sure if it is connected:
** (pdfpc:12145): CRITICAL **: string_to_string: assertion 'self != NULL' failed
Error creating control pipeline: Could not make element 

My setup is described at https://github.com/pdfpc/pdfpc/issues/313 .

I think my ideal setup would be :
Default: show only the notes
-Overlay the video thumbnail once the user moves the cursor, so it's easy to start the video
-Hide the thumbnail again, if the cursor is outside of the video thumbnail AND the user stops moving it

But if that is too much work, I'm ok with the behavior of #319

**Comment by AndreasBilke** [comment]
I tried to debug the problem further and now I am very puzzled. @pdfpc/maintainer could you try out the following pdf https://pub.bilke.org/2017-11-23-ZF0WUFfyjaM/notes-with-videos.tar.bz2 . It is our standard video example with latex notes. I got a really weird behaviour. For slide 3 I got two videos (one at a weird position). See the attached picture.

It seems that beamer is screwing things up the links/action mappings. We get two movie mappings for that slide and pdfpc correctly tries to display both.

Could you verify this? If it is true that beamer is messing up things, then we have no change of fixing this.

![2017-11-23-134453_3520x1080_scrot](https://user-images.githubusercontent.com/1804398/33173513-bb60d2b2-d054-11e7-90be-554608908499.png)

**Comment by phillipberndt** [comment]
The links are present as drawn by pdfpc, I verified that using a PDF editor. I also verified that I can recreate the example the way it looks to you. Seems to be a bug in the class.

Including videos via `\includemovie` works better (no duplicates) but embeds videos on the wrong slide. (1st video is included in 1st slide, for example).

..this makes the patch quite useless for the time being.

**Comment by AndreasBilke** [comment]
It seems that the hyperlinks (from hyperref) get broken if beamer is preparing the notes. If I include movies with `multimedia` package everything is fine. No double links, the patch works as expected.
Can you verify this? Maybe we should no longer announce the `hyperref` solution for embedding movies but promoting other packages.

**Comment by AndreasBilke** [comment]
@pdfpc/maintainer could you verify if the issue does not occur with `multimedia` package? what about promoting this package instead of `hyperref`?
