### ISSUE TITLE
Video after \pause

### ISSUE THREAD

**Issue by nim65s** [pdfpc/pdfpc#299]
### Expected Behaviour

A video after a `\pause` should be played only on the second slide.

### Actual Behaviour

When we put a video after a `\pause`, the placeholder is correctly only on the second slide (can see that on the little previews), but the video appears in both slides.

### If it's a bug: Steps to reproduce the behaviour (e.g. a minimal working example for the PDF)

Add a `\pause` line 31 in video-example.tex

#### pdfpc version

4.0.8

**Comment by AndreasBilke** [comment]
After quickly checking this example, it seems that latex beamer is inserting a video link on every page of this overlayed group. Therefore pdfpc recognizes a video also **before** the `\pause`.
This issue is latex beamer related. pdfpc does everything correctly in this situation.

**Comment by nim65s** [comment]
Ok, thanks, I'll report this to beamer.
