### ISSUE TITLE
Move to Gtk3

### ISSUE THREAD

**Issue by rschroll** [pdfpc/pdfpc#3]
pdfpc still uses the Gtk2 toolkit, which is getting old and suffering bit rot (see #2).  We should move to Gtk3.  Among other things, this would give us the ability to do CSS styling, which will probably help us in the "make everything black" aesthetic we're going for.

Unfortunately, one of the big things about the 2->3 transition was that Gdk.Pixmaps were removed, in favor of Cairo graphics (https://developer.gnome.org/gtk3/stable/ch25s02.html#id-1.6.3.4.5).  pdfpc uses pixmaps extensively as it caches images of the slides, so we'll have to replace them.  It's not entirely clear to me what they should be replaced by; perhaps Gdk.Pixbufs?

**Comment by AndreasBilke** [comment]
Hi,
i started the gtk3 transition (see https://github.com/AndreasBilke/pdfpc/tree/migration-gtk3). There are multiple things to consider:

* it compiles (yeah)
* Pixmaps are replaced by Cairo.ImageSurface 
* PNG compression does not work
* I have multiple white areas on the presenter screen, I don't know why
* if you use --disable-compression you can use it

**Comment by rschroll** [comment]
Way to go!  I've been dreading replacing the pixmaps, so I'm glad 
someone else took this on.  I haven't had a chance to look at this in 
depth, but a few comments off the top of my head:

- I had assumed that the pixmaps would be replaced by pixbufs, but 
you're using cairo surfaces.  Any particular reason you went that way?  
It's likely better; I'd just not considered it.

- Is the PNG compression not working because you haven't gotten to it, 
or is there a mystery?  If you know what needs to be done, I'll stay 
out of your way.  But if not, I'll be a second set of eyes on it.

- pdfpc does funky things with widget styling to make everything black. 
 In Gtk3, we can do a lot of this with CSS, I believe.  I've done a 
little with this in the past, and I'd be happy to attack that here.  
This may solve the white area problem.

- If you look at issue #1, we're discussing the code style we'd like to 
use.  Don't worry about matching everything right now -- you seem to be 
matching the code around it fine, and we can clean things up later.  
But one thing I'd like to do is reduce the use of "using" statements.  
If you could avoid introducing new ones, that'd be helpful.  (Also, 
please comment on #1 if you think we're making bad choices!)

Feel free to make a pull request, even if it's not ready to merge.  I'd 
also be happy to add you to the team here if you'd like.

I'm excited to see this!  Thanks!

**Comment by rschroll** [comment]
I've got the CSS styling working, and it gets rid of those white areas 
you were seeing.  See the migration-gtk3 branch in my personal 
repository for the details.

Let me know if I can help with the PNG compression.

**Comment by AndreasBilke** [comment]
Hi,
I choose cairo surfaces since they are mentioned as a Pixmap replacment in the GTK3 migration guide (see your link). I am not very into gtk programming, but as far as I understand it pixbufs are nothing you can render on the screen, instead they are just in memory image representations.
I will also have a closer look to the coding styles and will do my best do match them :).
The reason for the PNG compression crash are a mystery so far, but I havn't took a closer look to this issue. But any help is welcome!

**Comment by rschroll** [comment]
Well, the image surfaces seem to work well, so I won't argue with them.

I'll take a look at the PNG compresssion crash and see if I can figure 
anything out.

**Comment by rschroll** [comment]
I've just pushed an update to my branch that should make compressed 
caches work again.

The immediate problem you were having, I believe, was that 
surface.get_data() returns an unowned reference.  I suspect that the 
cache code didn't expect this and freed the memory before the surface 
was done with it.

But I think you were going down the wrong path, anyway.  
surface.get_data() return the raw image data, I believe.  Storing that 
would be marginally better than storing the whole surface, but not 
much.  We want to compress that data, and best way to do that is 
through PNGs.  Cairo does have some support for reading and writing 
PNGs directly (http://cairographics.org/manual/cairo-PNG-Support.html), 
but I'm not sure either will work for us.  They have write_to_png() and 
create_from_png(), but both of those expect filenames instead of a 
stream object.  There's also write_to_png_stream() and 
create_from_png_stream(), but these take functions, not streams, as 
arguments, and I suspect that these delegates are not properly 
annotated for vala.  (ReadFunc is supposed to return data through its 
argument I believe, but the argument isn't marked as out or ref.)

So instead, we can use Pixbufs.  They're not quite as slick, but they 
do seem to work.

I notice that there are a lot of warnings now.  I'd like to get rid of 
most of them before we merge this in.  Other than that, is there 
anything we're missing?

**Comment by rschroll** [comment]
I've pushed some more commits to my migrate-gtk3 branch.  These remove 
all but six warnings.  Four of these are taken care of in my "using" 
branch.  One is related to GStreamer and will be fixed by the gst1.0 
branch.  And one I've filed as bug #13.  Other than that, I think this 
is about ready to go.

I'd like to land the using branch first, so if someone could go ahead 
and greenlight that, it'd be great.  Then I'll rebase this work on top 
of that and submit pull request for y'all to look over.

**Comment by andybarry** [comment]
Just merged in the using branch, excited to see gtk3 and gstreamer 1.0 moving forward so quickly.

**Comment by AndreasBilke** [comment]
With GTK 3.14 I have some additional compiler warnings. Gtk.Alignment is now deprecated. In my gtk3 branch I replaced Gtk.Alignment.
But I have some stylisch issue (see attached screenshot). As the prerendering progress bar fills up, the text "Prerendering" gets hidden. Also at the end of prerendering (when the progress bar gets hidden) the slide counter on the right gets moved to the left for a very short time period. Then it gets back to the original position. Both are more cosmetical issues.
![pdfpc-progressbar-issue](https://cloud.githubusercontent.com/assets/1804398/6358083/66d1d6d0-bc69-11e4-81bb-22ace4bfbb83.png)

**Comment by rschroll** [comment]
The Alignment-less code works well on Gtk 3.10.  I made a slight change 
to the layout to stretch the progress bar out a bit further, if it has 
the room.  Hopefully it works on 3.14 as well.

Apparently, Gtk changed the behavior of progress bars in 3.14.  Now the 
text sits above the bar, whereas it used to live in the bar.  However, 
the CSS that styles the part of the bar that's highlighted apparently 
still applies to that same part of the text above the bar.  I was 
setting this text to be black, to show up over the white bar.  That's 
not what you want.  Another well-thought-out improvement from Gtk....  
I've made the text a uniform gray, so it should work everywhere.

I noticed the counter flash as well.  I think I've fixed it by making 
the progress bar invisible, instead of hiding it.

Please let me know if this works for you.  If so, I'll do some final 
rebasing and push it to master!

**Comment by AndreasBilke** [comment]
ProgressBar text is now visible during prerendering and also the "flash" of
the slider counter is gone. Works good.

**Comment by rschroll** [comment]
Good to hear!  If I don't hear any objections in the next few hours, 
I'll go ahead and push it to master.  But if anyone wants a bit more 
time to look it over, please say so.

Andreas, I hope I didn't annoy you by taking over the branch.  Once I 
understood the problem with the compression, I felt it'd be easier just 
to fix it myself, rather than try to explain it.

**Comment by andybarry** [comment]
I won't have time to look at it until tonight or tomorrow, so if you're happy with it go for it!  We can always patch in changes if needed.

**Comment by rschroll** [comment]
I've just pushed this to master.  This should serve as a good base for future improvements.
