### ISSUE TITLE
pdfpc crash on embedded video

### ISSUE THREAD

**Issue by erikheinz** [pdfpc/pdfpc#301]
pdfpc crashes for me when trying to display a page with an embedded video. This happens with the example file video-example.pdf as well. The error messages are:

pdfpc:19129): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed
** (pdfpc:19129): CRITICAL **: string_to_string: assertion 'self != NULL' failed
Error creating control pipeline: Could not make element 
(pdfpc:19129): GStreamer-CRITICAL **: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (dest)' failed
(pdfpc:19129): GLib-GObject-CRITICAL **: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
(pdfpc:19129): GLib-GObject-CRITICAL **: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
Segmentation fault

gst-launch has no problems displaying the video, so gstreamer installation should be OK.
The problem might be triggered by pecularities of my self-compiled Linux system with may be unusual versions of the components. Most libraries are pretty much up to date, though. What can I do to isolate the bug?

Thanks,
Erik

#### pdfpc version
pdfpc-v4.0.8-2-16-g386b16c

#### Used Distribution (GTK version, vala version)
homegrown Linux based on Gnome 3
gtk+-3.22.21
vala-0.36.0
gstreamer-1.12.3

#### Display Server (X/Wayland)
xorg-1.19.3

#### HiDPI Setting (yes/no)
no

**Comment by erikheinz** [comment]
Sorry, my fault. gst-plugins-bad was missing.
May be, there should be a check during installation.

**Comment by AndreasBilke** [comment]
Did you installed all nessessary dependecies? Especially we use
gst-plugins-bad for the gtk sink.

**Comment by AndreasBilke** [comment]
Great. I didn't received your second message about the missing dependency :)

**Comment by erikheinz** [comment]
That's because I installed from source. The dependency from gst-plugins-bad
is a run time dependency. So cmake doesn't check. May be it should?

**Comment by fnevgeny** [comment]
@erikheinz Didn't you say the same video played back fine from the command line? How did it work without the required plugins installed?

**Comment by AndreasBilke** [comment]
Because the codec where fine but the gtk sink we use here was missing

Am 11. Oktober 2017 16:47:12 MESZ schrieb Evgeny Stambulchik <notifications@github.com>:
>@erikheinz Didn't you say the same video played back fine from the
>command line? How did it work without the required plugins installed?

**Comment by fnevgeny** [comment]
@AndreasBilke Thanks, I didn't realize it. To me it is strange that even [the official Vala video embedding example](https://wiki.gnome.org/Projects/Vala/GStreamerSample) uses something from the "bad" package. Shouldn't there be a way to get there within the "good" gst area?

**Comment by AndreasBilke** [comment]
@fnevgeny We had a video solution with either X11 dependency (using only "base" I think) and a opengl solution (with "good" I think). But both were messy, buggy and didn't worked for everyone.
Gstreamer offers the gtk sink, which means that gstreamer is rendering directly to a gtk widget. This is I think the very best solution for us. But is comes for the price of having "bad" dependency as long as the gtk sink does not move to somewhere else.
