### ISSUE TITLE
Feature Request: Optional control buttons for tablets

### ISSUE THREAD

**Issue by torwag** [pdfpc/pdfpc#302]
I really love to see the annotation feature appearing in pdfpc.
That was the last missing feature for me to use it during lectures (used xournal with a crazy xorg-config instead).

However, technology advanced and I guess I am not the only one who had to switch from a laptop to a tablet/laptop combination (in my case an Lenovo Yoga). Common for those is the fact, that you do not have an easy access to the keyboard operating the device in the "tablet-mode" (e.g. the Yoga folds the keyboard to the back). Thus, as much as I am usually using a keyboard-centric workflow, for presentations I need some buttons on the screen for fast switching. I believe the presenter view still has plenty of space for buttons to switch pen, eraser, pointer functions. It could be hidden by default and appear if activated by clicking on a single button. Guess, this feature would make PDFPC close to perfect.

**Comment by fnevgeny** [comment]
I am genuinely wondering why you prefer not to use Yoga in the laptop mode (asking because I am using Yoga myself for presentations).

**Comment by torwag** [comment]
During presentation and annotation I prefer the flat tablet mode. In our class rooms we have slightly tilted presenter tables. Using a laptop is okay. Annotating on the screen is rather uncomfortable. Esp. for the Yoga as it has no lock-in mechanism for the screen in tablet mode (as most devices do not have). The screen tends to move during writing. All in all, laying it flat down on the table allows annotations in most natural way. However, as I said, for the Yoga, there is no way to access the keyboard in that way. 

I think buttons on the screen are a feature which (beside of the programming complexity added) adds only benefits.
1. People unused to pdfpc (e.g. a co-worker) can use it without memorizing the keyboard shortcuts.
2. People with tablet will like it
3. People dislike it simply switch them off (via pdfpc.rc), a shortcut, or pressing a small button to fold/unfold the menu.

**Comment by AndreasBilke** [comment]
@torwag (or @fnevgeny ) Are you able to do a little research on your self? I would be interested if GTK3 has some mechanism for detecting such a tablet or "no keyboard" mode.

I could imaging that we have buttons in the UI for tablet mode and none for keyboard mode (and do this automatically). But I have no access to such a device and can't do any prototype coding.

**Comment by phillipberndt** [comment]
You can [query the GdkSeat for available touch screens](https://developer.gnome.org/gdk3/stable/GdkSeat.html#gdk-seat-get-slaves) and display the buttons if there are any.

(I believe that `-w` should display the buttons even if no touch screens are available to allow developers to test this feature even if they don't have a touch screen available.)

**Comment by AndreasBilke** [comment]
@phillipberndt For the case of the lenovo yoga this might not help enough. The yoga has a touchscreen and a keyboard (and always connected). So we cannot distinguish if the yoga is used in tablet mode or in "normal mode", right?

**Comment by fnevgeny** [comment]
@AndreasBilke When I bought my Yoga ~3 years ago, I couldn't find a kernel event for switching to the tablet mode. But there must be a hardware support for that, since Windows detected it. Probably today there is a support in the mainline kernel. I just never use it in the tablet mode (not because of this, of course). I can try to find it out next week, it's not around me now.

In any case, I believe an automatic detection is of very minor importance - probably nobody would switch between the tablet/laptop modes in the middle of a presentation. So a command-line switch would suffice, in my opinion.

**Comment by AndreasBilke** [comment]
@fnevgeny I didn't meant to switch while running pdfpc, but others might have a situation where "user a" takes it as a tablet, "user b" with a keyboard and both are not familiar with pdfpc. Then having an automatic detection at startup would be nice.

**Comment by phillipberndt** [comment]
I don't know how the distinction is technically implemented, and, as you, I don't have access to such a device. *Maybe* the keyboard is deactivated in tablet mode. But would it hurt to display the buttons in notebook mode as well, as long as the device allows for pen input?

**Comment by AndreasBilke** [comment]
I am sceptical about the remaining space in the UI. if we have buttons we would loose something. Currently I think we already have a quite dense layout

**Comment by fnevgeny** [comment]
There could be a single small button invoking the whole panel if pressed. Another press - and the panel goes away, so a (temporary) overlaying of other GUI elements would probably be tolerable. Another possibility is to limit the "notes" widget vertically to the lower edge of the current slide and use the space for this panel. Or a combination of the two approaches (when the panel is invisible, the whole empty space below the next-slide preview is devoted to notes; when the panel is shown, the notes widget is resized accordingly).

**Comment by AndreasBilke** [comment]
Okay this would be the KISS version. I can live with it.

**Comment by torwag** [comment]
Thanks for all the comments. I am with @fnevgeny that a small single button could be used to open/close a menu-bar. Automatic recogntion would be nice, but I frighten that this, if not integrated in the GUI-API, would lead to many claims that it don't work on arbitrary devices. Devs would have a hard time to figure out what is going on, as they do not have access to these devices. 
I would add a config line in pdfprc.pc to switch off the button (and hence the access to the menu), if someone really dislikes it. Adding a command line flag is imho not really necessary. Either one uses that feature all the time or one dislikes it and switch it off permanently via the config file. Having a flag makes one group unhappy as they have to specify it over and over again.

What would be the procedure to add this feature. I have a few people around who can look into it. But as we did not yet contribute here, I have no idea how you prefer things to be done.

**Comment by phillipberndt** [comment]
>  Another possibility is to limit the "notes" widget vertically to the lower edge of the current slide and use the space for this panel. 

Please don't make the notes widget smaller. It's one of the key features of pdfpc to be able to add notes to slides.

> What would be the procedure to add this feature. I have a few people around who can look into it. But as we did not yet contribute here, I have no idea how you prefer things to be done.

I'd suggest the following: Fork the repository, play around until you manage to make it work. (If you're familar with Glib/GTK, vala feels comfortable pretty soon, pdfpc was my first contact with the language, too.) Then file a PR, and we (and everyone else interested) will give you feedback on where we think details might need to be changed and merge the PR once everything is resolved.

But this project isn't *that* large. If you prefer a different workflow, go ahead, we'll make it work. :)

**Comment by fnevgeny** [comment]
@phillipberndt 
> Please don't make the notes widget smaller. It's one of the key features of pdfpc to be able to add notes to slides.

After all it looks like it won't take too much of the "notes" real estate. Please see https://github.com/fnevgeny/pdfpc/commit/726a3eeb73bdb7fc9df95d51953caee9b3103cfa for a dummy demo. Alternatively, it can be implemented as an overlay - which is what I originally suggested, but the question is what is the lesser evil - a small space occupied permanently or temporary (periodic ?) occlusions of another widget. Or maybe you have a better idea where to but these buttons?

**Comment by AndreasBilke** [comment]
First, the buttons could only be displayed if there is a touch screen
attached (pberndt talked about the GdkSeat capabilities).

Second, another position might be between the overlay previews (and below
the current slide).

**Comment by fnevgeny** [comment]
> First, the buttons could only be displayed if there is a touch screen attached

I am not sure. There probably are people who would prefer using buttons with usual mouse pointer instead of memorizing keybindings. Certainly first-time users.

**Comment by AndreasBilke** [comment]
But the default key bindings are left and right keys. There are standard in such situations.

**Comment by fnevgeny** [comment]
Hmm, maybe I misunderstood the original request, but my impression is it is about the rest of the functionality as well (e.g., switching on the drawing mode etc).

**Comment by AndreasBilke** [comment]
Oh, you are right. I was on the assumption that he only wanted to switch slides.

But still showing the buttons only with a touch screen is my preferred way.

Am 15. Oktober 2017 09:22:15 MESZ schrieb Evgeny Stambulchik <notifications@github.com>:
>Hmm, maybe I misunderstood the original request, but my impression is
>it is about the rest of the functionality as well (e.g., switching on
>the drawing mode etc).

**Comment by torwag** [comment]
But that would require a 100% failsafe detection mechanism. As I said
earlier, this sort of automatism, usually ally results in a lot of user
feedback ala “detection does not work with <very-strange-local-device>
under <very-exotic-os>". Which are very very hard to solve, as no dev has
physical access to such a combo.

I would be happy with a slider button now and a automatism optionally later.



Am 15.10.2017 10:10 schrieb "Andreas Bilke" <notifications@github.com>:

**Comment by AndreasBilke** [comment]
@fnevgeny Optically I like your toolbox branch. Does the size is okay on your lenovo yoga? Would you like to add button actions to the toolbox?

**Comment by fnevgeny** [comment]
I'm actually thinking of making it a floating/draggable overlay so everyone can choose the position. Do you think it is OK? I plan to tinker with it during the weekend.

**Comment by AndreasBilke** [comment]
Yes why not

**Comment by fnevgeny** [comment]
Please have a look at the current implementation. To make the toolbar floating, I had to add a top-level overlay + a `Gtk.Fixed` container. That's seems the only way to achieve it. There is a minor problem with `Gtk.Fixed` that I haven't been able to solve - for a reason, tooltips are not working with its children.

Questions:
1. How many buttons/actions do we want? All existing  ones? The toolbar would become rather big...
2. The buttons that are currently implemented correspond to toggle actions. So in fact, these buttons can be `Gtk.ToggleButton`s, in which case the status icons (in the left bottom corner) would become redundant and can be removed; the freed place could be used for the (larger) button bar.

Any thoughts/comments/ideas?

**Comment by fnevgeny** [comment]
There is now a config file option `toolbox-direction`, accepting all four `LtoR/RtoL/TtoB/BtoT` variants (though the initial position needs to be fixed for some).

In principle, there are 40 or so actions, but some are less important and some are not needed at all in the presentation mode (e.g., note editing). I would sort them like

Basic navigation (mouse bindings; BTW, do you use an emulation of the right and middle mouse buttons ?):
- next
- prev
- overview

Already Implemented:
- blank
- freeze
- hide
- toggleDrawing
- toggleEraser
- togglePointer
- pause

Nice to have:
- setPenColor
- hideDrawing
- clearDrawing
- increasePen
- decreasePen
- increasePointer
- decreasePointer

Largely optional:
- gotoFirst
- gotoLast
- histBack
- lastOverlay
- next10
- nextOverlay
- nextUnseen
- prev10
- prevOverlay
- prevSeen
- goto
- quit
- start
- resetTimer
- reset

Likely unneeded:
- lastSlide
- jumpLastSlide
- endSlide
- decreaseFontSize
- increaseFontSize
- note
- overlay

**Comment by torwag** [comment]
Hi @fnevgeny,
I tested your branch and it looks already very promising.
I had troubles with the pdfpcrc settings, whenever I closed pdfpc, the given file (I called pdfpc -R ./pdfpcrc testfile.pdf) was empty and the size was 0. Not sure it is related to this branch or not.
However, due to that trouble I could not test the rotation of the menu.

Furthermore, I noticed a bit different behaviours for different buttons. The eraser seems to be only active if the pen itself is active. Is this the right behaviour or intended? 
You are right:

    setPenColor
    hideDrawing
    clearDrawing
    increasePen
    decreasePen
    increasePointer
    decreasePointer

are (for me) the only missing functions for the menu. To make the menu not very long, I could think of the concept that selecting e.g. the pen, a few more buttons will pop up under the pen to adjust thickness by multiple presses of a + and - button and change the colour by multiple presses of a colour button (as they are not that many).

That would also work for the eraser and the pointer. 

Other then this to be happy, I have a few more ideas in mind, but will submit them as different feature requests.

Thanks for your work, it looks really nice.

**Comment by fnevgeny** [comment]
@torwag,

> I had troubles with the pdfpcrc settings, whenever I closed pdfpc, the given file (I called pdfpc -R ./pdfpcrc testfile.pdf) was empty and the size was 0. Not sure it is related to this branch or not.
> However, due to that trouble I could not test the rotation of the menu.

You are confusing a per-presentation preference file (*.pdfpc), generated automatically, with the global pdfpcrc config file. Please `man pdfpcrc` for the latter.

> The eraser seems to be only active if the pen itself is active. Is this the right behaviour or intended?

Yes and no. This is exactly the same behaviour one gets with the key bindings. But I agree that it is not the most intuitive one. It should be altered on a higher level, though.

For the colours, there is already a [ColorButton](https://valadoc.org/gtk+-3.0/Gtk.ColorButton.html), I have already implemented it (though not committed yet). For the pen etc size adjustment, I intended to use [ScaleButton](https://valadoc.org/gtk+-3.0/Gtk.ScaleButton.html), but it appears to be broken, unfortunately.

BTW, you have not answered my question: do you use (in the tablet mode) an emulation for the 2nd and 3rd mouse buttons?

**Comment by AndreasBilke** [comment]
fnevgeny implemented it with #364
