### ISSUE TITLE
4.1 (?) release

### ISSUE THREAD

**Issue by fnevgeny** [pdfpc/pdfpc#303]
Do you think it is about time for a new official release? There have been several bug fixes and new features that probably justify a new version.

**Comment by AndreasBilke** [comment]
I just want to fix (or work around) #214 and then its time for a new release. And I don't care if we name it 4.1 or 4.0.9 :)

**Comment by AndreasBilke** [comment]
#214 seems to be fixed. I would wait some time (1 week) before pushing this as a release.
There is only one question. Until now, we had a list of main contributors if a user called `pdfpc --version`.
Do we want to keep this list (which becomes bigger and bigger) or do we want a `COLLABORATOR` file and point to this in the `pdfpc --version` call?
@fnevgeny @phillipberndt it's up to you!

**Comment by fnevgeny** [comment]
I am completely fine with either variant. (Though I think `CONTRIBUTORS` is a more widespread filename for this purpose.)

**Comment by phillipberndt** [comment]
I'd state that the copyright lies with the pdfpc authors and don't refer to anything specifically. There's a list of contributors in the readme, too - I'd stick with that one. But I don't really care. If you have a good reason for using a contributors file instead, go ahead.

**Comment by AndreasBilke** [comment]
I prefer to remove the list of authors at multiple points. I am always struggling whom to add to this list. To completely skip this "discussion" I would just maintain the list of contributors and only refer to this list.

**Comment by AndreasBilke** [comment]
Done.
