### ISSUE TITLE
What is the CSS class name for author's notes? (to increase them by editing the pdfpc.css)

### ISSUE THREAD

**Issue by Naereen** [pdfpc/pdfpc#304]
Hi!
The [provided `pdfpc.css` file](https://github.com/pdfpc/pdfpc/blob/master/rc/pdfpc.css) does not include a section (class or id) for the author's note box.

I don't really know where to look in the code and preferred to ask: what is the CSS class name for the author's notes?
It would be very convenient, to simply increase the fontsize a little bit when needed (by editing your personal `pdfpc.css` file).

Thanks in advance!

**Comment by Naereen** [comment]
Is it `notes_view` ? https://github.com/pdfpc/pdfpc/blob/386b16c105243b860660c22219f89d55146cf1c4/src/classes/window/presenter.vala#L118

**Comment by Naereen** [comment]
OK, sorry I found it, it is `notesView`:
https://github.com/pdfpc/pdfpc/blob/386b16c105243b860660c22219f89d55146cf1c4/src/classes/window/presenter.vala#L248

**Comment by Naereen** [comment]
(For an example of how to use it to zoom your author notes, see https://github.com/Naereen/slides/blob/master/pdfpc.css#L70)

**Comment by lornajane** [comment]
This was very helpful to me, thanks very much for sharing the exact example!
