### ISSUE TITLE
Write commands

### ISSUE THREAD

**Issue by eolianoe** [pdfpc/pdfpc#308]
Hello,
Is it possible or would it be possible to have the possibility to write commands rather than using key bindings as it is possible in vim or zathura?
For instance pressing 'plus' or writing ':increaseFontSize' would have the same effect.

**Comment by AndreasBilke** [comment]
No it is not possible and I also would not implement it. Since you can configure your key bindings freely you can do vim-like keybindings own your own.

**Comment by eolianoe** [comment]
Ok, thanks for your quick answer. I know that it's possible to configure the key bindings with the pdfrc file but sometimes it's more convenient to write the command with an auto-completion rather than looking for the key binding.

**Comment by fnevgeny** [comment]
There might be GUI controls for this soon #302.
