### ISSUE TITLE
Mono Fonts Aliasing broken

### ISSUE THREAD

**Issue by slardiere** [pdfpc/pdfpc#311]
### Fonts Aliasing

The commit 430d38e specially https://github.com/pdfpc/pdfpc/commit/430d38e06cea152e74d26b9bc5fe6aa3a5f86169#diff-1cf17a795c7670f6879c9ed7dd4db6dc broke the aliasing of the monospace fonts in the PDF (same PDF works well with others tools like evince)

The PDF is make with Latex/Beamer ; reverting specially this diff make the aliasing correct. I don't know what is the goal of this diff for this commit.

- Debian 9 up to date with X
- libgtk-3-dev 3.22.11-1
- libvala-0.34-0 0.34.7-1

**Comment by fnevgeny** [comment]
The change was introduced to prevent rendering of PDF annotations. It is not clear why it would affect (anti?)aliasing of some specific fonts. Can you provide a specific example? Which version of poppler is installed?

**Comment by slardiere** [comment]
- libpoppler-dev 0.48.0-2

I can provide screenshots of the same PDF with and without this patch.

**Comment by fnevgeny** [comment]
OK, and also minimal TeX and PDF files demonstrating the issue.

**Comment by slardiere** [comment]
Without Aliasing : ![screenshot-20171102112405-962x639](https://user-images.githubusercontent.com/511332/32321185-9cc946c6-bfc0-11e7-8e8f-6b9f757faefa.png)

With Aliasing ![screenshot-20171102112515-962x639](https://user-images.githubusercontent.com/511332/32321175-8f866566-bfc0-11e7-9be7-7d4a34d92d9b.png)
PDF : [testmono.pdf](https://github.com/pdfpc/pdfpc/files/1437340/testmono.pdf)
Sample Code : 
~~~
\documentclass{beamer}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{tikz}
\usepackage{beamerthemesplit}
\usepackage{pgfpages}

\usetikzlibrary{mindmap,trees,shadows,arrows,positioning,shapes}
\usetheme{Warsaw}
\beamertemplatetransparentcovered

\title[Test]{Test Mono Fonts Aliasing}

\begin{document}

\begin{frame}[fragile]
  \frametitle{Test Mono Fonts Aliasing}

  \begin{itemize}
    \item Test \texttt{Mono Fonts} Aliasing
  \end{itemize}

\begin{example}
\begin{verbatim}
Test Mono Fonts Aliasing
\end{verbatim}
\end{example}

\end{frame}

\end{document}
~~~

**Comment by fnevgeny** [comment]
When I compile your sample on my machine, everything looks perfect. Please try [test.pdf](https://github.com/pdfpc/pdfpc/files/1437380/test.pdf) and let me know. The difference is Type1 fonts in my case vs. Type3 in yours. Is there any reason using non-Type1 fonts nowadays?

**Comment by slardiere** [comment]
Ok, nice catch, thanks ! 
FTR, I'd to install the package `cm-super` on Debian to get only Type1 fonts.

**Comment by fnevgeny** [comment]
Good. In fact, looking more precisely at your PDF sample with Type3 fonts, I believe _all_ fonts (proportional and not alike) are not antialiased. It is just that the monospaced fonts look uglier without AA. It is not clear why poppler does not do AA in the case of Type3 fonts when the printing rendering is selected.
