### ISSUE TITLE
Wrong scale of thumbnails on presenter screen (HiDPI, Wayland)

### ISSUE THREAD

**Issue by diraimondo** [pdfpc/pdfpc#312]
After the Wayland HiDPI workaround (https://github.com/pdfpc/pdfpc/issues/214)  I'm facing a wrong scale on the presenter screen: the main screen looks right.

I'm using pdfpc 4.1 on Wayland with Gnome Shell 3.26.2, Vala 0.38.2 on Arch Linux. I'm using a Dell XPS 13 with an HiDPI internal screen with an external LoDPI screen/beamer.

![schermata da 2017-11-08 10-33-08](https://user-images.githubusercontent.com/4376789/32541667-acd537c8-c470-11e7-9687-e3df7a09e116.png)

```
$ xrandr
Screen 0: minimum 320 x 200, current 4480 x 1800, maximum 8192 x 8192
XWAYLAND3 connected 3200x1800+0+0 (normal left inverted right x axis y axis) 290mm x 170mm
   3200x1800     59.96*+
XWAYLAND4 connected 1280x1024+3200+0 (normal left inverted right x axis y axis) 340mm x 270mm
   1280x1024     59.89*+
```

It works well if I use pdfpc under Xwayland invoking `GDK_BACKEND=x11 pdfpc ...`.

**Comment by AndreasBilke** [comment]
@diraimondo could you check if pdfpc recognizes the correct scaling value for both monitors? In `fullscreen.vala` there is

```
this.gdk_scale = this.screen_to_use.get_monitor_scale_factor(this.screen_num_to_use);
```
In your setup you should get scaling of `1` for the beamer and `2` for your laptop monitor.

**Comment by diraimondo** [comment]
Sorry for the delay. This is the output with a small `printf` after the `this.gdk_scale` assignment:
```
this.gdk_scale = 2
this.gdk_scale = 1
Screensaver inhibited
Screensaver reactivated
```

**Comment by AndreasBilke** [comment]
Could you print the `this.screen_geometry` in `fullscreen.vala` *before* the wayland workaround is applied? (must be before line 111 in the current HEAD of master).

**Comment by AndreasBilke** [comment]
Very good. This wayland/gtk stuff is so screwed!
For your setup, wayland behaves the samse as X, but we apply the workaround (since we detect the wayland session).
If you remove this wayland  specific block, everything should be fine with your system, right?
Which still leaves me puzzled, since I see currently see no way in detecting "faulty" and correctly working wayland sessions.
@phillipberndt @fnevgeny maybe we should add a `--shitty-wayland` flag to define the different behavior?

**Comment by phillipberndt** [comment]
> maybe we should add a --shitty-wayland flag to define the different behavior?

Seems like the most reasonable way to move forward. Though I'm not certain whether it's fair to blame this entirely on Wayland, so I'd be careful regarding the name ;-)

**Comment by AndreasBilke** [comment]
@diraimondo I looked at your posts on #214. You said you were using gnome 3.26.1 and it worked. Now you have a problem with gnome 3.26.2. I looked into the arch repository. gnome 3.26.2 was uploaded 6 days ago. Do you know if the wrong scaling appeared with the switch of gnome from 3.26.1 to 3.26.2?

**Comment by AndreasBilke** [comment]
@phillipberndt I am very flexible with naming arguments in pdpfc :)

**Comment by diraimondo** [comment]
@AndreasBilke I reported that it worked but it was in the (home) different setting: there I use a HiDPI monitor. At work/class I use a LoDPI monitor.

I'll try to remove the hack to see if it works. I can make other tests if you need.

**Comment by diraimondo** [comment]
@AndreasBilke I confirm that in the work/class setting (internal HiDPI LCD, external LoDPI monitor/beamer) disabling the Wayland-specific workaround makes all work well (see below).

![schermata da 2017-11-15 17-35-18](https://user-images.githubusercontent.com/4376789/32847884-75c5c9a8-ca2b-11e7-879f-4e6326975916.png)

When at home (with an external HiDPI monitor) I will report further information using the same binary: if it can help...

**Comment by diraimondo** [comment]
This is my report using an HiDPI external monitor using gnome 3.26.2:

```
$ xrandr
Screen 0: minimum 320 x 200, current 7040 x 2160, maximum 8192 x 8192
XWAYLAND0 connected 3200x1800+0+0 (normal left inverted right x axis y axis) 290mm x 170mm
   3200x1800     59.96*+
XWAYLAND1 connected 3840x2160+3200+0 (normal left inverted right x axis y axis) 600mm x 340mm
   3840x2160     59.98*+
$ pacman -Q | grep "gnome-shell\|mutter"                                                                                                                
gnome-shell 3.26.2-1
mutter 3.26.2-1
```

without Wayland workaround (disabled in the code): GOOD LOOK
```
this.gdk_scale = 2
this.screen_geometry (before workaround) = (1600, 900)
this.screen_geometry (after workaround) = (1600, 900)
this.gdk_scale = 2
this.screen_geometry (before workaround) = (1920, 1080)
this.screen_geometry (after workaround) = (1920, 1080)
```
![schermata da 2017-11-16 08-26-14](https://user-images.githubusercontent.com/4376789/32878836-eb3e2bcc-caa7-11e7-8641-82a82349a174.png)

with the Wayland workaround (upon revert to the original code): WRONG LOOK
```
this.gdk_scale = 2
this.screen_geometry (before workaround) = (1600, 900)
wayland workaround applied
this.screen_geometry (after workaround) = (800, 450)
this.gdk_scale = 2
this.screen_geometry (before workaround) = (1920, 1080)
wayland workaround appliedthis.screen_geometry (after workaround) = (960, 540)
```
![schermata da 2017-11-16 08-28-36](https://user-images.githubusercontent.com/4376789/32878945-5f6708de-caa8-11e7-9454-94dbe6c5f4e0.png)

I started to suspect that they fixed the weird behavior of Mutter in the 3.26.2 release: indeed I can spot in https://git.gnome.org/browse/mutter/commit/?h=3.26.2 the change "Use the correct monitor for HiDPI scaling of shell chrome [Jonas; #788820]". We need a further condition for the workaround triggering condition! :-)

**Comment by AndreasBilke** [comment]
@perror what distribution (and version) are you using?

**Comment by perror** [comment]
Debian unstable (buster/sid) with:

    ii  xwayland          2:1.19.5-1   amd64        Xwayland X server
    ii  gnome-shell     3.26.2-1      amd64        graphical shell for the GNOME desktop
    ii  libvala-0.36-0   0.36.6-1      amd64        C# like language for the GObject system - library

**Comment by perror** [comment]
I confirm it still works with the configuration I gave above and a fresh clone of pdfpc github.

**Comment by diraimondo** [comment]
@perror What configuration have your monitors (output of `xrandr`)?

**Comment by perror** [comment]
Here is the result of my `xrandr`:

```
Screen 0: minimum 320 x 200, current 4480 x 1600, maximum 8192 x 8192
XWAYLAND0 connected 2560x1600+0+0 (normal left inverted right x axis y axis) 290mm x 180mm
   2560x1600     59.94*+
XWAYLAND2 connected 1920x1080+2560+0 (normal left inverted right x axis y axis) 160mm x 90mm
   1920x1080     59.96*+

```

**Comment by diraimondo** [comment]
@perror What factor scale do you use for both monitors? Gnome 3.26 exposes such value in the monitor configuration.

**Comment by perror** [comment]
Sorry for the long delay, I was 'out'.
So, the built-in display XWAYLAND0 (I am on my laptop) is at 200% and the external display XWAYLAND2 is at 100%.

**Comment by AndreasBilke** [comment]
@phillipberndt @fnevgeny I think we should add a workaround flag in pdfpc. What should be the "default" behaviour? As it is now (applying the workaround if we detect Wayland) or should it be applied only on request?
Arch Linux might be the most recent software stack and for them the workaround does not work (instead, wayland behaves correctly there). But Debian unstable needs the workaround (and probably Debian stable also). I don't know whats Fedora does (since they are also have quit up to date software).

**Comment by phillipberndt** [comment]
I would disable the workaround by default. That's the least confusing solution, and also the one which will most likely be forward compatible. (GTK/Wayland will eventually be fixed.)

**Comment by lorenzhs** [comment]
Does this handle Wayland’s fractional scaling? It appears to round down to the nearest integer scaling factor. With a 150% scaled screen, by default the previews are quite a bit too small, and with `--wayland-workaround` they’re downright tiny.

**Comment by AndreasBilke** [comment]
The API only gives us integers (see https://valadoc.org/gdk-3.0/Gdk.Monitor.get_scale_factor.html). So no chance with fractional scaling.

**Comment by lorenzhs** [comment]
So more of a gdk issue then, thanks.
