### ISSUE TITLE
No Fullscreen on macOS 10.12.6 with 4.1

### ISSUE THREAD

**Issue by kiryph** [pdfpc/pdfpc#315]
I have installed the most recent release 4.1 under macOS 10.12.6 (Sierra) as following:
```sh
$ brew install cmake vala gtk+3 libgee poppler librsvg libcroco
$ wget https://github.com/pdfpc/pdfpc/archive/v4.1.tar.gz
$ tar xvf https://github.com/pdfpc/pdfpc/archive/v4.1.tar.gz
$ cd pdfpc-4.1
$ mkdir build && cd build
$ cmake -DCMAKE_INSTALL_PREFIX="$HOME/.local" -DMOVIES=off ..
$ ccmake .. # modify following to use keg-only gettext:
# CMAKE_EXE_LINKER_FLAGS=-L/usr/local/opt/gettext/lib
# CMAKE_C_FLAGS=-I/usr/local/opt/gettext/include
$ make
```

There is also a [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pdfpc.rb) for your convenience but it has the same issue.

#### Used Distribution (GTK version, vala version)
macOS Sierra 10.12.6

```
❯ brew info vala
vala: stable 0.38.3 (bottled)
❯ brew info gtk+3
gtk+3: stable 3.22.26 (bottled)
````

First of all, I can view the [demo pdf](https://pdfpc.github.io/demo/pdfpc-demo.pdf) with two windows on each screen:
```
~/pdfpc-4.1/build/bin
❯ ./pdfpc  pdfpc-demo.pdf
```
It appears to be that it works successfully without x11/xquartz which is a good thing.
However, I have following issues:

- Application does not start in fullscreen or cannot be made fullscreen (e.g. by clicking on the green plus sign in the window which is nowadays the default behavior on macOS apps)
- the recently added jk `Go to the previous / next slide, skipping over overlays that have already been viewed, but at most one user slide.` skip slide number 4 when returning to previous slide in `pdfpcdemo.pdf` when on slide 5 (e.g. press 8x k, 1x j and we are on slide number 3 instead of 4). 
- swapping `j` and `k` in $HOME/.config/pdfpc/pdfpcrc and calling pdfpc with `./pdfpc -d 30 --pdfpc-location=$HOME/.config/pdfpc/pdfpcrc pdfpc-demo.pdf` overwrites config file with content. See following steps
```
$ cp ~/pdfpc-4.1/rc/pdfpcrc ~/.config/pdfpc/ # create identical copy of default values
# swap j and k
❯ diff ~/pdfpc-4.1/rc/pdfpcrc ~/.config/pdfpc/pdfpcrc
15c15
< bind k         nextUnseen
---
> bind j         nextUnseen
24c24
< bind j         prevSeen
---
> bind k         prevSeen
$ ./pdfpc -d 30 --pdfpc-location=$HOME/.config/pdfpc/pdfpcrc pdfpc-demo.pdf
Could not acquire DBus bus.
# exit pdfpc with q
$ cat ~/.config/pdfpc/pdfpcrc
[duration]
30
```

I could not reproduce the skipping or fullscreen issue in a Virtualbox VM with Guest OS Debian 9.

#### pdfpc version

`4.1` downloaded from github

#### Display Server (X/Wayland)

macOS (no X or wayland)

#### HiDPI Setting (yes/no)

not sure

**Comment by kiryph** [comment]
BTW: the avi file `apollo17.avi` in https://pdfpc.github.io/demo/pdfpc-video-example.zip cannot be played on VLC on macOS Sierra, even though VLC claims to support the video codec theora. The video plays in Debian 9 VM hosted on macOS Sierra.

**Comment by AndreasBilke** [comment]
1. [Fullscreening] Could you try older versions of pdfpc to test if this is a regression?
2. [nextUnseen] Sorry, I don't understand your problem
3. [overridden file] The option `--pdfpc-location` is supposed (as the name says) to tell pdfpc a new location for the pdfpc file (the default location would be in the same folder as the pdf just with the extension `.pdfpc`). So you are misusing this option. This is not a bug.
4. [apollo17.avi] If even your vlc player is not playing it, I think blaming pdfpc is the least useful option.

PS: Please open multiple issues for multiple problems. You mixed 4 items in one issue.

**Comment by kiryph** [comment]
> 4. [apollo17.avi] If even your vlc player is not playing it, I think blaming pdfpc is the least useful option.
>
> PS: Please open multiple issues for multiple problems. You mixed 4 items in one issue.

First of all, apology for mixing several issues into one issue and that my text sounded like I was blaming pdfpc for not playing `apollo17.avi`. In fact, I actually do not think it is an issue of pdfpc and never did. I mentioned this with the hope to get feedback from someone else using a Mac. I was expecting that someone with a Mac would likely respond to this issue and could give me a short feedback of his/her experience.

In order to clean things up, I will create a separate issue for the second (jk skipping a slide completely) and third item (`--pdfpc-location=LOCATION` should be better explained) and will use this issue for the fullscreen problem.

Finally, a big thanks for maintaining pdfpc which I think is a great project to improve presentations written in latex-beamer.

**Comment by kiryph** [comment]
> 1. [Fullscreening] Could you try older versions of pdfpc to test if this is a regression?

Right now I am stuck with the most recent vala version 0.38.3 which means compilation with 4.1, 4.0.8, and 4.0.7 work but not with 4.0.6 or older (see https://github.com/pdfpc/pdfpc/blob/master/CHANGELOG.txt)

I can report regarding the fullscreen issue that there is no change between versions 4.1, 4.0.8 and 4.0.7.

Right now, I have following gtk+3 programs installed on macOS with support for fullscreen:

- [Gimp](http://www.gimp.org/) (does NOTuse macOS native fullscreen which I like because there is no slow animation)
- [RawTherapee](http://rawtherapee.com/) (use macOS native fullscreen)
- [darktable](http://www.darktable.org/) (use macOS native fullscreen)

Maybe they can be of help

**Comment by AndreasBilke** [comment]
Are you willing to help us to resolve this issue (see #318 for my doubts)? Otherwise I would close this issue since non of the maintainer is a Mac OS user and it would be impossible for us to do it on our own.

**Comment by kiryph** [comment]
I would help you. However, I am afraid that I have no experience in writing GTK+ programs or GUI programming in general. Testing and giving feedback would be no problem.
