### ISSUE TITLE
Larger font notes

### ISSUE THREAD

**Issue by cordeiro** [pdfpc/pdfpc#32]
Would it be possible to change the fontsize of the notes? I think currently they are pretty small unfortunately.

[Issue first reported on https://github.com/davvil/pdfpc/issues/91, but still applies]

**Comment by AndreasBilke** [comment]
Would you like to suggest a new font size for notes?

**Comment by cordeiro** [comment]
The ideal font size probably will depend on the screen resolution and amount of notes from the user.
To make things simple, I would suggest to let the font size be an option, editable on the .pdfpc file.

**Comment by AndreasBilke** [comment]
My google search didn't come up with a quick solution to font scaling.
Would it be satisfactory for you if you have a key binding (say
CTRL-<plus>/<minus>) to scale the font size ad hoc in the program?

**Comment by cordeiro** [comment]
Sure, it will be of great help!
Thanks much!

**Comment by AndreasBilke** [comment]
I added some code to make notes font size in/decreasing possible during runtime. The new keybindings are + and -. Could you test my branch issue-32 and say if this is useful for you?

**Comment by cordeiro** [comment]
It didn't work here.
I've compiled it, ran with -S, added some notes and tried CTRL-+, CTRL--, +, - both during presentation or during note editing modes, but nothing happened.

But probably I'm doing something wrong. :)

**Comment by AndreasBilke** [comment]
the key binding is <plus>, without ctrl. and it should work during
presentation (no editing).

**Comment by AndreasBilke** [comment]
My testing was done with only one monitor attached. If I use two of them then my code did not work. I will have a look at this later.

**Comment by AndreasBilke** [comment]
Could someone else test this on their machines? I tested a second computer (with different vala versio etc) and it works there also.

**Comment by AndreasBilke** [comment]
@cordeiro could you test this feature from #37 ?

**Comment by cordeiro** [comment]
Not yet, sorry.

2015-07-02 4:25 GMT-03:00 Andreas Bilke <notifications@github.com>:
