### ISSUE TITLE
Option to not override drawing tool selection when using a tablet

### ISSUE THREAD

**Issue by leomao** [pdfpc/pdfpc#320]
### Expected Behaviour
Some tablets can't report as eraser input devices.  I think we should allow users to use the tablet just like another mouse and use keyboard to toggle the pen and eraser mode.

### Actual Behaviour
Can't use tablet with eraser tool

#### pdfpc version
Version: 4.1

#### Used Distribution (GTK version, vala version)
gtk 3.22.26
vala 0.38.3

#### Display Server (X/Wayland)
xorg-server 1.19.5

#### HiDPI Setting (yes/no)
no

**Comment by AndreasBilke** [comment]
Sorry I don't understand your issue.

**Comment by leomao** [comment]
Sorry for the late reply, I updated the issue.
The issue is that there is no way to use the connected tablet as the eraser tool if that tablet can't report as an eraser device.

**Comment by AndreasBilke** [comment]
Is #364 helping you? (its already in master)

**Comment by fnevgeny** [comment]
@leomao: it looks like the code does just that:

https://github.com/pdfpc/pdfpc/blob/df7ee95bb8d594a1435e2153a1fa48937987d8cc/src/classes/presentation_controller.vala#L472-L480

I wonder why it doesn't work as expected in your case.

**Comment by leomao** [comment]
The new release doesn't help.  Accroding to the code, when the input source reports itself as a pen, there is no way to switch to the eraser tool. I think this is the root cause.

**Comment by fnevgeny** [comment]
Ah, I see - the eraser isn't just not reported as an eraser, but reported as a **pen** (and not a generic mouse etc). Try commenting out lines 476-477 and see if it helps.

On the other hand, how does the tablet work with other software, e.g., gimp?

**Comment by fnevgeny** [comment]
@leomao: can you please check it?

**Comment by fnevgeny** [comment]
@leomao: thanks. I have no input tablet devices to check. Does gimp automatically recognize when you use pen or eraser, or you had to manually assign them?

**Comment by leomao** [comment]
Actually, the tablet device I tested doesn't have the ability to change modes.  I need to manually change the tool via the toolbox in gimp.  I think it always behaves like a pen.  So `source_type == Gdk.InputSource.PEN` causes the problem (which is always true).

**Comment by fnevgeny** [comment]
OK, good. All I wanted to make sure is we don't miss a property that other software uses to identify a source as an eraser in spite of being reported as Gdk.InputSource.PEN.

I think a config option should be added to disable the input type autodetection, e.g.

`option disable-input-autodetection true`

**Comment by fnevgeny** [comment]
@leomao, please check #388.

**Comment by jolars** [comment]
Shouldn't this option be configurable when calling pdfpc? That is, shouldn't there also be an entry in https://github.com/pdfpc/pdfpc/blob/master/src/pdfpc.vala ?

**Comment by fnevgeny** [comment]
> Shouldn't this option be configurable when calling pdfpc?

Why? The command line options are those one chooses depending on the presentation loaded. Stuff like hardware quirks depend on the hardware, and so typically set once; do you change the input device frequently?

**Comment by jolars** [comment]
> do you change the input device frequently?

Actually I do (switching between using a tablet and not using a tablet), but setting it once is fine anyway (I don't need the autodetect option).

> The command line options are those one chooses depending on the presentation loaded. Stuff like hardware quirks depend on the hardware, and so typically set once;

Yes, sorry, I hadn't figured out that there even was a configuration file. (The manpages for pdfpc only refers to pdfpcrc for setting key bindings and there is no information in the readme.)
