### ISSUE TITLE
Options in presenter view not usable on HiDPI screens

### ISSUE THREAD

**Issue by qfvldaa2xn** [pdfpc/pdfpc#321]
I had the same issue as in #312. But https://github.com/pdfpc/pdfpc/pull/317 solved it.

But now there is an issue with annotate, freeze, and black on HiDPI screens (i.e. the keys **n**, **f**, and **b** do not work as expected). On a non HiDPI screen all options work as expected though.

### Steps to reproduce the behaviour (e.g. a minimal working example for the PDF)
1. Open a PDF and let the presenter view be on the HiDPI screen
2. Try to click **f** or **b**. Then icons are too big and (probably) push the timer out of the screen (hence not visible anymore).
3. Try to click **n**. Then I am not able to annotate anything, but instead pdfpc freezes.

#### pdfpc version
pdfpc 4.1 including patch 317
(see https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/pdfpc&id=a8dfb3f0235732e9c2b8dc5b902fcf6a593a818d)

#### Used Distribution (GTK version, vala version)
archlinux
gtk3 3.22.26

#### Display Server (X/Wayland)
Wayland

#### HiDPI Setting (yes/no)
Yes

**Comment by AndreasBilke** [comment]
I tried Fedora with Wayland etc. and I can't reproduce. Can you help us in resolving this?

**Comment by qfvldaa2xn** [comment]
Sure, how can I help?

Here the presenter view on the left side and the presentation on the right side. Since #317 it works:
![With #317 it works](https://user-images.githubusercontent.com/13978911/33702965-2c9baa8e-db26-11e7-8724-511f5f1557b3.png)

When I press **f** the timer is not visible anymore, but I can continue with the presentation (same with **b**):
![f](https://user-images.githubusercontent.com/13978911/33703030-86b536a2-db26-11e7-8715-6fd06ac189ea.png)

When I press **n** it just freezes, no keys work (neither arrow keys nor ESC). Just stays at the current slide:
![screenshot from 2017-12-07 08-18-08](https://user-images.githubusercontent.com/13978911/33703181-5360f9a2-db27-11e7-8c44-c4c9032d5a0e.png)

**Comment by qfvldaa2xn** [comment]
When I switch the screens, presenter view on the non HiDPI screen and the presentation on the HiDPI screen everything works as expected:
![Presenter view non HiDPI **f**](https://user-images.githubusercontent.com/13978911/33703253-a5f1eed8-db27-11e7-9cb6-61ff55d4a867.png)

Also **n** works as expected.

**Comment by qfvldaa2xn** [comment]
I just realized that annotating works when the pdfpc window is frozen but I use another window in between and then I come back to the presentation then I can annotate as usual and all keys work again.

**Comment by lkuchenb** [comment]
I'm unsure whether I should report a new issue or whether this is the same issue.

I'm using a Macbook Pro 13" with a "Retina" display. Using features such as drawing, pointer or freeze renders the presenter view unusable for me. It freezes, I can still switch slides and see them change on the audience view, but I never see any of the requested features, e.g. the pointer.

With switched screens, i.e. the builtin display as audience view, it works fine. The pointer and drawing is quite laggy though.

pdfpc v4.1.2

**Comment by fnevgeny** [comment]
@qfvldaa2xn: What are the screen resolutions?

**Comment by fnevgeny** [comment]
So can someone experiencing these problem(s) report on the exact screen resolutions?

**Comment by lkuchenb** [comment]
@maehne The problem has somewhat vanished for me, even back then. After the next reboot I wasn't able to reproduce it any longer

**Comment by fnevgeny** [comment]
@maehne, @lkuchenb: Do I understand correctly that the only issue remaining is the oversized icons?
@qfvldaa2xn: What about you?

**Comment by qfvldaa2xn** [comment]
Sorry just saw your questions.
My screen solution is 3200x1800 and I still experience the issue, see:

![pdfpc_screenshot](https://user-images.githubusercontent.com/13978911/47963785-e338c280-e030-11e8-99f5-03ea7ab8bb25.png)

**Comment by maehne** [comment]
@fnevgeny: Sorry, I missed your last question. Yes, the icon on the lower left side is always oversized as in the screenshot by @qfvldaa2xn from today, 2018-11-04. Freeze and blank works as expected. However hide 'h' does not work as I would expect. According to `man pdfpc` it should "Hide  the  presentation  window  (i.e. make other windows on the other screen visible)". However, The presentation just goes black (as with pushing `b`). A second push on `h` makes the presenter console go black and the presentation screen to show the slide. A third push on `h` makes the presentation screen to go black again and the presentation console to show up. Finally, a fourth push on `h` displays both, presenter screen and presenter console again at the same time. The cause might be that the presenter console and presenter screen seem to get treated as tabs of the same full screen window on a single screen after pushing `h`.

This behaviour I observe with pdfpc v4.2.1 installed using `sudo port -v install pdfpc +quartz" on macOS High Sierra 10.13.6 (17G3025).

**Comment by fnevgeny** [comment]
@qfvldaa2xn: does it happen also in the single-screen mode (`pdfpc -S`)?

**Comment by fnevgeny** [comment]
@maehne, @qfvldaa2xn: Re: icons size, can you please check if removing `*this.gdk_scale` from these lines fixes the issue?

https://github.com/pdfpc/pdfpc/blob/e858f2067b10d1c567d6c30f2d07e6fecd4dcd27/src/classes/window/presenter.vala#L720-L721

**Comment by qfvldaa2xn** [comment]
@fnevgeny 
Regarding your first question `-S` has the same issue.
And second question, yes removing `*this.gdk_scale` fixes the issue :)

**Comment by fnevgeny** [comment]
@qfvldaa2xn: so now the `n`, `f`, and `b` functions work correctly? What about the toolbox buttons/icons - are they rendered OK after removing the `this.gdk_scale` mutipliers? If not, please post a screenshot.

**Comment by qfvldaa2xn** [comment]
Yes, the functions work fine and the buttons are rendered okay.
So from my side this issue can be closed! Thanks!

**Comment by maehne** [comment]
I just would like to confirm that the change above fixes the icon scaling on macOS as well.

**Comment by fnevgeny** [comment]
> I just would like to confirm that the change above fixes the icon scaling on macOS as well.

Does macOS use Wayland?!

**Comment by maehne** [comment]
No, their API is called Quartz, but I observed the same issues on my MacBook with Retina display.

**Comment by qfvldaa2xn** [comment]
@maehne did you try the suggesetion from here https://github.com/pdfpc/pdfpc/issues/321#issuecomment-435681726 or did you try https://github.com/pdfpc/pdfpc/commit/42b436a89971066603bc5e6161278173913ca785?

I never used macos myself, but `gdk_scale` applies there as well?

**Comment by maehne** [comment]
Me neither -- maybe my comment was to quick and it is still an issue. I am working this morning on a different monitor setup (2 Full HD 1920 x 1080 external monitors rather than one extra-wide screen with 3840 x 1080 resolution) than when I observed the scaling issue.

**Comment by fnevgeny** [comment]
3840 x 1080 doesn't look like retina... The size itself isn't an issue, my monitor is 3440x1440. The problems begin with DPI scaling, and this appears to be inconsistent in various implementations (apparently, wayland scales icons and other GUI elements differently).

**Comment by AndreasBilke** [comment]
On Tue Nov 06, 2018 at 01:54:10AM -0800, Torsten Maehne wrote:
> Me neither -- maybe my comment was to quick and it is still an issue. I
> am working this morning on a different monitor setup (2 Full HD 1920 x
> 1080 external monitors rather than one extra-wide screen with 3840 x 1080
> resolution) than when I observed the scaling issue.

We could also do scaling, iff we detect X11 sessions.

**Comment by fnevgeny** [comment]
> We could also do scaling, iff we detect X11 sessions.

Would it work also for macos? Do Quartz/QuartzX behave differently in this respect?

**Comment by AndreasBilke** [comment]
I don't know, but gdk know also a check for quartz back ends (but no distinction between X and non X)

**Comment by fnevgeny** [comment]
@maehne Torsten, can you please check?
