### ISSUE TITLE
Multiple videos on a single frame limited to 8?

### ISSUE THREAD

**Issue by complanar** [pdfpc/pdfpc#322]
The following minimal working example produces a pdf file with the desired output. 
I expected pdfpc to play the videos as normal.

### Actual Behaviour
Actually only the first 8 videos are played. When loading the frame the command line prints an error for every video that could not be loaded:
`Gstreamer error Could not initialise Xv output`

### Minimal working example
```
\documentclass[12pt]{beamer}
\usepackage{multimedia}
\usepackage{tikz}

\newcommand{\audio}{\movie{\rule{4cm}{0.5cm}}{scheming_weasel_faster_audio.mp4}}

\begin{document}
\begin{frame}{Multiple videos on a single frame}
  \begin{enumerate}
    \item \audio
    \item \audio
    \item \audio
    \item \audio
    \item \audio
    \item \audio
    \item \audio
    \item \audio
    \item \audio
    \item \audio
  \end{enumerate}
\end{frame}

\end{document}
```

### Environment
The described behaviour was viewed in pdfpc versions 4.0.7 and 4.0.2 (I did test on two different machines with different versions installed)

Linux mint 18.2, GTK3
X-Display Server

The problem persisted regardless of the used video file (differing in file names, file size, codec and so on, 10 different files and so on)

Can’t attach the used video file because of file type restrictions at upload.

**Comment by AndreasBilke** [comment]
I could not reproduce this with latest pdfpc, gstreamer, X server (... etc. I am using arch). It is very laggy to play these videos, but it works and I have no error messages.

Also pdfpc as itself does nothing limited to 8 videos per frame. Maybe this comes from gstreamer?

**Comment by complanar** [comment]
I forgot to mention, that this behaviour does not occur when using a single screen. 
To reproduce it with only one screen, I had to start pdfpc with -w option.

I can not upgrade quickly to latest version at the moment. I will try it in a couple of days when I have the time to compile it by myself.

**Comment by phillipberndt** [comment]
I don't see this restriction either (with `-w` you effectively have 16 xv overlays; I had no problem starting ~20 just now). I also assume that this is driver related. As a workaround, you could add your videos using

    \alt<1>{video here}{thumbnail here}

This way, you'd only have one video per real slide.
