### ISSUE TITLE
Feature Request:  Toggle to white, ruled and lined pages for quick explanations

### ISSUE THREAD

**Issue by torwag** [pdfpc/pdfpc#323]
Sometimes during a lecture or presentation, the audience might ask a question, which require some drawing, calculation, etc. Maybe one likes to write down some information which change from lecture to lecture (e. g. upcoming time-table changes, etc.)  
It would be handy to display an empty white page, a ruled page or a lined page (or for that matter any kind of pdf which contains a  single page and therefore act as some sort of template) just in-between the presentation to do exactly this. After finishing, the current slide of the actual presentation should be displayed again. 
It could be even the same single canvas and one can call it on top or remove it as needed. For a first functionality, I do not see the need to save the canva(s) for later usage. However, in the future it might become handy for some people if the, or in case of multiple canvas each, canvas will be saved as png so that one can e.g. hand it to the class or keep it for own usage or references.

**Comment by fnevgeny** [comment]
> It would be handy to display an empty white page, a ruled page or a lined page (or for that matter any kind of pdf which contains a single page and therefore act as some sort of template)

That implies the "template" pdf should have the same dimensions as your slides, meaning it cannot be something universal installed as a part of pdfpc. Which prompts me to ask - what is wrong with just adding an empty (or ruled, lined, etc to your liking) page at the end of your presentation just for this purpose? Then switch (e.g., using the `goto` action) to it and draw.

**Comment by AndreasBilke** [comment]
A proposal for achieving this behavior was made and #418 shows a way how to get to this notes page quickly.
