### ISSUE TITLE
Feature Request: Toggle between full annotation view and normal presenter view

### ISSUE THREAD

**Issue by torwag** [pdfpc/pdfpc#324]
For some time now, I am using pdfpc including the "new" annotation function. 
All this works great and I really appreciate your work and efforts here.

Using a relative small screen, the canvas of the current slide is rather small in the presenter view. 
It would be nice if there is the possibility to toggle between a full screen annotation view (including @fnevgeny nice button menu #302 ) and the normal presenter view. 

This would give us the full screen estate during drawing and annotation, which would significantly increase accuracy and precision. 

I guess, that the full screen itself is rather simple to accomplish, what might need work (if not done automatically by the underlying code for the canvas drawing) is the recalculation of the annotation coordinates. However, the functionality might be rather close to the implementation between the presenter view and the presentation view.  Basically, the annotation view would be the presentation view with enabled menu (#302) and enabled annotation function.

**Comment by AndreasBilke** [comment]
It is actually not that easy to have this feature in a nice way. The current layout is quite fixed and "manually" layouted. One solution would be to hide all Widgets except the current slide view. This might work (I didn't tested it) but for sure the rendering of the slide would be blurry (because it is pixel perfect rendered for the original size with all the widgets).

**Comment by torwag** [comment]
This looks really promising.
I can confirm it is working after applying the changes you described above.
Even rescaling of the hand-drawing seems to work flawless. 
One glitch I caught. Resizing after hand-drawing makes the drawing disappear in the presenter view. The presentation view works fine. Furthermore, albeit the pen is still selected, the mode switched. One has to deselect and re-select the pen. After that the existing drawings appear correct again and one can go on with further drawing.
Now, with this function all what would be needed is a shortcut to toggle between a maximized main presenter screen and the standard resp. the previous layout. It might be even nice to combine this with the pen-selection-hook thus, that if one select the pen, the screen will resize.

**Comment by torwag** [comment]
BTW. Does the rescaling also resample all thumbnails for every scale change? If so, it might be a good idea to test this extensively, as it could potentially slow down pdfpc a lot mid-term of the presentation.

**Comment by fnevgeny** [comment]
> One glitch I caught. Resizing after hand-drawing makes the drawing disappear in the presenter view. The presentation view works fine. Furthermore, albeit the pen is still selected, the mode switched. One has to deselect and re-select the pen. After that the existing drawings appear correct again and one can go on with further drawing.

Yes, I know. Same about the highlight (pointer) mode. It will be fixed, of course.

> It might be even nice to combine this with the pen-selection-hook thus, that if one select the pen, the screen will resize.

Maybe indeed, thanks; I didn't think about it. But it will need the caching to be redone, which is on the todo list anyway.

> BTW. Does the rescaling also resample all thumbnails for every scale change? If so, it might be a good idea to test this extensively, as it could potentially slow down pdfpc a lot mid-term of the presentation.

It does indeed. Again, #211 needs to be taken care of, sooner or later...
