### ISSUE TITLE
Annotating does not work when presenter view is not in focus.

### ISSUE THREAD

**Issue by qfvldaa2xn** [pdfpc/pdfpc#325]
Annotating does not work when another window than pdfpc presenter view is in focus.
I opened this new issue as this issue is unrelated from the HiDPI issue with **b** and **f** from #321.

### Steps to reproduce
1. Start a presentation with --switch-screens.
2. Click **n** to annotate something.
3. pdfpc seems froozen
4. Putting the presenter view into focus
5. Annotating works.

The third step is the unexpected behaviour.

#### pdfpc version
pdfpc 4.1

#### Used Distribution (GTK version, vala version)
archlinux
gtk3 3.22.26

#### Display Server (X/Wayland)
Wayland

**Comment by fnevgeny** [comment]
@qfvldaa2xn: what would be the "expected" behavior? I think note editing should be disabled if the presenter window is not in focus, that's all.

**Comment by qfvldaa2xn** [comment]
Sorry maybe the description of the issue was not clear enough. I didn't mean other windows of another application, but another pdfpc window.

When you start pdfpc with no additional arguments, then pdfpc opens and presenter view is in focus. In this first case **n** works as expected, because I can add an annotation. 

There are cases that, for example, the presentation view instead of the presenter view is in focus:
(1) When you start pdfpc with `--switch-screens` then the presentation view is in focus.
(2) Click on the presentation view with your mouse and it is also in focus.

In these cases when I press **n** pdfpc seems frozen and does not react to any input from the keyboard. Hence the issue is after pressing **n** in pdfpc when the focus is in any other pdfpc window than the presenter view pdfpc seems frozen.

**Comment by fnevgeny** [comment]
> I didn't mean other windows of another application, but another pdfpc window.

Sure, I understand. But why (and _how_) would you expect to edit notes if the current (full-screen!) window has no place for them?

**Comment by qfvldaa2xn** [comment]
Sorry I still have the feeling that we talk about something different. I don't want to add an annotation at the presentation window.

When I have pdfpc open I do not really see which window is in focus, right?
Because the presenter view is on one screen and the presentation view is on the other screen.
I just click through the presentation on the keyboard (at the moment I don't really see which window is in focus, because the arrow buttons work on both). Then I want to enter an annotation. It either works if the right window is in focus, or it doesn't and pdfpc freezes. So the problem here is the freezing of pdfpc!

The first time I was faced with pdfpc being frozen, I just killed the process.

So in my opinion this issue is still a bug, because pdfpc seems frozen and does not take any input anymore! (And not because I cannot edit an annotation in the cases described above.)

**Comment by fnevgeny** [comment]
I also have a feeling we talk about different things :). Let's make it clear: when I think of a two-screen setup, one is my latop's ahead of me, and the other is overhead/projector behind my back; I don't actually see the second one, lest "click" on it :). The `--switch-screens` option is a workaround for the cases when pdfpc for a reason wrongly identifies monitors as primary (presenter) and secondary (presentation). Neither can I imagine why would someone need to edit notes _during_ the presentation.

But your use case is certainly different; can you please explain what you use pdfpc for?

> I just click through the presentation on the keyboard (at the moment I don't really see which window is in focus, because the arrow buttons work on both).

Probably the presentation window shouldn't react to inputs at all. Again, in my use-case scenario, I see no need for this functionality.

> So in my opinion this issue is still a bug

I don't say it isn't; just trying to understand what really needs to be fixed.

**Comment by qfvldaa2xn** [comment]
Well, basically I first thought that it belongs to the same issue as #321, but as you see in following comment https://github.com/pdfpc/pdfpc/issues/321#issuecomment-349885992 it was not the same issue. Though I thought I might open a new issue.

I agree during a presentation I don't want to annotate anything, but actually I use pdfpc also when rehearsing a presentation and during rehearsals new ideas to annotate pop up. If I remember right, in my office I have to use `--switch-screens`. So that's how I stumbled upon this issue.

Back then I thought it might be interesting for you to know about the issue I stumbled upon. But you might be right, this is probably just an issue in rare cases! So feel free to just close the issue, as not many people will stumble upon this issue and there is actually even a workaround by clicking on the presenter view.

**Comment by fnevgeny** [comment]
> I agree during a presentation I don't want to annotate anything, but actually I use pdfpc also when rehearsing a presentation and during rehearsals new ideas to annotate pop up.

OK, but then the single-screen mode (-S) should be just fine for rehearsals?

> So feel free to just close the issue

I don't want without fixing it:) But I still think that the fix should be disabling the note editing (as I suggested in my first comment) or even all keyboard/mouse events (the last comment). And making the presenter window always focused, of course.

**Comment by qfvldaa2xn** [comment]
> OK, but then the single-screen mode (-S) should be just fine for rehearsals?

Sure, the single-screen mode is fine for rehearsals. I use to work on two screens in the office, that's why I didn't use the argument `-S`. But sure that's all you need for rehearsals.

> the fix should be disabling the note editing (as I suggested in my first comment) or even all keyboard/mouse events (the last comment) on the _presentation_ window.

I think that the second case is less user-friendly. Obviously in a perfect world no one would want to click in the presentation screen behind them. But it might happen accidentally (if someone is nervous or whatsoever), or someone might even have the idea to use the mouse pointer instead of the pdfpc pointer to show something on the slides? You never know... And in these cases I think it might be confusing if all input events are disabled. People than might think that pdfpc is frozen!? Imagine that during an important presentation.

> And making the presenter window always focused, of course.

That helps as well ;)

**Comment by maehne** [comment]
> Sorry I still have the feeling that we talk about something different. I don't want to add an annotation at the presentation window.
> 
> When I have pdfpc open I do not really see which window is in focus, right?
> Because the presenter view is on one screen and the presentation view is on the other screen.
> I just click through the presentation on the keyboard (at the moment I don't really see which window is in focus, because the arrow buttons work on both). Then I want to enter an annotation. It either works if the right window is in focus, or it doesn't and pdfpc freezes. So the problem here is the freezing of pdfpc!
> 
> The first time I was faced with pdfpc being frozen, I just killed the process.
> 
> So in my opinion this issue is still a bug, because pdfpc seems frozen and does not take any input anymore! (And not because I cannot edit an annotation in the cases described above.)

I also hit several times the freezing issue described by @qfvldaa2xn inadvertently. IMHO this does not only happen during "relatively rare" use cases such as rehearsals, but also during live presentations. As described in issue #379, `pdfpc` has quite some key bindings. E.g. `b` (blank) and `h` (hide) are right next to `n` and so you can hit `n` easily by accident. In addition, there are presenter remotes, which emulate a mouse (e.g., Logitech Spotlight), or one uses simply the mouse arrow to point on something on the slides. In these cases, it is relatively easy to accidentally click into the presentation window and thus giving it focus so that at the next push on `n` the freezing behaviour shows up.

Regarding the numerous key bindings, an additional issue is that there is no way to display the current key mapping inside pdfpc, when it is running. I always have to quit pdfpc to confer to the man page to look up the right key activate the right function. It would be actually nice if pdfpc would offer a kind of online help, e.g., when pressing `F1` or `?`, which would summarise at least the currently active key bindings. E.g., the "notes" area could be `misused` for that functionality. I.e., if a user presses `F1`, `?`, or any other key to which the online help function got mapped, a summary of all key mappings would get displayed in the notes pane. Once, the user would advance his presentation by a slide, the notes pane could get cleared again and show the notes associated with this new slide.

**Comment by fnevgeny** [comment]
> It would be actually nice if pdfpc would offer a kind of online help, e.g., when pressing `F1` or `?`

Yes, there is already such a request: #326.

**Comment by AndreasBilke** [comment]
Resolved with #407
