### ISSUE TITLE
Nothing happens when clicking video link

### ISSUE THREAD

**Issue by bisraelsen** [pdfpc/pdfpc#327]
### Expected Behaviour
video from example should display

### Actual Behaviour
On clicking in the presentation nothing happens, the terminal gives the following error

    (pdfpc:28829): CRITICAL **: pdfpc_view_behaviour_pdf_link_implementation_on_clicked_external_command: assertion 'arguments != NULL' failed

### If it's a bug: Steps to reproduce the behaviour (e.g. a minimal working example for the PDF)
Using `lxss` installation from README

#### pdfpc version
v3.1.1
#### Display Server (X/Wayland)
X (vcxsrv)
#### HiDPI Setting (yes/no)
no

**Comment by AndreasBilke** [comment]
Are you serious about the pdfpc version of v3.1.1? It would be 5 years old.

Am 8. Dezember 2017 01:53:13 MEZ schrieb Brett <notifications@github.com>:
>### Expected Behaviour
>video from example should display
>
>### Actual Behaviour
>On clicking in the presentation nothing happens, the terminal gives the
>following error
>
>(pdfpc:28829): CRITICAL **:
>pdfpc_view_behaviour_pdf_link_implementation_on_clicked_external_command:
>assertion 'arguments != NULL' failed
>
>### If it's a bug: Steps to reproduce the behaviour (e.g. a minimal
>working example for the PDF)
>Using `lxss` installation from README
>
>#### pdfpc version
>v3.1.1
>#### Used Distribution (GTK version, vala version)
>
>#### Display Server (X/Wayland)
>X (vcxsrv)
>#### HiDPI Setting (yes/no)
>no

**Comment by bisraelsen** [comment]
Yeah I was serious... I was running the original lxss which was 14.04, upgraded to 16.04 and things are better now.
