### ISSUE TITLE
Pointer/draw-mode not toggled

### ISSUE THREAD

**Issue by tpd-opitz** [pdfpc/pdfpc#329]
I installed `pdfpc` via *apt* on my xubuntu laptop (Lifebook E-series). I did not change any configuration of `pdfpc` (especually I did not edit, delete or move any of   `pdfpc`s configuration files.

### Expected Behaviour
after pressing `8` (either normal *number key* or on *numpad*) a pointer is shown on both, the *presenter view* and the *presentation view* and by *left click+drag* I can select a rectangle that gets highlighted.  

### Actual Behaviour
pressing `8` does no visual change, left click advances to next slide.

### If it's a bug: Steps to reproduce the behaviour (e.g. a minimal working example for the PDF)
[any]

#### pdfpc version
pdfpc v4.0.2

#### Used Distribution (GTK version, vala version)
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

libgtk-3-0:amd64             3.18.9-1ubuntu3.3         amd64  

#### Display Server (X/Wayland)
xfce4-about 4.12.1 (Xfce 4.12)

#### HiDPI Setting (yes/no)
no

**Comment by AndreasBilke** [comment]
> #### pdfpc version
> pdfpc v4.0.2

Please test the latest version from master.

**Comment by tpd-opitz** [comment]
you're saying that the version distributes by the standard ubuntu repository is simply too old?

**Comment by AndreasBilke** [comment]
Before starting to debug anything, I ask you to test the latest version.
Your version is almost two years old.

**Comment by tpd-opitz** [comment]
Is there any way to get a newer version using apt[-get] infrastructure or do I have to compile it myself?

**Comment by AndreasBilke** [comment]
Debian/Ubuntu has newer compiled versions (for newer distributions). I
don't know whats with the dependencies. I think compiling your self is the
easiest one.

**Comment by tpd-opitz** [comment]
I checked with v4.0.6 on ubuntu 17.04. There it works. Thanks!
