### ISSUE TITLE
Freezes when changing movie slides too quickly

### ISSUE THREAD

**Issue by funkey** [pdfpc/pdfpc#330]
### Expected Behaviour
No freeze ;)

### Actual Behaviour
When switching quickly between slides with videos, `pdfpc` freezes and spits out many of the following error messages:
```
Trying to dispose element inputselector21, but it is in PLAYING instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.
```
### If it's a bug: Steps to reproduce the behaviour (e.g. a minimal working example for the PDF)
Open a slide with several videos (like the one linked in the readme). Quickly change between the slides using the arrow keys.

#### pdfpc version
4.1 (current master 305c777)

#### Used Distribution (GTK version, vala version)
Vala 0.30.1
GTK 3.18.9

#### Display Server (X/Wayland)
X

#### HiDPI Setting (yes/no)
no

**Comment by phillipberndt** [comment]
I only get a warning, not a freeze, but

    (pdfpc:5856): GStreamer-CRITICAL **: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed


only surfaces when I toggle between video slides overly quickly. Both probably have the same origin.

**Comment by axtimwalde** [comment]
I can confirm this bug but instead of a freeze, I often get a black rectangle in the area where the video was supposed to play.  The area will stay there regardless what slide is being displayed, i.e. renders the presentation useless.  It is possible to pile up several of those dead areas by further switching over slides with videos fast.  My OS is Ubuntu 18.04.

**Comment by fnevgeny** [comment]
In PR #363, I suggest switching to fully synchronous video loading, eliminating the race condition.

A potential drawback could be some delay when switching to slides with videos embedded. Personally, I could not see any noticeable delay - neither with the standard demo, nor with my own presentations. However, I assume with a very old hardware there could be some. There is `#if MOVIE_LOAD_ASYNC` compilation option that can revert to the previous behavior, if desired. Let's see if there are complaints, then a command-line or config switch can be made for that.
