### ISSUE TITLE
Dual-screen mode broken on macOS 10.12.6 with 4.1 (and 3.1.1)

### ISSUE THREAD

**Issue by ChristopheBerthod** [pdfpc/pdfpc#331]
### Expected Behaviour
Dual-screen presentation
### Actual Behaviour
Only a wide presenter screen
#### pdfpc version
4.1 and 3.1.1
#### Used Distribution (GTK version, vala version)
macOS 10.12.6, Gtk+-3.22.26, vala 0.38.6
#### Display Server (X/Wayland)
X
#### HiDPI Setting (yes/no)
no

This may be related with #315. Something must have changed in the way macOS handles monitors and Gdk doesn't know about it: I can't tell exactly which macOS update is guilty, but at some point my pdfpc became unable to recognize that there is an external monitor connected to the laptop. As a result, both pdfpc-3.1.1 (the binary distributed by MacPorts) and pdfpc-4.1 (compiled by me) start in fullscreen mode, however with the presenter view occupying on the laptop monitor a screen with the total size of the two monitors, and nothing appearing on the external monitor.

As it turns out, the function `get_n_monitors()` used in pdfpc.vala returns 1 even if the external monitor is connected. The function `get_monitor_geometry()` returns a width of 2960, which is the sum of 1680 for my laptop and 1280 for my external monitor. This looks more like a Gdk-for-macOS problem, but I'm willing to help finding a fix, because I like the dual-screen mode of pdfpc very much, and could not find any satisfactory alternative on the mac to display LaTeX beamer presentations. Unfortunately, I know nothing about vala and Gdk, and will not be able to do anything beyond basic tests in the source code.

For information, the gtk+ version is 3.22.26, and the following warnings are issued when compiling pdfpc-4.1:

```
Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
Gdk.Display.get_device_manager has been deprecated since 3.20
Gdk.DeviceManager.get_client_pointer has been deprecated since 3.20
Gdk.Screen.get_monitor_at_point has been deprecated since 3.22
Gdk.Screen.get_monitor_scale_factor has been deprecated since 3.22
Gtk.Widget.override_font has been deprecated since 3.16
Gdk.Screen.get_primary_monitor has been deprecated since 3.22
```

**Comment by wrtc90** [comment]
For me (v4.1 on Mac OS 10.12.6, gtk+3 3.22.29_1, vala 0.38.3) dual-screen mode works. The only thing that doesn't is getting fullscreen windows.

**Comment by ChristopheBerthod** [comment]
That's exactly the point. You can get the presentation and the presenter windows, but you can't manage to have the presentation window going fullscreen on the external monitor (this is what I call—perhaps imprecisely—dual-screen mode).

Let me explain how I got around it. This is not a stable solution, but a trick that allows me to achieve the behavior I'm expecting. Perhaps it is useful for mac users. The idea is to minimally change the source code such that the presentation window looses its title bar and gets positioned relative to the upper-right corner of the main monitor when pressing a key. Using the MacOS monitor preferences, this upper-right corner can be made to coincide with the upper-left corner of the external monitor; this is the default behavior. (The option "Displays have separate Spaces" must be switched off in the preferences). In this way, the full-screen behavior on the external monitor is perfectly mimicked. For this to work, the main monitor width must be specified in the file pdfpcrc and the dimensions of the external monitor must be specified on the command line. (When the external monitor is connected, select "About This Mac" in the Apple menu and then the "Displays" tab to see the dimensions of the main and external monitors; on retina displays, scaling the numbers by a factor 1.8 or 2 is necessary). When everything is in place, I launch the presentation with, e.g.,

    /usr/local/pdfpc/bin/pdfpc -Z 1920:1200 slides.pdf

then I type "m" and that's it. If the external monitor cannot be located at the upper-right corner, one can also move manually the presentation window to the external monitor and then press "M". This should in principle remove the title bar and maximize the window like a full screen would do, but in fact it does not always work (it sometimes brings the window back to the main monitor) such that the "m" approach is better.

Here is the procedure for v4.1-7. I assume the configuration is such that the building of pdfpc works. Caution: the directory /usr/local/pdfpc is overwritten, so if you have previous versions of pdfpc there, save them first.

* As root, type:

    DIR=/usr/local/pdfpc
    rm -fr $DIR; mkdir -p $DIR/src; cd $DIR/src

* Download pdfpc-pdfpc-v4.1-7-g305c777.tar.gz in the directory /usr/local/pdfpc/src
* Download and save the script given below with the name "patch-pdfpc-v4.1.7.sh" in the directory /usr/local/pdfpc/src
* Edit the file patch-pdfpc-v4.1.7.sh and change "option main-screen-width 1680" with the width of your main monitor.
* Then type

    cd $DIR/src
    chmod 755 patch-pdfpc-v4.1.7.sh
    tar -xzf pdfpc-pdfpc-v4.1-7-g305c777.tar.gz
    cd pdfpc-pdfpc-305c777
    sh ../patch-pdfpc-v4.1.7.sh
    mkdir build; cd build
    cmake -DCMAKE_INSTALL_PREFIX=$DIR ..
    make install
    cd ../../; rm -fr pdfpc-pdfpc-305c777; cd ..
    chmod -R 755 $DIR
    chmod 644 $DIR/etc/pdfpcrc $DIR/share/man/man*/* $DIR/share/pixmaps/pdfpc/*

If everything goes well, you should have the modified executable in /usr/local/pdfpc/bin and the modified pdfpcrc in /usr/local/pdfpc/etc.


```bash
#!/bin/bash

#
# Changes to rc/pdfpcrc
#
cat << EOF >> rc/pdfpcrc

#### Workaround for #331
bind M maximize
bind m maximize_and_move
option main-screen-width 1680
option presenter-width 1440
option presenter-height 900
option current-height 85
option next-height 25
EOF

#
# Changes to src/classes/options.vala
#
sed -i '' -e '/public static bool version = false;/a\
\/\/ begin workaround for #331\
        public static int main_screen_width = 1680;\
        public static int presenter_width = 1280;\
        public static int presenter_height = 800;\
\/\/ end workaround for #331\
' src/classes/options.vala

#
# Changes to src/classes/config_file_reader.vala
#
sed -i '' -e '/switch (fields\[1\]) {/a\
\/\/ begin workaround for #331\
                case "main-screen-width":\
                    Options.main_screen_width = int.parse(fields[2]);\
                    break;\
                case "presenter-width":\
                    Options.presenter_width = int.parse(fields[2]);\
                    break;\
                case "presenter-height":\
                    Options.presenter_height = int.parse(fields[2]);\
                    break;\
\/\/ end workaround for #331\
' src/classes/config_file_reader.vala

#
# Changes to src/classes/presentation_controller.vala
#
sed -i '' -e '/public int current_user_slide_number { get; protected set; }/a\
\/\/ begin workaround for #331\
            public bool maximized { get; protected set; default = false; }\
\/\/ end workaround for #331\
' src/classes/presentation_controller.vala

sed -i '' -e '/add_action("hide", this.hide_presentation);/a\
\/\/ begin workaround for #331\
            add_action("maximize", this.maximize);\
            add_action("maximize_and_move", this.maximize_and_move);\
\/\/ end workaround for #331\
' src/classes/presentation_controller.vala

sed -i '' -e '/#if MOVIES/i\
\/\/ begin workaround for #331\
        protected void maximize() {\
			this.maximized = !this.maximized;\
            this.presentation.set_decorated(false);\
            this.presentation.maximize();\
        }\
        protected void maximize_and_move() {\
			this.maximize();\
            this.presentation.move(Options.main_screen_width,0);\
        }\
\/\/ end workaround for #331\
' src/classes/presentation_controller.vala

#
# Changes to src/classes/window/presenter.vala
#
sed -i '' -e '/base(screen_num);/s/base(screen_num);/\
\/\/ begin workaround for #331\
\/\/          base(screen_num);\
            base(screen_num,Options.presenter_width,Options.presenter_height);\
\/\/ end workaround for #331/ ' src/classes/window/presenter.vala

```

**Comment by maehne** [comment]
I have not observed this problem with the new pdfpc 4.2.1 version on macOS High Sierra. It is available via [MacPorts](https://www.macports.org). There's a Quartz variant, which integrates better with the macOS GUI:
```
$ sudo port -v install pdfpc +quartz
```
and there's an X11 variant (currently, the default), which should support video playback, but which might suffer other shortcomings:
```
$ sudo port -v install pdfpc +x11
```
I am using the Quartz variant and so far don't have remarked problems with dual screen setups. Though, things might be different for the X11 variant. It would be great if you could provide feedback, how this port in either of the two variants works for you!

**Comment by AndreasBilke** [comment]
Just out of curiosity: @maehne did you tried to build the quartz version WITH movie support? Pdfpc no longer uses direct x11 calls to play videos. Instead it relies on the gstreamer capabilities to render in gtk widgets

**Comment by maehne** [comment]
That's great news that movie support should now be independent of X11! I just recompiled pdfpc with `-DMOVIES=on` and tested it with the video test presentation available from the pdfpc website. Unfortunately, it doesn't work straight away. I received the following error messages:
```
$ pdfpc video-example.pdf
Error creating video sink: Could not make element sink0 of type gtksink.
Gstreamer installation may be incomplete.
Error creating video sink: Could not make element sink0 of type gtksink.
Gstreamer installation may be incomplete.
Error creating video sink: Could not make element sink0 of type gtksink.
Gstreamer installation may be incomplete.
```
So, I assume not yet all necessary dependencies are present. Currently, I have the following gstreamer1-related ports installed:
```
$ port installed | grep gstreamer
  gstreamer1 @1.14.4_0 (active)
  gstreamer1-gst-libav @1.14.4_0 (active)
  gstreamer1-gst-plugins-bad @1.14.4_1+x11 (active)
  gstreamer1-gst-plugins-base @1.14.4_0+ogg+x11 (active)
  gstreamer1-gst-plugins-good @1.14.4_0+pulseaudio+x11 (active)
  gstreamer1-gst-plugins-ugly @1.14.4_0 (active)
```
Available are:
```
$ port search gstreamer
clutter-gst @2.0.18 (graphics)
    Clutter GStreamer integration library.

clutter-gst3 @3.0.26 (graphics)
    Clutter GStreamer integration library.

gst-plugins-cairovis @0.1.1_3 (science, gnome)
    Scientific visualization plugins for GStreamer using Cairo graphics

gst-plugins-math @1.0.1 (science, gnome)
    Mathematical operations plugins for GStreamer

gstlal @0.10.4_1 (science)
    GStreamer elements for gravitational-wave data analysis

gstlal-calibration @0.5.10 (science)
    GStreamer elements for online GW data calibration

gstreamer1 @1.14.4 (gnome)
    GStreamer is a library for constructing graphs of media-handling components.

gstreamer1-gst-libav @1.14.4 (gnome)
    This is gst-libav, a set of plug-ins for GStreamer.

gstreamer1-gst-plugins-bad @1.14.4_1 (gnome)
    A set of plug-ins for GStreamer that need more quality.

gstreamer1-gst-plugins-base @1.14.4 (gnome)
    This is gst-plugins, a set of plug-ins for GStreamer.

gstreamer1-gst-plugins-good @1.14.4 (gnome)
    A set of good-quality plug-ins for GStreamer under GStreamer's preferred license,
    LGPL.

gstreamer1-gst-plugins-ugly @1.14.4 (gnome)
    A set of good-quality plug-ins for GStreamer that might pose distribution
    problems.

gstreamer010 @0.10.36_1 (gnome)
    GStreamer is a library for constructing graphs of media-handling components.

gstreamer010-gnonlin @0.10.17 (gnome)
    A set of non-linear editing plugins for GStreamer.

gstreamer010-gst-ffmpeg @0.10.13 (gnome)
    This is gst-ffmpeg, a set of plug-ins for GStreamer.

gstreamer010-gst-plugins-bad @0.10.23_23 (gnome)
    A set of plug-ins for GStreamer that need more quality.

gstreamer010-gst-plugins-base @0.10.36_3 (gnome)
    This is gst-plugins, a set of plug-ins for GStreamer.

gstreamer010-gst-plugins-gl @0.10.3_7 (gnome)
    This is gst-plugins, a set of plug-ins for GStreamer.

gstreamer010-gst-plugins-good @0.10.31_12 (gnome)
    A set of good-quality plug-ins for GStreamer under GStreamer's preferred license,
    LGPL.

gstreamer010-gst-plugins-ugly @0.10.19_8 (gnome)
    A set of good-quality plug-ins for GStreamer that might pose distribution
    problems.

gstreamer010-gst-rtsp @0.10.8 (gnome)
    library for building an RTSP streaming media server on top of GStreamer

p5-gstreamer1 @0.3.0 (perl)
    Bindings for GStreamer 1.0, the open source multimedia framework

p5.24-gstreamer1 @0.3.0_1 (perl)
    Obsolete port, replaced by p5.26-gstreamer1

p5.26-gstreamer1 @0.3.0 (perl)
    Bindings for GStreamer 1.0, the open source multimedia framework

phonon-backend-gstreamer @4.9.0 (audio, kde, kde4)
    GStreamer backend for Phonon

phonon-backend-gstreamer-qt5 @4.9.0 (audio, kde, kf5)
    GStreamer backend for Phonon

py27-gst-python @0.10.22_2 (python, gnome, multimedia)
    GStreamer python bindings

qt5-phonon-backend-gstreamer @4.9.0 (audio, kde, kde4)
    Obsolete port, replaced by phonon-backend-gstreamer-qt5

rb-gstreamer @1.1.3_1 (ruby, gnome)
    Ruby/GStreamer is a Ruby binding for GStreamer.

Found 29 ports.
```
Do you have a hint where to start looking for what is missing?

**Comment by fnevgeny** [comment]
gtk-sink used to be in the "bad" plugins package, but with the current gstreamer it is among the "good" ones:

[https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/). Perhaps because of this bad->good transition the MacOS build wasn't properly updated?

**Comment by maehne** [comment]
Thanks for the hint! `gstreamer1-gst-plugins-good` has a `gtk3` variant, which is by default off:
```
$ port variants gstreamer1-gst-plugins-good
gstreamer1-gst-plugins-good has the variants:
   gtk3: Enable GTK3 X11/GL windowing elements
     * requires x11
   jack: Enable Jack plugin
[+]pulseaudio: Enable PulseAudio plugin
   qt: Enable QT5 MAC windowing elements
   universal: Build for multiple architectures
[+]x11: Enable X11 support
```
Unfortunately, this `gtk3` variant currently imposes also the `x11` variant of `gtk3`. I don't know if this is still a requirement or some kind of historic artefact. Will have to find the time to patch the port and test it whether it works with the `gtk3 +quartz` variant. At least from a short glance at the pointed website nor from the plugin's README files, I was able to find this information.

**Comment by fnevgeny** [comment]
From the sources it looks like there is no dependence on X11 in ext/gtk/* except for gtkgstglwidget.c. So I guess it should build if USE_GTK3_GL is not defined.

**Comment by maehne** [comment]
Thanks, I will try that, but I will need to find some time to tinker with the `gstreamer1-gst-plugins-good`port.

**Comment by ChristopheBerthod** [comment]
@maehne. Sorry for the slow response. I'm still running Sierra 10.12.6. Indeed the version 4.2.1 with x11 has the problem (one single large screen), but with quartz it does not. It is still not quite perfect, though, because the window on the presentation screen keeps its title bar, so it is not really in full-screen mode.

**Comment by maehne** [comment]
Thanks for the feedback! I have seen similar windows resizing behaviour for other GTK+/X11 applications on macOS using the Xquartz server. So, root cause for this unfortunate pdfpc behaviour might be more fundamental. I can reproduce on macOS High Sierra, that pdfpc will show the windows' title bar. However, this is only the case if you move the mouse cursor to the upper screen boarder. This is expected behaviour for all full screen apps on macOS so that you may access the menu bar and Apple menu. At least on my machine, pdfpc in its +quartz variant has worked quite well over the past week, where I used it in several lectures. A windows' title bar was never disturbing the slide presentation on the projector. So, what other behaviour would you expect?

Do you still observe the GDK warnings, which you mentioned in your initial bug report?

**Comment by ChristopheBerthod** [comment]
Hello, perhaps there is something I'm doing wrong. I don't have my usual setup available right now, but there is a 16/9 tv here, so let's try. I compile my presentation in 16/9 format -- easy with with pdftex+pdfpc, right :-) -- and I launch it on this tv screen. With version 4.1 and the workaround described above, it works, with the presentation window occupying the full tv screen without title bar. Now I move to pdfpc 4.2.1:

$ port installed gtk3
The following ports are currently installed:
  gtk3 @3.22.11_0+x11
  gtk3 @3.22.26_0+x11
  gtk3 @3.22.30_0+quartz (active)
  gtk3 @3.22.30_0+x11

$ port installed pdfpc
The following ports are currently installed:
  pdfpc @4.2.1_0+quartz (active)
  pdfpc @4.2.1_0+x11

$ pdfpc --version
pdfpc v4.2.1
Copyright (C) 2010-2018 see CONTRIBUTORS

License GPLv2: GNU GPL version 2 <http://gnu.org/licenses/gpl-2.0.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ pdfpc slides-169.pdf
Could not acquire DBus bus.

On the tv, the presentation window has a title bar "pdfpc - presentation ()"; it is there even if my mouse is in the middle of the presenter screen. I click on the title bar and move the presentation window: when I drop it, it gets automatically repositioned vertically (with the title bar still visible), but not horizontally. If I click the green "+" button of the title bar, the window gets correctly positioned (with the title bar still visible); note: this is a "+" green button (old functionality), not a "<>" button for macOS full-screen mode. Perhaps Sierra and High Sierra show different behaviors here. [I won't move to High Sierra or Mojave until I find a way to run NoteBook (http://www.circusponies.com) on them...]

The GDK warnings where issued when compiling version 4.1 from source. I didn't try to compile version 4.2.1 from source.

**Comment by maehne** [comment]
> From the sources it looks like there is no dependence on X11 in ext/gtk/* except for gtkgstglwidget.c. So I guess it should build if USE_GTK3_GL is not defined.

@fnevgeny: I was able to build `gstreamer1-gst-plugins-good` with GTK+-3 support and successfully built `pdfpc` against it. Unfortunately, that did not make video playback work in your video test presentation. Though, there were no error messages concerning that `pdfpc` was not able to create a Gstreamer video sink. Is there some `pdfpc` switch to enable more debug output so that I can sure that the video actually got found and a video sink got constructed for playback?

The cause for the video playback problem might not be in `pdfpc` itself but Gstreamer. I tried to play back several videos using `gst-play-1.0`, but always only got audio and a black "OpenGL renderer" X11 window.

**Comment by fnevgeny** [comment]
@maehne:
> a black "OpenGL renderer" X11

Can you please try `gst-play-1.0 --videosink gtksink`, also run it with the `-v` flag and see if there are any hints.

I thought gstreamer itself is known to work with MacOS/quartz, not? Maybe you don't have some decoder plugins?

**Comment by maehne** [comment]
Thanks for the hints to debug the video output! I just tried to play a video using ```gst-play-1.0 --videosink gtksink apollo17.avi```. It works! Also, `ximagesink` works. Not working videosinks are `gtkglsink`, `osxvideosink`, and `glimagesink`. The latter three all show an empty OpenGL renderer X11 window. The debug output unfortunately does not provide any error or warning giving a hint about what might go wrong with the OpenGL rendering of the video. `glxgears` and `glxinfo` work. May it be that gstreamer is relying on features from a too recent version of the OpenGL standard? OpenGL gut deprecated by Apple last year and macOS only support quite old versions of OpenGL.

When building `pdfpc`, the Gstreamer libraries are found:
```
--->  Configuring pdfpc
Executing:  cd "/opt/local/var/macports/build/_Users_maehne_Build_experimental-macports_ports_graphics_pdfpc/pdfpc/work/build" && /opt/local/bin/cmake -G "CodeBlocks - Unix Makefiles" -DCMAKE_BUILD_TYPE=MacPorts -DCMAKE_INSTALL_PREFIX="/opt/local" -DCMAKE_INSTALL_NAME_DIR="/opt/local/lib" -DCMAKE_SYSTEM_PREFIX_PATH="/opt/local;/usr" -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_POLICY_DEFAULT_CMP0060=NEW -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_MODULE_PATH="/opt/local/share/cmake/Modules" -DCMAKE_PREFIX_PATH="/opt/local/share/cmake/Modules" -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib" -Wno-dev -DMOVIES=on -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.13" -DCMAKE_OSX_SYSROOT="/" /opt/local/var/macports/build/_Users_maehne_Build_experimental-macports_ports_graphics_pdfpc/pdfpc/work/pdfpc-4.2.1
-- The C compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Vala: /opt/local/bin/valac (found suitable version "0.42.2", minimum required is "0.26")
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.29.2")
-- Checking for module 'gobject-2.0'
--   Found gobject-2.0, version 2.58.1
-- Checking for module 'gio-2.0'
--   Found gio-2.0, version 2.58.1
-- Checking for module 'gee-0.8'
--   Found gee-0.8, version 0.20.1
-- Checking for module 'poppler-glib>=0.22'
--   Found poppler-glib, version 0.69.0
-- Checking for module 'gtk+-3.0>=3.20'
--   Found gtk+-3.0, version 3.22.30
-- GTK is compiled with X11 -- enabling X11 support
-- Checking for module 'x11'
--   Found x11, version 1.6.7
-- Checking for module 'gthread-2.0'
--   Found gthread-2.0, version 2.58.1
-- Checking for module 'pangocairo'
--   Found pangocairo, version 1.42.4
-- Checking for module 'gstreamer-1.0'
--   Found gstreamer-1.0, version 1.14.4
-- Checking for module 'gstreamer-base-1.0'
--   Found gstreamer-base-1.0, version 1.14.4
-- Checking for module 'gstreamer-audio-1.0'
--   Found gstreamer-audio-1.0, version 1.14.4
-- Checking for module 'gstreamer-video-1.0'
--   Found gstreamer-video-1.0, version 1.14.4
-- Performing Test CC_HAS_DISCARDED_QUALIFIERS
-- Performing Test CC_HAS_DISCARDED_QUALIFIERS - Failed
-- Performing Test CC_HAS_INCOMPATIBLE_POINTER_TYPES
-- Performing Test CC_HAS_INCOMPATIBLE_POINTER_TYPES - Success
-- Performing Test CC_HAS_DEPRECATED_DECLARATIONS
-- Performing Test CC_HAS_DEPRECATED_DECLARATIONS - Success
-- Performing Test CC_HAS_IMPLICIT_FUNCTION_DECLARATION
-- Performing Test CC_HAS_IMPLICIT_FUNCTION_DECLARATION - Success
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_COMPILER
    CMAKE_POLICY_DEFAULT_CMP0025

```

As I wrote earlier, `pdfpc` does not issue any error message, but also does not launch any of the embedded videos in the `video-example.pdf`.

**Comment by maehne** [comment]
@fnevgeny: Maybe we should move the video playback discussion to a separate issue?

**Comment by fnevgeny** [comment]
@maehne 
> Maybe we should move the video playback discussion to a separate issue?

Yep, that would make sense.

**Comment by fnevgeny** [comment]
Can you please try the current [multimonitor](https://github.com/pdfpc/pdfpc/tree/multimonitor) branch?

**Comment by fnevgeny** [comment]
No feedback from the users, assuming the issue resolved.
