### ISSUE TITLE
Latex Beamer \pause command breaks order of the preview slides

### ISSUE THREAD

**Issue by f3rdy** [pdfpc/pdfpc#335]
### Expected Behaviour

The preview slides are shown in correct ordering, although in a latex beamer frame a `\pause` command is used.

### Actual Behaviour

The ordering of the preview slides is screwed, when a latex beamer frame has a `\pause` command in it.

#### pdfpc version

4.0.7 on Ubuntu/Linux 17.10

**Comment by AndreasBilke** [comment]
Does it only happen when you notes or in any case? If you have the bug in
any case, please give a MWE.

**Comment by AndreasBilke** [comment]
Could you also test the latest pdfpc version?

**Comment by f3rdy** [comment]
Little busy ATM preparing slides ;). Couldn't reproduce it using a simple
[mwe.pdf](https://github.com/pdfpc/pdfpc/files/1830366/mwe.pdf) though. I think my other document has some screwed settings, packages, formatting... will get onto that later on.

**Comment by AndreasBilke** [comment]
I think the bug was fixed in a recent version.

**Comment by f3rdy** [comment]
Same with freshly built 4.1. Most probably my document is behaving badly.

**Comment by AndreasBilke** [comment]
Sens it, I can have a look

Am 20. März 2018 19:05:24 MEZ schrieb Fred Thiele <notifications@github.com>:
>Same with freshly built 4.1. Most probably my document is behaving
>badly.

**Comment by AndreasBilke** [comment]
Could you provide an example?

**Comment by AndreasBilke** [comment]
Please reopen it when the problem still exists with the latest code and a mwe
