### ISSUE TITLE
PDFs with multiple differing page dimensions/sizes don't render correctly

### ISSUE THREAD

**Issue by lorenzhs** [pdfpc/pdfpc#336]
### Expected Behaviour

In a PDF file in which different slides have different sizes, expected behaviour would be that every slide fills all available space (i.e. every slide's scaling factor is calculated independently)

### Actual Behaviour

Only the first slide's size is used to determine the scaling factor during rendering. This leads to slides with different dimensions either being cut off or filling just a small part of the available space

### If it's a bug: Steps to reproduce the behaviour (e.g. a minimal working example for the PDF)

Take two pdfs with differing dimensions and concatenate them using pdftk. This happens when merging pdfs produced by LaTeX Beamer and Powerpoint into a single presentation.

#### pdfpc version

v4.1 (Debian unstable)

#### Used Distribution (GTK version, vala version)

Debian unstable/sid: GTK 3.22.29, vala 0.40.0

#### Display Server (X/Wayland)

X

#### HiDPI Setting (yes/no)

no

**Comment by lorenzhs** [comment]
Related: https://github.com/pdfpc/pdfpc/blob/0976260aa8c9578464c8d2f9373f4bb5df453c17/src/classes/metadata/pdf.vala#L659-L691 and https://github.com/pdfpc/pdfpc/blob/0976260aa8c9578464c8d2f9373f4bb5df453c17/src/classes/renderer/pdf.vala#L77-L79

**Comment by AndreasBilke** [comment]
Could you explain what the use case is to have different sized slides in a presentation?

Am 26. März 2018 11:40:00 MESZ schrieb "Lorenz Hübschle-Schneider" <notifications@github.com>:
>Related:
>https://github.com/pdfpc/pdfpc/blob/0976260aa8c9578464c8d2f9373f4bb5df453c17/src/classes/metadata/pdf.vala#L659-L691
>and
>https://github.com/pdfpc/pdfpc/blob/0976260aa8c9578464c8d2f9373f4bb5df453c17/src/classes/renderer/pdf.vala#L77-L79

**Comment by lorenzhs** [comment]
We have to combine a LaTeX beamer presentation and one exported from Powerpoint. Switching over between two separate instances of pdfpc is annoying because system UI is not being properly hidden unless both windows are alt-tabbed to, which creates additional delays etc :/

**Comment by lorenzhs** [comment]
Thank you very much!
