### ISSUE TITLE
Feature Request: Logitech Spotlight support/emulation

### ISSUE THREAD

**Issue by DropInBiofuels** [pdfpc/pdfpc#337]
### Expected Behaviour
I would love to have Logitech Spotlight support/emulation (https://www.logitech.com/en-us/product/spotlight-presentation-remote)

e.g. the pointer appears as already implemented while the rest is darkened. I know that this already works by drawing a rectangle with the mouse, but the Spotlight does not support click and drag. 

The Spotlight itself can already act as a HID controlling the cursor, it can be used to forward, go back and control the pointer.

**Comment by AndreasBilke** [comment]
Without any external help we cannot implement this.
