### ISSUE TITLE
Feature request: zoom in/out and move

### ISSUE THREAD

**Issue by jpggithub** [pdfpc/pdfpc#338]
It would be nice to have some keybindings to zoom in/out and move the zoomed page.

Sometimes I use A4 document and I have to use another pdf viewer to zoom in on some parts of them.
When you zoomed in the document, then you need to move the displayed part to focus on the right parts of the document.

Anyway, thank you for this great project!

**Comment by AndreasBilke** [comment]
Sorry, I think this is completely out of scope for a presentation program.
Since we are missing man power for developing additonal features in pdfpc,
I will close this issue.

**Comment by jpggithub** [comment]
I think it is not out of scope at all because I need it for some presentations and I can't always plan which pdf's or extracts of pdf I will have to to zoom in. 

I understand your lack of man power to develop this feature but please consider the option to re-open this bug.


Finally, I use Zathura in full screen.   It has not all the interesting features of pdfpc but it provided many configurable key strokes and the possibility to zoom in/out easily.

**Comment by AndreasBilke** [comment]
If someone is willing to develop it I'm happy. But for now, this issue would result in a forever dangling thing
