### ISSUE TITLE
Debian Bug #895224: pdf-presenter-console: [regression] after upgrading to GStreamer 1.14.0, fails to play movies

### ISSUE THREAD

**Issue by barak** [pdfpc/pdfpc#339]
Please see https://bugs.debian.org/895224 which has sufficient information to replicate the issue.

**Comment by lorenzhs** [comment]
Do you have the package `gstreamer1.0-gtk3` installed? That fixes it for me.

**Comment by AndreasBilke** [comment]
It was a dependency issue. See bug comments at bugs.debian.org.
