### ISSUE TITLE
hyperlinks are not working

### ISSUE THREAD

**Issue by dio4ev** [pdfpc/pdfpc#340]
### I read the SUPPORT.md file (yes/no)
no
### Expected Behaviour
clickable hyperlinks 
### Actual Behaviour
the hyperlinks are not clickable 
### If it's a bug: Steps to reproduce the behaviour (e.g. a minimal working example for the PDF)
I used the normal hyperref package for latex and the command \href for links
#### pdfpc version
v4.1
#### Used Distribution (GTK version, vala version)
OS: Arch Linux 
Kernel: x86_64 Linux 4.15.15-1-ARCH
GTK Theme: Adwaita [GTK2/3]
#### Display Server (X/Wayland)
X
#### HiDPI Setting (yes/no)
yes for i3wm

**Comment by AndreasBilke** [comment]
Please send a MWE

**Comment by dio4ev** [comment]
Below you can see a minimal example of my presentation with all included packages etc.
The links are not clickable with pdfpc, but with evince they work.

>\documentclass{beamer}
\usepackage{etex}
>
>\usepackage[utf8x]{inputenc}
\usepackage[T1]{fontenc}
\PassOptionsToPackage{landscape}{geometry}
\usepackage{tikz}
\usetikzlibrary{timeline,shapes.geometric,arrows,shadows,positioning}
\usepackage{color}
\usepackage{amssymb}
\usepackage{pifont}
\usepackage{listings}
\usepackage{hyperref}
\usepackage{lmodern}
% \usepackage{pgfpages} %compile with this for dspdfviewer
% \setbeameroption{show notes on second screen=right} %compile with this for dspdfviewer
>
>\begin{document}
>
>\begin{frame}[c]{Web Interface Demo}
  \begin{block}{}
    \centering
    \href{www.google.at}{Google} \\
    \url{www.google.at} \\
  \end{block}
\end{frame}
>
>
>\end{document}

**Comment by AndreasBilke** [comment]
At a first glance I cannot reproduce it. But: is there somewhere at the document clickable areas? You could find them by hovering over the whole slide and see if the cursor changes.

**Comment by dio4ev** [comment]
So the hyperlinks are working for you with this MWE?
I am not able to find any clickable area...

**Comment by phillipberndt** [comment]
Works for me as well, I can click the google link to open a browser.

**Comment by AndreasBilke** [comment]
Do you use HiDPI settings? Thats the only explanation where it can go wrong
for me.

**Comment by dio4ev** [comment]
Yes I use some DiDPI settings for i3

**Comment by dio4ev** [comment]
I have tested it now on my Desktop-PC without HiDPI settings and the links are not working...

**Comment by AndreasBilke** [comment]
That's a good sign :) and you are using the latest master code?

**Comment by dio4ev** [comment]
No I'm using the package available for arch linux [https://www.archlinux.org/packages/community/x86_64/pdfpc/](url)

Should I try the latest master code?

**Comment by dio4ev** [comment]
With the latest code at the master branch, the hyperlinks are working. :)

**Comment by MatCos** [comment]
Although this issue is closed for some time now, I noticed today, that hyperlinks for local files (e.g. local html files) are not working. I believe the expected behaviour is opening the html file in a browser. At least other pdf-viewers do that. I'm at the latest version 4.5 on Ubuntu 20.04. 

Here is a MWE:

```
\documentclass{beamer}
\usepackage{etex}

\usepackage[utf8x]{inputenc}
\usepackage[T1]{fontenc}
\PassOptionsToPackage{landscape}{geometry}
\usepackage{color}
\usepackage{amssymb}
\usepackage{pifont}
\usepackage{listings}
\usepackage{hyperref}
\usepackage{lmodern}
% \usepackage{pgfpages} %compile with this for dspdfviewer
% \setbeameroption{show notes on second screen=right} %compile with this for dspdfviewer

\begin{document}

\begin{frame}[c]{Web Interface Demo}
\begin{block}{}
\centering
\href{www.google.at}{Google} \
\url{www.google.at} \
\url{localfile.html} \
\href{localfile.html}{Local file} \
\end{block}
\end{frame}

\end{document}
```

**Comment by fnevgeny** [comment]
@MatCos Please see whether #630 fixes it for you.

**Comment by MatCos** [comment]
Yes, that's great. Thank You
