### ISSUE TITLE
Installation doesn't fully respect CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by logological** [pdfpc/pdfpc#343]
When passing a directory via CMake's `CMAKE_INSTALL_PREFIX` variable, I expect all pdfpc files to be installed there.  The pdfpc binary, man pages, and pixmaps are installed in the correct places, but the `pdfpcrc` file is not.

**Steps to reproduce**

Check out the project from Git and build/install it as usual, except that when running CMake you should pass a different installation directory via `-DCMAKE_INSTALL_PREFIX`:

```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/stow/pdfpc ..
make
sudo make install
```

**Actual Behaviour**

All files are installed to the correct places except for `etc/pdfpcrc`:

```
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/stow/pdfpc/bin/pdfpc
-- Up-to-date: /usr/local/stow/pdfpc/share/pixmaps/pdfpc/blank.svg
-- Up-to-date: /usr/local/stow/pdfpc/share/pixmaps/pdfpc/hidden.svg
-- Up-to-date: /usr/local/stow/pdfpc/share/pixmaps/pdfpc/snow.svg
-- Up-to-date: /usr/local/stow/pdfpc/share/pixmaps/pdfpc/pause.svg
-- Up-to-date: /usr/local/stow/pdfpc/share/pixmaps/pdfpc/saved.svg
-- Up-to-date: /usr/local/stow/pdfpc/share/pixmaps/pdfpc/loaded.svg
-- Up-to-date: /usr/local/stow/pdfpc/share/pixmaps/pdfpc/locked.svg
-- Up-to-date: /usr/local/stow/pdfpc/share/pixmaps/pdfpc/highlight.svg
-- Up-to-date: /usr/local/stow/pdfpc/share/pixmaps/pdfpc/pen.svg
-- Up-to-date: /usr/local/stow/pdfpc/share/pixmaps/pdfpc/eraser.svg
-- Up-to-date: /usr/local/stow/pdfpc/share/man/man1/pdfpc.1
-- Up-to-date: /usr/local/stow/pdfpc/share/man/man5/pdfpcrc.5
-- Up-to-date: /usr/local/etc/pdfpcrc
-- Up-to-date: /usr/local/stow/pdfpc/share/pixmaps/pdfpc/pdfpc.css
```

**Expected Behaviour**

`etc/pdfpcrc` should be installed as `/usr/local/stow/pdfpc/etc/pdfpcrc`

pdfpc version: git master (15b9cea3dc3167477691b61d5875896129923a79)

**Comment by AndreasBilke** [comment]
Actually, I can't replicate this.
```
andreas@huginn ~/devel/git/pdfpc/build
[git|master] $ cmake -DCMAKE_INSTALL_PREFIX=/usr/home/andreas/PDFINST/stow ..
andreas@huginn ~/devel/git/pdfpc/build
[git|master] $ make
andreas@huginn ~/devel/git/pdfpc/build
[git|master] $ sudo make install 
Password:
[100%] Built target pdfpc
Install the project...
-- Install configuration: ""
-- Installing: /home/andreas/PDFINST/stow/bin/pdfpc
-- Set runtime path of "/home/andreas/PDFINST/stow/bin/pdfpc" to ""
-- Installing: /home/andreas/PDFINST/stow/share/pixmaps/pdfpc/blank.svg
-- Installing: /home/andreas/PDFINST/stow/share/pixmaps/pdfpc/hidden.svg
-- Installing: /home/andreas/PDFINST/stow/share/pixmaps/pdfpc/snow.svg
-- Installing: /home/andreas/PDFINST/stow/share/pixmaps/pdfpc/pause.svg
-- Installing: /home/andreas/PDFINST/stow/share/pixmaps/pdfpc/saved.svg
-- Installing: /home/andreas/PDFINST/stow/share/pixmaps/pdfpc/loaded.svg
-- Installing: /home/andreas/PDFINST/stow/share/pixmaps/pdfpc/locked.svg
-- Installing: /home/andreas/PDFINST/stow/share/pixmaps/pdfpc/highlight.svg
-- Installing: /home/andreas/PDFINST/stow/share/pixmaps/pdfpc/pen.svg
-- Installing: /home/andreas/PDFINST/stow/share/pixmaps/pdfpc/eraser.svg
-- Installing: /home/andreas/PDFINST/stow/share/man/man1/pdfpc.1
-- Installing: /home/andreas/PDFINST/stow/share/man/man5/pdfpcrc.5
-- Installing: /home/andreas/PDFINST/stow/etc/pdfpcrc
-- Installing: /home/andreas/PDFINST/stow/share/pixmaps/pdfpc/pdfpc.css
```

But: You can also set `SYSCONFDIR` separately. This is where the pdfpcrc file will be stored. Normally, it is placed at `${CMAKE_INSTALL_PREFIX}/etc` (see CMakeLists.txt in the root dir).

**Comment by logological** [comment]
You are right; the problem is not reproducible from a clean `build` directory.  I think my problem was that I first ran `cmake ..` before running it again with the `-DCMAKE_INSTALL_PREFIX=…` option.  I was expecting CMake to use the new install prefix for everything, but instead it uses a mix of the old and new ones.  I'm not sure if this is a problem with CMake, with my mental model of how it works, or with how pdfpc uses CMake.  Sorry for not having given complete steps to reproduce.

**Comment by AndreasBilke** [comment]
I am also not sure who is using what wrong. But if you have any suggestions to make the cmake script more predictable, I am open to changes.

I close this issue since cmake installs the files at the correct place for a clean build run.
