### ISSUE TITLE
Display poster image for animations

### ISSUE THREAD

**Issue by cwinant** [pdfpc/pdfpc#348]
Currently pdfpc display animations, but does not diplay the first frame before starting the animation, if it is called for.  If the poster is requested by the pdf file, pdfpc displays
"Movie requests poster. Not yet supported."

In my experience, presentations that include animations almost always benefit by having the first frame shown before running the animation, since this is a natural place for the presenter toexplain the format of the animation and what the attendance should be looking for.

Would it be possible to build in support for poster?

Note that okular and evince and evince appear to support posters, but both display some random frame in the animation, rather than the first frame, as does reader

**Comment by fnevgeny** [comment]
Frankly, I consider this an _anti_-feature. If you are forced (sometimes at the last moment) to use the "official" conference computer which, as luck would have it, doesn't support the format of your videos, you are left with dumb slides containing neither videos nor posters. Having the poster image embedded in PDF is a safety net. And it's a trivial task when preparing presentations with `make` or like. I suppose everybody does it, right? :)

**Comment by cwinant** [comment]
The point of showing the first fram is to give the presenter time to
explain what the audience will see when the animation is run.  This is why
the Adobe viewer shows the first frame.

Clinton

**Comment by fnevgeny** [comment]
I don't say showing the first frame as the poster image is wrong. My point is that preparing the poster image should be the responsibility of the PDF _creator_, not viewer.

**Comment by fnevgeny** [comment]
Sure. Something like
```
    \movie[showcontrols]
    {\includegraphics[width=0.7\textwidth]{frame1.png}}
    {movie.mp4}
```

**Comment by cwinant** [comment]
I tried making that solution work at the time I enetered the request, and
it did not, although I don't remember the details.  I could recreate them
if that would be helpful.  Also on some occasions I show animations pulled
off the web, in which case I don't have the individual frames. I suppose
one can use ffmpeg to pull a frame off a movie?

I guess from my perspective it would be best if pdfpc worked like acrobat
reader, since that is the de facto standard (albeit unavailable to linux
users).

At any rate thanks for considering this    Clinton

**Comment by fnevgeny** [comment]
> I tried making that solution work at the time I enetered the request, and it did not, although I don't remember the details. I could recreate them if that would be helpful.

If it doesn't work, report it as a bug

> Also on some occasions I show animations pulled off the web, in which case I don't have the individual frames. I suppose one can use ffmpeg to pull a frame off a movie?

Right; or vlc, or just print screen...

> I guess from my perspective it would be best if pdfpc worked like acrobat reader

Well like I said in my first reply, relying upon the viewer to make posters is the least portable way to make slides with animation.
