### ISSUE TITLE
Feature request: laser pointer

### ISSUE THREAD

**Issue by massimiliano-leoni** [pdfpc/pdfpc#349]
I think it would be handy to mirror the mouse pointer to the audience view when the pointer is on the current slide in the presenter view.

When I give a presentation I occasionally move the mouse pointer to point at some features in the current slide. However, to do this I have to turn around and look at the audience screen to position the mouse pointer correctly.
What I would like, instead, is to be able to move the mouse pointer on the current slide in the screen I'm looking at, the one with plenty of information, and have pdfpc give some feedback in the screen my audience is looking at. It could be, for example, rendered as a laser pointer.

**Comment by AndreasBilke** [comment]
I think you are searching for the "Pointer Mode", see pdfpc(1).

But, did you actually read the SUPPORT.md? I'm just wondering...

**Comment by massimiliano-leoni** [comment]
Hi!
I didn't know about this pointer mode, my distributions' [Ubuntu 16.04] repositories have an older version of `pdfpc`.
I hadn't read the support file, but I have now. I was writing from my phone yesterday.
