### ISSUE TITLE
Possible wrong argument to uintHashFunc()

### ISSUE THREAD

**Issue by lcp** [pdfpc/pdfpc#351]
While I was packaging pdfpc 4.1.2 for openSUSE, I got the following error from the rpm check:

E: pdfpc 64bit-portability-issue /home/abuild/rpmbuild/BUILD/pdfpc-4.1.2/src/classes/presentation_controller.vala:231

This usually happens when passing an integer to a pointer argument. And this is the code raises the error:

[https://github.com/pdfpc/pdfpc/blob/v4.1.2/src/classes/presentation_controller.vala#L231](url)
``return uintHashFunc(this.keycode | this.modMask);``

I checked libgee and found the definition of ``GeeHashDataFunc()``:

``typedef guint (*GeeHashDataFunc) (gconstpointer v, void* user_data);``

It seems to me that ``GeeHashDataFunc()`` reads pointers, so I modified the code to:

``uint input = this.keycode | this.modMask;``
``return uintHashFunc(&input);``

This time, the rpm check passed. I'm no vala user so not sure if this is the right fix.

**Comment by AndreasBilke** [comment]
Could you check #352 ?

**Comment by lcp** [comment]
It works for me. Thanks!
