### ISSUE TITLE
Show current slide and notes

### ISSUE THREAD

**Issue by nikonikolov** [pdfpc/pdfpc#353]
It would be really nice if the presenter can actually see both the notes and the **current** slide on the laptop screen while presenting, instead of having to turn around all the time. I am willing to help implement this, but will need some guidance where to start. Thanks!

**Comment by AndreasBilke** [comment]
You want to see latex beamer notes and the current slide both on the presenter, right? Then: within `src/classes/window/presenter.vala` the layout of the presenter view is made. You certainly have to relayout the whole thing or remove something. Probably hiding the text notes section if you have latex beamer notes might be an option.

**Comment by nikonikolov** [comment]
Thanks for the tip! #220 seems to provide a working solution which instead of the next slide shows the current one. I would prefer this over hiding the notes. The provided solution in #220 is a bit unconditional, but how about creating a command-line option which enables this behavior? Would this be an acceptable change?

**Comment by fnevgeny** [comment]
@nikonikolov Please see #471. Maybe you don't need to use the beamer notes at all...
