### ISSUE TITLE
Notes are out of sync if PDF starts with page number 0

### ISSUE THREAD

**Issue by languitar** [pdfpc/pdfpc#355]
I am using the beamer theme [metropolis](https://github.com/matze/mtheme), which sets the title slide to slide number zero. Consequently, the first PDF page number is 0.

**Expected Behaviour**

Notes in pdfpc files are correctly attached to the corresponding slides based on the PDF page and LaTeX slide numbers.

**Actual Behaviour**

All slide notes are shifted by one because pdfpc always starts counting with 1, even if the PDF page number is zero.

**Steps to reproduce**

1. Attached are a PDF file and an accompanying pdfpc file with notes to demonstrate the problem: 
[test.tar.gz](https://github.com/pdfpc/pdfpc/files/2231638/test.tar.gz)

pdfpc version: v4.1.2
Used Distribution (GTK version, vala version): archlinux with i3. Gtk 3.22.30 and 2.24.32
Display Server (X/Wayland): X
HiDPI Setting (yes/no): no

**Comment by AndreasBilke** [comment]
Did you wrote the notes file by your self? I entered the notes from scratch for your PDF. pdfpc saves the notes for the slide with title "This is the first slide" at index 2. This might be "wrong", since it is page label 1, sure. But the result is correct. Did I missed something?

I can't see how you produced your `defence.pdfpc` file within pdfpc.

**Comment by languitar** [comment]
The file was produced with [pdfpc-latex-notex](https://github.com/cebe/pdfpc-latex-notes), which uses the actual PDF page numbers for indexing the notes.

**Comment by fnevgeny** [comment]
Then it is a bug in `pdfpc-latex-notex`, isn't it?

**Comment by AndreasBilke** [comment]
@fnevgeny It's not a bug. I think `pdfpc-latex-notes` does the right thing. We have wrong assumptions. See #367

**Comment by fnevgeny** [comment]
@languitar I suppose if you use [pdfpc.sty](https://github.com/pdfpc/pdfpc/blob/master/latex/pdfpc.sty) instead of `pdfpc-latex-notes` everything should work correctly...
