### ISSUE TITLE
Feature request: Buttons for drawing and pointing mode functions

### ISSUE THREAD

**Issue by languitar** [pdfpc/pdfpc#356]
The drawing and pointing modes are pretty useful. But I am not using pdfpc often enough to remember the keys to use these mode all the time. What about adding some buttons to control the functions in the presenter screen?

**Comment by AndreasBilke** [comment]
I think this is already covered by #302

**Comment by languitar** [comment]
Oh right, with the tablet in the title, that was hard to spot.
