### ISSUE TITLE
Animation does not work in Kubuntu 18.04

### ISSUE THREAD

**Issue by jayschieber** [pdfpc/pdfpc#358]
I opened your test file, video-example.pdf, in pdfpc. I have the two-monitor rendering problem already noted for Plasma 5.  I use that workaround.  But the video does not play.  I try your documented test using gst-launch-1.0, and the video plays fine. However, it fails to play in pdfpc. 

If I run pdfpc from command line, I get the messages below.
This is using pdfpc v4.1, and whatever is stock in Kubuntu 18.04.

Screensaver inhibited

(pdfpc:8194): GLib-GObject-CRITICAL **: 17:18:22.675: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(pdfpc:8194): GStreamer-CRITICAL **: 17:18:22.702: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (dest)' failed

(pdfpc:8194): Gtk-CRITICAL **: 17:18:22.702: gtk_widget_add_events: assertion 'GTK_IS_WIDGET (widget)' failed

(pdfpc:8194): GLib-GObject-WARNING **: 17:18:22.702: invalid (NULL) pointer instance

(pdfpc:8194): GLib-GObject-CRITICAL **: 17:18:22.702: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(pdfpc:8194): GLib-GObject-WARNING **: 17:18:22.702: invalid (NULL) pointer instance

(pdfpc:8194): GLib-GObject-CRITICAL **: 17:18:22.702: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(pdfpc:8194): GLib-GObject-WARNING **: 17:18:22.702: invalid (NULL) pointer instance

(pdfpc:8194): GLib-GObject-CRITICAL **: 17:18:22.702: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(pdfpc:8194): GLib-GObject-CRITICAL **: 17:18:22.702: g_object_set: assertion 'G_IS_OBJECT (object)' failed

** (pdfpc:8194): CRITICAL **: 17:18:22.702: pdfpc_view_video_add_video: assertion 'video != NULL' failed

(pdfpc:8194): GLib-GObject-CRITICAL **: 17:18:22.702: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(pdfpc:8194): GStreamer-CRITICAL **: 17:18:22.702: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (dest)' failed

(pdfpc:8194): GLib-GObject-CRITICAL **: 17:18:22.702: g_object_set: assertion 'G_IS_OBJECT (object)' failed

** (pdfpc:8194): CRITICAL **: 17:18:22.702: pdfpc_view_video_add_video: assertion 'video != NULL' failed

(pdfpc:8194): Gtk-CRITICAL **: 17:18:22.805: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(pdfpc:8194): Gtk-CRITICAL **: 17:18:22.805: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(pdfpc:8194): Gtk-CRITICAL **: 17:18:22.805: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(pdfpc:8194): Gtk-CRITICAL **: 17:18:22.805: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(pdfpc:8194): Gtk-CRITICAL **: 17:18:41.763: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

** (pdfpc:8194): CRITICAL **: 17:18:41.763: pdfpc_view_video_remove_video: assertion 'self != NULL' failed

(pdfpc:8194): Gtk-CRITICAL **: 17:18:41.764: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

** (pdfpc:8194): CRITICAL **: 17:18:41.764: pdfpc_view_video_remove_video: assertion 'self != NULL' failed
Screensaver reactivated

**Comment by fnevgeny** [comment]
Confirming the bug on vanilla 18.04.

**Comment by fnevgeny** [comment]
Please install gstreamer1.0-gtk3. Apparently, gtksink was promoted from gst-plugins-bad :).

**Comment by AndreasBilke** [comment]
It's in the suggested dependency list of the package, right?

**Comment by fnevgeny** [comment]
> It's in the suggested dependency list of the package, right?

Well yes, but one shouldn't expect regression after upgrading OS. In Ubuntu-16.04, this package wasn't there at all. So it's certainly a packaging bug - there is no gstreamer1.0-gtk3 dependency in [https://packages.ubuntu.com/bionic/pdf-presenter-console](https://packages.ubuntu.com/bionic/pdf-presenter-console).

**Comment by AndreasBilke** [comment]
Ubuntu is just copying the Debian package. https://packages.debian.org/buster/pdf-presenter-console . Debian has the recommended package. I can't help if Ubuntu does not care.

**Comment by AndreasBilke** [comment]
Probably they copied it at an "unstable" moment from Debian

**Comment by fnevgeny** [comment]
> Probably they copied it at an "unstable" moment from Debian

Yes, probably. I filed a bug but then realized it was already reported (but with no solution):
[https://bugs.launchpad.net/ubuntu/+source/pdf-presenter-console/+bug/1781425](https://bugs.launchpad.net/ubuntu/+source/pdf-presenter-console/+bug/1781425)

**Comment by jayschieber** [comment]
I can confirm that installing the package gstreamer1.0-gtk3 does fix the problem.
