### ISSUE TITLE
[SOLVED] Demo video doesn't play. gst-launch is OK

### ISSUE THREAD

**Issue by orestesmas** [pdfpc/pdfpc#359]
**Expected Behaviour**
demo video "apollo17.avi" playing

**Actual Behaviour**
Video does not play. When reaching the slide where video is located, terminal shows a bunch of Gtk-CRITICAL errors:

(pdfpc:5062): GLib-GObject-CRITICAL **: 19:15:42.833: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(pdfpc:5062): GStreamer-CRITICAL **: 19:15:42.859: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (dest)' failed

(pdfpc:5062): Gtk-CRITICAL **: 19:15:42.859: gtk_widget_add_events: assertion 'GTK_IS_WIDGET (widget)' failed

(pdfpc:5062): GLib-GObject-WARNING **: 19:15:42.859: invalid (NULL) pointer instance

(pdfpc:5062): GLib-GObject-CRITICAL **: 19:15:42.859: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(pdfpc:5062): GLib-GObject-WARNING **: 19:15:42.859: invalid (NULL) pointer instance

(pdfpc:5062): GLib-GObject-CRITICAL **: 19:15:42.859: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(pdfpc:5062): GLib-GObject-WARNING **: 19:15:42.859: invalid (NULL) pointer instance

(pdfpc:5062): GLib-GObject-CRITICAL **: 19:15:42.859: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(pdfpc:5062): GLib-GObject-CRITICAL **: 19:15:42.859: g_object_set: assertion 'G_IS_OBJECT (object)' failed

** (pdfpc:5062): CRITICAL **: 19:15:42.859: pdfpc_view_video_add_video: assertion 'video != NULL' failed

(pdfpc:5062): GLib-GObject-CRITICAL **: 19:15:42.859: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(pdfpc:5062): GStreamer-CRITICAL **: 19:15:42.859: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (dest)' failed

(pdfpc:5062): GLib-GObject-CRITICAL **: 19:15:42.859: g_object_set: assertion 'G_IS_OBJECT (object)' failed

** (pdfpc:5062): CRITICAL **: 19:15:42.859: pdfpc_view_video_add_video: assertion 'video != NULL' failed

(pdfpc:5062): Gtk-CRITICAL **: 19:15:42.967: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(pdfpc:5062): Gtk-CRITICAL **: 19:15:42.967: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(pdfpc:5062): Gtk-CRITICAL **: 19:15:42.967: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(pdfpc:5062): Gtk-CRITICAL **: 19:15:42.967: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(pdfpc:5062): Gtk-CRITICAL **: 19:15:43.895: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

** (pdfpc:5062): CRITICAL **: 19:15:43.895: pdfpc_view_video_remove_video: assertion 'self != NULL' failed

(pdfpc:5062): Gtk-CRITICAL **: 19:15:43.895: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

** (pdfpc:5062): CRITICAL **: 19:15:43.895: pdfpc_view_video_remove_video: assertion 'self != NULL' failed

**Steps to reproduce**

1. Launch the demo PDF as explained in the documentation.

pdfpc version: v4.1.2 (Compiled from GitHub) - also tried with the one provided by Ubuntu Bionic. Same result
Used Distribution (GTK version, vala version): Ubuntu Bionic 18.04
Display Server (X/Wayland): X
HiDPI Setting (yes/no): NO

**Comment by AndreasBilke** [comment]
Can you try the solution proposed in #358?

**Comment by orestesmas** [comment]
Installing gstreamer1.0-gtk3 solve the problem. Thanks!!
