### ISSUE TITLE
gst-launch- and pdfpc

### ISSUE THREAD

**Issue by pawelsikorski** [pdfpc/pdfpc#360]
Hi, 
Are there any know issues with making this work on fedora28?  I think I have installed  all possible combinations of gstreamer, but  am not  able to make even the vido test work:

gst-launch-1.0 filesrc location=<your video> ! decodebin ! ximagesink
gives me: 
Pipeline is PREROLLING ...
Missing element: Audio Video Interleave (AVI) demuxer
ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0: Your GStreamer installation is missing a plug-in.
Additional debug info:

I can see that it must be a gst issue, and I can not find any solution. I have been looking for a good video solution for beamer presentations for a long time, so would really like to get this running. 

Best regards
Pawel

**Comment by AndreasBilke** [comment]
Sorry, we cannot provide support for gstreamer itself or distribution specific issues
