### ISSUE TITLE
Use PDF Page Labels for connection between slide and notes

### ISSUE THREAD

**Issue by AndreasBilke** [pdfpc/pdfpc#367]
Currently, we connect the (0-indexed) page number with a note. It might happen (see #355) that our assumption on page numbers is violated.

I propose to use PDF page labels for this purpose. We could fix #355, make `.pdfpc` file more human readable (since it maps to what a user sees in his pdf viewer), we support cebe/pdfpc-latex-notes better, and it would allow us to have features like "notes for page IV".

Is there anything which speaks against using page labels?

**Comment by fnevgeny** [comment]
This certainly sounds as the right thing to do. However - are the page labels guaranteed to be present in PDF? And if yes, are they necessarily unique?

**Comment by fnevgeny** [comment]
OK, thanks. Then I see no drawbacks of switching to page labels.

**Comment by mayanksuman** [comment]
One clarification: Does this break loading of any pre-existing pdfpc file?

**Comment by AndreasBilke** [comment]
> One clarification: Does this break loading of any pre-existing pdfpc file?

Only those who have already notes attached (in the .pdfpc file) AND have page labels beginning with 0. But these cases have screwed .pdfpc files for now anyways.

**Comment by Sharu95** [comment]
I experienced the same recently, due to the indexing problem and came here from #355. I figured a temporary workaround, for me at least, was to overwrite the generated .pdfpc-file (generated from `pdfpc-latex-notes`) with a small script. If it will be useful to anyone, at all, here is the Python-snippet which replaces the postfix number after `###` in the .pdfpc-file: 

```
input_file = 'main.pdfpc'
output_file = 'notes.pdfpc'

with open(input_file, 'r') as f:
  lines = f.read().split('\n')

with open(output_file, 'w+') as out:
  for line in lines:
    if '###' in line:
      overlay_num = int(line.split(' ')[-1])
      overlay_num = f'### {overlay_num + 1}'
      out.write(overlay_num + '\n')
    else:
      out.write(line + '\n')

import subprocess
cmd = 'pdfpc -R notes.pdfpc main.pdf'
process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
try:
  output, error = process.communicate()
except KeyboardInterrupt:
  print('Exit')
```
