### ISSUE TITLE
RFC: four-state operation mode

### ISSUE THREAD

**Issue by fnevgeny** [pdfpc/pdfpc#369]
Currently, there are three toggles to change the operation mode:

1. Pointer on/off
2. Drawing on/off
3. Eraser/Pen

This in principle gives 3! = 6 combinations, but only 4 are meaningful:

- None (normal presentation)
- Pointer
- Drawing pen
- Eraser

In my opinion, this is both confusing and requires more clicks to switch to a desired mode. So I suggest to use a four-state status changeable by four actions like selectPointer|selectPen|selectEraser|selectNone instead of the three current toogle*'s (think of a group of four radiobuttons instead of three checkboxes).

With this, some actions would become redundant. Say, no need to have separately increasePen/decreasePen and increasePointer/decreasePointer - a single pair of buttons would suffice, acting depending on the current context. Similarly, setColor would work either as setPenColor  or as the currently missing setPointerColor (BTW, am I the only one who misses the green pointer? :)).

**Comment by AndreasBilke** [comment]
I totally agree that reducing the function space is better for the user. So I agree to your RFC.

Regarding the pointer colour: if it makes you happy, why not? :)

Just one thing: Does it make sense for you to mark a region with the pointer (you can click highlight areas) and then use the pen for additional drawing? Is this currently possible?

**Comment by fnevgeny** [comment]
@AndreasBilke: do you suggest adding the fifth, "marker" mode? Like pen, but with a < 1 opacity and a larger size?

**Comment by AndreasBilke** [comment]
![2018-10-04-185440_1920x1200_scrot](https://user-images.githubusercontent.com/1804398/46490034-2f60cf00-c807-11e8-945d-e774934351f5.png)

See screenshot. And yes, this seems be a fifth mode for me. Do you think this is necessary?

**Comment by fnevgeny** [comment]
I was actually thinking of something like "Highlighter" in [xournal](http://xournal.sourceforge.net/).

Also, a "magnifying glass" would be an interesting option.

**Comment by AndreasBilke** [comment]
I mean that you can combine the pointer mode (where you can highlight rectangular areas) and the pen to write within that highlighted area. That would be the fifth (if we want it at all) mode.

**Comment by fnevgeny** [comment]
Well, visually, one can achieve this effect by first drawing and then switching to the pointer mode and highlighting a region (which I guess is exactly what you did to produce the screenshot). But you want to be able to do it in the other direction: first highlight a region and then draw, keeping the highlighted region intact, right? It sounds to me like an extension of the drawing mode rather than a separate one; but in either case, there should be a way to perform different actions (region select or pen drawing) using the same (currently) action - mouse dragging. For example, by keeping a modifier key (e.g., `Ctrl`) pressed. But this would be problematic for tablets.

Alternatively, the highlighted region defined in the pointer mode can be made "non-volatile", i.e., keep it after having left the pointer mode by changing to drawing.

What do you think?

**Comment by AndreasBilke** [comment]
I just wanted your opinion. Yes, I did the screenshot by first drawing and then highlighting. We can keep the

**Comment by fnevgeny** [comment]
OK, this is a bit more complicated. Do we really need the `hideDrawing` action? I mean, there is `clearDrawing` which erases everything (on the current page). `hideDrawing`, on the other hand, hides drawings on all pages. And the only way to show them (all) again is to `toggleDrawing` **twice** - far from intuitive, IMHO. Is the ability to switch on/off all drawings simultaneously really important?

**Comment by AndreasBilke** [comment]
> Is the ability to switch on/off all drawings simultaneously really
> important?

No. :)

**Comment by fnevgeny** [comment]
Re: hideDrawing - well, I kept it meanwhile - it didn't require much code anyway, but changed the functionality to the real toggle mode. Please have a look at the current status in the "operation-mode" branch.

**Comment by AndreasBilke** [comment]
> Please have a look at the current status in the "operation-mode" branch.

I like it! It feels so much clearer now :) Thank you very much. The only thing is, that the key bindings does not feel intuitive to me.

I could imaging something like for a default configuration:

```
Key 1: Drawing Mode
Key 2: Erasing Mode
Key 3: Pointer Mode
Key 4/5 (or 8/9): Increase/Decrease the pen OR the pointer, depending on the selected mode
Key 0: Normal Mode
Key c: For clearing the drawings
Key I_DONT_KNOW: for hiding the drawings
```

**Comment by fnevgeny** [comment]
> The only thing is, that the key bindings does not feel intuitive to me.

I absolutely agree. My intent at this stage was to keep the bindings as close to the original ones as possible (hence, only '0' is new).

I will open a separate request for discussing keybindings - with many years of incremental additions behind, it is not a surprise the current bindings are not optimal; there is actually more to it, IMO, than non-intuitiveness.

So if there are no other objections, I suggest to merge this as is and work on keybindings separately.
