### ISSUE TITLE
pdfpc 4.2: icons move.svg, settings.svg, and linewidth.svg are not installed

### ISSUE THREAD

**Issue by maehne** [pdfpc/pdfpc#374]
The icons `move.svg`, `settings.svg`, and `linewidth.svg` are not listed in the `install()` argument list in `pdfpc/icons/CMakeLists.txt` and thus don't get installed to $PREFIX/share/pixmaps/pdfpc/ along with the other icons. This leads to warnings when launching `pdfpc`:
```
$ pdfpc video-example.pdf
Warning: Could not load icon /opt/local/share/pixmaps/pdfpc/move.svg (Datei »/opt/local/share/pixmaps/pdfpc/move.svg« konnte nicht geöffnet werden: No such file or directory)
Warning: Could not load icon /opt/local/share/pixmaps/pdfpc/settings.svg (Datei »/opt/local/share/pixmaps/pdfpc/settings.svg« konnte nicht geöffnet werden: No such file or directory)
Warning: Could not load icon /opt/local/share/pixmaps/pdfpc/linewidth.svg (Datei »/opt/local/share/pixmaps/pdfpc/linewidth.svg« konnte nicht geöffnet werden: No such file or directory)
```

**Comment by AndreasBilke** [comment]
Fixed with #375

**Comment by fnevgeny** [comment]
Oops. My bad :(

**Comment by maehne** [comment]
Thanks for quickly merging the fix! Would it be possible to tag it as either a new release or reset the tag for version 4.2? It would be facilitate packaging the software.

**Comment by AndreasBilke** [comment]
> Thanks for quickly merging the fix! Would it be possible to tag it as either a new release or reset the tag for version 4.2? It would be facilitate packaging the software.

I released v4.2.1

**Comment by AndreasBilke** [comment]
> Oops. My bad :(

And I didn't looked carefully while merging :)

**Comment by maehne** [comment]
Thanks for tagging the new release! I used it to update the MacPorts port of pdfpc. I just submitted it for review to the MacPorts trac ([ticket #57381](https://trac.macports.org/ticket/57381)). It may take some time until it gets accepted, but then you might consider it to mention it on your web page.

**Comment by AndreasBilke** [comment]
This is off topic:

Since we have a mac user at our hand, could you check the issue 331 if this
is still a problem (with mac ports)?

Thank you!

**Comment by maehne** [comment]
FYI, my update to the pdfpc port got accepted ([MacPorts ticket #57381](
https://trac.macports.org/ticket/57381)). Thus, the current version of pdfpc is now easily installable on macOS using [MacPorts](https://www.macports.org). There's a Quartz variant, which integrates better with the macOS GUI:
```
$ sudo port -v install pdfpc +quartz
```
and there's an X11 variant (currently, the default), which should support video playback, but which might suffer other shortcomings:
```
$ sudo port -v install pdfpc +x11
```
