### ISSUE TITLE
Source path is hardcoded and used for loading run-time resources

### ISSUE THREAD

**Issue by fnevgeny** [pdfpc/pdfpc#376]
`CMAKE_SOURCE_DIR`, hardcoded during the compilation, is used with the _highest priority_ to look for resources (icons, css, rc files) during run time. This is convenient for testing, but undesired for production (and confusing, since not documented; in fact, it was the reason #374 went undetected in the first place). For most users, it adds several unnecessary filesystem look-ups.

I think this behavior should be conditionally enabled depending on a command-line flag or an environment variable.

**Comment by AndreasBilke** [comment]
How about  `cmake -Ddev=on` which could enable the icon loading directly from the source tree. And in other cases it searches icons in the system paths?

**Comment by fnevgeny** [comment]
Yes, it is a possibility. A (very minor) drawback is that there would be two different executables for development and "normal" work. I was thinking about something like `PDFPC_DIR` shell variable - when set, it would be treated as, currently, `CMAKE_SOURCE_DIR` is. The drawback is that one needs to explicitly export/setenv it while developing. On the other hand, a benefit is that it can also be used for installing/testing pdfpc with no system privileges. Or, e.g., for testing different configs/CSS's without editing/replacing files.

**Comment by AndreasBilke** [comment]
But if you forget to set the shell variable (which might happen if you
continue programming the next day) the behaviour might be unexpexted again.

With the `-D` switch, the setting is saved als long as you don't delete the
compiling folder.

**Comment by fnevgeny** [comment]
> But if you forget to set the shell variable (which might happen if you continue programming the next day) the behaviour might be unexpexted again.

No, what I mean is - if the shell variable is undefined, no extra path is searched at all - only the system and user locations, as in the man page.
