### ISSUE TITLE
Notes on seperate file

### ISSUE THREAD

**Issue by Bersam** [pdfpc/pdfpc#385]
Hey there,

This is a question not a bug, can we use pdfs on separate pdf file? if not do you guys have any idea how to merge two pdf for notes and presentation file together so I can use them on pdfpc? Is there any way to set a margin instead of bottom, top?

**Comment by HermannDppes** [comment]
# Merging
It should be reasonably easy to combine two pdf files in any way you want using [pdfpages](https://www.ctan.org/pkg/pdfpages). This is what pdfjam/-join/-nup does internally anyway.

If you don't mind me asking: Why do you have your notes in a separate file in the first place?

# Margin
I do not understand your question regarding margins.

**Comment by Bersam** [comment]
Thank you @hermanndppes,
I'll try pdfjam, thanks! 
Regarding margin, right now if you run pdfpc with - - notes bottom, it will assume that notes are in lower 50% of page. Is there any way to change this percentage?

**Comment by AndreasBilke** [comment]
> Regarding margin, right now if you run pdfpc with - - notes bottom, it will assume that notes are in lower 50% of page. Is there any way to change this percentage?

No, there is no option. This feature comes from the notes on second slide feature from latex beamer. And there, a page is always split in halfs.
