### ISSUE TITLE
Video playback not working on macOS when building `pdfpc` against the GTK+-3 Quartz variant

### ISSUE THREAD

**Issue by maehne** [pdfpc/pdfpc#386]
This new issue shall be used to continue the related discussion in issue #331 concerning problems with the non-working video playback in `pdfpc` when it is built the Quartz variant of GTL+-3.

**Expected Behaviour**

`pdfpc` should play the videos embedded in [`video-example.pdf`](
https://pdfpc.github.io/demo/pdfpc-video-example.zip).

**Actual Behaviour**

The videos don't start at all. There are no warning or error messages giving a hint what goes wrong. The `apollo17.avi` video plays back correctly with:
```
gst-play-1.0 -v --videosink gtksink apollo17.avi
```
However, I noticed, that this application starts Xquartz even though GTK+-3 is installed in in its Quartz variant.

**Steps to reproduce**
1. Checkout the branch `fix-gstreamer1-gst-plugins-good-deps` from my [`experimental-macports` repository](https://github.com/maehne/experimental-macports).

2. Add the contained `ports/` directory to your `/opt/local/etc/macports/sources.conf` file.

3. Install pdfpc 4.2.1_2 through MacPorts:
```sh
sudo port -v install pdfpc +quartz
```
4. Change to the directory with [`video-example.pdf`](
https://pdfpc.github.io/demo/pdfpc-video-example.zip) and and start it with
```
pdfpc video-example.pdf
```

pdfpc version: 4.2.1
Used Distribution (GTK version, vala version): macOS 10.13.6 (17G3025) using MacPorts 2.5.4
Display Server (X/Wayland): Quartz
HiDPI Setting (yes/no): yes

**Comment by fnevgeny** [comment]
> However, I noticed, that this application starts Xquartz even though GTK+-3 is installed in in its Quartz variant.

Probably the x11/no_x11 ABI's are partially compatible. But shouldn't the two variants be installed in different paths, including plugins etc? Why does Quartz find Xquartz plugins at all?

**Comment by maehne** [comment]
Xquartz.app is the X11 server for macOS. On my current setup, the Gstreamer libraries are built also with X11 support. So, I guess this triggers launching the X11 server even though the window opened by `gst-play-1.0` is definitely a native macOS window using Quartz for the rendering. I can even close the Xquartz.app, which should otherwise lead to a kill of the `gst-play-1.0` application.

On MacPorts, only a single variant of each port can be active at a time. All GTK+-3-related ports have been installed in their `+quartz` variant. The Gstreamer-related ports currently don't have such a dedicated variant. I will have to find the time to uninstall all Gstreamer-related ports und explicitly disable the X11 variant. Maybe, this will help.

**Comment by fnevgeny** [comment]
> the window opened by gst-play-1.0 is definitely a native macOS window using Quartz for the rendering

Then it's strange the videos don't work in pdfpc. You can try a simple vala/gstreamer/gtksink example from here: https://wiki.gnome.org/Projects/Vala/GStreamerSample ("Vala GStreamer Video Example").

**Comment by fnevgeny** [comment]
Well, it's a good news! Then it must be something subtle preventing videos in pdfpc working.

**Comment by maehne** [comment]
Yes, the simple Vala example also plays `apollo17.avi`.

**Comment by maehne** [comment]
I have now also tested video playback on Windows when compiling pdfpc using the MinGW-w64 toolchain of MSYS2 and which also provides packages for all other dependencies including a native GTK+-3 implementation and Gstreamer. To compile pdfpc with `-DMOVIES=on`, I had to additionally provide an implementation of `realpath()`, which I found in a [MinGW ticket](https://sourceforge.net/p/mingw/patches/256/). Then compilation worked. However, I observe the same issue as on macOS: The video won't playback inside `pdfpc`. Playing back `apollo17.avi` using `gst-play-1.0.exe` and the `gtksink` works out of the box. So, this issue seems to concern non-X11 platforms.

**Comment by fnevgeny** [comment]
Thanks for all your efforts!

> So, this issue seems to concern non-X11 platforms.

Could be, but maybe just a bug that doesn't surface on "well tested" platforms.

Is sound audible in `video-example.pdf`? Does some processing take place at all (reflected in CPU load)?
Please try getting rid of any occurrence of `adaptor1` in `add_video_control()`.

**Comment by fnevgeny** [comment]
> Please try getting rid of any occurrence of `adaptor1` in `add_video_control()`.

as well as `scale`, `rate`, `caps`, `filter`.

**Comment by fnevgeny** [comment]
@maehne: ping?

**Comment by fnevgeny** [comment]
I assume the #391 patch fixes the issue. If not, please reopen the issue.
