### ISSUE TITLE
Video playback isn't working on pdfpc from Fedora 29 packages

### ISSUE THREAD

**Issue by YaLTeR** [pdfpc/pdfpc#393]
For some reason, `pdfpc` packaged in Fedora 29 (v4.1.2) doesn't play back videos. There are no messages in the terminal, and playing back through `gst-launch-1.0` works fine.

Building the latest version (v4.2.1) from releases manually produced pdfpc with working video playback.

Used Distribution (GTK version, vala version): Fedora 29 x86_64, GTK 3.24.1
Display Server (X/Wayland): Wayland
HiDPI Setting (yes/no): no

**Comment by fnevgeny** [comment]
Does the official (github) v4.1.2 work if manually compiled? If yes, this must be a Fedora package bug.

**Comment by YaLTeR** [comment]
Official v4.1.2 compiled from .tar.gz in the Releases does not play back video either.

**Comment by fnevgeny** [comment]
OK, there have been a few video-related fixes between 4.1.2 and 4.2.1, but I wouldn't expect any to be detrimental for the playback as such... If you're interested, you can `git bisect` to find the commit that fixes the problem. Since the current version works, I close the issue.

**Comment by YaLTeR** [comment]
Looks like the bug was introduced in 13e3b372711fdc94acdb26be69ef0cf1465911ed and then subsequently fixed in 21e4efb3afe325fe7e2f800d1c22fd1bc28bc3d7 which happened to be just 3 commits after the v4.1.2 release. Perhaps it would've been better to draft a v4.1.3 right after that since video support is kinda important. :smile:

**Comment by fnevgeny** [comment]
> Looks like the bug was introduced in 13e3b37 and then subsequently fixed in 21e4efb

Ah, indeed. I introduced it unknowingly and immediately forgot after the Andreas's fix :)

> Perhaps it would've been better to draft a v4.1.3 right after that since video support is kinda important.

Probably. On the other hand, there is now v4.2.1 anyway.
