### ISSUE TITLE
window mode

### ISSUE THREAD

**Issue by vzaliva** [pdfpc/pdfpc#395]
I understand it uses **fullscreen** mode for showing notes on the 2nd screen. I am looking for one where presentation and notes are shown in two separate **windows** at the same screen. The reason is that I would like to present over video conferencing software and share presenter window only while keeping notes on my screen. Is it possible to implement such a feature? I can help with testing.

**Comment by fnevgeny** [comment]
`pdfpc -w`? `pdfpc -Z`?

**Comment by vzaliva** [comment]
`pdfpc -w` shows both slides and notes side-by-side in a **single** window. I want 2 separate windows.

**Comment by AndreasBilke** [comment]
@vzaliva so you want 3 windows in total? A presentation for the audience, a presentation for you and notes for you?

**Comment by vzaliva** [comment]
I would like 2 windows: 

1. Presentation for the audience
2. Notes for me

Like `pdfpc` does this now but use 2 **windows** on a single display instead of 2 fullscreen **displays**.

When presenting over Skype, Slack, bluejeans, Google Meet, etc from my laptop (not using projector or external screen)  I can choose to share one window (presentation for the audience) and see my notes in the other window.

In general, this could be even useful for people with multiple displays. It gives user flexibility to arrange windows on his displays, choose which ones to show in full screen, Modern window managers allow the user to manage all that.

**Comment by AndreasBilke** [comment]
I'm confused. `pdfpc -w` creates 2 windows and **don't make it
fullscreen**. The first window contains your presentation, the second
window is the presentation view (and this is the current slide + notes).

So you can share your presentation window and have your notes (+
presentation) separately.

**Comment by vzaliva** [comment]
hmm. this is not what I see here. Maybe I have older version installed via `apt` on Ubuntu, not this fork.

**Comment by vzaliva** [comment]
v4.1

**Comment by AndreasBilke** [comment]
> v4.1

This two window behaviour is there since ever.

I mean, pdfpc uses in any case two windows. The difference between `-w` and
nothing is, that with `-w` these two windows are not brought to fullscreen
state.

**Comment by vzaliva** [comment]
I am sorry, you are right. It was my window manager configuration which made this windows show on top of another. I am using i3wm and usually, windows are tiled. But for some reason pdfpc windows was opened as "floating" and they overlapped each other.

Thank you for helping me to figure this out.
