### ISSUE TITLE
Failure to properly show presentation and notes

### ISSUE THREAD

**Issue by JoWi2** [pdfpc/pdfpc#397]
After having successfully used pdfpc in the past, I ran into a serious problem this time.
The slides I created (Antergos, TeXstudio 2.12.14, pdfpc 4.2.1-3) fail to be shown properly. Same goes for the presenter notes.
This is the error I get:

```
pdfpc --notes=right  /path/to/my/slides/test/test.pdf
--notes option detected. Disable auto grouping.

(pdfpc:2330): Gdk-CRITICAL **: 11:45:56.428: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed

(pdfpc:2330): GdkPixbuf-CRITICAL **: 11:45:56.428: gdk_pixbuf_save_to_callbackv: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(pdfpc:2330): Gdk-CRITICAL **: 11:45:56.429: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed

(pdfpc:2330): GdkPixbuf-CRITICAL **: 11:45:56.429: gdk_pixbuf_save_to_callbackv: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Screensaver inhibited

(pdfpc:2330): GdkPixbuf-CRITICAL **: 11:45:57.071: gdk_pixbuf_loader_write: assertion 'buf != NULL' failed
Could not load cached PNG image for slide 0: Unrecognized image file format
```

When I add the option --disable-compression, I do not get that error anymore, but the presentation does not show on the projector/second screen, and the presenter view looks like this, 
![screenshot_20181208_143803](https://user-images.githubusercontent.com/13626739/49748117-df710f00-fc72-11e8-955a-2d539e2df670.png)
Which is obviously not very helpful!

On my machine the same problem occurs with this test PDF 
[test.pdf](https://github.com/pdfpc/pdfpc/files/2664155/test.pdf)

The respective Tex file is also attached as a txt file.

Thank you for fixing this!
[test.txt](https://github.com/pdfpc/pdfpc/files/2664160/test.txt)

**Comment by AndreasBilke** [comment]
What you want is to use the option "show notes on second screen" for latex beamer (https://www.scivision.co/beamer-latex-dual-display-pdf-notes/).

It puts the notes side by side to the actual slide. Then you can use `--notes=right`.

**Comment by JoWi2** [comment]
Yeah..... that's embarrassing...!!!
Totally fixed it! Thanks so much and sorry for the inconvenience! I'm really sorry. So I guess this can be closed/deleted...

**Comment by AndreasBilke** [comment]
No Problem!
