### ISSUE TITLE
Plug-and-play monitor support

### ISSUE THREAD

**Issue by fnevgeny** [pdfpc/pdfpc#408]
If run initially with a single physical monitor attached but another one is connected afterwards, pdfpc should open the presentation view on the second monitor (perhaps asking for confirmation).

**Comment by AndreasBilke** [comment]
This would require a complete rewrite of the layouting and caching coffee since the new monitor could have a different size.

Am 18. Dezember 2018 22:19:40 MEZ schrieb Evgeny Stambulchik <notifications@github.com>:
>If run initially with a single physical monitor attached but another
>one is connected afterwards, pdfpc should open the presentation view on
>the second monitor (perhaps asking for confirmation).

**Comment by fnevgeny** [comment]
> The presenter screen is one's built-in laptop monitor, which never changes.

While true, I realized it actually might be quite useful for the presenter window to be resizable, too. Say, sometimes you want to look at/run something on your desktop etc. So, e.g., press `w` to toggle between the fullscreen and windowed modes (the presentation remains fullscreen on the second monitor, of course).

**Comment by fnevgeny** [comment]
@AndreasBilke, please see the "window-resize" branch. Currently, the presentation window (in the windowed mode) is fully resizable. There are some glitches to be ironed out (pointer/drawing modes need to be switched off/on to re-enable, and videos on the current page need to switch page forward/back to resize).

**Comment by AndreasBilke** [comment]
Some time ago I also tried to make pdfpc dynamically resizable. I also
choosed the Gtk.AspectFrame so I think this is the right way to do. :)

**Comment by fnevgeny** [comment]
Great minds think alike :)

**Comment by torwag** [comment]
I want to add, that yes the presenter view on the internal display should not change... but in reality it happens from time to time that the internal display rescales due to the video presenter settings. That can be changed but more often, people just leave it as it is .... as you know this stuff usually happens 5 min before the presentation starts ;). Nevertheless, I had never a problem with scaling of pdfpc.
