### ISSUE TITLE
Reloading current presentation

### ISSUE THREAD

**Issue by fnevgeny** [pdfpc/pdfpc#409]
It would be nice to be able to reload the presentation when the file changes, which happens all the time during preparation of the talk.

**Comment by AndreasBilke** [comment]
Done with #410

**Comment by LnLcFlx** [comment]
There is no possibility to reload upon file change automatically right now, right?

**Comment by fnevgeny** [comment]
> There is no possibility to reload upon file change automatically right now, right?

Right.
