### ISSUE TITLE
Support for zoom

### ISSUE THREAD

**Issue by fnevgeny** [pdfpc/pdfpc#414]
It is desirable sometimes to enlarge a part of the slide (usually, a graph). I think it would be reasonable to implement it in the "highlight/pointer" mode: First, highlight a rectangular region with the mouse drag as usual, and then hit a key, e.g., `Z` - the highlighted area would be zoomed in to fill the entire screen view. `Esc` to exit.

There is some similarity to #338, but in that case the functionality requested was more like a (sliding) magnifying glass, if I understood correctly, which is indeed something not normally needed for _presentations_.

**Comment by mayanksuman** [comment]
> I think it would be reasonable to implement it in the "highlight/pointer" mode: First, highlight a rectangular region with the mouse drag as usual, and then hit a key, e.g., Z - the highlighted area would be zoomed in to fill the entire screen view.

Good Idea! But what if user need to use drawing tool on the zoomed part.

 I think that Zoomed view should have possibility of drawing over it. That is not possible with current division of modes in pdfpc.

I suggest in stead of currently available 5 modes (`NORMAL`, `POINTER`, `PEN`, `ERASER` & `OVERVIEW`), `pdfpc` can have three modes only.

1. `NORMAL` - same as current one. Used for presentation.
2. `INTERACTIVE` - Should have tools for pointer, pen, eraser and zoom. Any tools can be used without leaving the mode. `Esc` escape to NORMAL mode. 
3. `OVERVIEW` - same as before.

This division also make use of some options (like +, - etc.) more logical. Additionally, user interaction with presentation will be better. Additionally, we can have color option for pointer (Someone might dislike red pointer) just like pen with this set of modes.

What do you think?

**Comment by mayanksuman** [comment]
One more thought: 
Instead of some area selected and then go for zoom (`fixed region zoom`), can we go for `moving region zoom` as done by logitech Spotlight device.

In this case their is no possibility of drawing on zoomed region, so we get rid of lot of complexity of the last approach. However, `moving region zoom` is less powerful in some use cases (in which the zoom window should stay we want to point/draw something on the region).

**Comment by fnevgeny** [comment]
> I think that Zoomed view should have possibility of drawing over it.

There should be a limit to implementing any thinkable complexity. Really, if after zooming in you still cannot explain to people what is there without extra drawing, you probably need to redo the slide from scratch...

>That is not possible with current division of modes in pdfpc.

It is unrelated.
