### ISSUE TITLE
no longer shows notes separately

### ISSUE THREAD

**Issue by kbro237** [pdfpc/pdfpc#416]
After updated to the latest version, running pdfpc with the notes option doesn't seem to split up the beamer file and shows both the slide and notes with a white border.

I downgraded to 4.2.1 and it works again.

pdfpc version: 4.3.0
Used Distribution (GTK version, vala version): homebrew
Display Server (X/Wayland):
HiDPI Setting (yes/no):

**Comment by AndreasBilke** [comment]
I can confirm this.

**Comment by AndreasBilke** [comment]
Faulty commit is 8e6feb395524c7742472540e5152428bb65a949e

**Comment by fnevgeny** [comment]
@kbro237, using this occasion, I want to understand - what is the reason(s) you use the beamer notes (rather than the pdfpc notes)? Is it just the automatic update in the case of beamer or something else?
Thank you in advance.

**Comment by AndreasBilke** [comment]
Closed with #417
