### ISSUE TITLE
Feature Request: Quick bookmarks

### ISSUE THREAD

**Issue by torwag** [pdfpc/pdfpc#418]
For teaching, sometimes you want to jump back to a certain slide e.g., the inital question, or the "overall" image which you used to explain in detail in the following slides. Or students ask and you need to go back to that slide to explain it again.
It would be helpful, to have a way to add a quick "bookmark" and jump forth and back to between this and the current slide e.g. by a single keypress (or button click).
I believe it should be as simple as possible, only one bookmark, pressing a set-key or set-button on a slide saves the page number as bookmark, pressing within the presentation the quick-jump-key or button to jump to that marked slide, pressing it again on that key, jumps back to the page where the jump was comming from. 

Alternatively, but more complex, people could tag slides with names (maybe even within the note functionality e.g. by adding a keyword name: my_important_slide) and the already existing go-to function could be modfied to accept (and suggest) those tags as alternative to page numbers. This would have the charm to not create even more key-bindings.
That would also make #323 redunant, as people could tag an empty slide "notes" and jump to this slide easily

**Comment by AndreasBilke** [comment]
>I can provide support or even let this implement in some sort of student
>assignment if this is of interest in general

That would be great!

**Comment by fnevgeny** [comment]
`m` to bookmark and `M` to return to it any time later. Then in theory `Shift+Backspace` to go back in the history, but it's buggy. You can open a bug report so it will not be forgotten :)

**Comment by torwag** [comment]
@fnevgeny I didn't now a bookmark function was available already. 
According to the man file
`m` for bookmark
`Shift+m` (M) for jumping back 
this works well,
However, using `Shift+Backspace`, I always end-up on the first slide.
My suggestion would be to save the current slide before initiating a jump via `Shift+m`
Furthermore, I thing that it might not hurt to keep the "saved" logo (maybe rename bookmarked) on the presenter view, as it could help to make clear that this page is saved.

**Comment by fnevgeny** [comment]
> I didn't now a bookmark function was available already.

We have an updated shiny [demo](https://github.com/pdfpc/pdfpc/releases/download/v4.3.0/pdfpc-demo.pdf) :)

> However, using `Shift+Backspace`, I always end-up on the first slide.

Yes, I noted the history navigation is buggy. It might even work if you press `Shift+Backspace` again...

> Furthermore, I thing that it might not hurt to keep the "saved" logo (maybe rename bookmarked) on the presenter view, as it could help to make clear that this page is saved.

I'm not sure I understand the reason. Why? Would you be paging through an entire presentation just to find a bookmarked slide? I'd rather it be somehow indicated in the overview.

**Comment by torwag** [comment]
> > Furthermore, I thing that it might not hurt to keep the "saved" logo (maybe rename bookmarked) on the presenter view, as it could help to make clear that this page is saved.
> I'm not sure I understand the reason. Why? Would you be paging through an entire presentation just to find a bookmarked slide? I'd rather it be somehow indicated in the overview.

Well I thougt it wouldn't hurt that I get a visible reminder that I bookmarked that particular page. Just as a reminder, e.g. to make sure my I really saved the last slide of the current lecture.

Which brings me to the point, that I would like to see and use a 
"autobookmark-the-current-slide-on-exit-feature"-hook in conjunction with a "goto-last-slide-on-open"-hook  Thus, pdfpc would open a presentation and continous on the last slide.

However, you are right, a mark in the overview would be great as well.

**Comment by fnevgeny** [comment]
> Which brings me to the point, that I would like to see and use a
> "autobookmark-the-current-slide-on-exit-feature"-hook in conjunction with a "goto-last-slide-on-open"-hook. Thus, pdfpc would open a presentation and continous on the slide from the previous session.

Do you really need this? Have you tried the reload feature (`Ctrl+r`) in the master branch? #410

**Comment by torwag** [comment]
Ok most part is already implemented. I still like the idea to use the note window to add metadata like bookmark names resp. tags (e.g. chap1, chap2, chap3, etc. to jump to the start slides for a certain chapter). This "note-metadata-method" could be extended in the future to even more fine-control the presentation, e.g. one could set and change video start and endpoints. It could reset, start or stop timers, set pen size and colour individually. etc.    
However, this is a complete different topic beside of being used to create bookmarks and therefore, I think it would be good to close this one and create a new one, if people like the idea

**Comment by torwag** [comment]
Just to sum up for people who scroll down to look for a solution:
Already implemented:

`m` to create the bookmark (you can only create one for now)
`Shift+m` (M) for jumping back to that bookmark
`Shift+Backspace` jumps back from bookmark to the previous page (this is a bit buggy right now)
