### ISSUE TITLE
Alternative way to preview overlays 

### ISSUE THREAD

**Issue by torwag** [pdfpc/pdfpc#421]
This is not a feature request but rather an idea and I would like to get some feedback about it.

Contrary to hacky PowerPoint animations, where people tend to add white boxes to 'remove' stuff and place images over other images and move content around for the sake of animations, usually overlays are created in a way that you slowly populate the slide step by step. At the end everything has its defined space on that single slide. 
Thus, I believe it would be possible to not only render the past and current overlays but the next n overlays as well with a decreasing opacity as more steps away the content will be.

Thus, instead of looking to the small overlay-slides underneath for the previous (which by the way I never use or need) and the next one, I would be able to see what will be the next 2-3 overlays directly on the main slide of the presenter view. 
I believe that this is much more intuitive and easy on the eyes (sometimes I really have troubles to find the differences between the main slide view and the next overlay slide view resp. to read the text of the next overlay) .
The idea came to my mind, as I caught myself recently using the freeze function to jump 2-3 overlays or even slides forth and back, to get a quick idea of the details of what is coming next during the lecture.

Attached you can find a very first mock up how it could look like. Maybe it needs more clear separation of what is preview and what is on the presentation screen already. Maybe one could simply switch this feature on and off by a key-binding.
  
![overlay_preview_mockup](https://user-images.githubusercontent.com/2484912/51715102-b1376b00-2037-11e9-9cb1-7a515dac0ebb.png)

**Comment by fnevgeny** [comment]
> instead of looking to the small overlay-slides underneath for the previous (which by the way I never use or need)

Me too, I admit.

> and the next one, I would be able to see what will be the next 2-3 overlays directly on the main slide of the presenter view.

BTW, if you don't mind that your audience  sees this "preview" as well, the `\setbeamercovered{dynamic}` beamer option will do this exactly.
