### ISSUE TITLE
execute external scripts 

### ISSUE THREAD

**Issue by torwag** [pdfpc/pdfpc#431]
I know feature request can only work if people work on it and I do a lot of request ;)

In some settings, I switch between pdfpc and other programs forth and back. Thus, sometimes I have to constantly switch the display mode from a two-screen settings to a mirroring mode.
Finally, I believe that an external script could help me here to switch between these two modes and that this script should be managed by the window manager (i3). 
However, I was wondering would there be an interest/need to be able trigger external scripts from within pdfpc? The point here, is the fact that usually pdfpc is working in full screen mode and therefore it would be nice to be able to bind a script/scripts to pdfpc hotkeys thus, that one can trigger actions without leaving pdfpc. 

Use cases:

1. Ask your favorite screen grapper to save a screenshot, resp. start or stop screen casting
2. Trigger external web APIs e.g. to initiate a class room online question during lecture
3. Play some audio in the background
4. Refresh or trigger a certain web page (e.g. for the mentioned auxiliary screen)
5. Dim the lights ;)

I know that all this can be done, or should be better done, from within the window-manager. The benefit of having pdfpc starting scripts would be that people can share them easily, as with all those different window managers, there are otherwise many solutions how to do it.

**Comment by AndreasBilke** [comment]
I would favor the option of having this feature in pdfpc. Since (most?) of
these scripts are presentation related it wouldn't make sense to have that
functionality in your desktop environment. Also having that per desktop
environment isn't very portable.

Instead of just having hotkey based scripts it also would be nice if pdfpc
could call scripts automatically (e.g. for slide changes, entering specific
slides etc).

**Comment by torwag** [comment]
Well, I was thinking of a mechanism, how pdfpc events could trigger certain scripts. In python, I would use decorators for that job, not sure how to do that in vala.

**Comment by AndreasBilke** [comment]
I simplified solution was merged with #448
