### ISSUE TITLE
Installs `etc` to `CMAKE_INSTALL_PREFIX`

### ISSUE THREAD

**Issue by paulmenzel** [pdfpc/pdfpc#433]
**Expected Behaviour**

    $ cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib /dev/shm/bee-root/pdfpc/pdfpc-4.3.2-0/source
    $ make
    $ make install DESTDIR=/dev/shm/bee-root/pdfpc/pdfpc-4.3.2-0/image

This should create the directory `etc/` directly under `/dev/shm/bee-root/pdfpc/pdfpc-4.3.2-0/image/`.

**Actual Behaviour**

It is installed under `/dev/shm/bee-root/pdfpc/pdfpc-4.3.2-0/image/usr/`.

pdfpc version: 4.3.2
Used Distribution (GTK version, vala version): 3.24.8

**Comment by fnevgeny** [comment]
README explains:

`cmake -DCMAKE_INSTALL_PREFIX="/usr" -DSYSCONFDIR=/etc ..`

On the other hand, there should be no need for this most of the time. Please try #434.

**Comment by AndreasBilke** [comment]
This should be fixed with #434
