### ISSUE TITLE
Weird behavior with --notes option

### ISSUE THREAD

**Issue by jolars** [pdfpc/pdfpc#435]
I created a pdf presentation with notes from the following simple beamer example:

```latex
\documentclass{beamer}

%\setbeameroption{show notes} un-comment to see the notes

\begin{document}

\begin{frame}

\begin{itemize}
  \item<1-> Eggs
  \item<2-> Plants
    \note[item]<2>{Tell joke about plants.}
    \note[item]<2>{Make it short.}
  \item<3-> Animals
\end{itemize}

\end{frame}

\end{document}
````

Then I ran `pdfpc test.pdf --notes=left` (or right, bottom and top)

**Expected Behaviour**

I expected the program to start and display notes.

**Actual Behaviour**

If I provide `--notes=right` or (left) I get

```
(pdfpc:24784): Gdk-CRITICAL **: 16:40:35.046: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed

(pdfpc:24784): GdkPixbuf-CRITICAL **: 16:40:35.046: gdk_pixbuf_save_to_callbackv: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(pdfpc:24784): Gdk-CRITICAL **: 16:40:35.047: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed

(pdfpc:24784): GdkPixbuf-CRITICAL **: 16:40:35.047: gdk_pixbuf_save_to_callbackv: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Screensaver inhibited

(pdfpc:24784): GdkPixbuf-CRITICAL **: 16:40:35.128: gdk_pixbuf_loader_write: assertion 'buf != NULL' failed
Could not load cached PNG image for slide 0: Unrecognized image file format
```

and the program doesnt' start.

If I instead set `--notes=top` or bottom, the program starts but the display seems to be cut in half, like so:

![image](https://user-images.githubusercontent.com/13087841/57145011-a0c72700-6dc2-11e9-8b40-996f8da18236.png)

**Steps to reproduce**

As outlined above.

pdfpc version: 4.3.2
Used Distribution (GTK version, vala version): gtk3 3.24.8-1ubuntu1, vala 0.44.3
Display Server (X/Wayland): X
HiDPI Setting (yes/no): no

**Comment by AndreasBilke** [comment]
If you use the --notes option, pdfpc assumes the "split notes" version
(i.e. "show notes on second screen" options in latex beamer).

The notes you are using are not supported by pdfpc (and will never be, since
pdfpc can't predict where to find notes slides).

Please try

\setbeameroption{show notes on second screen}

**Comment by timokau** [comment]
Note for others discovering this issue in the future:
- `\setbeameroption{show notes on second screen}` requires `\usepackage{pgfpages}`
- it will display the notes on the right side by default, therefore you need `--notes=right`
