### ISSUE TITLE
Mac integration + video support?

### ISSUE THREAD

**Issue by momovelo** [pdfpc/pdfpc#436]
Hi everyone,
I there a way to have a good integration to mac OSX with the video support? I used the x11 installation, the videos are support but there is a lot of problems with the windows... One appear and not the other, very bad resolution, fullscreen impossible etc.
Thanks!

**Comment by fnevgeny** [comment]
See #386, #423...

**Comment by momovelo** [comment]
Thanks for the quick answer!  So yes #386 refer to this problem. With macport and x11 the videos works but the windows management is very bad. With macport and xquartz, or with Homebrew, the integration is good but the videos doesn't works anymore. But i don't see any way to solve this problem...
Furthermore, in #423 if I try to install pdfpc with Hombrew I don't have this kind of error. I have only:
`MacBook-Pro-de-Jeremy-2:demo jeremymartinon$ /usr/local/bin/pdfpc video-example.pdf`
`Could not acquire DBus bus.`
I've also look on internet about this error but I didn't find anything, sorry.
Thanks again.

**Comment by fnevgeny** [comment]
> Furthermore, in #423 if I try to install pdfpc with Hombrew I don't have this kind of error.

Which version? Note that you didn't fill in the bug report template.

The DBus warning is likely irrelevant.

**Comment by momovelo** [comment]
Sorry again, I'm not a regular user of github. Currently, Homebrew provide the 4.3.0 version.

**Comment by fnevgeny** [comment]
Well, when you submit a new bug report, you should see a template with questions like version, X11 type, etc.

Anyway, the previous discussions stopped because (1) the developers have no access to Mac machines and (2) the feedback from the submitters ceased...

**Comment by momovelo** [comment]
Good to know, thanks.
That's too bad... I don't know if I will be able to find a proper way to run pdfpc on mac but if I find I will let you know ;)
