### ISSUE TITLE
Keep demo presentations updated and distributed with the sources

### ISSUE THREAD

**Issue by fnevgeny** [pdfpc/pdfpc#439]
In fact, perhaps the whole pdfpc.github.io site should be moved to the main pdfpc repository.

**Comment by LecrisUT** [comment]
Would be good to have an alternative homepage like the `pdfpc.github.io` for those who are still not familiar to how GitHub works (admittedly the number of people seem to go down very fast). I remember that I first came to the `pdfpc.github.io` page when looking for a pdf presenter and the first few screenshots sold me.

An update to the site would be better, when anyone finds time for it. I will do some toying around with LaTeX packages and see how `media9`, `movie15` and other similar packages behave, particularly on macOS. I can try and make example tex file including all of the packages and the differences for future examples.

**Comment by fnevgeny** [comment]
> Would be good to have an alternative homepage like the `pdfpc.github.io`

Sure, the idea wasn't to get rid of `pdfpc.github.io`, but rather to have it under the same version control to be always in sync and easier to update on releases.

>  I will do some toying around with LaTeX packages and see how `media9`, `movie15`

`movie15` is officially unmaintained, `media9` solely relies upon flash playback, meaning it will never be supported by `pdfpc`.

**Comment by LecrisUT** [comment]
Are there any alternative packages that are compatible with `pdfpc`? How about beamer's `multimedia`? Any methods to include playback control without using flash?

**Comment by fnevgeny** [comment]
`multimedia` is THE supported package. https://github.com/pdfpc/pdfpc/releases/download/v4.3.0/pdfpc-video-example.zip

**Comment by AndreasBilke** [comment]
You want to switch to the pdfpc/gh-pages branch to maintain the website?

**Comment by fnevgeny** [comment]
No, I was thinking about the master branch, keeping under the docs folder.

**Comment by AndreasBilke** [comment]
I'm a little puzzled if we really want that. I think this would result in
"broken urls" for people linking to the current site.

https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages

They write, we need to delete the pdfpc.github.io repository (fine, no
problem) BUT

https://help.github.com/en/articles/user-organization-and-project-pages

says that we would (if its a doc/ in pdfpc/master) get a url of
https://pdfpc.github.io/pdfpc

Since we have no control over https://pdfpc.github.io/ we cannot add a
redirection to <..>/pdfpc

Do you also understand it that way?

**Comment by fnevgeny** [comment]
Hmm, strange. It doesn't make sense. It indeed looks like the /docs site will correspond to https://pdfpc.github.io/pdfpc, but then probably the _organization_ site can stay as is (that is, the pdfpc.github.io repository) and so we should be able to make a redirection? We have both the organization and project names the same, which adds to confusion...

Right now, in https://github.com/pdfpc/pdfpc/settings we have GitHub Pages source: None (disabled). I guess it shouldn't make any damage to enable the /docs source?

**Comment by AndreasBilke** [comment]
On Fri Aug 16, 2019 at 03:51:42PM -0700, Evgeny Stambulchik wrote:
> Hmm, strange. It doesn't make sense. It indeed looks like the /docs site
> will correspond to https://pdfpc.github.io/pdfpc, but then probably the
> _organization_ site can stay as is (that is, the pdfpc.github.io
> repository) and so we should be able to make a redirection? We have both
> the organization and project names the same, which adds to confusion...

If I understand it correctly, you can't have both and therefore no control
over `/` redirection.

> Right now, in https://github.com/pdfpc/pdfpc/settings we have GitHub
> Pages source: None (disabled). I guess it shouldn't make any damage to
> enable the /docs source?

In the worst case we can undo it :)

But something else came into my mind. The docs/ folder in the master branch
is the one that gets published.

Currently the master branch holds the development version of pdfpc, but we
want to publish informations only about the stable version.

To have code and docs/ in sync we must make the master branch our stable
branch and the development must reside in another branch (which I would
have no problem with).

**Comment by fnevgeny** [comment]
> If I understand it correctly, you can't have both and therefore no control over `/` redirection.

Then what would be shown at /?

> But something else came into my mind. The docs/ folder in the master branch is the one that gets published. Currently the master branch holds the development version of pdfpc, but we want to publish informations only about the stable version. To have code and docs/ in sync we must make the master branch our stable branch and the development must reside in another branch (which I would have no problem with).

Fine with me, too.

Irrespective of whether master is stable or development, the dynamic part of the website contents (demo PDF's, html'ized man pages) shouldn't, in principle, be under version control - these files are generated; just as compiled executables. On the other hand, github insists on everything to be under git. How do we solve this? Either using the "assets" for releases (OK for PDF's, but awkward for man pages), or agreeing to use git also for these generated files but committing them only prior to a release. In any case, it isn't an automatic operation, and so we could do as well with `master` remaining the development branch.

Or maybe let's forget about this idea, and only move the demo sources to this git - like the title of this issue says...

**Comment by AndreasBilke** [comment]
Fixed with #449
