### ISSUE TITLE
Images Don't Render In Full Quality

### ISSUE THREAD

**Issue by mrbmi513** [pdfpc/pdfpc#441]
**Expected Behaviour**
Images render in full quality with smooth edges.

**Actual Behaviour**
Images render in low quality with jagged edges. Disabling caching and compression doesn't seem to help.

**Steps to reproduce**

1. Open presentation with `pdfpc -z -c presentation.pdf`
2. Open a slide with an image.

I've noticed this with PNG and JPG images.

pdfpc version: 4.1 (from Ubuntu repos)
Used Distribution (GTK version, vala version): Ubuntu 18.04.2/GNOME 3.28.2
Display Server (X/Wayland): X
HiDPI Setting (yes/no): no

**Comment by fnevgeny** [comment]
It was fixed soon after the 4.1 release. Please see #344.

**Comment by mrbmi513** [comment]
Thanks for the info. Built from source and it works perfectly.
