### ISSUE TITLE
Save pen annotations compatible with xournal++

### ISSUE THREAD

**Issue by wallento** [pdfpc/pdfpc#442]
Saving the drawings is an important feature that is missing. xournal++ seems to work well in this respect and they currently work on a new file format that contains the PDF along with annotations. Shouldn't it be possible to use the xournal++ subsystem as both pdfpc and xornal++ use similar basic libraries?

**Comment by fnevgeny** [comment]
I really don't understand the value of such a feature. xournal is something different, it _is_ intended to modify outlook of existing, third-party PDF documents (directly or not is irrelevant for this discussion). On the other hand, annotations in pdfpc are transient by nature: they serve as a tool to highlight/clarify something that (a member of) a given audience finds unclear. If you believe something should be altered in your presentation permanently, go ahead and modify it with the original authoring software it was created with...

**Comment by wallento** [comment]
It is an important feature to me and my colleagues in teaching. It allows us to develop a problem along the slides, note clarifications etc. Of course I can do it in post processing or keep alternative slide decks, but whats the point. It is very convenient and keeps many people in teaching from actually moving from Powerpoint.

@AndreasBilke So, you agree that this is useless and not a feature intended or why close?

**Comment by fnevgeny** [comment]
So what's missing in xournal for you? Support for dual screens?

**Comment by wallento** [comment]
The entire functionality of pdfpc. I think as a first step the most awesome solution would be to have the xournal++ annotation logic in the slide view, including the ability to save them. That is why I asked in this particular direction. I am not sure about the technical complexity and have just started to look into it.

**Comment by fnevgeny** [comment]
> I think as a first step the most awesome solution would be to have the xournal++ annotation logic in the slide view, including the ability to save them

I am not sure you realize it, but even that "first step" means:

- Xournal devs publish a standard for their format
- Somebody (in all the likelihood xournal folks as well) make a reusable library implementing the relevant API, with provisions for backward compatibility etc
- Somebody writes a Vala binding to the above API
- Somebody modifies pdfpc to use the above with the required glue calls _and_ writes the appropriate GUI code.

Each "somebody" should have a sufficiently strong incentive for doing the work. And at least for the first three items in the list you should not expected to easily find volunteers on the pdfpc side...

In fact, it is not quite clear what you mean by "to have the xournal++ annotation logic in the slide view". Just to display the slides produced with xournal? Or modify them on the fly as you do in xournal itself? If the latter, how is it different from the full xournal functionality? If the former, just export the slides in the PDF format.

**Comment by AndreasBilke** [comment]
I think pdfpc is a presentation tool and not a pdf drawer. This functionality of that issue has (for me) nothing to do with the purpose of pdfpc.

I agree with evgeny, that the current drawing support is for volatile information during a talk.

**Comment by wallento** [comment]
@fnevgeny I was actually thinking of looking into it myself if nobody else sees the need and wants to volunteer. I just wanted to propose it and try to get a better estimate about complexities I should anticipate and the chances of getting a PR accepted. It seems to me I don't really need to think about the first when the second is not the case. So I will better look into how to solve it with another flow or other tools that may become useful for my problem. Thanks for your suggestions.

@AndreasBilke thanks for the clarification. I will look into better options then, maybe extend xournal++ to have the pdfpc functionality then.

**Comment by fnevgeny** [comment]
> I just wanted to propose it and try to get a better estimate about complexities I should anticipate and the chances of getting a PR accepted. It seems to me I don't really need to think about the first when the second is not the case.

For the first, see my reply with the list of work items to do. For the second, I don't see how you drew this conclusion. There was nothing in your original post hinting that you intend to implement it yourself. When you have a PR, please feel free to reopen the issue.
