### ISSUE TITLE
Build errors: error: Creation method of abstract class cannot be public.

### ISSUE THREAD

**Issue by sanjayankur31** [pdfpc/pdfpc#445]
**Expected Behaviour**
Should build correctly.

**Actual Behaviour**
Does not currently build.

**Steps to reproduce**

1. Attempt to build on Fedora rawhide (f31)
2. .

pdfpc version: 4.3.4

Used Distribution (GTK version, vala version):

Fedora 31:

```
-- Found Vala: /usr/bin/valac (found suitable version "0.45.3", minimum required is "0.34") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
-- Checking for module 'gobject-2.0'
--   Found gobject-2.0, version 2.61.1
-- Checking for module 'gio-2.0'
--   Found gio-2.0, version 2.61.1
-- Checking for module 'gee-0.8'
--   Found gee-0.8, version 0.20.1
-- Checking for module 'poppler-glib>=0.22'
--   Found poppler-glib, version 0.73.0
-- Checking for module 'gtk+-3.0>=3.22'
--   Found gtk+-3.0, version 3.24.10
-- GTK is compiled with X11 -- enabling X11 support
-- Checking for module 'x11'
--   Found x11, version 1.6.8
-- Checking for module 'gthread-2.0'
--   Found gthread-2.0, version 2.61.1
-- Checking for module 'pangocairo'
--   Found pangocairo, version 1.43.0
-- Checking for module 'gstreamer-1.0'
--   Found gstreamer-1.0, version 1.16.0
-- Checking for module 'gstreamer-base-1.0'
--   Found gstreamer-base-1.0, version 1.16.0
-- Checking for module 'gstreamer-audio-1.0'
--   Found gstreamer-audio-1.0, version 1.16.0
-- Checking for module 'gstreamer-video-1.0'
--   Found gstreamer-video-1.0, version 1.16.0
```

Full build log is attached:
[tmpvadqqrx0_build.txt](https://github.com/pdfpc/pdfpc/files/3458029/tmpvadqqrx0_build.txt)

Failed build link:
https://koji.fedoraproject.org/koji/taskinfo?taskID=36636754

Downstream Fedora bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1736412

**Comment by fnevgeny** [comment]
Please test #446.

**Comment by fnevgeny** [comment]
@sanjayankur31: BTW, I noticed that Fedora doesn't provide the cairo[-overlay] gstreamer plugin - [apparently, since 2014](https://src.fedoraproject.org/rpms/gstreamer1-plugins-good/blob/master/f/gstreamer1-plugins-good.spec). Without it, the video controls in pdfpc will be absent. Please consider filing a Fedora bugreport.

**Comment by sanjayankur31** [comment]
Thanks for the quick fix. I'll test it out soon. I've also filed a bug for the missing cairo-overlay plugin bits:

https://bugzilla.redhat.com/show_bug.cgi?id=1737254

**Comment by sanjayankur31** [comment]
Works, built for F31 now.
