### ISSUE TITLE
Pressure-sensitive drawing

### ISSUE THREAD

**Issue by jolars** [pdfpc/pdfpc#450]
pdfpc v 4.3.4

I am using a tablet to draw on presentations and it would be great if pdfpc would support pen pressure when drawing. In addition, I believe that it should be possible to improve resolutions of drawings.

**Comment by jolars** [comment]
There is an example here: https://www.gtk.org/tutorial1.2/gtk_tut-23.html#ss23.4 that uses XInput to enable pressure and subpixel drawings and more, but it's for gtk1.2 so I don't know if it applies anymore.

**Comment by fnevgeny** [comment]
Without an appropriate hardware it would be both problematic and lacking incentive for developers to deal with it. Consider a birthday present :).

**Comment by fnevgeny** [comment]
What do you have in mind, BTW, by using the pressure? Alter the width of the line? Opacity? Color? :)
> In addition, I believe that it should be possible to improve resolutions of drawings.

I believe it's unrelated.

**Comment by jolars** [comment]
> What do you have in mind, BTW, by using the pressure? Alter the width of the line? Opacity? Color? :)

Primarily width of line, but maybe also opacity in the sen of anti-aliasing (or sub-pixel rendering, I'm not really sure about the difference).

> I believe it's unrelated.

Okay, but perhaps anti-aliasing would at least make it *seem* more clear.

I noticed that there is a newer version of the docs for gtk2 [here](https://developer.gnome.org/gtk-tutorial/stable/x2529.html) by the way.

**Comment by fnevgeny** [comment]
> Okay, but perhaps anti-aliasing would at least make it _seem_ more clear.

This is again unrelated to the type of the input device, IMO. To make drawing smooth, a kind of smoothing/interpolation should be implemented, likely in the form of Bézier curves.

> I noticed that there is a newer version of the docs for gtk2 [here](https://developer.gnome.org/gtk-tutorial/stable/x2529.html) by the way.

Gtk2 is long in the past, too... Anyway, it's not about finding a relevant API, but finding a hardware. Fortunately, I discovered that my new touch-screen laptop actually can work with an optional active pen, and that arrived last week. Gave up on waiting for the birthday gift, you see :).

**Comment by fnevgeny** [comment]
@jolars give this pull request a try, please. #461

**Comment by jolars** [comment]
Fantastic! Will do when I get back to work next week.

**Comment by jolars** [comment]
I just tested this out and it works great. Thanks for implementing this @fnevgeny !

**Comment by jbrea** [comment]
@jolars I am curious about your setup. Would you mind sharing with me how you connect the tablet to write on the presentation?

I also started using a tablet to draw on slides with pdfpc. Currently I use x11vnc to connect the android tablet to my linux machine, but this is not 100% satisfactory, because of the slight lag of vnc and I don't see pressure-sensitivity.

(@fnevgeny pdfpc is a fantastic tool; I use it a lot and since quite a while. Many thanks!)

**Comment by jolars** [comment]
> @jolars I am curious about your setup. Would you mind sharing with me how you connect the tablet to write on the presentation?
> 
> I also started using a tablet to draw on slides with pdfpc. Currently I use x11vnc to connect the android tablet to my linux machine, but this is not 100% satisfactory, because of the slight lag of vnc and I don't see pressure-sensitivity.
> 
> (@fnevgeny pdfpc is a fantastic tool; I use it a lot and since quite a while. Many thanks!)

Ah, maybe I've should've been more specific when I said "tablet". I am actually using a wacom pen tablet and not an android tablet.

**Comment by jbrea** [comment]
Ah, I see :) Thanks.

**Comment by fnevgeny** [comment]
As a side note, using a smartphone to fully control presentation has been my dream for a long time... (even before I came across pdfpc).
