### ISSUE TITLE
Building on Mint / documentation problem

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pdfpc/pdfpc#452]
It seems that on Linux Mint 19.2 one needs to do

`sudo apt install gtk+-3.0`

as well as to install the other dependencies that you mention, Else one gets this error upon compiling:

```
--   No package 'gtk+-3.0' found
CMake Error at /usr/local/share/cmake-3.11/Modules/FindPkgConfig.cmake:418 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.11/Modules/FindPkgConfig.cmake:585 (_pkg_check_modules_internal)
  src/CMakeLists.txt:6 (pkg_check_modules)
```
It semes one needs to install the following packages too (though possibly my install had them originally):

gstreamer-1.0

pdfpc version: current website version
Used Distribution (GTK version, vala version): Mint 19.3
Display Server (X/Wayland): X
HiDPI Setting (yes/no): yes

**Comment by LinuxOnTheDesktop** [comment]
Also:
```
[. . .]
--   No package 'gstreamer-1.0' found
CMake Error at /usr/local/share/cmake-3.11/Modules/FindPkgConfig.cmake:418 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.11/Modules/FindPkgConfig.cmake:585 (_pkg_check_modules_internal)
  src/CMakeLists.txt:18 (pkg_check_modules)
-- Configuring incomplete, errors occurred!
$ sudo apt install gstreamer
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gstreamer
~/NJ/office/pdf-presenter-console/pdfpc-4.3.4/build $ sudo apt install gstreamer-1.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'gir1.2-gstreamer-1.0' for regex 'gstreamer-1.0'
Note, selecting 'libqt5gstreamer-1.0-0' for regex 'gstreamer-1.0'
libqt5gstreamer-1.0-0 is already the newest version (1.2.0-5).
gir1.2-gstreamer-1.0 is already the newest version (1.14.5-0ubuntu1~18.04.1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

**Comment by einhander** [comment]
Hi,
Install *-dev packages according your distribution manual and error messages
For ex. gstreamer-1.0-dev as described in error message.



вс, 13 окт. 2019 г., 5:32 LinuxOnTheDesktop <notifications@github.com>:

**Comment by LinuxOnTheDesktop** [comment]
It seems to me that the error messages and your instructions are a poor guide to what I needed to install. The latter included:

- libgstreamer1.0-dev
- libgstreamer-plugins-base1.0-dev (which brought its own dependencies with it).

Cf. [this existing bug report of yours](https://github.com/pdfpc/pdfpc/issues/78). That report was closed on the basis that the problem is not your problem. Yet, there does seem to be a problem with your documentation here.

**Comment by fnevgeny** [comment]
> It seems to me that the error messages and your instructions are a poor guide to what I needed to install. The latter included:
> 
>     * libgstreamer1.0-dev
> 
>     * libgstreamer-plugins-base1.0-dev (which brought its own dependencies with it).

Did you actually read the README file? These packages **are** listed.

**Comment by LinuxOnTheDesktop** [comment]
The ReadMe does have

sudo apt-get install cmake valac libgee-0.8-dev libpoppler-glib-dev
libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
gstreamer1.0-gtk3

I am sure I ran that command before I attempted to install the software and, thus, before I had problems. Yet, installing two of those packages seemed to solve the problems . . I don't know what happened. I am sorry.
