### ISSUE TITLE
Presentation goes black after switching display mode on Mac OS

### ISSUE THREAD

**Issue by maeln** [pdfpc/pdfpc#455]
**Expected Behaviour**
On Mac OS, after switching back and forth between separate display mode and clone display mode (CMD+F1), the presentation window and the presenter window should display their content normally.

**Actual Behaviour**
After switching to clone display mode and back again to separate display, the window that is on the external display (usually the presentation) only display a black window. 
Forcing the refresh of the window through minimizing and then maximizing the window solve the issue.

**Steps to reproduce**

1. Open a presentation with pdfpc with the presentation on a separate screen and the presenter window on the main screen
2. Switch (via CMD+F1) to clone screen mode
3. Switch back to separate display mode (CMD+F1)
4. Presentation window should now just display black

**Notes**
This is a bug I personally encountered with my own software on Mac OS. The usual issue is that switching screen mode change the dpi/internal resolution and lose the current framebuffer. One way to solve the issue is usually to listen to any dpi changed event or window resize event and force a framebuffer refresh when that happen. But I am not familiar enough with PDFPC's code or GTK to know how to solve this issue.

pdfpc version: v3.4..4
Used Distribution (GTK version, vala version): ? / Mac OS 10.14.6
Display Server (X/Wayland): ?
HiDPI Setting (yes/no): Yes

**Comment by maeln** [comment]
As a side note: Trying to use the shortcut 'b' or switching the slides or resetting the presentation does not fix it. Only forcing a redraw of the whole window via the OS does the job.

**Comment by fnevgeny** [comment]
Please try the current branch. There have been changes related to monitor events.

**Comment by maeln** [comment]
Tried with the lastest `master` revision and indeed it work like a charm :) .

**Comment by fnevgeny** [comment]
Great to know. I have MacOS only in a VM, and there is no support for dual displays :).
