### ISSUE TITLE
Can’t start presentation with a changed page size

### ISSUE THREAD

**Issue by sssalkr** [pdfpc/pdfpc#456]
**Expected Behaviour**
Regular start of presentation mode
**Actual Behaviour**
Error: 

`pdfpc --notes=right Test.pdf`
`--notes option detected. Disable auto grouping.`
`(pdfpc:22079): Gdk-CRITICAL **: 16:49:03.480: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed`
`(pdfpc:22079): GdkPixbuf-CRITICAL **: 16:49:03.480: gdk_pixbuf_save_to_callbackv: assertion 'GDK_IS_PIXBUF (pixbuf)' failed`
`(pdfpc:22079): Gdk-CRITICAL **: 16:49:03.481: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed`
`(pdfpc:22079): GdkPixbuf-CRITICAL **: 16:49:03.481: gdk_pixbuf_save_to_callbackv: assertion 'GDK_IS_PIXBUF (pixbuf)' failed`
`Screensaver inhibited`
`(pdfpc:22079): GdkPixbuf-CRITICAL **: 16:49:03.552: gdk_pixbuf_loader_write: assertion 'buf != NULL' failed`
`Could not load cached PNG image for slide 0: Format der Bilddatei unbekannt`

**Steps to reproduce**

1. Compile this Latex-Code

`\documentclass{beamer}`
`\usepackage{babel}`
`\usepackage[utf8]{inputenc}`
`\usepackage[T1]{fontenc}`
`\usepackage{lmodern}`
`\geometry{paperwidth=24cm,paperheight=18cm}`
`\usepackage{pgfpages}`
`\setbeameroption{show notes on second screen=right}`
`\begin{document}`
`\begin{frame}`
`Test`
`\end{frame}`
`\begin{frame}`
`Frame 2`
`\end{frame}`
`\begin{frame}`
`3`
`\end{frame}`
`\end{document}`

2. `pdfpc --notes=right Test.pdf`

pdfpc version:
Used Distribution (GTK version, vala version):
Display Server (X/Wayland):
HiDPI Setting (yes/no):

**Comment by AndreasBilke** [comment]
I experience the same with the current released version. But using the
current master version I don't have that issue. Can you confirm it?

**Comment by sssalkr** [comment]
I tried the compilation from sources guide instead of the version I can get via synaptic. So it's v4.3.4 from June 20th. With the same result

`BAD status: invalid matrix (not invertible)
BAD status: invalid matrix (not invertible)

(pdfpc:21585): Gdk-CRITICAL **: 20:37:33.876: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed

(pdfpc:21585): GdkPixbuf-CRITICAL **: 20:37:33.876: gdk_pixbuf_save_to_callbackv: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
BAD status: invalid matrix (not invertible)
BAD status: invalid matrix (not invertible)

(pdfpc:21585): Gdk-CRITICAL **: 20:37:34.284: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed

(pdfpc:21585): GdkPixbuf-CRITICAL **: 20:37:34.284: gdk_pixbuf_save_to_callbackv: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Screensaver inhibited

(pdfpc:21585): GdkPixbuf-CRITICAL **: 20:37:34.952: gdk_pixbuf_loader_write: assertion 'buf != NULL' failed
Could not load cached PNG image for slide 0: Format der Bilddatei unbekannt
`

**Comment by fnevgeny** [comment]
> Yes, can confirm that

Can we close it then? Or, @AndreasBilke , do you intend to fix it also in the 4.3 branch?

**Comment by AndreasBilke** [comment]
> Can we close it then? Or, @AndreasBilke , do you intend to fix it also in the 4.3 branch?

No :)
