### ISSUE TITLE
Single-file xxx.pdfpc format

### ISSUE THREAD

**Issue by jdpipe** [pdfpc/pdfpc#457]
I suggest that pdfpc be extended to support opening pdf and zip files directly, via a file association with the .pdfpc suffix. 

For zip files, this could be easily achieved by making use of libzip and adding some abstractions to your file-reading operations, or could be implemented using fuse-zip to mount the zip file in userspace. Neither would be very difficult to do. There could be performance implications for video playback, potentially, but I suspect not. The zip file would then just be treated as a PDF file sitting within a directory, as in the current implementation.

This would have the advantage that any .pdf file that one wanted to set up for easy access through pdfpc would simply need to have its extension changed. Any PDF with associated attachments (embedded videa, metadata/configuration files, etc) could be zipped up in a defined way and then opened directly via file association. The advantage of this is that one would be able to 'set up' a presentation on a new machine by simply copying a single file with a defined file suffix.

I have proposed pdfpc to be used at a conference that I am involved with, but so far I think that some of the challenges with the file format will be seen as a barrier to adoption. Hence my suggestion.

**Comment by jdpipe** [comment]
Good comment. The ideal path would be to implement support for whatever the standard PDF way of embedding video might be.

Having said that, PDFPC already exists, and supports a directory structure for associating video with a PDF file. It would be a relatively trivial extension to allow a zip-file to be used as the source of the directory structure, instead of a live directory. This would make it easier for people giving presentations to copy whatever is needed onto the presentation machine, and easier to keep presentations organised, etc.

Here is a Latex package that handles embedding of video in Latex-generated PDFs:
http://texdoc.net/texmf-dist/doc/latex/media9/media9.pdf

On the other hand, not all PDF generators support video embedding, so an alternative way may be useful/appreciated by some users.
https://ask.libreoffice.org/en/question/166982/how-do-i-create-a-pdf-in-libreoffice-with-an-embedded-video/
https://bugs.documentfoundation.org/show_bug.cgi?id=46624

**Comment by fnevgeny** [comment]
Media9 playback is based on the flash player. No chance it will ever be supported in pdfpc. But video embedding (PDF attachments) are supported by other packages.

Back to the original request, I really don't like it. Applications that use a zip format to combine components (LibreOffice etc) are those that do create the whole contents. pdfpc is not a PDF creator, so why should we do it? zip or similar archiving utilities are freely available for any platform.

> I have proposed pdfpc to be used at a conference that I am involved with, but so far I think that some of the challenges with the file format will be seen as a barrier to adoption. Hence my suggestion.

I don't see this as a barrier to the world domination. Not at this moment... What are these "challenges with the file format" anyway?

**Comment by AndreasBilke** [comment]
> Having said that, PDFPC already exists, and supports a directory structure for associating video with a PDF file. It seems like it would be a relatively trivial extension to allow a zip-file to be used as the source of the directory structure, instead of a live directory.

I would argue that packing everything in some (kind of) proprietary zip-file you loose all the benefits of having standard file formats.

E.g. PDFs can be viewed with many different applications, video files as well.

Let's imaging that you have software troubles during presentation (*even* pdfpc is not perfect) you can switch to some other tool and still go on with your talk.
