### ISSUE TITLE
Improvements to pointer mode

### ISSUE THREAD

**Issue by mayanksuman** [pdfpc/pdfpc#458]
`POINTER` mode is helpful but relatively limited when compared to modern presenter tools (Logitech Spotlight). I think following improvement in the mode will be nice.

 1. The pointer should disappear (without leaving `POINTER` mode) after left idle for sometime or when slide is changed (and reappear as soon as the mouse moves).
 2. `POINTER` mode can have three sub-modes (regular pointer (current option), spotlight and zoom lens. In spotlight sub-mode, the whole of screen except a circular zone centered at cursor is darkened. In zoomed lens sub-mode, the circular zone centered at cursor is zoomed out. Needless to say, the spotlight and zoom lens move with mouse movement.
3. The spotlight and zoomed lens should stop as soon as user stop moving the mouse.
4. The sub-mode can be cycled by double click in `POINTER` mode.

The first feature is consistent with use of presenter: pointer do not remain at slide if it is not being used.
 
The last 3 features are inspired by logitech spotlight. These features request if implemented will solve #414 also.

**Comment by AndreasBilke** [comment]
Will you be able helping implementing this?

**Comment by mayanksuman** [comment]
I can try when I have free time.

**Comment by jspitz** [comment]
As for the spotlight mode, you could also check how [Impressive](https://sourceforge.net/projects/impressive/) does it (it has quite a usable spotlight mode). Maybe also the "highlight boxes" and "zoom box" mode of Impressive are worth consideration.

**Comment by AndreasBilke** [comment]
Point 1 and 3 are handled in #480. Zooming Lense (Point 2) is handled in #419 

Spotlight Lense can be done within the pointing mode. Just switch to pointing mode and drag a rectangular shape on the screen.

**Comment by jspitz** [comment]
> Spotlight Lense can be done within the pointing mode. Just switch to pointing mode and drag a rectangular shape on the screen.

But this shape is (1) rectangular and (2) does not move with the mouse. This is not what is meant here with "spotlight lense"

**Comment by fnevgeny** [comment]
Re: the zooming lens mode (moving with the pointer), I personally do not like it. I was at lectures ones or twice where this feature was used, and it was really annoying. I wonder if someone in the auditorium ever enjoys it... The static zoom (selecting a specific area, usually a graph, to increase its readability) is a different story. The spotlight mode perhaps has right to exist...

**Comment by jspitz** [comment]
Note that I have note talked about moving zooming lense, but moving spotlight.

**Comment by fnevgeny** [comment]
@jspitz Indeed. In your reply, you quoted  a text containing "lens", which confused me. I guess it's better to open a separate issue to avoid confusion.

**Comment by jspitz** [comment]
> I guess it's better to open a separate issue to avoid confusion.

Done #484.
