### ISSUE TITLE
pdfpc sees one display instead of two

### ISSUE THREAD

**Issue by jackhill** [pdfpc/pdfpc#459]
Hi,

I'm running pdfpc 4.3.4 on GNU Guix with GNOME 3.30 under X. pdfpc see one big display instead of my laptop monitor and external monitor connected over VGA. This causes the fullscreen windows to the the wrong size. Both the presenter console and audience slide view are as wide as both monitors. In addition to a fix, I'd also be interested in knowing if there is a workaround. Let me know if I can provide additional information.

```
$ pdfpc -M
Monitors: 1
 0: * (null) 	[3200x1080+0+0@0Hz 	scale=100%]
$ xrandr
Screen 0: minimum 320 x 200, current 3200 x 1080, maximum 8192 x 8192
LVDS-1 connected primary 1280x800+0+0 (normal left inverted right x axis y axis) 261mm x 163mm
   1280x800      60.00*+  59.99    59.97    59.81    59.91  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
VGA-1 connected 1920x1080+1280+0 (normal left inverted right x axis y axis) 475mm x 267mm
   1920x1080     60.00*+
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis
```

**Comment by fnevgeny** [comment]
> ```
> $ pdfpc -M
> Monitors: 1
>  0: * (null) 	[3200x1080+0+0@0Hz 	scale=100%]
> $ xrandr
> Screen 0: minimum 320 x 200, current 3200 x 1080, maximum 8192 x 8192

Well, xrandr sees your two monitors as a single screen, and that's what pdfpc uses. Did you enable the xinerama extension by chance? Propriety ATI/AMD drivers in use?

**Comment by jackhill** [comment]
Oh good catch. I'm using the integrated intel graphics adaptor with the free drivers. This is how GNOME configured the displays using the "join display" option. If I instead configure them from xrandr on the command line `xrandr --output VGA-1 --auto --right-of LVDS-1` it is still one X screen.

Is there a way to make this work without modifying xorg.conf? If not, then I guess this is a feature request. I wonder if there is a different API we could use to look up the screen demensions.

**Comment by AndreasBilke** [comment]
> Is there a way to make this work without modifying xorg.conf? If not, then I guess this is a feature request. I wonder if there is a different API we could use to look up the screen demensions.

Is there a reason why you use the "join display" option? Disabling that should result in a two monitor setup which pdfpc can handle appropriate.

pdfpcs fundamental design decision is having two distinct display/monitors and each of it shows one pdfpc window. Supporting your setup would require a lot of work.

**Comment by jackhill** [comment]
> Is there a reason why you use the "join display" option? Disabling that should result in a two monitor setup which pdfpc can handle appropriate.

With GNOME 3.30 on X with GNU Guix, the three options are `Join Displays`, `Mirror`, and `Single Display`. `Join Displays` is the only option that offers mee the set up that I want: showing different things on my laptop display and an external monitor/projector. GNOME is able to correctly identify displays by number for matching them up with the icons in the configuration wizard. I'll note that even without GNOME, using an .xsession script that launches XMonad, I use `xrandr --output VGA-1 --auto --right-of LVDS-1` to configure the displays, and that results in one X screen as well.

> pdfpcs fundamental design decision is having two distinct display/monitors and each of it shows one pdfpc window. Supporting your setup would require a lot of work.

Noted. The way I'm managing outputs is really the most convienent for me. I assumed that this was how others were doing it as well, but I'm curious to hear how others are doing it. The only way that I know how to create separate X screens is to modify xorg.conf and restart the server. Is there an easier way?

It does look like when running GNOME on Wayland and using the `Join Displays` option that XWayland sees two screens and pdfpc interprets that correctly. Unfortunately, Guix doesn't support GNOME on Wayland yet, but perhaps there is hope for the future that this issue will become irrelevant ☺.

**Comment by fnevgeny** [comment]
Sorry for misleading. `Screen 0: minimum 320 x 200, current 3200 x 1080, maximum 8192 x 8192` is actually normal, I see a similar geometry. However, pdfpc works fine in dual-screen setup for me (and shows two monitors in the `-M` output). Checked both Wayland and X11. It's Ubuntu-19.04 (Gnome 3.32.1). It's an HDMI external monitor, not VGA as in your case, though. Can you test with HDMI?

**Comment by fnevgeny** [comment]
PS. Just to make sure - does "full screen" mode work correctly for other Gtk apps, e.g. Firefox (press F11), evince (F5), etc?

**Comment by jackhill** [comment]
I don't have have HDMI hardware, so I'm afraid that I can't test there, but that's probably not that important because I tested on my VGA hardware with Ubuntu 19.10 and X, and pdfpc sees both monitors and works correctly. Therefore, it seems like it is a problem in the Guix package, but I'm sure what.

Thanks for your help and patience.

**Comment by fnevgeny** [comment]
@jackhill Can you check the FF/evince full-screen mode? If these don't work correctly, too, that must be a high-profile bug in Guix.

**Comment by jackhill** [comment]
> @jackhill Can you check the FF/evince full-screen mode? If these don't work correctly, too, that must be a high-profile bug in Guix

@fnevgeny I did jeck that, but forgot to mention it. yes, those work correctly.

**Comment by fnevgeny** [comment]
Hmm, interesting. Which Vala version is in Guix?

**Comment by jackhill** [comment]
0.44.5

I'm currently looking into whether the issue is similar to https://issues.guix.gnu.org/issue/38163 (GDK not returning the correct refresh rate).

**Comment by fnevgeny** [comment]
Very probably, it is related - good catch. If xrandr is compiled out, all related information would be unavailable.

**Comment by jackhill** [comment]
Indeed. When running pdfpc from the "staging" branch with the fix, it sees multiple monitors and works correctly. Since this is a bug in Guix (hopefully to be fixed soon) and not in pdfpc, I'm going to close this issue. Sorry for the noise, and thanks for troubleshooting with me!
