### ISSUE TITLE
Mention that switch-screens and single-screen can be combined

### ISSUE THREAD

**Issue by lemmy** [pdfpc/pdfpc#460]
The manual page may mention that the ```--switch-screens``` and ```--single-screens``` can be combined to show the presentation screen instead of the presenter screen on a single monitor setup.

By the way, thanks for pdfpc.

**Comment by AndreasBilke** [comment]
I prefer to mention only eliminating combinations of command line options. If you document "acceptable" combinations, then you need to make a complete list of it.

@fnevgeny what is your opinion?

**Comment by fnevgeny** [comment]
The master branch doesn't require this combination - `-s|--switch-screens` along should suffice.

**Comment by AndreasBilke** [comment]
Then in any case this doc section is not needed.
