### ISSUE TITLE
Small strip in presentation view

### ISSUE THREAD

**Issue by real-or-random** [pdfpc/pdfpc#462]
**Expected Behaviour**
presentation view covers entire screen

**Actual Behaviour**
The "window" (without decoration) misses to cover a small strip of the screen. There I see just what has been rendered before I started pdfpc

![Screenshot from 2019-11-17 16-11-40](https://user-images.githubusercontent.com/1071625/69009397-18226980-0955-11ea-9aea-9914bdf69439.png)
The strip always appears on the side facing the presenter view. If the left screen shows presenter view and the right screen shows the presentation view, then the strip will appear on the left-hand side of the right screen. If I position the screen differently, the strip changes.

In fact, I get some visual distortion even with `-S`. Then I get the presenter view on the left screen, and the right screen remains blank (desktop background) but there "strip" again that distorts the background there. The distortion is an offset to the top, see here:
![Screenshot from 2019-11-17 16-12-23](https://user-images.githubusercontent.com/1071625/69009402-207aa480-0955-11ea-9600-82e89c667348.png)

So I guess that in fact the presenter window is too large. When I change the focus to the presentation view, then this window is fine but then a "dual" issue occurs in the presenter view:
![Screenshot from 2019-11-17 16-17-28](https://user-images.githubusercontent.com/1071625/69009489-d3e39900-0955-11ea-82b9-4cb55ad2507f.png)

pdfpc version: 4.3.4
Used Distribution (GTK version, vala version): Arch Linux, gtk 3.24.12, Cinnamon 4.2.4
Display Server (X/Wayland): Xorg
HiDPI Setting (yes/no): no

**Comment by fnevgeny** [comment]
Please try the master branch - is the problem still there?

**Comment by real-or-random** [comment]
It's still there on master.

**Comment by real-or-random** [comment]
This is related to window decorations. 

After reading https://unix.stackexchange.com/questions/52565/how-to-disable-window-decorations-in-cinnamon, I created the following devielspie2 config in `$HOME/.config/devilspie2/pdfpc.lua`:
```
if (get_application_name() == "pdfpc") then
    undecorate_window();
end
```

Then the issue is gone.

**Comment by fnevgeny** [comment]
Good catch. I would expect, though, that window managers disable decorations for full-screen windows by default. Do you need to place similar workarounds for other applications in the full-screen mode (firefox, evince, vlc,...)?

Can you try adding  `this.set_decorated(false);` just after `this.move(monitor_geometry.x, monitor_geometry.y);` in src/classes/window/fullscreen.vala?

**Comment by fnevgeny** [comment]
https://specifications.freedesktop.org/wm-spec/wm-spec-1.4.html says:

> _NET_WM_STATE_FULLSCREEN indicates that the window should fill the entire screen and have no window decorations. Additionally the Window Manager is responsible for restoring the original geometry after a switch from fullscreen back to normal window. For example, a presentation program would use this hint.

I checked and `fullscreen_on_monitor()` does set this atom. So not sure why Cinnamon ignores it...

**Comment by real-or-random** [comment]
> Can you try adding `this.set_decorated(false);` just after `this.move(monitor_geometry.x, monitor_geometry.y);` in src/classes/window/fullscreen.vala?

That fixes the issue but now both windows appear on the second screen, and none on the first one. (I can drag the presenter window back however manually...).

> https://specifications.freedesktop.org/wm-spec/wm-spec-1.4.html says:
> 
> > _NET_WM_STATE_FULLSCREEN indicates that the window should fill the entire screen and have no window decorations. Additionally the Window Manager is responsible for restoring the original geometry after a switch from fullscreen back to normal window. For example, a presentation program would use this hint.
> 
> I checked and `fullscreen_on_monitor()` does set this atom. So not sure why Cinnamon ignores it...

Hm no idea. I googled a little and found https://github.com/linuxmint/muffin/issues/530 but this is not related. It only appears then window effects are enabled but I disabled them.

I don't need any weird workarounds for other fullscreen applications.

**Comment by fnevgeny** [comment]
> That fixes the issue but now both windows appear on the second screen, and none on the first one. (I can drag the presenter window back however manually...).

Weird... Can you also try replacing `this.fullscreen_on_monitor(...)` with just `this.fullscreen()`?

**Comment by fnevgeny** [comment]
No response for a long time, closing.
