### ISSUE TITLE
Tab does not work with focused presentation view

### ISSUE THREAD

**Issue by real-or-random** [pdfpc/pdfpc#463]
**Steps to reproduce**
1. Start presentation
2. Click on presentation view to focus this windows
3. Press Tab

**Expected Behaviour**
Slide selection appears

**Actual Behaviour**
Nothing

pdfpc version:
Used Distribution (GTK version, vala version):
Display Server (X/Wayland):
HiDPI Setting (yes/no):

**Comment by AndreasBilke** [comment]
Why should you focus the presentation view? And, wouldn't it be counter intuitive if pressing a key in one window would result with an action in another window?

**Comment by real-or-random** [comment]
> Why should you focus the presentation view?

I discovered this as a workaround to #462 but in general I think that this can happen by accident, e.g., when you try to use the laser pointer on the presentation view or by pressing Alt+Tab if you want to switch to a demo and should have pressed H.

> And, wouldn't it be counter intuitive if pressing a key in one window would result with an action in another window?

Hm, I don't think so. I see this as a single application, and it felt counter-intuitive to me that Tab does not work. At least it's inconsistent. Some of the keys work and some don't. For example, Ctrl+O works in both windows but also triggers an action in the presenter view. Ctrl+N works in the presenter view only.

**Comment by AndreasBilke** [comment]
I would prefer to make the keybinding behavior consistent (e.g. removing Ctrl+O in the presentation view) instead of making TAB accessible usable in the presentation. @fnevgeny What are you thinking?

**Comment by fnevgeny** [comment]
The behavior should be consistent, no doubt. I, too, think the presentation window shouldn't react to keyboard and mouse events. In general, the "where is my mouse??" situation should be familiar to anybody working with two displays. We may, however, provide a cue for the user if such an event is detected on the presentation window - e.g., flash the (presenter) view or make a beep. Or (and) move the focus to the presenter window.

There is, however, one case that needs a special consideration: when invoked with `-sS`. Frankly, I don't understand why people are using it (#460) - in this mode pdfpc becomes just another fullscreen PDF viewer, but apparently there is some appeal...

**Comment by real-or-random** [comment]
> The behavior should be consistent, no doubt. I, too, think the presentation window shouldn't react to keyboard and mouse events. In general, the "where is my mouse??" situation should be familiar to anybody working with two displays. We may, however, provide a cue for the user if such an event is detected on the presentation window - e.g., flash the (presenter) view or make a beep. Or (and) move the focus to the presenter window.

I'd still vote for making the keys available in both windows equally. Note that there is no way to detect which fullscreen window has the focus, so I wouldn't want to be lost in the middle of my talk pressing RightArrow like crazy and thinking my machine has frozen because I can't go to the next slide for some reason I really don't want to debug in front of the audience. I don't think the average user even has a concept of focus in his mind for focus when it comes to fullscreen windows. And I fail to see the disadvantage of making the keys work everywhere. What should go wrong?

If you don't want to go that way, then some visual cue is the minimum that should be done. (But then again: What's the point of the cue? He needs to remember from the manual what a flashing screen means, and then it simply tells the user to switch the focus to the other window. Why not directly do what the user has in mind?)

**Comment by fnevgeny** [comment]
In fact, when you press `Tab`, it isn't just "does not work". Both the presenter and presentation windows stop reacting to any other input until you press `Tab` again.

> What's the point of the cue? He needs to remember from the manual what a flashing screen means, and then it simply tells the user to switch the focus to the other window. Why not directly do what the user has in mind?

The user will likely want to select a slide in the overview using the mouse, not? So the burden of "finding" the pointer and moving it to the proper screen is on the user anyway...

**Comment by fnevgeny** [comment]
OK, to summarize:

* The `Tab` "lockup" is fixed by #470.
* The following actions are not performed when the respective keys/buttons are pressed on the presentation screen:
   * `overview`;
   * `note`;
   * `overlay`.

All three above are those assuming user interacting with widgets on the presenter screen, so it does make sense to treat them differently, IMO.
