### ISSUE TITLE
Two movies in the same slide not working

### ISSUE THREAD

**Issue by pantale** [pdfpc/pdfpc#464]
Would like to show a slide page with two movies side by side like page 5 of the modified demo document.

The page containing two movies can't be displayed, interface freezes while trying to display page 5.

pdfpc version: v4.3.0
Used Distribution (GTK version, vala version): 
Display Server (X/Wayland): 
HiDPI Setting (yes/no): no
[video-example.pdf](https://github.com/pdfpc/pdfpc/files/3868709/video-example.pdf)

**Comment by AndreasBilke** [comment]
I tried with v4.3.4 on my FreeBSD box and I have no troubles playing both videos t the same time.

1. Can you try the latest released version?
2. Can you give more details about your system?

**Comment by pantale** [comment]
Yes, true.

Using the very last version works well.
Sorry for the disturbance, and great job.

Kindly regards

Olivier Pantalé
