### ISSUE TITLE
Show slide (rather than notes) on presenter screen in drawing mode

### ISSUE THREAD

**Issue by ferdinand-fichtner** [pdfpc/pdfpc#465]
Hi, 

I am using pdfpc with beamer.sty, creating notes with \setbeameroption{show notes on second screen}. Things work flawless (Ubuntu Virtual Machine in Windows 10) except one nuisance: When in drawing mode, the presenter screen still shows the notes. It seems to me that it would be much more natural to switch the presenter screen to show the current slide (rather than the notes) when drawing, because otherwise writing or drawing elements "on the slide" is effectively impossible. The same problem arises in the pointer mode.

Or am I missing something? Is there a key to switch the presenter view before entering drawing mode? I cannot find anything in this direction...

Best regards
Ferdinand

**Comment by fnevgeny** [comment]
Please see #471. Maybe you don't need to use the beamer notes at all...

**Comment by fnevgeny** [comment]
Closed in lieu of #479.
