### ISSUE TITLE
Wrong slide count in pace calculation

### ISSUE THREAD

**Issue by DominikMa** [pdfpc/pdfpc#468]
**Expected Behaviour**
The calculation for indication of too slow/fast pace should be based on the last slide defined by the user. Setting the end slide does not affect the calculation of too slow/fast pace. 

**Actual Behaviour**
In [timer_label.vala](https://github.com/pdfpc/pdfpc/blob/c8f0e1edb37a97e6156afedbe51a462b89d952fc/src/classes/timer_label.vala#L264) in
```Vala
// New indication of too slow/fast pace independently
// of the time left.
int current_slide_number = this.controller.current_user_slide_number;
int slide_count = this.controller.user_n_slides;
```
the calculation of the slide count uses `user_n_slides` and therefore `get_user_slide_count` from [pdf.vala](https://github.com/pdfpc/pdfpc/blob/c8f0e1edb37a97e6156afedbe51a462b89d952fc/src/classes/metadata/pdf.vala#L583) which returns the actual number of user slides.
If the user for example set the `end_silde` because there are some backup slides after the final slide the calculation of pace will not change and show a too slow pace indicator.

Maybe the calculation can use `get_end_user_slide` from [pdf.vala](https://github.com/pdfpc/pdfpc/blob/c8f0e1edb37a97e6156afedbe51a462b89d952fc/src/classes/metadata/pdf.vala#L591) as slide count.

**Comment by fnevgeny** [comment]
You are right, thanks. In fact, I recall noticing it once with my own presentation, but forgot to fix afterwards :).
