### ISSUE TITLE
Preparations for Release

### ISSUE THREAD

**Issue by rschroll** [pdfpc/pdfpc#47]
I think we should aim to cut a new release of pdfpc sooner rather than later.  There's all sorts of stuff we could put into a new release, but I want to figure out what the minimum is.  I'd rather make multiple releases, because we keep landing great new features, than make no releases while waiting for all those great features to land.  Here's what I can think of.  Please add whatever I've forgotten.

- [x] Create new webpage for pdfpc.  (Presumably pdfpc.github.io.)
- [x] Update documentation to point to new webpage.
- [x] Update man page.
- [x] Update copyright statements as appropriate.
- [x] Make a decision on the new rendering scheme (#22), even if that decision is to put off the decision until later.
- [x] Update version number and tag release.
- [x] Fix #15.

I think we should be planning to advance the major version number.  A new GTK version, a new GStreamer version, and new maintaners are enough to warrant that.  But I don't know if we want to release 4.0 right away, or release a 3.9 series as a test.  Your thoughts?

**Comment by AndreasBilke** [comment]
Update man page: in the man page a contact mail address of davvil was given. Do we want this also for the new maintainer or shall the user visit the github page instead?

Update copyright statements as appropriate: who should be noticed here? All code contributors or just "pdfpc maintainer"?

Decision on rendering scheme: I would post pone this decision to some next releases.

Update version number and tag release: I share your arguments about a 4.0 release

**Comment by davvil** [comment]
Congratulations for your efforts! It looks good and is really nice to see pdfpc come to life again :)

I also think a 4.0 version is in place. It is also more catchy!

BTW. In the new webpage at the end you state that pdfpc is "a fork of a fork". I don't consider this repo to be a fork (except in the purely git-technical sense). I would say you inherited the project, no need to keep both separate.

**Comment by andybarry** [comment]
Wow this is awesome.  Very exciting.  You all have done an impressive amount of work!

I agree with @davvil about going to 4.0 and I'm also onboard about delaying a rendering scheme change decision until the next release.

**Comment by AndreasBilke** [comment]
Any ideas for a new copyright statement? I would create a new pull request for it.

It would also be great if someone could double check the changes on the website and the README/manpage  in #48.

**Comment by rschroll** [comment]
On Wed, May 27, 2015 at 3:19 PM, Andreas Bilke 
<notifications@github.com> wrote:
> Any ideas for a new copyright statement? I would create a new pull 
> request for it.
> 

I see two options offhand:
1) Add a copyright statement for each person who touched a file (in a 
significant way).
2) Add a blanket copyright statement with credit to "The PDFPC 
project", and then explain in the README or LICENSE file who the PDFPC 
project is.

I'm leading towards the former, even though it would be a bit more 
work.  As the list of contributors changes, it could get confusing as 
to who actually owns copyright on the various files.  It seems like 
someone must have written a script that goes through the git history 
and lists who modified which files.

**Comment by AndreasBilke** [comment]
> 1) Add a copyright statement for each person who touched a file (in a 
> significant way).

I googled a little bit and came to this:

$ git shortlog -sn

gives you the contributors, sorted by number of commits

$ git log --author="David Vilar" --pretty=tformat: --numstat | gawk \
  '{ add += $1; subs += $2; loc += $1 - $2 } END \
  { printf "added lines: %s removed lines: %s total lines: %s\n", add, subs, loc }' -

Gives you the number of changed lines. Both is not a good metric how
important the changes were, but it is an indicator.

One could go through

$ git shortlog -n

and look at the commit messages to decide in the importantness

**Comment by rschroll** [comment]
I have updated copyright statements in #51.  As I say there, let's hold off on merging this until we're just about ready to hit 4.0.

It sounds like there's a consensus for holding off on #22, so I've ticked that off.  I would like to get a (temporary) fix for #15 in, though, so I'll add that to our checklist.

I'm going to see if I can get a fix for #29 in, since that should be low risk.  But let's no hold up 4.0 if that doesn't happen.

@AndreasBilke, what are your thoughts on #32/#37?

**Comment by AndreasBilke** [comment]
@rschroll, I would wait with #32/#37 until we released 4.0. There should be more discussion on how this feature should work (global/local font size). Since I am not a user of this type of notes I have no opinion on this at all. I would only add features on behalf of others.

**Comment by rschroll** [comment]
Sounds good.  With the user CSS files, there is a way to adjust this 
font size right now.  It's not interactive, but at least it's something.

Once we get #54 merged, I think the only things to do is get the 
copyright statements updated (#51) and the docs and version number 
updated (#52, which will include #50).  I'll take responsibility for 
getting those merged in.

@AndreasBilke, @andybarry: Are you guys okay with that, or is there 
something else we need to do?

**Comment by AndreasBilke** [comment]
> @AndreasBilke, @andybarry: Are you guys okay with that, or is there 
> something else we need to do?

Nothing except organizing a release party?

**Comment by andybarry** [comment]
This is awesome.  I'm swamped trying to finish my thesis -- looking forward
to giving my defense using 4.0!

**Comment by rschroll** [comment]
I just pressed the trigger.  4.0 is out there.  Hopefully everything is correct; if not we can hurry up with 4.0.1.

Thanks everyone for helping bring pdfpc back to life.  Thanks especially to Andreas, who has been taking care of those boring but necessary things we needed to do to get 4.0 out the door!  And best of luck to Andy with his defence.  You'll do fine, I'm sure.

**Comment by davvil** [comment]
Congratulations for 4.0. Don't forget to tell me where the release party is! :)
