### ISSUE TITLE
Markdown notes

### ISSUE THREAD

**Issue by TheAssassin** [pdfpc/pdfpc#476]
I'd like to propose using Markdown for writing custom notes in the pdfpc format.

I'm not a fan of the native beamer notes "second screen" thing. It's more of a workaround than a solution. Hence I've been using plain text notes for years.
The lack of *any* serious formatting options in the custom notes format is really annoying. As a presenter, I need to navigate quickly through my notes. Structure helps a lot. Paragraphs are not nearly enough. Most people probably use item lists, but those aren't available at all; one has to use paragraphs with leading dashes or so, but they don't keep the indentation on line breaks etc.

Markdown is very simple to learn. Users can quickly write custom notes. It's very widely understood by people, especially in the scientific/computing domain.
Of course Markdown is way less feature filled in comparison to LaTeX. That's a plus here. Notes usually don't need any fancy formatting like color etc., as they're read in bad lighting situations. White text on black background is usually sufficient.
Being relatively simple as a format might make it possible to even render it from LaTeX using https://github.com/cebe/pdfpc-latex-notes/. One could translate `itemize`/`enumerate` environments to their Markdown pendants.
Even if that's not possible or supported, writing Markdown within the LaTeX beamer document would be acceptable to me.

I think Markdown is going really enhance the pdfpc user experience and workflow. And it shouldn't be too hard to implement. There's tons of engines out there one can use to render Markdown into e.g., HTML.

I'd be willing to look into how to render Markdown and possibly implement it in pdfpc with your assistance. The easiest way would probably be to render the Markdown into HTML and use some sort of native webview widget.

**Comment by fnevgeny** [comment]
Well, there was a [discussion](https://github.com/pdfpc/pdfpc/issues/472) about removing the beamer-style notes, but there is a strong lobby against, so it seems like it will stay, though likely in an improved way - using the same screen space as the "native'' pdfpc textual notes. As to the latter, they will also remain. Then adding yet another format, with a feature set somewhere  in between the two, and requiring not negligible coding to support, does not seem to me justified.

**Comment by TheAssassin** [comment]
Well, all I want to achieve is an improvement in showing notes. Most other tools you can use for presentations also more or less support a "subset" of their regular features when writing notes, as far as I can tell.

My idea for using Markdown was inspired by the existing notes' presentation. White text on black background is IMO ideal for reading notes during a presentation. I was just annoyed by the lack of "structure" in those notes. I've been using "bullet points" by prepending dashes to lines, but the lack of indentation made them annoying to read.

I'm aware of this "two page notes" system Beamer supports. But that's totally overkill

I think the amount of code for supporting Markdown can be kept relatively low. As said one can use an external parser, only the rendering needs to be implemented. Using some sort of web view, which exists in any UI toolkit nowadays, is the easiest way, as you can feed the HTML the parsers can generate directly in there, or even support HTML directly.
I know Qt can render HTML texts in labels for instance, and the [GtkLabel](https://developer.gnome.org/gtk3/stable/GtkLabel.html#gtk-label-set-markup) class seems to support HTML, too.

**Comment by fnevgeny** [comment]
> I'm aware of this "two page notes" system Beamer supports. But that's overkill. Please show me use cases where you'd need e.g., formulas or tikz in your notes.

If you read through the entire discussion I referred to (#472) in my previous reply, you'll see there are people who use quite advanced typesetting techniques in the notes.

So IMO it boils down to the question/decision whether the support for the beamer notes is to stay. If yes, I see no justification for another, intermediate solution -- you can use a minimal subset of latex satisfying your needs (bulleted lists with correct indentation).

**Comment by TheAssassin** [comment]
I would be fine if pdfpc were to render the notes, i.e., from the pdfpc files. What I don't like about the twopage stuff is it's annoying to write, annoying to review, ...

**Comment by fnevgeny** [comment]
> What I don't like about the twopage stuff is it's annoying to write, annoying to review, ...

Can you please elaborate why? I again draw your attention to the aforementioned discussion, specifically [this comment](https://github.com/pdfpc/pdfpc/issues/472#issuecomment-563457183).

**Comment by TheAssassin** [comment]
It's annoying to handle when writing with most editors. I host my own ShareLaTeX instance for example. I'd have to turn off the two page mode every time I create beamer presentations to make sure I don't have to scroll twice as much when creating the actual slides, and then for testing the presentation I'd have to turn it on again. To me that's a really bad workflow. I am not aware of editors which can just hide every second slide for editing to be able to use the two-page mode without having that problem.

**Comment by fnevgeny** [comment]
Well, I think an implementation of the markdown rendering shouldn't be very difficult. There is a [semi-official VAPI](https://gitlab.gnome.org/GNOME/vala-extra-vapis/blob/master/libmarkdown.vapi) and even a [markdown viewer written in Vala](https://gitlab.com/craigbarnes/showdown).

**Comment by fnevgeny** [comment]
@AndreasBilke Do you think support for this should be optional like `MOVIES`?

**Comment by AndreasBilke** [comment]
Do you know if this vala-extra-vapis can be found in a standard Linux
distribution? (That should lead us to the answer for optional or non
optional)

Like the initial reason for an optional `MOVIES` support was, that we
wanted to have pdfpc on non-X11 plattforms. I think nowadays even `MOVIES`
could be non-optional.

**Comment by fnevgeny** [comment]
> Do you know if this vala-extra-vapis can be found in a standard Linux
distribution?

We don't need it as a whole, just `libmarkdown.vapi` (in fact, only a small subset of it would suffice), so I plan to package it with `pdfpc`. But it needs the library itself (`discount`, aka `libmarkdown2`), and I am not sure how easy it is to get on non-Unix platforms.

**Comment by AndreasBilke** [comment]
I think we never cared for Windows :) Linux+BSDish is enough :)

PS: discount is in the FreeBSD ports tree

**Comment by fnevgeny** [comment]
I see it in [homebrew](https://formulae.brew.sh/formula/discount), too, so macOS isn't a problem either.
