### ISSUE TITLE
Video doesn't start in xmonad

### ISSUE THREAD

**Issue by robertsawko** [pdfpc/pdfpc#477]
Hi,

Thanks a lot for contributing this software to github. It's really useful and I am redoing many of my slides to include presenter notes as well.

I am trying to play `pdfpc-video-example` on ArchLinux. I do not have desktop environment but my window manager is xmonad. My problem is that when I click on videos I am seeing this error:

```
Error creating video sink: Could not make element sink0 of type gtksink.
Gstreamer installation may be incomplete.
```
and the presentation moves onto the next slide. Perhaps I need something else installed or something in my environment is still missing. Please let me know.

Used Distribution (GTK version, vala version): gtk3 1:3.24.13-1 gtk2 2.24.32-1 extra/vala 0.46.5-1
Display Server (X/Wayland): X
HiDPI Setting (yes/no): both

**Comment by fnevgeny** [comment]
Have you read the [FAQ](https://github.com/pdfpc/pdfpc/blob/master/FAQ.rst)?

**Comment by robertsawko** [comment]
Sorry, I haven't. Thanks. I had a look now. `gst-play-1.0` was not working for me, but I installed some additional plugins and now I can play the video from the commandline.

So I think it's down to the WM. I have a shortcut for floating and maximising the window

```haskell
, ((mod4Mask, xK_f), withFocused $ windows . (flip W.float $ W.RationalRect 0 0 1 1))
```
I will investigate this. I do use the shortcut after I launch the application, would that affect it?

**Comment by fnevgeny** [comment]
I don't understand, sorry - do you say that the command-line playback, exactly as listed in the FAQ, works, but doesn't in pdfpc?

**Comment by robertsawko** [comment]
Sorry. I am confusing with irrelevant information.

Yes the commandline playback works: video and sound, but when I open in pdfpc and try to click on the image, as the bullet points says it just moves over to the next slide. This seems to like a control issue, but it might also be related to my window manager somehow.

**Comment by fnevgeny** [comment]
> Yes the commandline playback works: video and sound,

Without _any_ warning?

> but when I open in pdfpc and try to click on the image, as the bullet points says it just moves over to the next slide.

Without _any_ warning?

**Comment by robertsawko** [comment]
Yes. Mysteriously. Neither is producing any warning.

```Press 'k' to see a list of keyboard shortcuts.
Now playing /home/rsa/downloads/pdfpc-video-example/apollo17.avi
Redistribute latency...
0:00:36.4 / 0:00:36.4       
Reached end of play list.```

**Comment by robertsawko** [comment]
Sorry. Got it. I had to click on the what speakers notes video.

**Comment by fnevgeny** [comment]
> I had to click on the what speakers notes video.

Hmm, you had to click on what exactly?

**Comment by robertsawko** [comment]
Gosh, really sorry for misreporting things so badly. Edited the answer.

**Comment by fnevgeny** [comment]
OK, I see. Translating to the pdfpc parlance, I take it you originally tried to click on the presentation window instead of the presenter one :).
