### ISSUE TITLE
pdfpc can not be closed on Ubuntu 19.10

### ISSUE THREAD

**Issue by DaGeRe** [pdfpc/pdfpc#478]
**Expected Behaviour**

If I start a presentation with pdfpc mypresentation.pdf and want to quit it by hitting ESC oder q, the program should finish.

**Actual Behaviour**

pdfpc is not finished on hitting ESC or q, only way to exit it is to change window by Alt+Tab and afterwards hit Ctrl + C in console.

**Steps to reproduce**

1. Install pdfpc via apt in Ubuntu 19.10.
2. Start pdfpc with any pdf.

Additionally, I tried to build latest (fffc400aeba00f0eada3b5fd48789caa22394f09) pdfpc. It generally seemed to work, e.g.

> bin/pdfpc -v
> pdfpc v4.3.0
> Copyright (C) 2010-2018 see CONTRIBUTORS
> 
> License GPLv2: GNU GPL version 2 <http://gnu.org/licenses/gpl-2.0.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.

I can not start any pdf, it always returns:
> No CSS file found

pdfpc version: 4.3.4
Used Distribution (GTK version, vala version): Ubuntu 19.10
Display Server (X/Wayland): Xorg (default Ubuntu 19.10)
HiDPI Setting (yes/no): unknown (did not configure this)

**Comment by fnevgeny** [comment]
> If I start a presentation with pdfpc mypresentation.pdf and want to quit it by hitting ESC oder q, the program should finish.

No it shouldn't. Please see the man page. The default is `Ctrl+q`. Many default keybindings changed in 4.3.0, described in [CHANGELOG.txt](https://github.com/pdfpc/pdfpc/blob/4.3-maintenance/CHANGELOG.txt).

> I can not start any pdf, it always returns:
> 
> > No CSS file found

Again, see the updated docs. You miss the `-N` flag (or need to properly install pdfpc first).

**Comment by DaGeRe** [comment]
Ok, thanks for the quick reply! Sorry, I did not check the documentation deep enough.
