### ISSUE TITLE
pointer hides timer

### ISSUE THREAD

**Issue by angpan32** [pdfpc/pdfpc#481]
PDFPC does not display the timer while the pointer mode is activated (or the Toolbox is displayed, etc). I give my presentation constantly using the pointer, and it would be nice if I didn't have to switch it off just to see how much time I have left.

**Comment by AndreasBilke** [comment]
I can't confirm this behaviour. Can you submit a screen shot or something
lese where we can see your issue?

**Comment by angpan32** [comment]
Dear Andreas

sorry for the late reply. Please see what I mean with these two screenshots:
when the pointer is selected, the timer and slide counter are not displayed

best regards

**Comment by fnevgeny** [comment]
> with these two screenshots

I see no screenshots...

**Comment by angpan32** [comment]
Hello

I am not sure why, I have attached two .png files to the previous email…anyway, you can see them here
https://www.dropbox.com/transfer/AAAAAACvq73eD6MvwiWMIohosemD7ck4_Ys58fuJqqncBnTshjIB1RM <https://www.dropbox.com/transfer/AAAAAACvq73eD6MvwiWMIohosemD7ck4_Ys58fuJqqncBnTshjIB1RM> 

best regards

**Comment by fnevgeny** [comment]
Please list all the required info for a [bug report](https://github.com/pdfpc/pdfpc/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) - versions etc.

**Comment by fnevgeny** [comment]
No feedback, closing.
