### ISSUE TITLE
Implement spotlight mode

### ISSUE THREAD

**Issue by jspitz** [pdfpc/pdfpc#484]
This is a spin-off of #458.

pdfpc has a pointer mode, and the feature of highlighting a rectangular area where the background is shaded. However, it does not feature yet a spotlight mode like [Impressive](https://sourceforge.net/projects/impressive/) or the Logitech Spotlight presenter have.

Spotlight mode is like pointer, a circular area that moves with the mouse and can be adjusted in size, but instead of highlighting the spot by a different color, it shades the background. So in a way it is a combination of the existing two modes.

The feature seems to have been requested multiple times already (#458, #337).

**Comment by fnevgeny** [comment]
What should the spotlight behavior be re:

* pointer timeout
  * switch off (that results in a "flash" of the grayed-out area)
  * switch off the spot area itself (the entire slide becomes grayed-out)
  * do nothing
* highlighted area (from the normal "pointer" mode), if it exists by the time the spotlight mode is selected
  * keep it shown
  * clear
  * don't show but remember and show again if switch back to the pointer mode

?

**Comment by jspitz** [comment]
> What should the spotlight behavior be re:
> 
>     * pointer timeout
>       
>       * switch off (that results in a "flash" of the grayed-out area)
>       * switch off the spot area itself (the entire slide becomes grayed-out)
>       * do nothing

the latter.

>     * highlighted area (from the normal "pointer" mode), if it exists by the time the spotlight mode is selected
>       
>       * keep it shown
>       * clear
>       * don't show but remember and show again if switch back to the pointer mode

the latter.

**Comment by fnevgeny** [comment]
Well, take it for a spin...

**Comment by fnevgeny** [comment]
@jspitz ping?

**Comment by jspitz** [comment]
I'll try when I am back from vacations.

**Comment by jspitz** [comment]
Tested now, works beautifully as I would expect it to.

Thanks!
