### ISSUE TITLE
Homebrew version up to date

### ISSUE THREAD

**Issue by LecrisUT** [pdfpc/pdfpc#489]
I've just updated the homebrew repository to 4.4, and removed the vala patch as instructed. Are there any tests of the new versions that need to be done?

So far I've only noticed that plug-and-play monitor does not work, at least for me.

- PnP not working on MacOS?

```Monitor (null) added```

**Comment by fnevgeny** [comment]
If it's a bug report, please fill in all the [required details](https://github.com/pdfpc/pdfpc/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md). None of the core developers have a Mac hardware to test, so you'll likely need to debug yourself. Note that there was a success report earlier regarding the PnP on MacOS, see #455, you may want to discuss it with @maeln.

**Comment by LecrisUT** [comment]
What I wanted to ask, is if there are any new features that you would like tested, since I have a MacOS available.

As for the PnP bug, @maeln 's ticket was with switching the display mode from cloned to extended, and not exactly the PnP feature (also, yes it does work as intended in that regard). I have traced back to the `FullScreen` constructor, and I think there's a problem with `GTK`, since `pdfpc` does send the correct monitor number to create the new display (`1`), but for some reason `GTK` decides to open it in display `0`.  When initialized without PnP, the same command work as intended. If you have any clues on what to check let me know.

**Comment by fnevgeny** [comment]
OK, so what really happens? The presentation window opens above the presenter one overlapping it? What if you run with `-w presenter`?

**Comment by LecrisUT** [comment]
Ok, I've opened an official bug report submission for that. Check #490
