### ISSUE TITLE
Dead link in man and Readme

### ISSUE THREAD

**Issue by EtienneM** [pdfpc/pdfpc#49]
Not a big deal but the link http://westhoffswelt.de/projects/pdf_presenter_console.html is in the README file and in the man. However it is a dead link. 

Moreover, in the man there is a typo in the FEATURES / End slide section:

> "[...] the actual presentation **vie** the 'e' key [...]"

You probably meant "via"

**Comment by AndreasBilke** [comment]
Thank you, the dead link issue has been addressed in #48 as a preparation
for a new release.

But I will change the misspelled word in the man page

**Comment by EtienneM** [comment]
Oups... sorry!

Actually you changed the link to https://github.com/jakobwesthoff/Pdf-Presenter-Console. However there is no clue in this repository that the new one is https://github.com/pdfpc/pdfpc...

**Comment by AndreasBilke** [comment]
With #48 we should have updated all links. If you find in this pull request some missed links please comment that pull request.
