### ISSUE TITLE
MacOS PnP not functioning

### ISSUE THREAD

**Issue by LecrisUT** [pdfpc/pdfpc#490]
**Expected Behaviour**

   After monitor is plugged, a new Desktop/screen/window should be created in monitor 2. The presentation screen should then be created there. (Uncertain what happens for more than 1 monitor)
![Intended](https://user-images.githubusercontent.com/25577083/75735998-68280f00-5d3f-11ea-8d51-ada650816b36.png)
![Intended(2)](https://user-images.githubusercontent.com/25577083/75736000-69593c00-5d3f-11ea-805b-fae89acadf91.png)

**Actual Behaviour**

   Both monitors refresh, then the new presentation window is created on the main screen instead of monitor 2.
![Before_PnP](https://user-images.githubusercontent.com/25577083/75735987-62cac480-5d3f-11ea-9e10-28f0488e9951.png)
![After_PnP](https://user-images.githubusercontent.com/25577083/75736003-6a8a6900-5d3f-11ea-873b-c2fcbc6b8bec.png)
![After_PnP(2)](https://user-images.githubusercontent.com/25577083/75736004-6b22ff80-5d3f-11ea-9c0b-55a89e4eed67.png)

**Steps to reproduce**

1. Open pdfpc
2. Plug a monitor

pdfpc version: **4.4.0**
Used Distribution (GTK version, vala version): **3.24.14** / **0.46.6**
Display Server (X/Wayland): Forgot which
HiDPI Setting (yes/no): **no**
(Latest Homebrew repo (2020/3/3))

Curiously enough, `pdfpc` sends the correct monitor number to create the second screen (in `fullscreen` constructor to `gdk.window`), in all cases. Might be a bug with gtk. If there are more detailed test that can better pinpoint the problem let me know.

**Comment by fnevgeny** [comment]
Just in case, try first with a simpler presentation, especially without videos. And what about `-w presenter`?

**Comment by LecrisUT** [comment]
Exactly the same for both cases. In windowed mode, the presenter screen is windowed, and presentation is fullscreened on main monitor after PnP.

**Comment by LecrisUT** [comment]
After some more digging, I've found that the problem is that after connecting the new monitor, `Gdk.Display.Monitor.get_geometry` does not get the right geometry for the new monitor.

If I manually add the `move` command to the correct pixel, it correctly fullscreens to the right monitor.

In the current code there is no catch to check if after plugging in, the monitor geometry has been moved yet or not.

**Comment by fnevgeny** [comment]
Have you tried setting `option move-on-mapped = true`?

**Comment by LecrisUT** [comment]
This is mysterious I'm getting `segmentation fault: 11` no matter what and how I run. (Unrelated to the problems above).

I don't know what broke in `homebrew` or where. Everything worked just fine the last few days.
Could use a confirmation from anybody if it's a common problem with current `homebrew` or just me

**Comment by fnevgeny** [comment]
Please don't use comment edits for providing substantial new information. Notifications on edit events are not sent by github, so it's too easy to miss.

Send `pdfpc -M` output before and after the second monitor plugging (without pdfpc running). Same with `xrandr` (if that exists under MacOS).

**Comment by LecrisUT** [comment]
Sorry for the edit.

Here is the `pdfpc -M`:
```
Monitors: 1
 0: * (null) 	[1440x900+0+0@0Hz 	scale=100%]

Monitors: 2
 0: * (null) 	[1440x900+0+0@0Hz 	scale=100%]
 1:   (null) 	[2560x1440+1440+0@0Hz 	scale=100%]
```

Found an equivalent for `xrandr` but with much more info generated:
```
Persistent screen id: 77E200AD-B0E6-0317-4BBF-F8B53DA3952C
Contextual screen id: 69732032
Type: MacBook built in screen
Resolution: 1440x900
Hertz: N/A
Color Depth: 4
Scaling:off
Origin: (0,0) - main display
Rotation: 0 - rotate internal screen example (may crash computer, but will be rotated after rebooting): `displayplacer "id:77E200AD-B0E6-0317-4BBF-F8B53DA3952C degree:90"`
Resolutions for rotation 0:
  mode 0: res:1440x900 color_depth:4 <-- current mode
  mode 1: res:1152x720 color_depth:4
  mode 2: res:1024x768 color_depth:4
  mode 3: res:1024x640 color_depth:4
  mode 4: res:1280x800 color_depth:4
  mode 5: res:800x600 color_depth:4
  mode 6: res:800x500 color_depth:4
  mode 7: res:640x480 color_depth:4
  mode 8: res:720x480 color_depth:4
  mode 9: res:1280x720 color_depth:4
  mode 10: res:1680x1050 color_depth:4
  mode 11: res:1920x1080 color_depth:4
  mode 12: res:1920x1200 color_depth:4
  mode 13: res:2560x1440 color_depth:4
  mode 14: res:2560x1600 color_depth:4
  mode 15: res:1440x810 color_depth:4
  mode 16: res:720x450 color_depth:4 scaling:on
  mode 17: res:840x525 color_depth:4 scaling:on
  mode 18: res:960x540 color_depth:4 scaling:on
  mode 19: res:960x600 color_depth:4 scaling:on
  mode 20: res:1280x720 color_depth:4 scaling:on
  mode 21: res:1280x800 color_depth:4 scaling:on

Persistent screen id: 44A341C7-92C0-8155-7193-FB4696BFD953
Contextual screen id: 69503753
Type: 27 inch external screen
Resolution: 2560x1440
Hertz: N/A
Color Depth: 4
Scaling:off
Origin: (1440,0)
Rotation: 0
Resolutions for rotation 0:
  mode 0: res:2560x1440 color_depth:4 <-- current mode
  mode 1: res:2560x1440 color_depth:8
  mode 2: res:1280x720 color_depth:4
  mode 3: res:1280x720 color_depth:8
  mode 4: res:640x480 color_depth:4
  mode 5: res:640x480 color_depth:8
  mode 6: res:800x600 color_depth:4
  mode 7: res:800x600 color_depth:8
  mode 8: res:1024x768 color_depth:4
  mode 9: res:1024x768 color_depth:8
  mode 10: res:1024x576 color_depth:4
  mode 11: res:1024x576 color_depth:8
  mode 12: res:1280x960 color_depth:4
  mode 13: res:1280x960 color_depth:8
  mode 14: res:1344x1008 color_depth:4
  mode 15: res:1344x1008 color_depth:8
  mode 16: res:1344x756 color_depth:4
  mode 17: res:1344x756 color_depth:8
  mode 18: res:1440x900 color_depth:4
  mode 19: res:1440x900 color_depth:8
  mode 20: res:1680x1050 color_depth:4
  mode 21: res:1680x1050 color_depth:8
  mode 22: res:1600x1200 color_depth:4
  mode 23: res:1600x1200 color_depth:8
  mode 24: res:1600x900 color_depth:4
  mode 25: res:1600x900 color_depth:8
  mode 26: res:1920x1080 color_depth:4
  mode 27: res:1920x1080 color_depth:8
  mode 28: res:1920x1200 color_depth:4
  mode 29: res:1920x1200 color_depth:8
  mode 30: res:2048x1152 color_depth:4
  mode 31: res:2048x1152 color_depth:8
  mode 32: res:2560x1600 color_depth:4
  mode 33: res:2560x1600 color_depth:8
  mode 34: res:1280x720 color_depth:4 scaling:on
  mode 35: res:1280x720 color_depth:8 scaling:on
  mode 36: res:720x450 color_depth:4 scaling:on
  mode 37: res:720x450 color_depth:8 scaling:on
  mode 38: res:840x525 color_depth:4 scaling:on
  mode 39: res:840x525 color_depth:8 scaling:on
  mode 40: res:800x600 color_depth:4 scaling:on
  mode 41: res:800x600 color_depth:8 scaling:on
  mode 42: res:800x450 color_depth:4 scaling:on
  mode 43: res:800x450 color_depth:8 scaling:on
  mode 44: res:960x540 color_depth:4 scaling:on
  mode 45: res:960x540 color_depth:8 scaling:on
  mode 46: res:960x600 color_depth:4 scaling:on
  mode 47: res:960x600 color_depth:8 scaling:on
  mode 48: res:1024x576 color_depth:4 scaling:on
  mode 49: res:1024x576 color_depth:8 scaling:on
  mode 50: res:1280x800 color_depth:4 scaling:on
  mode 51: res:1280x800 color_depth:8 scaling:on

Execute the command below to set your screens to the current arrangement:

displayplacer "id:77E200AD-B0E6-0317-4BBF-F8B53DA3952C res:1440x900 color_depth:4 scaling:off origin:(0,0) degree:0" "id:44A341C7-92C0-8155-7193-FB4696BFD953 res:2560x1440 color_depth:4 scaling:off origin:(1440,0) degree:0"
```

**Comment by fnevgeny** [comment]
> The plugged monitor variables are:
> 
> ```
> width=0, height=0,
> ```

Certainly not good; but that's what we get from Gdk. Likely the bug is not ours. There was a related MacOS-specific issue recently, BTW: <https://gitlab.gnome.org/GNOME/gtk/issues/2004>.

**Comment by LecrisUT** [comment]
Are there other signals or commands that can make `pdfpc` wait until the OS has finished calibrating the monitor position?

> BTW: https://gitlab.gnome.org/GNOME/gtk/issues/2004.
This one should already be fixed in `3.24.14` which is already up in `homebrew`. I'll poke around GTK's github and see if it is another problem there.

**Comment by fnevgeny** [comment]
> Are there other signals or commands that can make `pdfpc` wait until the OS has finished calibrating the monitor position?

Hmm, it's not the monitor position, but rather dimensions which are not defined. In any case, I don't see it's said anyway in the docs that at the point when the signal is fired something might be not ready yet. So it sounds like a bug in gtk (in the quartz implementation). I suggest you file a bug report with them to clarify.

> > BTW: https://gitlab.gnome.org/GNOME/gtk/issues/2004.
> 
> This one should already be fixed in `3.24.14` which is already up in `homebrew`.

I know, just to point to a related quartz issue. Furthermore, maybe on macos the whole process of monitor plugging works in two steps: first, the monitor-added signal is fired and then monitors-changed. This would be strange and suboptimal (why should I go over the whole list and check which one really changed when there exists a signal to point to a specific one?!). But who knows.

**Comment by LecrisUT** [comment]
I have run some test on the signals. If I use `monitors-changed` I get the correct position of the monitors, but `monitor-added` does not get the correct position, even after I connect with `connect_after`.

A hackish workaround is to save the added monitor from `monitor-added` and wait for `monitors-changed` signal and connect the rest of pdfpc code there. Although I've seen in the documentation that windows does not support the latter?

Anyway, I'll make a bug report and post it tomorrow on gtk.

**Comment by fnevgeny** [comment]
What about the [size_changed](https://valadoc.org/gdk-3.0/Gdk.Screen.size_changed.html) signal?

**Comment by LecrisUT** [comment]
> What about the [size_changed](https://valadoc.org/gdk-3.0/Gdk.Screen.size_changed.html) signal?

`size_changed` sort of works, but only the first time you plug in. If you unplug and plug back it in, the signal is not emitted.
`monitors-changed` works, but it is triggered twice when you connect or disconnect a monitor.
`monitor-added` is triggered too early so the monitor has not created the geometry yet.

the order of triggers are:
```
monitor-added/monitor-removed
monitors-changed
(size-changed)
monitors-changed
```

**Comment by fnevgeny** [comment]
> Anyway, I'll make a bug report and post it tomorrow on gtk.

@LecrisUT Have you?

**Comment by LecrisUT** [comment]
Ah, yes. But they are yet to respond: [GNOME/gtk:2502](https://gitlab.gnome.org/GNOME/gtk/issues/2502)

**Comment by LecrisUT** [comment]
A fix in `GTK` is coming which will fix this problem. So this will be shortly resolved in upcoming `homebrew` updates.

**Comment by fnevgeny** [comment]
Very good, thanks!
