### ISSUE TITLE
pdfpc package error with duration option

### ISSUE THREAD

**Issue by ArTourter** [pdfpc/pdfpc#491]
This is a bug report for the latex package rather than the program.
The following document fails to compile

```latex
\documentclass{beamer}
\usepackage[duration=20]{pdfpc}

\author{me}
\title{a title}

\begin{document}
\maketitle
\end{document}
```

**Expected Behaviour**
normal compilation

**Actual Behaviour**
Compilation fails with the error:
```
! Incomplete \ifx; all text was ignored after line 69.
<inserted text>
\fi
l.3
```

**Steps to reproduce**
compile the mwe with your processor of choice!

I have tried the other options and they all work fine. only when `duration` is used, alone or with other options, does the compilation fails.

**Comment by fnevgeny** [comment]
Please check the linked PR.

**Comment by ArTourter** [comment]
Yes, removing these 2 lines fixes the problem!

Thanks
