### ISSUE TITLE
Video is slightly larger than poster

### ISSUE THREAD

**Issue by gammell** [pdfpc/pdfpc#495]
**Expected Behaviour**
A video and its associated poster will be the same size.

**Actual Behaviour**
The video is slightly larger than the provided poster, order of 1pt all around (estimated). See pictures. Bug is consistent regardless of video/poster size.
Poster: https://imgur.com/RyjcqFM
Video: https://imgur.com/7TG9b76
GIMP Comparison (poster: red, video: green): https://imgur.com/kywfcnC

**Steps to reproduce**
1. Download pdfpc-video-example.zip from pdfpc.github.io and run in pdfpc.

OS: Ubuntu 18.04
pdfpc version: 4.1
Command: pdfpc -s video-example.pdf

**Comment by gammell** [comment]
I've been trying to LaTeX my way to a solution for this, but I'm wondering if it's a known thing and/or if people have already found a way to deal with it?

**Comment by fnevgeny** [comment]
I don't see this issue with the current version (4.4.0). Please check it out. BTW, from the screenshots it seems the video example is not from our current web page, either.

**Comment by gammell** [comment]
Huh, yeah, my example is out of date and I was using the `\href` approach over `\movie`. That's embarrassing. It seems to work fine, but pdfpc does not support the `autostart` option to `\movie`?

**Comment by gammell** [comment]
Actually, should I leave this open as it is a problem with the `\href` approach?

**Comment by AndreasBilke** [comment]
> Actually, should I leave this open as it is a problem with the `\href` approach?

The `\href` approach is not recommended (and explicitly marked as buggy in the man page). I would say no :-)

**Comment by fnevgeny** [comment]
The problem with `autostart` is not related to pdfpc per se. It (and [many other movie-related API's](https://gitlab.freedesktop.org/poppler/poppler/-/merge_requests/301)) was missing in the Poppler glib bindings up to a recent version (0.80). Now it will take time for the changes to propagate to Vala as shipped with your favorite Linux distro...

**Comment by gammell** [comment]
> The problem with `autostart` is not related to pdfpc per se. It (and [many other movie-related API's](https://gitlab.freedesktop.org/poppler/poppler/-/merge_requests/301)) was missing in the Poppler glib bindings up to a recent version (0.80). Now it will take time for the changes to propagate to Vala as shipped with your favorite Linux distro...

Just checking my understanding of the above. So pdfpc will support `autostart` once the updates to the underlying library are readily available? Or will is there also still work to update pdfpc to use the newly exposed features in the updated API?

**Comment by fnevgeny** [comment]
> Or will is there also still work to update pdfpc to use the newly exposed features in the updated API?

A few lines of trivial code.

**Comment by fnevgeny** [comment]
> A few lines of trivial code.

To make it clear - this is for the functionality that is already in pdfpc (e.g., autostart, start/stop positions). But not for new features like video rotation :).

**Comment by gammell** [comment]
If anyone is looking for a solution to this in the mean time, the following worked for me. It is most likely imperfect LaTeX.

I've retyped it from a more complex document I'm working on, so hopefully I haven't made any typos.

```
\usepackage{calc}% For adding lengths

\newlength{\videofudgex}
\setlength{\videofudgex}{-1pt}
\newlength{\videofudgey}
\setlength{\videofudgey}{-0.9pt}

\newlength{\videofudgewidth}
\setlength{\videofudgewidth}{-1pt}
\newlength{\videofudgeheight}
\setlength{\videofudgeheight}{-1.9pt}

\newsavebox{\posterbox}

\newbox\videobox
\newlength{\videowidth}
\newlength{\videoheight}
\newlength{\videodepth}

%Usage: \video{/path/to/poster}{/path/to/video}
\newcommand{\video}[2]%
{%
    % Save the poster so we know its size (and ratio).
    \savebox{\posterbox}%
    {%
            \includegraphics[width=\textwidth,height=\textheight,keepaspectratio]{#1}%
    }%
    
    % Calculate the size of the video from the poster
    \settowidth{\videowidth}{\usebox{\posterbox}}%
    \settoheight{\videoheight}{\usebox{\posterbox}}%
    \settodepth{\videodepth}{\usebox{\posterbox}}%
    %Then adjust
    \addtolength{\videowidth}{\videofudgewidth}%
    \addtolength{\videoheight}{\videofudgeheight}%

    % Define a box to define the video size, and put the poster inside it.
    \setbox\videobox=\vbox{\vspace{\videofudgey}\usebox{\posterbox}}%
    \wd\videobox=\videowidth%
    \ht\videobox=\videoheight%
    \dp\videobox=\videodepth%

    % Actually typeset the poster & video
    \centering%
    \vfil%
    \href%
    {%
        % Video
        run:#2?noprogress&autostart&loop%
    }%
    {%
        % Poster
        % Shift the poster to line up with the video
        \hskip\videofudgex%
        % Insert the video box containing the poster
        \box\videobox%
    }%
    \vfil%
}%

```
