### ISSUE TITLE
Make pdfpc run from build directory

### ISSUE THREAD

**Issue by rschroll** [pdfpc/pdfpc#5]
It's a pet peeve of mine, but I feel I should be able to run software after compiling it, without installing it.  This doesn't work for pdfpc, for two reasons:

1) The icons are not found.  This is minor, and doesn't prevent pdfpc from running.
2) No keymap is found, which makes it hard to control.  (See davvil/pdfpc#31.)  I'd argue that pdfpc should have a sensible default built-in, in case the user messes up the keymap file.

**Comment by andybarry** [comment]
Yes!  I'd forgotten about that confusing and annoying keymap issue.  I wholeheartedly agree :)
