### ISSUE TITLE
Support for automatic transitions (i.e., Beamer's \transduration)

### ISSUE THREAD

**Issue by gammell** [pdfpc/pdfpc#503]
Does the ongoing work to implement transitions (e.g., #496 #500), include adding support for automatic slide transitions as specified with \transduration{} in Beamer?

There is an excellent MWE here:
  https://tex.stackexchange.com/a/40335
which I can confirm works on Atril (XFCE's default pdf viewer) but not the Ubuntu 18.04 version of pdfpc.

Note that I'm looking to control individual slides, not the entire presentation as discussed in #229.

**Comment by gammell** [comment]
Thanks for planning to implement this feature in 4.5.0, please let me know if there's anything I can do to help out. I don't think I have the capacity to look the codebase at the moment, but I am happy to test/debug if that's necessary.

**Comment by fnevgeny** [comment]
@gammell you are welcome to test it now.

**Comment by gammell** [comment]
Sure thing @fnevgeny, I've got it compiled and did a quick test but I am seeing a little bit of weird behaviour. I don't have enough time to untangle the issues properly today, but I'll post full details tomorrow hopefully. Thanks again.

**Comment by gammell** [comment]
Hi @fnevgeny, thanks again for implementing this feature.

I've tested it on a MWE of a common presentation pattern I use, which is initial manually advanced slides, then a number of regularly advanced automatic slides, and then a final slide that automatically appears very slowly. Regular slides may then follow (MWE below).

The automatic advancement worked in general, but I did find some issues. I've done my best to provide test notes as clearly as possible. Where appropriate, I've included slide duration and transition times to replicate the behaviour in the MWE (on my computer). I hope the feedback helps.

1. **Slide duration timer starts at the start of incoming transition** (`\fadetime` = `1.0` and `\advtime` = `0.1`): This behaviour is inconsistent with other presentation software (Powerpoint and Keynote) and pdf viewers (Atril) that I've used, which all seem to time slide advancement from the end of the incoming transition. I personally think this would be the expected and simplest behaviour for the end user.
2. **Fast slide durations ignore the final _outgoing_ transition** (`\fadetime` = `1.0`, `\advtime` = `0.01`): When the slide duration time is sufficiently fast the outgoing transition from an advancement is ignored (i.e., the incoming transition of the first slide without automatic advancement, the `\infty` slide in the MWE). When the slide duration is longer this outgoing transition is respected as expected (c.f., `\advtime` = `0.01` vs. `0.1`).

Those are the two issues that I think require a closer look. Some other less-important things:

1. **Automatic advancement on the first slide has no initial effect**: The first slide is never automatically advanced when you open the file but will be advanced automatically if you return to the slide (e.g., go forward then back). I expected the slide duration to start when `pdfpc` opens. I would personally never do this but I can see situations in which people would and will be confused by the current behaviour. You could always get this behaviour with the current implementation by adding a blank initial slide.
2. **Automatic advancement on the last slide has no effect**. On some presentation software/pdf viewers you can advance past the final slide to a black "presentation over" screen and automatic advancement on the final slide has the same effect. I don't think `pdfpc` has anything equivalent and I really don't really see the use case. And it is even more obvious how to achieve this with your slide deck.

### MWE
```
\documentclass{beamer}

\newcommand{\fadetime}{2.0}
\newcommand{\advtime}{0.1}

\begin{document}
    \begin{frame}
        \transfade[duration=\fadetime]%
        How to count:
    \end{frame}

    %Manual advance

    \begin{frame}
        \transfade[duration=\fadetime]%
        1
        \transduration{\advtime}%
    \end{frame}

    %Automatic advance

    \begin{frame}
        \transfade[duration=\fadetime]%
        1, 2
        \transduration{\advtime}%
    \end{frame}

    %Automatic advance

    \begin{frame}
        \transfade[duration=\fadetime]%
        1, 2, 3
        \transduration{\advtime}% This should be 0.0.
    \end{frame}

    %Automatic advance

    \begin{frame}
        \transfade[duration=5.0]% SLOW transition in.
        1, 2, 3, \ldots, $\infty$
    \end{frame}

    % Manual advance

    \begin{frame}
        \transfade[duration=\fadetime]%
        Presentation continues.
    \end{frame}
\end{document}
```

**Comment by fnevgeny** [comment]
Thanks for the detailed report!

> The first slide is never automatically advanced when you open the file

I don't see it defined in your MWE. But it should work once the presentation *begins* - i.e., you press the `s` (by default) button. The timer doesn't start counting until you press `s`, either (or move to a new slide), so why should the slide transition behave differently?

> Automatic advancement on the last slide has no effect

Again, you don't use it in the MWE. But if you want the black screen in the end, enable the `black-on-end` option in pdfpcrc.

I'll look into the rest of your comments later.

**Comment by gammell** [comment]
Yes, you are correct. The two minor ones aren't things that I tested with my MWE, I found them with the Stack Exchange MWE.

**Comment by gammell** [comment]
> But it should work once the presentation _begins_ - i.e., you press the `s` (by default) button. The timer doesn't start counting until you press `s`, either (or move to a new slide), so why should the slide transition behave differently?

I completely agree and should have said I didn't know/look into how to tell `pdfpc` to start. In a quick test it appears to work properly after pressing `s`.

> But if you want the black screen in the end, enable the `black-on-end` option in pdfpcrc.

Great to know, I'm not familiar with how to use pdfpcrc, but I guess I could look into it.

**Comment by gammell** [comment]
I haven't been able to test whether automatic advancement works with `black-on-end`.

I installed the PR version to a unique path with `cmake -DCMAKE_INSTALL_PREFIX="/opt/pdfpc/prerelease/"` in order to keep my Ubuntu 18.04 version and I can't figure out what `pdfpcrc` file the PR version is using... I've confirmed it's not the `/etc/pdfpcrc` as installed by `apt`.

**Comment by fnevgeny** [comment]
You should set it in the user-level config file. Please `man pdfpcrc`.

**Comment by gammell** [comment]
Thanks. I had to manually create the user-level config file but then with `option black-on-end true` in `$HOME/.config/pdfpc/pdfpcrc`  automatic slide advancement worked for the last slide on a quick test.

**Comment by fnevgeny** [comment]
@gammell please give it a try now...

**Comment by gammell** [comment]
Hi @fnevgeny 
I didn't have as much time to test it this time, but everything seemed to work with the MWE except for one weird bug.

If the incoming transition time is sufficiently small for a slide that is automatically advanced after 0 seconds, then the transition for the next slide appears to be ignored. You can see the incorrect and correct behaviour in the updated MWE below with `\fadetime` = `0.03` and `0.04`, respectively. In the first case the `\infty` slide appears with no transition along with the `3` slide. But in the second case it has the requested 2.5s fade in after `3` appears.

I'll try to find a bit more time to poke at it tomorrow to see if I can turn anything else up. Thanks again for implementing this feature!

```
\documentclass{beamer}

\newcommand{\fadetime}{0.04}
\newcommand{\advtime}{0.5}

\begin{document}
    \begin{frame}
        \transfade[duration=\fadetime]%
        How to count:
    \end{frame}

    %Manual advance

    \begin{frame}
        \transfade[duration=\fadetime]%
        1
        \transduration{\advtime}%
    \end{frame}

    %Automatic advance

    \begin{frame}
        \transfade[duration=\fadetime]%
        1, 2
        \transduration{\advtime}%
    \end{frame}

    %Automatic advance

    \begin{frame}
        \transfade[duration=\fadetime]%
        1, 2, 3
        \transduration{0.0}%
    \end{frame}

    %Automatic advance

    \begin{frame}
        \transfade[duration=2.5]%
        1, 2, 3, \ldots, $\infty$
    \end{frame}

    % Manual advance

    \begin{frame}
        \transfade[duration=\fadetime]%
        Presentation continues.
    \end{frame}
\end{document}
```

**Comment by fnevgeny** [comment]
I hope it is OK now...

**Comment by gammell** [comment]
Hi @fnevgeny,

I only found the one issue detailed above in the second version of the code. Sorry for not letting clearer. Is there something new to test?

**Comment by fnevgeny** [comment]
Yes, I pushed new changes half an hour ago. Did you check them out?

**Comment by gammell** [comment]
Oh, sorry, I got confused by the commit date. I just tested quickly, and yeah, everything I can think of works well for me. I would say it seems like a pretty stable implementation.

Thanks again.

**Comment by fnevgeny** [comment]
> Oh, sorry, I got confused by the commit date.

Yes, it's strange indeed that github shows all commits from 3 days ago. Well, at least this is not a bug *I* should deal with :).

There are a few more commits, please check that nothing is broken.

**Comment by gammell** [comment]
> There are a few more commits, please check that nothing is broken.
I tried fast advance with a reasonable fade, a reasonable advance with a fast fade, and 0.0 advance and fade, with the MWE and they all seemed to still work as expected.

**Comment by fnevgeny** [comment]
Good, thanks.

@AndreasBilke then the PR is for your approval, probably as "squash and merge"...
