### ISSUE TITLE
Pointer hides timer

### ISSUE THREAD

**Issue by atrieu** [pdfpc/pdfpc#504]
Hi, I have the same issue as #481 I think.

**Expected Behaviour**
Have timer and slide counter during presentation.

**Actual Behaviour**
Timer and slide counter are hidden/disappear.

**Steps to reproduce**

1. Open a presentation with pdfpc.
2. Press 2 to activate pointer mode.
3. Timer and slide counter have disappeared. It happens in both windowed and full screen modes.

pdfpc version: 4.4.0
Used Distribution: macOS Mojave 10.14.3, installed pdfpc via homebrew

**Comment by fnevgeny** [comment]
>     1. Open a presentation with pdfpc.

Just _any_ file?

**Comment by atrieu** [comment]
> Just _any_ file?

I tried with two presentations I made using beamer + the demo pdfpc presentation, all have same behavior.

**Comment by fnevgeny** [comment]
- What is the output of `pdfpc -M`?
- Can you try a presentation with a different geometry? Just any portrait PDF file.

Any other macOS user having the same problem? @LecrisUT ?

**Comment by atrieu** [comment]
> * What is the output of `pdfpc -M`?
```
Monitors: 2
 0: * (null) 	[2880x1800+0+110@0Hz 	scale=200%]
 1:   (null) 	[1920x1080+1440+0@0Hz 	scale=100%]
```

> * Can you try a presentation with a different geometry? Just any portrait PDF file.

Tried with an a4 research paper. I get a slightly different behaviour, when I activate the pointer, the "slide" in the presenter view gets bigger and timer/slide counter disappears. Same thing if I do freeze instead of pointer. But weirdly enough, opening the toolbox doesn't do any of this, but timer/counter still disappears if I select stuff from the toolbox.

**Comment by LecrisUT** [comment]
I can't replicate on MacOS Catalina (10.15.3), regardless of configuration and landscape/portrait.
I'm on a macbook so my resolution is much smaller than @atrieu

**Comment by atrieu** [comment]
I'm on a Macbook Pro 13, but hooked with a 27 inch display ;-)

And actually, scratch my previous comment, the slides in the presenter view do get bigger with a regular presentation too, not just with a portrait PDF file, so same behavior in all cases.

**Comment by fnevgeny** [comment]
@atrieu Can you switch to the native resolution of the main monitor (i.e., to have scale=100%)? If it's impossible, try swapping the presenter/presentation monitors (`pdfpc -s`).

**Comment by LecrisUT** [comment]
@fnevgeny It's a HiDPI problem

**Comment by LecrisUT** [comment]
I've managed to replicate the error. And it only occurs when the presenter screen resolution is HiDPI. `-W` I don't think does anything

PS: my brain hurts after having to switch to 720x450 to test this on both monitors

**Comment by atrieu** [comment]
It works with pdfpc -s, so I guess I need to find out how to change the scale for the retina screen now...

Thanks for the help!

**Comment by fnevgeny** [comment]
@LecrisUT Hmm, so `-W` makes no difference with HiDPI? Neither for better, nor for worse? Strange...

**Comment by LecrisUT** [comment]
@fnevgeny It seems that the presentation is fullscreened or zoomed in excessively in the HiDPI mode. Does it have to do with anything of the `-W` workaround mentioned in the documentation? If not I suspect it is another `gtk+3` acting up problem. I'll try to trace it tomorrow. Can you guide me to the line code related to the workaround, and other parts to debug?

**Comment by fnevgeny** [comment]
> PS: no difference for better or worse with `-W`

Also in the windowed (not full screen) mode?

**Comment by LecrisUT** [comment]
Windowed mode works perfectly. The problem is that it somehow decides to zoom/fullscreen the presenter screen and the timer gets trimmed beyond the screen borders. The zoom does not occur if not in HiDPI.

**Comment by fnevgeny** [comment]
Try removing this block in `src/classes/window/presenter.vala`:
```
                if (!Pdfpc.is_Wayland_backend()) {
                    width *= this.gdk_scale;
                    height *= this.gdk_scale;
                }
```

**Comment by LecrisUT** [comment]
@fnevgeny Removing the block resolves the issue. What was the original use of it? It seems well scaled regardless

**Comment by LecrisUT** [comment]
PS: I have found other segmentation faults with portrait presentation when I compiled with `icc`. Doesn't occur when using `homebrew`'s settings, so I have to make a workflow there to better test.

**Comment by fnevgeny** [comment]
> What was the original use of it? It seems well scaled regardless

Well, as the `if` condition shows, x11 _does_ need it. But wayland (and apparently, quartz) doesn't. So you need to provide something like `Pdfpc.is_Quartz_backend()` and modify the code respectively...

**Comment by fnevgeny** [comment]
BTW, under Linux I can set GDK_SCALE to simulate the pixel scaling. Is there something similar for macOS?

**Comment by LecrisUT** [comment]
GDK_SCALE still gives the appropriate scale (200%) at the HiDPI resolution.

**Comment by fnevgeny** [comment]
The question is whether by changing this env variable you can affect the rendering. At least under VM, it appears to be totally ignored.

**Comment by LecrisUT** [comment]
I think it's the same for physical mac. Should it look zoomed in or sharper?

**Comment by fnevgeny** [comment]
E.g., the toolbox should be increased in size proportionally.

**Comment by LecrisUT** [comment]
With the section (!wayland backend) commented out, the toolbox is still increased proportionally.

**Comment by fnevgeny** [comment]
So is there a difference or not between `GDK_SCALE=1 pdfpc` and `GDK_SCALE=2 pdfpc`?

**Comment by LecrisUT** [comment]
Input in the command line? None whatsoever

**Comment by fnevgeny** [comment]
So I'm returning to my original question: 

> BTW, under Linux I can set GDK_SCALE to simulate the pixel scaling. Is there something similar for macOS?

**Comment by LecrisUT** [comment]
Hmm it seems that the command line command doesn't change `this.gdk_scale`. It seems to be overwritten by the monitor's setting. I have manually overwritten random scales and the toolbox still remains the same size (depending on the original resolution and scale factor of the monitor). Although `gdk_scale` is defined internally so it shouldn't be different from other OS?

**Comment by LecrisUT** [comment]
*Correction: if I uncomment the scaling in presenter part, the toolbox does scale accordingly.

https://github.com/pdfpc/pdfpc/blob/a83a0540fb0db2060a0a1748b72ea9cc85b1b9a3/src/classes/window/presenter.vala#L792-L795

**Comment by fnevgeny** [comment]
> Hmm it seems that the command line command doesn't change `this.gdk_scale`. It seems to be overwritten by the monitor's setting.

That's exactly the point. Monitor settings are unaffected by `GDK_SCALE` under macOS - contrary to Linux. See here:

```
$ pdfpc -M
Monitors: 1
 0: * DisplayPort-3     [1920x1080+0+0@60Hz     scale=100%]

$ GDK_SCALE=2 pdfpc -M
Monitors: 1
 0: * DisplayPort-3     [1920x1080+0+0@60Hz     scale=200%]

```

**Comment by LecrisUT** [comment]
Ok, after doing some digging, I've understand what `GDK_SCALE` is. I see it's `x11` specific so yeah, you're right it would not work for macOS. I've tried to look for an alternative  with no success. The closest I've got is the name of the variable in `quartz` that would need to be changed [backingscalefactor](https://developer.apple.com/documentation/appkit/nswindow/1419459-backingscalefactor).

The only method I have to change the monitor scale factor is to change it in the settings itself.

**Comment by fnevgeny** [comment]
> The only method I have to change the monitor scale factor is to change it in the settings itself.

Which doesn't exist under VM. To summarize, somebody with a native mac hardware should
- check whether it's a macOS or specifically Quartz issue
- write, respectively, Pdfpc.is_macOS/Quartz_backend()
- update the `if` condition
