### ISSUE TITLE
Click to play movies in presentation screen

### ISSUE THREAD

**Issue by hanslovsky** [pdfpc/pdfpc#514]
This is more a question for guidance than a feature request: I want to give a presentation through zoom video conferencing and I have only a single monitor. I start pdf presenter console like this:
```
pdfpc -Ss presentation.pdf
```
Everything works fine, I can click through the presentation and I can see the presentation on the screen share in zoom. I cannot, however, click to play videos. Instead, it just skips to the next slide.  The videos play fine without switching presenter and presentation screens (the `-s` flag), i.e.
```
pdfpc -S presentation.pdf
```

I see two possible solutions to my problem but I have not figured out how to get there.
 1. Click to play videos in presentation screen. Is there a way to activate that?
 2. Have both presentation and presenter screen on the same monitor so I can alt-tab cycle through it. I was unable to achieve that with just the `-S` flag or setting `-1 eDP-1 -2 eDP-1`.

I m running `pdfpc` from Arch Linux.

Thank you for any help and I greatly appreciate this tool. I have used it many times in a multi-monitor setup but this is the first time for me in a single-monitor scenario.

**Comment by hanslovsky** [comment]
I found a solution for my issue, the window mode:
```
pdfpc -w both presentation.pdf
```
I can maximize both windows, then screen share the presentation view and navigate in the presenter view. It works great!

**Comment by AndreasBilke** [comment]
Very good :)

**Comment by fnevgeny** [comment]
I think it should be possible to control the videos from the presentation window, certainly in the single-screen mode. It's actually a regression happened somewhere along the 4.4 development.
