### ISSUE TITLE
Can't quit the application

### ISSUE THREAD

**Issue by jrwrigh** [pdfpc/pdfpc#516]
**Expected Behaviour**
Press <kbd>q</kbd> or <kbd>Esc</kbd> to exit the application

**Actual Behaviour**
Nothing happens. The only way to quit the program is to go to a different window (via keyboard shortcuts since I can't access the toolbar), open a terminal, and kill the program manually

**Steps to reproduce**

1. `pdfpc [any pdf]`

pdfpc version: `v4.4.0`
Used Distribution (GTK version, vala version): Not sure how to determine
Display Server (X/Wayland): X
HiDPI Setting (yes/no): no

This was installed via `pacman`. I'm running a Manjaro machine.

**Comment by fnevgeny** [comment]
Please read the (updated) docs that come with the version you use.

**Comment by jrwrigh** [comment]
Thanks! I was going off a man page online.

For those curious, for my distribution, it was <kbd>Ctrl</kbd>+<kbd>q</kbd>
