### ISSUE TITLE
Cursor for pen tool disappears during annotation

### ISSUE THREAD

**Issue by jolars** [pdfpc/pdfpc#521]
**Expected Behaviour**

Red dot should stay visible while in annotation mode.

**Actual Behaviour**

Red dot cursor for pen tool spuriously disappears while annotating presentations. Sometimes the arrow cursor is visible and the red dot is not, sometimes only the red dot is visible, sometimes both disappear. Changing tools from the annotation tool to another tool (eraser for instance) and then back to annotation tool brings the dot back, but then it will disappear again after a while. Moving the cursor outside the drawing area also brings the cursor back temporarily.

The problem appears both if I am using my wacom tablet and when I am using my mouse.

I've added an animated gif below of the issue.

![pdfpc-bug](https://user-images.githubusercontent.com/13087841/81262537-5106e580-903e-11ea-97b6-3e97bbe6bee2.gif)

**This issue does not to occur with the pdfpc release 4.3.4**

**Steps to reproduce**

1. Start a presentation with pdfpc (settings to -S, -s, -w does not matter)
2. Change to the annotation tool
3. Start drawing

pdfpc version: git 95e8226 and pdfpc release 4.4.0
Used Distribution (GTK version, vala version): Ubuntu 20.04, Vala 0.48.3, gtk 3.24.18
Display Server (X/Wayland): X and Wayland
HiDPI Setting (yes/no): no

EDIT: I tested out the issue with the pdfpc releases 4.4.0 and 4.3.4 and it works on 4.3.4 but not on 4.4.0.

**Comment by jolars** [comment]
I think I've identified out the culprit: ee664f3bf7d4bde31a490c40b4dca0d2ad43e84e

Reverting this commit fixes the problem for me.

**Comment by fnevgeny** [comment]
Please test [this fix](https://github.com/pdfpc/pdfpc/compare/fix-521?expand=1#diff-e6836511538cd7b397c8f6fe030e8e2f).

**Comment by jolars** [comment]
> Please test [this fix](https://github.com/pdfpc/pdfpc/compare/fix-521?expand=1#diff-e6836511538cd7b397c8f6fe030e8e2f).

that does the trick! it works as expected now, thanks.
