### ISSUE TITLE
Keyboard shortcuts are different than indicated in pdfpc-demo.pdf

### ISSUE THREAD

**Issue by avs2** [pdfpc/pdfpc#526]
I notice a lot of the keyboard shortcuts are different on my computer compared to what the `pdfpc-demo.pdf` file says. These are the ones I have been able to find:
- Skipping through a slide with overlays just takes `Up` and `Down`, no `Shift` needed.
- `Shift` + `PageUp` and `Shift` + `PageDown`,  `Shift` + `Up` and `Shift` + `Up`, and `Shift` + `Space` skips 10 slides ahead or back, instead of the indicated functions.
- `M` and `Shift` + `M` don't seem to do anything.
- `N` create an annotation, no `Ctrl` needed.
-  `Ctrl` + `T` doesn't reset the timer. The other timer commands work as documented.
- The laser is activated with `8` instead of `2`
- Drawing is activated with `5` instead of `3`. Toggling between draw and erase is done with `2`.
- Deactivating all drawings with `d` doesn't work.
- `T` does not invoke the toolbox.

I have to add that I am trying to use `pdfpc` together with `jahnf/Projecteur`, but if I quit that application the behavior above is the same so I don't think that is the cause. Any ideas why this is? Thanks for the great software.

pdfpc version: the latest version for "Debian, Ubuntu, and other Debian-based systems"
Used Distribution (GTK version, vala version): Linux Mint 19.3 Cinnamon
Display Server (X/Wayland): Sorry I don't know what this is.
HiDPI Setting (yes/no): Sorry I don't know what this is.

**Comment by fnevgeny** [comment]
The document you downloaded are for the current version. The version you are using is way behind. Please read the pdfpc man page that came with your OS.

**Comment by avs2** [comment]
My apologies if this is super obvious. I installed pdfpc using
```
sudo apt-get install pdf-presenter-console
```
Does that not give me the latest version?

**Comment by fnevgeny** [comment]
It gives you the latest version of what your OS distribution maintainers chose to package.
