### ISSUE TITLE
The note screen is too small since #533

### ISSUE THREAD

**Issue by einhander** [pdfpc/pdfpc#534]
Thank you for #533 it's a really good feature, but the note screen is too small on my 12 inch laptop.
Is there is a way to increase its size or switch it's position with the current slide screen?

**Comment by fnevgeny** [comment]
You can play with `next-height` and `current-size` options in pdfpcrc.

**Comment by fnevgeny** [comment]
Does it help?

**Comment by einhander** [comment]
Yes, thank you.
