### ISSUE TITLE
Multiple videos in the same slide

### ISSUE THREAD

**Issue by gdlg** [pdfpc/pdfpc#537]
Hello,

pdfpc used to support having multiple videos on the same slide, however it seems that this possibility was removed by commit 52808c69b648e9d71729184b64492c88c9748aea.

At least on my machine, the latest master branch hangs on the call to gst_element_get_state when multiple videos are inserted in the same slide:
```
(gdb) f 3
#3  0x0000555555570683 in pdfpc_controlled_movie_init_movie2 (self=0x555555a9f310, movie=0x555555a9f5e0, 
    uri=0x7fff900463c0 "****.mp4", suburi=0x0)
    at /home/***/pdfpc/build/src/classes/action/movie.c:715
715		gst_element_get_state (_tmp2_, NULL, NULL, GST_CLOCK_TIME_NONE);
```

Is it intended or is it a regression?

**Comment by fnevgeny** [comment]
Yes, it is a regression. Somehow, I missed that people might need more than one movie per slide :).

**Comment by gdlg** [comment]
Thanks, I find that having multiple small videos on the same slide is a really useful feature. I did a quick fix by adding a list of videos to View.Video, however I am not sure that’s the proper way of addressing the problem. Should I do a PR?

**Comment by fnevgeny** [comment]
Yes, please do.

**Comment by nebw** [comment]
Would it be possible to release a new version that includes this fix? It's a somewhat major regression and I'd prefer to keep the latest stable version installed.
