### ISSUE TITLE
Add back the window role to differentiate presentation and presenter

### ISSUE THREAD

**Issue by lambtho12** [pdfpc/pdfpc#540]
In commit e1c39d8ed9a79ec711cc5b7a0e9e0fcd89244ba0 , a part of the code common to presentation and presenter was moved to fullscreen. In the process, the `role` attribute was dropped. This attribute is really important for some tiling window manager (such as awesomewm), as it allows to easily differentiate the two windows and ensure their correct display (see issues #66, #79 for instance).

I never used vala before, but I guess something along these lines in `fullscreen.vala` should do it
```vala
this.title = is_presenter ? "presenter" : "presentation";
```

----
pdfpc version: 4.4.0

**Comment by fnevgeny** [comment]
The titles *are* different. See <https://github.com/pdfpc/pdfpc/blob/master/src/classes/window/fullscreen.vala#L128>.

**Comment by lambtho12** [comment]
Sorry my bad. I wanted to say
```vala
this.role = is_presenter ? "presenter" : "presentation";
```

Title are indeed already there. It is the *role* attribute that is missing

**Comment by fnevgeny** [comment]
But why do you need the role attribute set if a distinct title is present? It's X11-specific and, furthermore, "If a window already has a unique title, you don’t need to set the role, since the WM can use the title to identify the window when restoring the session." <https://valadoc.org/gtk+-3.0/Gtk.Window.set_role.html>

**Comment by lambtho12** [comment]
I was trying to replicate [this fix](https://github.com/pdfpc/pdfpc/issues/79#issuecomment-144048607) proposed in #79. This is easier as the role is fixed while the title changes based on the name of the document.
But I guess I can try to filter using the window name and a wildcard or something instead of simply using the role.

**Comment by fnevgeny** [comment]
Just in case, try enabling `move-on-mapped` in pdfpcrc. Maybe you don't need any tricks with titles at all.

**Comment by lambtho12** [comment]
Thank you for this suggestion, but it does not seems to work (the presentation is on the right screen but not in fullscreen).

If anyone is interested, here is the current rule I have that seems to be working ok (it needs more testing to be 100% sure)

```lua
-- PDFPC (Open on top and in fullscreen)
{
    rule_any = { 
        instance = { "pdfpc" }, 
        name = "pdfpc - presentation.*"
    },
    callback = function(c) 
        c:move_to_screen() 
    end,
    properties = { 
        ontop = true,
        maximized = true,
        fullscreen = true
    }
},
```

**Comment by fnevgeny** [comment]
> the presentation is on the right screen

Then `move_to_screen()` in your script is not needed?
