### ISSUE TITLE
Location of pdfpcrc file when install prefix is set.

### ISSUE THREAD

**Issue by gammell** [pdfpc/pdfpc#543]
If you are installing from source and configure `pdfpc` with an install prefix, e.g.,
```
cd pdfpc_git_clone/build/
cmake -DCMAKE_INSTALL_PREFIX="/opt/pdfpc/" ../
make -j
sudo make install
```
then while most files appear under the install prefix as expected
```
$ tree /opt/pdfpc/
/opt/pdfpc/
├── bin
│   └── pdfpc
└── share
    ├── man
    │   ├── man1
    │   │   └── pdfpc.1
    │   └── man5
    │       └── pdfpcrc.5
    └── pixmaps
        └── pdfpc
            ├── blank.svg
            ├── empty.svg
            ├── eraser.svg
            ├── hidden.svg
            ├── highlight.svg
            ├── linewidth.svg
            ├── loaded.svg
            ├── locked.svg
            ├── move.svg
            ├── notes.css
            ├── pause.svg
            ├── pdfpc.css
            ├── pen.svg
            ├── saved.svg
            ├── settings.svg
            └── snow.svg
```
the system-level `pdfpcrc` file does not. It appears in
```
/etc/opt/pdfpc/pdfpcrc
```
I don't know for sure that this is incorrect behaviour, but I've never seen it in any other packages I've installed similarly.

Bonus marks: `/opt/pdfpc/share/man/man5/pdfpcrc.5` correctly says that `/etc/opt/pdfpc/pdfpcrc` is the location of the system-level config file. It's the only way I found it! :slightly_smiling_face: 
```
$ man /opt/pdfpc/share/man/man5/pdfpcrc.5

...

FILES
       /etc/opt/pdfpc/pdfpcrc
           System-wide configuration file

       $XDG_CONFIG_HOME/pdfpc/pdfpcrc
           User configuration file (if $XDG_CONFIG_HOME is not set, $HOME/.config will be used).

```

**Comment by gammell** [comment]
Sorry, I should say that I expected the system-level config to live at:
```
/opt/pdfpc/etc/pdfpcrc
```
i.e., for it to be `$CMAKE_INSTALL_PATH/etc/pdfpcrc` as with `bin` and `share` instead of being `/etc/$CMAKE_INSTALL_PATH/pdfcprc`

**Comment by fnevgeny** [comment]
It's documented: <https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#special-cases>. If you believe it's wrong, file a bug report against cmake.

**Comment by gammell** [comment]
My apologies and thanks for the clarification.
