### ISSUE TITLE
create a list of all the dependencies and how to get 'em

### ISSUE THREAD

**Issue by brkorb** [pdfpc/pdfpc#544]
**Only submit a feature request if you read the SUPPORT.md file**

The feature wish description:
I tried to build, but it choked because it couldn't find Vala.
I got libvala, then it failed on gee. Gee, wiz, how many more?
Hard to answer since I don't know what "gee"is and there are no obvious clues.
I also don't know where to ask a question. So, I ask here. Sorry.

**Comment by fnevgeny** [comment]
Reading [README](https://github.com/pdfpc/pdfpc/blob/master/README.rst) would be a rather obvious first step...
