### ISSUE TITLE
pdfpc and Gstreamer

### ISSUE THREAD

**Issue by olivier-klein** [pdfpc/pdfpc#547]
Hi,
Running the video-example within pdfpc does not work after upgrade on Manjaro. The error message is the following:
Error creating video sink: Could not make element sink0 of type gtksink.
gstreamer seems installed properly. The following command works
gst-play-1.0 --videosink gtksink apollo17.avi
Any idea of what needs to be fixed?
Best,
Oli

**Comment by fnevgeny** [comment]
> The following command works
> gst-play-1.0 --videosink gtksink apollo17.avi

Without _any_ warning?

**Comment by olivier-klein** [comment]
Yes,uou are right, I do notice now that there is indeed a warning
** (gst-play-1.0:163473): WARNING **: 20:35:40.344: Couldn't create specified video sink 'gtksink'

for info gstreamer is version 1.16.2-2 there is also the 32 bit lib installed: lib32-gstreamer

**Comment by fnevgeny** [comment]
Well, then you should read the [FAQ](https://github.com/pdfpc/pdfpc/blob/master/FAQ.rst)...

**Comment by olivier-klein** [comment]
Thanks. Installing the package gst-plugin-gtk did the trick and solved the issue on arch-linux.
I guess the codec was previously supported by some other package (probably gst-plugins-good) and this dependecy dissapered after some clean-up effort inside the different libraries. I will contact the package maintainer to notify this change.
Best,
