### ISSUE TITLE
Allow users to UNDO strokes/actions when drawing

### ISSUE THREAD

**Issue by danilocesar** [pdfpc/pdfpc#548]
Here's a common situation:

You're there, making your presentation and drawing a bit on top of a page, when you make a mistake.
Mistakes happens, sometimes it's easier to just go there and erase it. Sometimes it isn't.

Would be really helpful to add a new shortcut "CTRL+Z" that removes the last action/stroke from the user. The past X actions can be stored so the user can revert the last X actions.

- When an action ends (eg: mouse button up or pen up), the current buffer is saved in a list of buffers.
- When a new action starts and ends, a new buffer is copied in the same list.
- When CTRL+Z is pressed, the latest item is thrown away and the top buffer is now presented.
- When the buffer list gets bigger than X, drop the first item.

Something like this ^
Since storing cairo buffers might be very memory consuming, an optimization would be to change the on_move method to store each action. then only two buffers per page would be required, one older, a list of actions, then the current one, when  OLD+Action=current one. If the list gets bigger than X, then the oldest stroke is drawn into the old buffer (making that action irreversible) and dropped from the list.

**Comment by jkudla** [comment]
I started trying to implement this.

However, I struggle here: `set_surface` seems to change nothing in all my experiments, while `set_new_surface` immediately clears the drawing. Is it necessary to call some update method? I tried queue_pen_surface_draws. Also using `save` and `restore` on the `Cairo.Context` didn't work.

**Comment by fnevgeny** [comment]
Showing the actual code might help...

**Comment by dov** [comment]
Regarding the implementation, here's alternate possible method. Don't store the image buffers, but store all the cairo lineto and moveto actions in a list. On Control-Z do the following:

* Erase all the current overlay
* Remember the bounding box of the drawing command list
* pop all drawing commands from the end of the drawing command until (and including) a previous moveto command
* Redraw the new drawing list to the overlay buffer
* Reexpose the rectangle of the previous bounding box.
* (An optimization is to reexpose only the **difference** between the current and the previous bounding boxes)

This should be fast enough for a few thousand drawing commands in my opinion.

**Comment by fnevgeny** [comment]
See https://github.com/pdfpc/pdfpc/issues/518#issuecomment-665133480

**Comment by dov** [comment]
FYI: I started working on this and made a first implementation. See: https://github.com/pdfpc/pdfpc/pull/644 .

I'll be happy to get comments about my implementation, as I have not done much Vala programming, during the last decade. :-)

**Comment by fnevgeny** [comment]
Implemented by #644.
