### ISSUE TITLE
Help does not show up?

### ISSUE THREAD

**Issue by tobiasBora** [pdfpc/pdfpc#551]
**Expected Behaviour**

When I press `?` (Azerty layout), I can't see any help message, or any change. I also tried to press `Shift + !` (should map to Qwerty `?`), same issue.

**Actual Behaviour**

I'd expect the help menu to show up.

**Steps to reproduce**

1. start `pdfpc` on any pdf (like the `demo` one, I use `pdfpc` distributed from nixpkgs 20.03 on a nixos 20.03 system)
2. press `?`

pdfpc version: 4.3.4
Used Distribution (GTK version, vala version): 3.24.21/2.24.32
Display Server (X/Wayland): X, libX11 1.6.8
HiDPI Setting (yes/no): no

**Comment by fnevgeny** [comment]
This was added in v4.4.0.
