### ISSUE TITLE
Hide unwanted PDF note icon

### ISSUE THREAD

**Issue by rddunphy** [pdfpc/pdfpc#552]
Not really sure if this is a bug or if I'm missing something obvious, in which case apologies! 

When I open a PDF slideshow with notes inserted using the `\pdfpcnote` Latex command, an icon representing the note is sometimes displayed. On my native PDF viewer this icon appears on every slide, but in pdfpc it looks like it only appears on overlay slides. Here's a minimal working example:

![pdfpc_note](https://user-images.githubusercontent.com/10012625/95371801-99b71900-08d2-11eb-9983-1ec836c6861e.png)

**Steps to reproduce**

Compile the example with PdfTex and open it in pdfpc:

```latex
\documentclass[aspectratio=1610]{beamer}
\usepackage{pdfpc}

\begin{document}
\begin{frame}[plain]
    \begin{itemize}
    \item<+-> test1
    \item<+-> test2
    \end{itemize}
    \pdfpcnote{a note}
\end{frame}
\end{document}
```

pdfpc version: v4.3.4
Used Distribution (GTK version, vala version): GTK
Display Server (X/Wayland): X
HiDPI Setting (yes/no): yes

**Comment by fnevgeny** [comment]
It will probably be fixed by #239.
