### ISSUE TITLE
Ctrl+o not working

### ISSUE THREAD

**Issue by TMueller83** [pdfpc/pdfpc#554]
**Expected Behaviour**
According to the man page the `Ctrl+o` shortcut should manually define overlay pages. In v4.4.0 this shortcut seems to do nothing.

Could you please tell me, how the entries in the `pdfpc` file defining the overlays should look, such that I can put the overlays manually for the time beeing? Thank you very much in advance!

One last question: Is there any documentation on the `pdfpc` files other than the one provided in the man page (I think the man page does not list all the command-line options available in the `pdfpc` files)?

**Actual Behaviour**
In v4.4.0 nothing seems to happen upon pressing `Ctrl+o`.

**Steps to reproduce**

1. Open a random pdf file with pdfpc (possibly with the `-g` option to disable automatic grouping)
2. Press `Ctrl+o` on any page
3. Nothing happens

pdfpc version: 4.4.0
Used Distribution (GTK version, vala version): GTK 3.22.30, Vala 0.40.24
Display Server (X/Wayland): X
HiDPI Setting (yes/no): no

**Comment by TMueller83** [comment]
I have played a bit with the code and I think I have more or less located the problem: If I understand it right the `Ctrl+o` shortcut triggers the `overlay` action, which in turn calls the function `toggle_skip` defined in `src/classes/presentation_controller.vala`. However, the function `toggle_skip` seems to have some problems.

- If one is in overview mode this function is not called at all when `Ctrl+o` is pressed, which is probably not the intended behaviour.
- I assume that outside of overview mode (i.e., if `overview_shown=false`) the function should probably call `this.metadata.toggle_skip()` somewhere, but it doesnt. I have tried to modify the function in the following way
  ```c
        protected void toggle_skip() {
            if (overview_shown) {
                int user_selected = this.overview.current_slide;
                int slide_number = this.metadata.user_slide_to_real_slide(user_selected);
                if (this.metadata.toggle_skip(slide_number, user_selected) != 0) {
                    this.overview.remove_current(this.user_n_slides);
                }
            } else {
                int user_selected = this.current_slide_number;
                int slide_number = this.metadata.user_slide_to_real_slide(user_selected);
                this.metadata.toggle_skip(slide_number, user_selected);
                this.overview.set_n_slides(this.user_n_slides);
                this.controllables_update();
            }
        }
  ```
  and this already leads to some kind of the expected behavior, but its not quite right. Maybe this helps already a bit to fix this issue.

**Comment by fnevgeny** [comment]
The format of the .pdfpc files will very likely change in v4.5. If you are *very* adventurous, you can try the ["pdfpc" branch](https://github.com/pdfpc/pdfpc/tree/pdfpc).

**Comment by TMueller83** [comment]
Hi @fnevgeny, thank you for you answer! I have just tested the "pdfpc" branch and I can confirm that `Ctrl+o` works as expected in this branch if one is in normal view (presenter) mode. However, even in this branch `Ctrl+o` seems to do nothing in overview mode (i.e., the view obtained after pressing `Tab`), which is probably not the intended behavior.

**Comment by fnevgeny** [comment]
Well, as far as I'm concerned, it **is** the intended behavior. BTW, why do you need this feature - because the authoring software you use is incapable of grouping (read: labeling) slides properly, or you're just given a presentation from elsewhere that needs to be fixed?

**Comment by TMueller83** [comment]
Hi @fnevgeny, I need this feature because I am using a presentation that was created with LaTeX-Beamer using the package `pgfpages` and the Beamer option `show notes on second screen`. This screws the page numbering completely, such that I need to add the overlays manually.

**Comment by fnevgeny** [comment]
Well, if you're fully sold to LaTeX for formatting the notes, that's the only way. Otherwise, you can use Markdown (in the current branch) which in principle lets you do arbitrarily rich stuff, too. And you can do it from within the document itself using pdfpc.sty.

**Comment by TMueller83** [comment]
Hey @fnevgeny, thank you for pointing out the possibility to use Markdown, which is actually also really cool. But I have already formatted all my notes with LaTeX and I just needed a possibility to add the overlays manually. But I already figured it out by myself, using the `[skip]` section in the `.pdfpc` file, where I just write the overlay pages by hand for the time beeing and it works perfectly fine. I just wanted to report this bug in order to try helping a bit with the development and maintenance, since I think pdfpc is a really cool program and maybe other users stumble about this bug in the future too.

**Comment by LinuxOnTheDesktop** [comment]
Might I add the following? (If not, I'll create a new issue.)

I am displaying slides creating in PowerPoint. To that I used PowerPoint's 'export' -> PDF function. That function itself has some rather hidden options but, not knowing what (if anything) to do with them, I left that at defaults. When I display the resulting PDF in pdfpc, there are no 'overlays', i.e. page-elements-appearing-upon-click, though those things existed in my original PowerPoint. So: I tried pressing ctrl-O, within pdpc. So doing create a rather small image of . . my previous slide. Is this a bug? At the least there seems a lack of documentation. _Perhaps one is meant to be working from a PDF which contains overlay elements as separate slides. If so, how can PowerPoint create such slides?_ Thanks. (I will be giving a presentation soon and if I can't get overlays working I'll have to resort to LibreOffice Impress - despite its changing of my fonts - or else I'll have to use PowerPoint within a VM.)

**Comment by AndreasBilke** [comment]
@LinuxOnTheDesktop The manual overlay marking should be agnostic to the pdf creating program. Maybe it's better you create a separate issue with some MWE.

**Comment by LinuxOnTheDesktop** [comment]
Thanks, Andreas.

(1) 'The manual overlay marking should be agnostic to the pdf creating program': I do not understand. Do you mean that 'manual overlay marking' should work irrespective of the pre-existing state of the slides?

 (2) What do you mean by 'MWE'?

(3) Can pdfpc show overlays that were created in PowerPoint?

**Comment by AndreasBilke** [comment]
> (1) 'The manual overlay marking should be agnostic to the pdf creating
> program': I do not understand. Do you mean that 'manual overlay marking'
> should work irrespective of the pre-existing state of the slides?

It should not matter if the slides where created with LaTeX, Powerpoint or
some thing else. The manual overlay marking should aways work.

> 
>  (2) What do you mean by 'MWE'?

A minimum working example where your described effect happens.

> 
> (3) Can pdfpc show overlays that were created in PowerPoint?

Probably not (if there is no in-file marking of slides which are overlays)

**Comment by LinuxOnTheDesktop** [comment]
Thanks. And sorry to go on, but . .

i) _Are there instructions anywhere on how manually to set up overlays?_

ii) _It would be good for users and prospective users of pdfpc to know (via documentation somewhere) whether or not a vanilla PowerPoint file containing overlays will have its overlays retained_ by pdfpc. I fear that the thing that those people should be told that such a file will not retain its overlays. If so, then:

iii) It would be good were vanilla PowerPoint overlays to work in pdfpc.

One reason that I have not provided a 'MWE' is as follows. As I hope _i_ and _ii_ make clear, at present I do not know what is meant to work (native PowerPoint overlays?) and how it is meant to work. (How does one setup manual overlays?)

**Comment by HermannDppes** [comment]
> Perhaps one is meant to be working from a PDF which contains overlay elements as separate slides.

Yes, one is. I thought that understandable from the documentation but perhaps it is not. Do you have any idea where in the documentation of overlays phrasing something differently would have made that clearer to you?

> i) Are there instructions anywhere on how manually to set up overlays?

Yes: “If your preferred slide-producing method does not work correctly with this detection, you can supply this information using the 'Ctrl + o' key for each slide that is part of an overlay (except the first one!).” Are these not clear enough? Or not findable enough?

> If [one needs separate slides], how can PowerPoint create such slides?

> ii) It would be good for users and prospective users of pdfpc to know (via documentation somewhere) whether or not a vanilla PowerPoint file containing overlays will have its overlays retained by pdfpc.

This assertion as-stated is next to meaningless as pdfpc does not display “vanilla PowerPoint file[s]” and thus asking whether anything in them is preserved by pdfpc gets rather confusing when they aren't touched at all. The probably-intended question whether PowerPoint exports overlays in a way that pdfpc does automatically detect, in some configuration of settings, and how that should be documented in pdfpc definitely seems like a separate issue to me.

> iii) It would be good were vanilla PowerPoint overlays to work in pdfpc.

Yes, it might be. But unless PowerPoint produces PDF files where it is at the very least *possible* to figure out what goes when, there is not much pdfpc can do.

**Comment by LinuxOnTheDesktop** [comment]
@HermannDppes thank you for your reply.

**I The _findability_ of overlay instructions**

It would be good were the README (and thus the landing page of the github website) to include a reference to the _manual_. To that end, the text,

> If you encounter problems while running pdfpc, please consult the [FAQ](https://github.com/pdfpc/pdfpc/blob/master/FAQ.rst) first

could be amended to mention, additionally, the manual (which is to say, `man pdfpc`).

**II The _adequacy_ of overlay instructions**

The following instruction is too sparse.

> [Y]ou can supply this information using the 'Ctrl + o' key for each slide that is part of an overlay (except the first one!)

Say I have two slides of the following nature. The first contains elements 1.1 and 1.2, each of which should appear upon a separate click. The second slide is the same - it contains 2.1 and 2.2, each of which should appear upon a separate click. The instructions do not tell me how to achieve that result. Am I meant to put each element (1.1 etc.) on a separate slide, and then, in pdfpc, view each of those slides in turn, pressing ctrl-o each time? If so, then the instructions should say so. If not, then the instructions should tell me what I _should_ do.

**III On pdfpc being able to reproduce PowerPoint overlays**

'Vanilla PowerPoint files': yes, my mistake; I meant to speak of vanilla _PDF_ files, exported from PowerPoint. By 'vanilla' I mean to convey that nothing special has been done with those files. Rather, and merely, the following took place. The user used PowerPoint to create a presentation; then the user exported the Presentation as PDF, and did so using the default settings for that action.

If PointPoint cannot export PDFs in such a way as to retain overlay information, then indeed pdfpc cannot render those overlays. But _is there_ some PowerPoint option that allows exported PDFs to preserve that information? It seems to me that the pdfpc documentation should answer that question. For, it seems to me that using PowerPoint-generated overlays is something that some people will want to do with pdfpc. But all of this (viz., _III_) is indeed not a problem with 'ctrl-o' and so probably should indeed have its own github 'issue'.

**Comment by HermannDppes** [comment]
> The following instruction is too sparse.

Well, I only quoted the part I thought most relevant for that very specific question. The full section Overlay reads:

> Many slide preparation systems allow for overlays, i.e.  sets of slides that are logically grouped together as a single, changing slide.  Examples include enumerations where bullet items are displayed one after another, or rough "animations", where parts of a picture change from slide  to  slide.  Pdfpc includes facilities for dealing with such overlays.
>
> In  this  description, we will differentiate between slides (i.e.  pages in the PDF document) and "user slides", that are the logical slides.  The standard forward movement command (page down, enter, etc.) moves through one slide at a time, as expected.  This means that every step in the overlay is traversed.  The backward movement command works differently depending on whether the current and previous slides are part of an overlay:
>
> * If the current slide is part of an overlay we just jump to the previous slide.  That means that we are in the middle of an overlay and can jump forward and backward through the single steps of it
>
> * If the current slide is not part of an overlay (or if it is the first one), but the previous slides are, we jump to the previous user slide.  This means that when going back in the presentation you do not have to go through every step of the overlay, pdfpc just shows the first slide of  each  overlay.
>   As one typically goes back in a presentation only when looking for a concrete slide, this is more convenient.
>
> The Shift + Page up/down key combinations work on the "user slide" basis.  You can use them to skip the rest of an overlay or to jump to the previous user slide, ignoring the state of the current slide.
>
> When going through an overlay, two additional previews may be activated in the presenter view, just below the main view, showing the next and the previous slide in an overlay.
>
> Pdfpc  tries to find these overlays automatically by looking into the page labels in the PDF file.  For LaTeX this works correctly at least with the beamer class and also modifying the page numbers manually (compiling with pdflatex).  If your preferred slide-producing method does not work correctly with this detection, you can supply this information using the 'Ctrl + o' key for each slide that is part of an overlay (except the first one!).  The page numbering is also adapted.  This information is automatically stored.

---

> Say I have two slides of the following nature. The first contains elements 1.1 and 1.2, each of which should appear upon a separate click. The second slide is the same - it contains 2.1 and 2.2, each of which should appear upon a separate click. The instructions do not tell me how to achieve that result. Am I meant to put each element (1.1 etc.) on a separate slide, and then, in pdfpc, view each of those slides in turn, pressing ctrl-o each time? If so, then the instructions should say so.

Yes,¹ and I would say the instructions say so. Otherwise, the rule about overlays consisting of multiple PDF pages which we want to perceive as a single slide is violated.

¹: Well, to be less ambiguous, you would probably want to have four (or six) slides, (one with nothing,) one with 1.1, one with 1.1 and 1.2, (one with nothing,) one with 2.1 and finally one with 2.1 and 2.2. Then you should press ctrl+o on both complete (and both other non-empty) slides. So that when just displaying the pages of the PDF in order, it looks as you intend it to look in the presentation. But I'm uncertain how you want it to look, because describing it in text instead of showing something sure increases ambiguity about matters of visual presentation (even though it is admittedly faster than having to download any files).

---

> But all of this (viz., III) is indeed not a problem with 'ctrl-o' and so probably should indeed have its own github 'issue'.

Then I'll refrain from commenting further in this issue.
