### ISSUE TITLE
Missing webkit-gtk when building from source macOS

### ISSUE THREAD

**Issue by AnselmC** [pdfpc/pdfpc#555]
**Expected Behaviour**
Can build `pdfpc` from source following instructions in README.

**Actual Behaviour**
`cmake` fails w/ following output
```
➜  build git:(master) cmake ..
-- The C compiler identification is AppleClang 10.0.1.10010046
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Vala: /usr/local/bin/valac (found suitable version "0.48.11", minimum required is "0.34") 
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'gobject-2.0'
--   Found gobject-2.0, version 2.66.2
-- Checking for module 'gio-2.0'
--   Found gio-2.0, version 2.66.2
-- Checking for module 'gee-0.8'
--   Found gee-0.8, version 0.20.3
-- Checking for module 'poppler-glib>=0.22'
--   Found poppler-glib, version 20.10.0
-- Checking for module 'gtk+-3.0>=3.22'
--   Found gtk+-3.0, version 3.24.23
-- Checking for module 'webkit2gtk-4.0'
--   No package 'webkit2gtk-4.0' found
CMake Error at /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/FindPkgConfig.cmake:545 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)
  src/CMakeLists.txt:7 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
```

From what I understand `webkit-gtk` is not available for macOS. Any tips on how to build this?
My motivation is that I need multiple videos in a slide and there hasn't been a release with that feature/fix yet.

I also tried to install version 4.3.4 and here `cmake` works but the source code doesn't compile with the installed `vala` version from `brew install --only-dependencies pdfpc`.

**Steps to reproduce**

1. clone repo: `git clone git@github.com:pdfpc/pdfpc.git`
2. install deps: `brew install --only-dependencies pdfpc`
3. attempt build: `cd pdfpc && mkdir build && cd build && cmake ..`

pdfpc version: master branch
Used Distribution (GTK version, vala version):3.22,  0.48.11

**Comment by fnevgeny** [comment]
There is a macport https://ports.macports.org/port/webkit2-gtk/, so I see no reason why homebrew wouldn't exist.

**Comment by AnselmC** [comment]
Unfortunately its not available on homebrew. I guess only option is to install macports only for this...

**Comment by fnevgeny** [comment]
Well, since it exists in macports I assume it should be mostly a trivial exercise to compile it under homebrew. I suggest you give it a try or ask help from someone @ homebrew.  Nobody from the core pdfpc developers works with macOS, sorry.

**Comment by AnselmC** [comment]
Sure, it works fine. I'd just suggest to update the readme instructions to clarify on this issue. If you'd like I can create a PR for that

**Comment by fnevgeny** [comment]
Hmm, to clarify what exactly?

**Comment by AnselmC** [comment]
<img width="973" alt="image" src="https://user-images.githubusercontent.com/22545864/98132008-3530af00-1ebc-11eb-9818-622996e567ae.png">
that webkit-gtk isn't currently available on homebrew and hence needs to be installed via macports

**Comment by fnevgeny** [comment]
I assume that once pdfpc-4.5 is released, whoever takes care of its homebrew build will fix the issue of webkit in some way. At which point the readme will become correct as is. And, BTW, it is correct as is now, as far as the officially *released* version of pdfpc is concerned. I again suggest you to seek help with this distro-specific problem elsewhere...

**Comment by JuliDi** [comment]
> There is a macport https://ports.macports.org/port/webkit2-gtk/, so I see no reason why homebrew wouldn't exist.

Looks like this does not work anymore on the latest macos version. Installing via macports fails now, too, because a dependency (gupnp-igd) can't be installed (see https://ports.macports.org/port/gupnp-igd/summary).

If anyone has an idea of how to get webkit2-gtk installed on Big Sur, I'd really appreciate that.
As of now it doesn't seem possible to install v4.5 of pdfpc on macos.

**Comment by fnevgeny** [comment]
Well, hopefully this will be resolved soon. webkit2-gtk is used in many projects.
