### ISSUE TITLE
Notes are invisible as it is grey text on a grey background

### ISSUE THREAD

**Issue by github-jnauta** [pdfpc/pdfpc#557]
**Expected Behaviour**
When upgrading pdfpc from 4.1.x to the latest release of 4.4.0, the notes are not displayed properly but appear to be grey text on a grey background. Thus, when I use ctrl+n and type a new note, it does appear in the `.pdfpc` file, but I cannot see it in the presenter mode as shown below.

![image](https://user-images.githubusercontent.com/26090403/97083743-8619eb00-1612-11eb-95e1-0a71f74df5b3.png)

It used to work in the 4.1.x version installed through `apt-get`, but now my notes fail to appear. Any idea what can cause this, since I have found others that have successfully used notes in the latest version?

**Code used to reproduce error**
`test.tex`
```
\documentclass[aspectratio=169]{beamer}
\usetheme{CambridgeUS}

\begin{document}
    \begin{frame}
        \frametitle{Frame 1}
        Some text
    \end{frame}
    \begin{frame}
        \frametitle{Frame 2}
        Some more text
    \end{frame}
\end{document}
```

`test.pdfpc`
```
[duration]
0
[notes]
### 1
Some text
### 2
Some more text
```

pdfpc version: 4.4.0
Used Distribution (GTK version, vala version):
Display Server (X/Wayland): 
HiDPI Setting (yes/no):

**Comment by fnevgeny** [comment]
Please see #511.

**Comment by github-jnauta** [comment]
Thanks, seemed to do the trick. Simply `export GTK_IM_MODULE=uim` works and makes the notes appear again.

**Comment by fnevgeny** [comment]
Do you really need xim for other apps at all?
