### ISSUE TITLE
Pausing changes size of screen content

### ISSUE THREAD

**Issue by BeastyBlacksmith** [pdfpc/pdfpc#558]
**Expected Behaviour**

Pressing `p` to pause only stops the timer

**Actual Behaviour**

It also changes the size of the slides in the presenter view ( just like when using the pointer ) which causes the notes to move off screen.

**Steps to reproduce**

1. Start presentation
2. Press `p`

pdfpc version: 4.4.0
Used Distribution (GTK version, vala version): Vala 0.48.11, GTK 3.24.23
Display Server (X/Wayland): X
HiDPI Setting (yes/no): I don't think so.

This was on MacOS 10.15.7 in windowed mode

**Comment by fnevgeny** [comment]
I cannot reproduce it; but I have only a VM mac.

> just like when using the pointer

What do you mean?

**Comment by BeastyBlacksmith** [comment]
I uploaded a screencapture [here](https://www.dropbox.com/s/9omp7zc88ajywsg/pdfpc-bug.mp4?dl=0)

**Comment by fnevgeny** [comment]
Do you observe this with *any* presentation (e.g., our [standard demo](https://github.com/pdfpc/pdfpc/releases/latest/download/pdfpc-demo.pdf)) or only this specific file?

BTW, why do you need "-w presentation"? Frankly, I was sure nobody would ever use it :).

**Comment by BeastyBlacksmith** [comment]
For screensharing, because Cisco Webex did not recognize the windows of pdfpc, so I couldn't just share the presentation window, but had to share the whole desktop.
Will check with the demo and report back

**Comment by fnevgeny** [comment]
Sorry, I don't understand. `-w presentation` puts the **presentation** window (on the second display) in the windowed mode, while the presenter remains full-screen, as indeed seen in the video capture you provided.

**Comment by BeastyBlacksmith** [comment]
> Do you observe this with any presentation (e.g., our standard demo) or only this specific file?

Same thing happens with the standard demo ( after I added notes ).

> presentation window (on the second display) in the windowed mode,

I see, I misunderstood then

**Comment by fnevgeny** [comment]
Do you actually have a dual-screen setup? Try enforcing the windowed option indeed, `-w both`, and/or single-screen variant `-S`.

**Comment by fnevgeny** [comment]
And, how was pdfpc compiled - is it a homebrew or ports build?

**Comment by BeastyBlacksmith** [comment]
Its happing in all modes. It is a homebrew build

**Comment by fnevgeny** [comment]
Can you check whether it also happens on another mac?

**Comment by fnevgeny** [comment]
@BeastyBlacksmith please try #692, probably it will fix your issue.

**Comment by fnevgeny** [comment]
Assuming it's fixed.
