### ISSUE TITLE
Change size of presenter window in windowed mode

### ISSUE THREAD

**Issue by owenjm** [pdfpc/pdfpc#560]
Currently only the presentation window can be resized in windowed mode (via the -Z flag).  I cannot find any means to resize the presenter window, which is quite small on my 4k monitor.  In this brave new zoom-based world (which makes the windowed presentation mode far more useful) it would be a handy option to have.

If I am missing something obvious (and I feel I must be) then my apologies.

**Comment by fnevgeny** [comment]
Resize as you would any other application window.

**Comment by owenjm** [comment]
Thanks for your quick reply -- unfortunately, this doesn't work with Compiz
/ Unity: resize is not allowed.  Looking with xprop on the presenter
window, this seems to be the issue:

WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified minimum size: 1920 by 1080
                program specified maximum size: 1920 by 1080
                program specified base size: 0 by 0
                window gravity: NorthWest

So, it appears my windowmanager is just following instructions by not
allowing resizing ...?

**Comment by owenjm** [comment]
Ah, please ignore -- seems I was using ubuntu's older pdfpc rather than the
one I'd build from git.  When I correctly run the right software, resizing
(of both windows) is possible via the usual way.  My bad, and apologies.

**Comment by fnevgeny** [comment]
Ah yes, I forgot that Ubuntu still ships 4.3.
