### ISSUE TITLE
Two movies on one slide

### ISSUE THREAD

**Issue by seijiadachi** [pdfpc/pdfpc#561]
I'd like to show multiple movies on a singe slide. As a try, Evgeny Stambulchik's video-example was modified so that two (identical) movies were placed on one single slide. It was compiled with lualatex and the generated pdf file was opened with pdfpc. When moving to the slide with two movies, 

Expected Behaviour
pdfpc shows this slide and the movies on it. 

Actual Behaviour
pdfpc seems dead while displaying the previous slide. No keys work except for shutting it down forcibly. 

Steps to reproduce
1. $ lualatex twoMoviesMode1.tex
2. $ pdfpc twoMoviesMode1.pdf
3. go to page 4 and then go further by clicking on the right cursor key, for example. 

pdfpc version:
Used Distribution (GTK version, vala version): ??? Version 4.4.0-1, installed from a package of debian bullseye
Display Server (X/Wayland): must be X
HiDPI Setting (yes/no): ???

[twoMoviesMode1.zip](https://github.com/pdfpc/pdfpc/files/5502202/twoMoviesMode1.zip)

**Comment by fnevgeny** [comment]
Same as #537. @AndreasBilke we need to release 4.4.1 :).

**Comment by AndreasBilke** [comment]
@fnevgeny Is the current master suitable for 4.4.1 or do we need to cherry
pick changes?

**Comment by fnevgeny** [comment]
No, the master will become 4.5. We have the 4.4-maintenance branch that needs to cherry pick simple bug fixes.
