### ISSUE TITLE
Is master branch where development happens?

### ISSUE THREAD

**Issue by wentasah** [pdfpc/pdfpc#564]
It seems that development now happens on pdfpc branch, but github shows the master branch, which is not updated, by default (see https://github.com/pdfpc/pdfpc/). If this is the case, please [switch](https://github.com/pdfpc/pdfpc/settings/branches) the default branch to pdfpc so that github visitors see the latest updates.

**Comment by fnevgeny** [comment]
No, master is the development branch. "pdfpc" was (in retrospect, confusingly) named for working on the new .pdfpc file format. #556.

**Comment by wentasah** [comment]
Thanks. I was confused by 8cb735f ("Give the CL "windowed" option precedence over pdfpcrc", 2020-11-06), which is in _4.4-maintenance_ and _pdfpc_ but not in _master_.
