### ISSUE TITLE
pdfpc video crash

### ISSUE THREAD

**Issue by rs-11** [pdfpc/pdfpc#566]
**Expected Behaviour**
when opening the embedded video sample presentation and clicking on the video, it should play.

**Actual Behaviour**
pdfpc crashes when I click on video. Console output:
```
Could not acquire DBus bus.
Segmentation fault: 11
```

**Steps to reproduce**

1. install pdfpc on mac via brew
2. download sample video file
3. launch pdfpc on said pdf with ``pdfpc video-example.pdf``
4. scroll to the video and click on it.

pdfpc version: pdfpc 4.4.1
Used Distribution (GTK version, vala version): MacOS Big Sur; gtk+3 3.24.24; vala 0.50.2
Display Server (X/Wayland): default MacOS BigSur
HiDPI Setting (yes/no): not applicable on mac

**Comment by fnevgeny** [comment]
> MacOS Big Sur

To me, it says exactly nothing. If you need a macOS-specific help, file a bug report against the brew port. Otherwise, do fill in **all the fields** as requested.

**Comment by rs-11** [comment]
Hi, I added gtk+3 and vala versions. If you need any more info, please tell me where I can find it. Thanks!

**Comment by fnevgeny** [comment]
Well, you report a bug in pdfpc, and don't tell which version of pdfpc... even after reminding to fill in all entries... Also, did you read the [FAQ](https://github.com/pdfpc/pdfpc/blob/master/FAQ.rst)?

**Comment by rs-11** [comment]
Yes I read them! I am well aware that this is likely an issue on my end, but I was not yet able to figure it out yet. I am quite a newbie with such things. I hoped you could help me, but it is fine you don't have time to do so.
The thing you mentioned in de FAQ I also couldn't get to work, but I'll try again.
Thanks anyway!
