### ISSUE TITLE
Update CHANGELOG

### ISSUE THREAD

**Issue by Toromtomtom** [pdfpc/pdfpc#568]
I guess this is more of a meta-issue. I see that there was a 4.4.1 release, but the CHANGELOG and the Releases page give no information on the changes since 4.4.0. Is this a bug-fix release that all users should upgrade too? Is there some other place where this release was announced?

**Comment by fnevgeny** [comment]
> I see that there was a 4.4.1 release, but the CHANGELOG

It's in the [CHANGELOG](https://github.com/pdfpc/pdfpc/blob/4.4-maintenance/CHANGELOG.txt) of the 4.4-maintenance branch.

> and the Releases page give no information on the changes since 4.4.0.

Updated, thanks.
