### ISSUE TITLE
Video playback in arch failing

### ISSUE THREAD

**Issue by mil-ad** [pdfpc/pdfpc#574]
I get the following error when trying the video demo presentation on Arch:

```
Error creating video sink: Could not make element sink0 of type gtksink.
Gstreamer installation may be incomplete.
```

I have `gstreamer 1.18.2-1` and `gst-plugins-good 1.18.2-1` installed.

I saw similar issues (e.g. #423) for other OSs.

pdfpc version: pdfpc v4.5
Used Distribution (GTK version, vala version): Manjaro
Display Server (X/Wayland): X
HiDPI Setting (yes/no): Yes

**Comment by fnevgeny** [comment]
Have you read the [FAQ](https://github.com/pdfpc/pdfpc/blob/master/FAQ.rst)?

**Comment by mil-ad** [comment]
Thanks @fnevgeny somehow missed the FAQ. So installing `gst-plugin-gtk` package did the trick.

However, I think I'm running into a separate issue which may be by design. Is video playback expected to work with `--single-screen` option? I'm currently testing this with a single monitor and when I do `pdfpc -Ss video-example.pdf` to get presentation view on a single screen clicking on the video simply goes to the next slide.

**Comment by fnevgeny** [comment]
It's kinda by design in the sense that when both the presenter and presentation screens are there (which is the default), the user control/interaction is supposed to be only within the context of the presenter. See some discussion, especially towards the end, here - #518.

**Comment by mil-ad** [comment]
I see. I guess my use case is doing presentations over Zoom or something. In that case I want pdfpc to act as a fancy single window PDF viewer.

**Comment by fnevgeny** [comment]
Well, my last comment in #518 indicates I agree that in the single-window mode such a functionality should be enabled in the presentation window. So feel free to open a ticket for the video playback control :).

**Comment by sesselastronaut** [comment]
> Thanks @fnevgeny somehow missed the FAQ. So installing `gst-plugin-gtk` package did the trick.
> 
> However, I think I'm running into a separate issue which may be by design. Is video playback expected to work with `--single-screen` option? I'm currently testing this with a single monitor and when I do `pdfpc -Ss video-example.pdf` to get presentation view on a single screen clicking on the video simply goes to the next slide.

I'm having a similar issue on single and dual screen. Running the example and clicking on the video moves the presentation on too the next slide instead of playing the video. Only Example 3 starts playing by itself as it should.
