### ISSUE TITLE
Reorganize installation structure

### ISSUE THREAD

**Issue by fnevgeny** [pdfpc/pdfpc#575]
I think the current installation scheme is confusing. E.g., the SVG icons go to `$(PREFIX)/share/pixmaps/pdfpc`. Strictly speaking, SVG is not a pixmap format, but more importantly, these icons in fact are private pdfpc GUI resources, which no other app should be interested to reuse. Same directory also holds CSS files, and it is already beyond any doubt that this is not the right place.

I suggest instead to organize everything under `$(PREFIX)/share/pdfpc`, probably with further subdirectories like `icons` and `css`. Not sure about `pdfpcrc`, maybe it should move there as well.

**Comment by AndreasBilke** [comment]
> I suggest instead to organize everything under `$(PREFIX)/share/pdfpc`,
> probably with further subdirectories like `icons` and `css`. Not sure
> about `pdfpcrc`, maybe it should move there as well.

I agree except with the pdfpcrc file. This is a config file and belongs to
/etc

**Comment by fnevgeny** [comment]
The problems with pdfpcrc as the configuration file:
1. We overwrite it with `make install`.
2. Without the file, pdfpc is unusable.

Given 1, I don't think people store any modifications there. Together with 2, this makes it a "read-only architecture independent data file" (https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html)...
