### ISSUE TITLE
Can't set notes position 

### ISSUE THREAD

**Issue by sesselastronaut** [pdfpc/pdfpc#576]
**Expected Behaviour**
Setting the notes position to bottom or left and calling the presentation with the corresponding option `pdfpc --notes=left` or `bottom` should change the position.
**Actual Behaviour**
With either option `bottom` or `left` the notes stay on the right hand bottom corner of the presenter screen.
**Steps to reproduce**
1.MWE
```
\documentclass{beamer}
\usepackage{babel}    
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}   

%\setbeameroption{show notes on second screen=bottom}
\setbeameroption{show notes on second screen=left}       

\begin{document}

\begin{frame}
Test
  \note{test the position}
\end{frame}

\begin{frame}
Test II
  \note{test the position II} 
\end{frame}
\end{document}

```
2. calling the mwe with `pdfpc --notes=left mwe.pdf` or `pdfpc --notes=bottom mwe.pdf` uncomment the `\setbeameroption` accordingly.

pdfpc version: v4.5
Used Distribution (GTK version, vala version): libgtk-3-0:amd64  3.24.24-1 (Debian testing)
Display Server (X/Wayland): X
HiDPI Setting (yes/no): yes

**Comment by fnevgeny** [comment]
That's how it's supposed to work...

**Comment by sesselastronaut** [comment]
Ok, my guess was that the options would change something on the position of the notes. My aim would be to make them more readable as with these settings the notes are to small to read while in a presentation:
![Screenshot_2021-01-17_20-51-30](https://user-images.githubusercontent.com/861210/104854307-36dc1180-5906-11eb-8a3f-5ca65572ba31.png)

**Comment by fnevgeny** [comment]
Press `Shift+C` to customize the GUI layout; `Escape` when done.

**Comment by sesselastronaut** [comment]
@fnevgeny, many thanks, this kind of solved the problem for me. However, would be great though if the notes could be placed below the corresponding window e.g. in the screenshot above, the "test the position" note below the "Test" frame. This together with the layout customization would then allow displaying the frame with its corresponding notes next to it and not diagonal. But maybe this just seems for me intuitively the better workflow. In any case I'll close this issue.

**Comment by fnevgeny** [comment]
Well, there are 5 slide views in total in the pdfpc presenter window, which gives 5! = 120 variants of different layout topologies :). BTW, in the variant you suggested either the size of the main view or the notes would be very small (at least with the typical, horizontal wide desktop displays; for smartphones such a layout is indeed reasonable, see #572).
