### ISSUE TITLE
\pdfpcnote unavailable with lualatex

### ISSUE THREAD

**Issue by blacheref** [pdfpc/pdfpc#581]
**Actual Behaviour**
When compiling the following code:
```
\documentclass{beamer}
\usepackage{pdfpc}
\begin{document}
\begin{frame}{}
  \pdfpcnote{Note}
\end{frame}
\end{document}
```
with lualatex or xelatex, we get the following error message:
```
! Undefined control sequence.
\pdfpcnote #1->{\edef \\{\string \n }\pdfannot 
                                               width 0pt height 0pt depth 0p..
```
Would it be possible to replace `\pdfannot`  with [`\pdfcomment{#1}`](https://ctan.org/pkg/pdfcomment) in [`pdfpc.sty`](https://github.com/pdfpc/pdfpc/blob/master/latex/pdfpc/pdfpc.sty#L154) to remove the error ?

**Comment by fnevgeny** [comment]
`pdfcomment` has serious problems of its own, e.g., it doesn't support multi-paragraph text.

As a simple workaround, load the `luatex85` package. A right fix will follow later.

**Comment by blacheref** [comment]
ok, I didn't try with multi-paragraph text and thanks for the `luatex85`fix for now

**Comment by fnevgeny** [comment]
@blacheref please test #582.

**Comment by blacheref** [comment]
working nicely, thanks !
