### ISSUE TITLE
Demo file: tell the user, sooner, how to exit

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pdfpc/pdfpc#583]
**Expected Behaviour**

If none of `Escape`, `q` and `ctrl-C` make the program exit, at least tell the user, earlier in the demo file, what key (combination) will make the program exit.

**Actual Behaviour**

The keys mentioned above do not make the program exit. And the demo file imparts the right key combination (namely, `ctrl-q`) only on its last slide.

**Steps to reproduce**

1. Excitedly run the latest version of pdfpc in order to investigate new features.
2. Realise one has forgotten how to exit.
3. Struggle (and be reminded of what people say exiting from certain text editors . .).

pdfpc version: latest git.
Used Distribution (GTK version, vala version): Mint 20.1 Cinnamon; GTK and vala versions unknown and irrelevant.
Display Server (X/Wayland): X.
HiDPI Setting (yes/no): yes.

**Comment by fnevgeny** [comment]
`Ctrl-Q` is not a stranger in the "quit" domain, either. E.g., Firefox or (more PDF-specific) Acrobat reader use this shortcut to quit. Also, I suppose you can always switch to another window with the WM's window list shortcut like `Alt-tab` or whatever.

Having said that, I suggest to start the presenter in the windowed mode by default, like a majority of PDF viewers. @AndreasBilke what do you think?

**Comment by AndreasBilke** [comment]
> Having said that, I suggest to start the presenter in the windowed mode
> by default, like a majority of PDF viewers. @AndreasBilke what do you
> think?

Since rescaling to full screen works like a charm I am in favor of starting
in windowed mode.
