### ISSUE TITLE
The program should be intelligent enough to presume a missing 'pdf' suffix

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pdfpc/pdfpc#584]
```
$ ls
ls
pdfpc-demo.pdf  pdfpc-demo.pdfpc
$  pdfpc pdfpc-demo
Pdf file "pdfpc-demo" not found
```

I am unsure that I have ever encountered a pdf file that did not have the '.pdf' suffix. So it would be useful to presume it. That is so especially for the following reason. When one is starting a presentation, one does not want to hang around.

pdfpc version: latest git

I would file this as a feature request, were you not to say that any such requests require that the requester help with implementation. My coding abilities might be insufficient for that.

**Comment by fnevgeny** [comment]
I'm unaware of a single Linux app that works this way. If you so inclined, modify the autocomplete settings of your shell accordingly.

> When one is starting a presentation, one does not want to hang around.

Indeed, just open the presentation in advance.
