### ISSUE TITLE
Umlauts like öäüÖÄÜ are not rendered correctly in the comments with LuaLaTeX.

### ISSUE THREAD

**Issue by MartinX3** [pdfpc/pdfpc#586]
**Expected Behaviour**
`Erzähle den Eierwitz`

**Actual Behaviour**
`Zeile ErzÃ¤hle den Eierwitz`

**Steps to reproduce**

1. Execute the [minimal example](https://github.com/pdfpc/pdfpc/files/6045559/MinimalExample.zip) with LuaLaTeX

pdfpc version: v0.6.0
Used Distribution (GTK version, vala version): Arch Linux XFCE4 | GTK v3.24.26  | vala 0.50.3
Display Server (X/Wayland): X
HiDPI Setting (yes/no): no

PS:
The tips from https://github.com/pdfpc/pdfpc/issues/579 didn't help me :(

**Comment by fnevgeny** [comment]
When you report a bug, always provide a MWE. `M` stands for **minimal**. `W` stands for **working**. Both are crucial. This comment relates to your other issues as well.

**Comment by MartinX3** [comment]
I updated the bug report with a minimal example using LuaLaTeX

**Comment by fnevgeny** [comment]
Hmm, strange. pdflatex and xelatex work correctly. I'm afraid you'll have to ask on a lualatex forum. It sounds like something pretty low-level in the driver...

**Comment by MartinX3** [comment]
Oh, but the normal Text can render all of the öäüÖÄÜ, just the pdfpcnotes have this problem.
Are you sure that it's still a low level problem?

**Comment by fnevgeny** [comment]
That's my opinion.

**Comment by ArchangeGabriel** [comment]
@MartinX3 Were you able to solve this? I’m stumbling upon the same problem…

**Comment by MartinX3** [comment]
@ArchangeGabriel I gave up and switched to xelatex

**Comment by HermannDppes** [comment]
@MartinX3 @ArchangeGabriel If you ever want to switch back, I think I have solved the problem how to work around the fact that LuaTeX is not as smart as XeTeX in terms of implicit encoding conversions. Check out the version of the package at [pdfpc-latex/#6](https://github.com/pdfpc/latex-pdfpc/pull/6), it should do what you want.

**Comment by MartinX3** [comment]
@fnevgeny please reopen and connect it with @HermannDppes pull request. <3
(I test it after it got merged and part of the next texlive packages release.)

**Comment by fnevgeny** [comment]
I believe labeling this as a 3-rd party issue is correct. Once can argue whether it's a problem of lualatex or pdfpc.sty, but certainly pdfpc itself has nothing to do with it.

**Comment by MartinX3** [comment]
I mixed the projects.
My brain did show me the same project name in the PR and just cut off the `-latex`. xD
