### ISSUE TITLE
New line `\\` in comments doesn't work

### ISSUE THREAD

**Issue by MartinX3** [pdfpc/pdfpc#587]
**Expected Behaviour**
`\pdfpcnote{Stelle Deine Zimmerpflanze auf den Tisch \\ Zweite Zeile}`
turns into 
```
Stelle Deine Zimmerpflanze auf den Tisch
Zweite Zeile
```

**Actual Behaviour**
`Stelle Deine Zimmerpflanze auf den Tisch Zweite Zeile`

**Steps to reproduce**

1. Checkout https://github.com/MartinX3-EducationOrganization/hbrs-latex-vorlage-praesentation
2. `make all`
3. If it can't write the files, you need to create the `out` dir first.

pdfpc version: v0.6.0
Used Distribution (GTK version, vala version): Arch Linux XFCE4 | GTK v3.24.26  | vala 0.50.3
Display Server (X/Wayland): X
HiDPI Setting (yes/no): no

**Comment by fnevgeny** [comment]
Please read the docs on Markdown formatting. Single newline is ignored (not unlike TeX). If you want plain text notes, use the respective pdfpc.sty option.

**Comment by MartinX3** [comment]
But if I use `\\\\` in a `pdfpcnote` the second `pdfpcnote` is not in a new line.
Instead it is in the same line of the second half of the first `pdfpcnote`

**Comment by fnevgeny** [comment]
I repeat, read the Markdown docs.

**Comment by stefan2904** [comment]
Hm, but this is supposed to work, right?

Unfortunately it renders both lines in one line (which breaks the markdown rendering).

![image](https://user-images.githubusercontent.com/527767/114758041-d15cbd00-9d5c-11eb-9b1e-e1c7bc484448.png)

**Comment by stefan2904** [comment]
Maybe you can add an example on how to use markdown formatting inside a `\pdfpcnote` to the Readme?

**Comment by fnevgeny** [comment]
> Unfortunately it renders both lines in one line (which breaks the markdown rendering).

Please (i) open a new issue and (ii) provide an MWE demonstrating the problem.
