### ISSUE TITLE
LaTeX option overridenote is not working

### ISSUE THREAD

**Issue by MartinX3** [pdfpc/pdfpc#588]
**Expected Behaviour**
* Bla
* Bla

**Actual Behaviour**
The text doesn't get rendered.

**Steps to reproduce**
`\usepackage[overridenote=true]{pdfpc}`
`\note[item]{Erzähle den Eierwitz}`
1. Execute the [minimal example](https://github.com/pdfpc/pdfpc/files/6045891/Minimal.example.zip) with LuaLaTeX

pdfpc version: v0.6.0
Used Distribution (GTK version, vala version): Arch Linux XFCE4 | GTK v3.24.26  | vala 0.50.3
Display Server (X/Wayland): X
HiDPI Setting (yes/no): no

**Comment by fnevgeny** [comment]
Provide a MWE.

**Comment by MartinX3** [comment]
Added, I forgot it

**Comment by fnevgeny** [comment]
Works fine for me (except for the umlaut, of course).

**Comment by MartinX3** [comment]
Weird, here `lualatex Praesentation.tex && pdfpc Praesentation.pdf` results in
![image](https://user-images.githubusercontent.com/4518092/109224906-dff71100-77bc-11eb-84f5-034dc556b069.png)

**Comment by fnevgeny** [comment]
Yes, strange. Does it work with pdflatex? (need to add `\usepackage[T1]{fontenc}` in this case)

**Comment by fnevgeny** [comment]
PS.
```
$ lualatex --version
This is LuaTeX, Version 1.10.0 (TeX Live 2019/Debian)
```

**Comment by MartinX3** [comment]
Hmm, maybe the newer TeX Live has some incompatibilities/deprecations?

```
$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020/Arch Linux)
```
Using
```
\usepackage[T1]{fontenc}
\usepackage[overridenote=true]{aussehen/pdfpc}
```
Same behaviour, no notes.
But the `ä` is still correctly rendered.

**Comment by fnevgeny** [comment]
Amusing. Here,
```
$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
```
What if you drop `=true`?

**Comment by MartinX3** [comment]
Same problem :D
I am far too far in the future with my tools :dancers:

**Comment by fnevgeny** [comment]
And directly using `\pdfpcnote` in the same example works?!

**Comment by MartinX3** [comment]
With `lualatex`:
![image](https://user-images.githubusercontent.com/4518092/109227863-47af5b00-77c1-11eb-8437-aa72dfc02b36.png)

With `pdflatex`:
![image](https://user-images.githubusercontent.com/4518092/109227793-2e0e1380-77c1-11eb-8e3d-9de7fd74f894.png)

:D

**Comment by fnevgeny** [comment]
> With pdflatex:

In this case you need `\usepackage[T1]{fontenc}` then it should render correctly. At least here it does.

**Comment by MartinX3** [comment]
Ah, yes, that works
![image](https://user-images.githubusercontent.com/4518092/109228462-24d17680-77c2-11eb-8368-54966cbb0f4d.png)

**Comment by fnevgeny** [comment]
A bit of sanity at least...

Does simple `\note` (without `[item]`) work?

**Comment by MartinX3** [comment]
Neither in `pdflatex` or `lualatex` :)

**Comment by fnevgeny** [comment]
Well, the [respective code](https://github.com/pdfpc/pdfpc/blob/378a6a25487c5cbc1796cedc560fc3f88a2fb10b/latex/pdfpc/pdfpc.sty#L80-L85) is pretty straightforward. Try to enter it directly in your .tex...

**Comment by MartinX3** [comment]
That works :)
So setting the option as a packet parameter doesn't work with TexLive 2020

**Comment by fnevgeny** [comment]
It's weirder even more... Do other `pdfpc.sty` options work?

**Comment by MartinX3** [comment]
I'm not able to set the options as parameters with
`\usepackage[xxx=1,yyy=12:34,zzz=true]{aussehen/pdfpc}`

But if I edit the pdfpc.sty and set the values by myself it works.
Examples:

`\DeclareStringOption[1]{duration}`
`\DeclareBoolOption[true]{overridenote}`

**Comment by fnevgeny** [comment]
Try using properly `\usepackage{pdfpc}` instead of `aussehen/pdfpc`

**Comment by fnevgeny** [comment]
See https://github.com/latex3/latex2e/issues/422

**Comment by MartinX3** [comment]
Ah, thank you!
With pdflatex the options are working then.
It seems I need to wait for texlive 2021 on 2021-04-06 to get both, the hotfix for the Latex2E and pdfpc 0.6.0 or which version is there at that release date.
It seems that sadly there is no minor release between texlive versions.

**Comment by fnevgeny** [comment]
Not sure why you need to wait for the fix. Just install pdfpc.sty in a system path. Or put it in the current directory in the worst case.

**Comment by MartinX3** [comment]
Ah, that are good Ideas, too.
The only disadvantage is, that I will miss the automatic updates.
