### ISSUE TITLE
`--last-minutes` does not always work correctly

### ISSUE THREAD

**Issue by sedrubal** [pdfpc/pdfpc#591]
**Expected Behaviour**

When running

```bash
$ pdfpc --duration=30 --last-minutes=2 ...
```

the timer should be white for 28 minutes and orange for the last 2 minutes.

**Actual Behaviour**

The timer is white and after ~4 minutes it turns orange. This is not always reproducible. It seems like the behaviour is sometimes random.

**Steps to reproduce**

1. `pdfpc --duration=30 --last-minutes=2 presentation.pdf`
2. Start (may pause the timer)
3. wait

pdfpc version: pdfpc v4.5
Used Distribution (GTK version, vala version): Arch package, gtk3 1:3.24.28-3, vala 0.52.1-1
Display Server (X/Wayland): X
HiDPI Setting (yes/no): no

**Comment by fnevgeny** [comment]
Please read the "Timer" section of the pdfpc man page.

**Comment by sedrubal** [comment]
Thanks, now I understand it. In this case I'd suggest to change the help text and the explanation of `--last-minutes` in the man page and add a note, that this value will be ignored and you should read the section "Timer" :wink:

**Comment by fnevgeny** [comment]
Yes, you are right.

**Comment by sedrubal** [comment]
Thank you ;)
