### ISSUE TITLE
Support for msys2

### ISSUE THREAD

**Issue by AP2008** [pdfpc/pdfpc#595]
I have read the README.md. There seems no information on compiling on msys2. So, is there any way to compile it on msys2 ?

**Comment by fnevgeny** [comment]
Likely there is. But you have to find it out yourself. None of the active pdfpc developers works with Windows.

**Comment by einhander** [comment]
@fnevgeny does it mean that pdfpc will work on windows?

**Comment by fnevgeny** [comment]
@einhander Right. It does already for me, including dual screen and videos. Just Markdown notes don't work (but I guess you specifically couldn't care less :-))

**Comment by AndreasBilke** [comment]
@fnevgeny Are you using msys2 or the cygwin solution?

**Comment by fnevgeny** [comment]
msys2
