### ISSUE TITLE
Multiple workspaces

### ISSUE THREAD

**Issue by z4lem** [pdfpc/pdfpc#597]
**Only submit a feature request if you read the SUPPORT.md file**

The feature wish description:
It would be nice if its possible to move only the presenter view to a specific workspace in `i3.`
The same way as it is currently possible with monitors via parameter. 

Tools for online conferences or OBS allow to share/record individual windows/workspaces.
If only one monitor exists the pdfpc presenter & audience view are recognized as one window.

However, it would be useful to split them up if you're presenting online without a 2nd monitor (e.g. Notebook).

**Comment by AndreasBilke** [comment]
If I understand you correctly you either can move the window manually OR
target it by its window title (see
https://github.com/pdfpc/pdfpc/blob/master/FAQ.rst) for an example.

**Comment by z4lem** [comment]
Thanks for your reply! 
However, moving the entire pdfpc window is working fine with i3-wm. 

The issue is that if you have only one (hardware) screen, pdfpc is rendered as only one window. I.e. there is no separation between presenter and audience view. maybe the screenshot below explains it a bit.
![image](https://user-images.githubusercontent.com/23519149/123944582-8b97b400-d99d-11eb-9dbc-7b235ca2ddb5.png)

**Comment by fnevgeny** [comment]
What you see is indeed a single window, supposed to be viewed this way by the presenter. If you need two separate windows on a single physical monitor, run with the `-w both` option. Then each one can be moved/resized separately.

**Comment by z4lem** [comment]
Woa, that works well! 
Thank you :+1:
