### ISSUE TITLE
Video will not play on Ubuntu 18.04

### ISSUE THREAD

**Issue by Kchour** [pdfpc/pdfpc#598]
pdfpc version:  v4.6pre
Used Distribution (GTK version, vala version):  GTK+3.22.30  and vala 0.40.23
Display Server (X/Wayland): x11
HiDPI Setting (yes/no): no

**Expected Behaviour**

5 sec video clip should play upon mouse click (should flash green, black, red, black, and blue)

**Actual Behaviour**

pdfpc just sits there, the console also prints:
```
Screensaver inhibited
Error creating video sink: Could not make element sink0 of type gtksink.
Gstreamer installation may be incomplete.
Screensaver reactivated

```

I've also read the FAQ;
![apollo17](https://user-images.githubusercontent.com/21199708/126070948-814bc3a7-df8d-4bd1-a84e-582363120cbf.jpg)

https://user-images.githubusercontent.com/21199708/126070949-b576c896-4fd9-4436-b32d-4e000eb40ce5.mp4

[test.pdf](https://github.com/pdfpc/pdfpc/files/6836419/test.pdf)
 `gst-play-1.0 --videosink gtksink test.mp4` works properly. 

**Steps to reproduce**

Simply compile a pdf with the attached latex project (3 files) and the following latex code. Open the resulting pdf with pdfpc and try playing the video. 

```
\documentclass{beamer}

\usepackage{listings}
\lstset{language={[LaTeX]TeX}, basicstyle=\small}

\usepackage{multimedia}

\usepackage{hyperref}
\usepackage[utf8]{inputenc}
\usepackage{xspace}

\useoutertheme{shadow}
\usecolortheme{beaver}

\newcommand{\singleitem}[1]{\begin{itemize}\item #1\end{itemize}}
\newcommand{\pdfpc}{\texttt{pdfpc}\xspace}
\newcommand{\opt}[1]{\texttt{#1}\xspace}

\setbeamertemplate{navigation symbols}{}

\defbeamertemplate{footline}{my foot}{%
\vskip1pt%
\makebox[0pt][l]{\insertshortauthor}%
\hspace*{\fill}\insertshorttitle\hspace*{\fill}%
\llap{\insertframenumber\phantom{/}}
}
\setbeamertemplate{footline}[my foot]

\mode<presentation>

\begin{document}

\begin{frame}
	  \begin{center}
		\movie{\includegraphics[width=0.7\textwidth]{apollo17.jpg}}{test.mp4}
	\end{center}
\end{frame}

\end{document}

```
Would appreciate some direction!

**Comment by fnevgeny** [comment]
> `gst-play-1.0 --videosink gtksink test.mp4` works properly.

Without a *single* warning?!

**Comment by Kchour** [comment]
> > `gst-play-1.0 --videosink gtksink test.mp4` works properly.
> 
> Without a _single_ warning?!

Now that you mention it, I guess trying to say something already works "properly" is too relative of a term.

I get the following warning, but the video still plays though :
```
** (gst-play-1.0:28928): WARNING **: 16:19:34.377: Couldn't create specified video sink 'gtksink'

```

**Comment by fnevgeny** [comment]
So please do read the FAQ and follow the suggestion there.

**Comment by Kchour** [comment]
I tried installing gstreamer1.0-gtk3 again via: `sudo apt-get install gstreamer1.0-gtk3` but my pc says it's already installed:

`gstreamer1.0-gtk3 is already the newest version (1.14.5-0ubuntu1~18.04.2)

Just not sure what else I'm missing

**Comment by fnevgeny** [comment]
Very strange. Well, try re-installing it...

**Comment by fnevgeny** [comment]
Also, see if enabling debugging with `--gst-debug-level=LEVEL` gives some hints.

**Comment by Kchour** [comment]
Tried reinstalling as follows:

```
sudo apt-get install --reinstall libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
```

...but still, `gst-inspect-1.0 gtksink` returns `No such element or plugin 'gtksink'.

I also didnt really notice anything interesting running `gst-play-1.0 --videosink gtksink test.mp4 --gst-debug-level=4`, except for the same issue as above (no gtksink found). 

Here's the console [output](https://github.com/pdfpc/pdfpc/files/6864892/blah_debug.txt). The `test.mp4` continues to play properly tho.

Maybe there is a different sink I can try using that you may know of in [here](https://github.com/pdfpc/pdfpc/blob/master/src/classes/action/movie.vala#L688)?

**Comment by fnevgeny** [comment]
`0:00:00.010488987 15275 0x55cbbc25c0c0 INFO      GST_PLUGIN_LOADING gstplugin.c:915:_priv_gst_plugin_load_file_for_registry: plugin "/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0/libgstplayback.so" loaded`

Hmm, do you have a parallel installation of gstreamer under /usr/local/?!

**Comment by Kchour** [comment]
I don't think I completely understand your question, can you clarify?

 Isn't `/usr/local/lib/x86_64-linux-gnu/` normally where gstreamer is installed? Anyway, there's not really anything in `/usr/local`, but here's the output of `ls`
```
kenny@kenny-Inspiron-7577:/usr/local$ ls -al
total 44
drwxr-xr-x 11 root root 4096 Mar 10  2020 .
drwxr-xr-x 11 root root 4096 Dec 16  2020 ..
drwxr-xr-x  2 root root 4096 Jul 22 17:32 bin
drwxr-xr-x  2 root root 4096 Jul 18 08:49 etc
drwxr-xr-x  2 root root 4096 Aug  5  2019 games
drwxr-xr-x 27 root root 4096 Jul 22 17:14 include
drwxr-xr-x 11 root root 4096 Jul 22 17:32 lib
drwxr-xr-x  4 root root 4096 Mar 10  2020 libexec
lrwxrwxrwx  1 root root    9 Feb  4  2020 man -> share/man
drwxr-xr-x  2 root root 4096 Aug  5  2019 sbin
drwxr-xr-x 28 root root 4096 Jul 22 17:14 share

```

**Comment by fnevgeny** [comment]
> Isn't `/usr/local/lib/x86_64-linux-gnu/` normally where gstreamer is installed?

No. Not by Ubuntu.
