### ISSUE TITLE
Spit `latex/` off into a new repo

### ISSUE THREAD

**Issue by Foggalong** [pdfpc/pdfpc#599]
Moving `latex/` off into a new repository, just to house the `pdfpc` CTAN package, would bring a real visibility benefit.

It's not immediately obvious to people visiting this GitHub repository as is that the package is here. Similarly when [external sources](https://www.ctan.org/pkg/pdfpc) link back to here as the source of the LaTeX package, the first impression is that they've linked to the wrong place since at first glance this looks like (just) the source repo for pdfpc proper.

Given the `pdfpc` package is relatively new this would be the best time to do it without it causing broken links downstream, whereas down the line more places will hopefully be linking here. I'd hope that with it being more visible people might find it more easily than the [third](https://github.com/p4pyru5/pdfpc-latex-notes) [party](https://github.com/cebe/pdfpc-latex-notes) [versions](https://www.overleaf.com/project/60fae7e12ef17c2b5736e034).

Whatever you think of this idea, I also wanted to thank you for making such a neat piece of software! pdfpc makes presenting with beamer a much easier experience so it's very much appreciated :)

**Comment by AndreasBilke** [comment]
@fnevgeny What do you think about that? I wouldn't mind if we move it to its own repo.

**Comment by fnevgeny** [comment]
Fine with me.

**Comment by muelli** [comment]
Note to future self: look here for the LaTeX package: https://github.com/pdfpc/latex-pdfpc
