### ISSUE TITLE
Program shows outlines around some images that should not be present and are absent on other pdf viewers

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pdfpc/pdfpc#601]
**Expected Behaviour**

No outline around an image where there is no outline.

**Actual Behaviour**

Some images have outlines.

**Steps to reproduce**

1. Examine the attached PDF in a program other than pdfpc.
2. Look at it in pdfpc.

[test pdf.pdf](https://github.com/pdfpc/pdfpc/files/6963294/test.pdf.pdf)

pdfpc version: 4.5.3
Used Distribution (GTK version, vala version): GTK - unknown; how do I determine it? vala -  - unknown; how do I determine it?
Display Server (X/Wayland): X
HiDPI Setting (yes/no): yes, on laptop monitor, no on 'extended' monitor that shows the slides (but the boxes show on the presenter's view too).

I note that I am about to give a presentation - using an affected file - on Thursday (!).

**Comment by fnevgeny** [comment]
In `evince`, I see the same outline box. Also in Acroread, when clicking on the image. How did you produce the file? If in *TeX, provide the source.

**Comment by LinuxOnTheDesktop** [comment]
Thanks for the response. I have found the culprit: I produced the file in Microsoft Word; all and only the affected images have Word's 'soft edges' property applied to them.

![image](https://user-images.githubusercontent.com/47056543/128908312-69ecfb5b-990e-4d6d-97ef-69b35e74e050.png)

The resulting images render correctly in the following:

- Okular, running on Linux Mint;
- SumatraPDF, running on Windows.

Also though - interestingly and worryingly - Acrobat Reader (on Windows) garbles my test pdf and the pdf from which I extracted the image for the test pdf. For, Acrobat renders the test pdf like this, i.e. with garbled colours (!):

![image](https://user-images.githubusercontent.com/47056543/128908135-52a0be16-0db7-44db-9448-b840dde9a04c.png)

For the Acrobat problem, it seems relevant that I was using Word in full dark mode.

I have not tested the files in any other PDF viewers.

**Comment by fnevgeny** [comment]
OK; so I suppose the ticket can be closed?

**Comment by LinuxOnTheDesktop** [comment]
> so I suppose the ticket can be closed?

The matter is unclear. Here is how. _If_ we take it that Okular and Sumatra render the pdf rightly, then pdfpc is among the programs that render the file _incorrectly. And some evidence that Okular and Sumatra render the pdf rightly is: 
Word is unlikely to be producing pdfs. Still, some evidence to the contrary is: Acrobat Reader is unlikely to render pdfs wrongly.

**Comment by AndreasBilke** [comment]
But isn't it supposed to be a box around the image if you turn *on* the soft edges feature? So in my understanding Okular and Sumatra behaves strange.

**Comment by LinuxOnTheDesktop** [comment]
No. Word's 'soft edges' feature softens the border between an image and the image's background. The feature should not and within Word itself does not create an outline where there was no outline before. Okular and Sumatra render such images correctly: the 'box' should not be there.

**Comment by fnevgeny** [comment]
pdfpc itself knows nothing about PDF. Whatever Word does to produce the "soft edges" in the PDF output, goes to poppler for rendering (evince also uses poppler, BTW). So if you believe the rendering is incorrect, submit a bug report against poppler.

**Comment by LinuxOnTheDesktop** [comment]
> So if you believe the rendering is incorrect, submit a bug report against poppler.

[Done](https://gitlab.freedesktop.org/poppler/poppler/-/issues/1113). I imagine that you should insert something about poppler - and filing bugs against it - in your FAQ.

**Comment by fnevgeny** [comment]
> [Done](https://gitlab.freedesktop.org/poppler/poppler/-/issues/1113). 

Good, thanks.

> I imagine that you should insert something about poppler - and filing bugs against it - in your FAQ.

Well, "F" in FAQ stands for "frequently". So far, it doesn't seem like that.
