### ISSUE TITLE
Something missing from the FAQ and manpage: what happens to 'notes' if one replaces the pdf to which they pertain

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pdfpc/pdfpc#602]
I used pdfpc to write 'notes' for a PDF. Now I find I need to alter the PDF. The notes are stored in a file different from the PDF. The FAQ should say what happens if I replace the PDF file with a new version of it. (What does happen - I find, to my relief - is that the notes are preserved.)

The user wants to know also when the notes are saved. (The answer, I take it, is when the program is closed. To guard against crashes and power failure, a save-at-will feature would be welcome.)

I am willing to help write the relevant part of the FAQ and/or manpage - but it would make more sense for someone who knows the intricacies so to do. (For what happens when, e.g. the replacement PDF has a different number of slides to the original?)

**Comment by fnevgeny** [comment]
> The FAQ should say

It's unclear to me why you believe that your every question should be covered in the FAQ... Especially when the answer is quite straightforward (and indeed you found it yourself) - pdfpc tries its best to make it work.

**Comment by LinuxOnTheDesktop** [comment]
I take your point - made elsewhere - that the FAQ should contain only questions that are asked _frequently_. Yet, I wrote (though not every time), not of the FAQ but of the 'FAQ _and/or manpage_' (emphasis added). And of course one thinks - sometimes wrongly, probably - that questions that are natural for oneself will be natural for others.

**Comment by fnevgeny** [comment]
Commit 1198934167169f0986d1cad9d8593b4f9c2f74fc clarifies the point somewhat.
