### ISSUE TITLE
'Found conflicting notes' message seems to be produced erroneously

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pdfpc/pdfpc#603]
**Expected Behaviour**

No such message.

**Actual Behaviour**

I saw the message - displayed (together with some notes) when I quit pdfpc. Subsequent runs of pdfpc, with the same files, did _not_ produce the message. I detected no mangling of notes.

**Steps to reproduce**

Uncertain; here is a link to [the PDF file](https://app.box.com/s/v5ygpv4bvyjdv0llavwplfbt6pninxmv) and here is a link to [the PDFPC file](https://app.box.com/s/kprmx86psdv16pytkuxqqu6vhs9dcu7s). (I do not wish those files to be available publicly for long, though.) Yet, perhaps replacing the PDF file - with another of the same name and same number of slides - caused the problem; cf. ##602.

pdfpc version: 4.5pre (compiled from yesterday's git)
Used Distribution (GTK version, vala version): unknown - how do I determine those versions?
Display Server (X/Wayland): X
HiDPI Setting (yes/no): yes. (I experienced the problem when using a laptop with HDMI and when the laptop was attached to no secondary screen.)

**Comment by fnevgeny** [comment]
> **Steps to reproduce**
> 
> Uncertain

Sorry, cannot fix unreproducible issues... You need to provide an MWE.

> pdfpc version: 4.5pre (compiled from yesterday's git)

4.5 was released last year. Not sure where you dug out 4.5pre...

**Comment by LinuxOnTheDesktop** [comment]
> 4.5 was released last year. Not sure where you dug out 4.5pre...

As said, I am using the git version.
```
$ pdfpc --version
pdfpc v4.5pre
Copyright (C) 2010-2020 see CONTRIBUTORS
```

I'll work on steps to reproduce the problem if I have time.
