### ISSUE TITLE
Seemingly one call scroll notes only by entering editing mode

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pdfpc/pdfpc#604]
**Expected Behaviour**

There should be some way to scroll through notes - notes for a slide where those notes 'overflow' - without entering editing mode. For: reading is not editing; one might forget about ctrl-n when presenting and indeed forget to press <esc> when one has finished scrolling); it is natural to try clicking on the notes (which will, actually, show the next slide!).

**Actual Behaviour**

Please see above.

**Steps to reproduce**

1. Create a note long enough to generate a scroll bar.
2. (Not advised!) Try to read the whole of the note when presenting.

pdfpc version: 4.5pre (compiled from yesterday's git)
Used Distribution (GTK version, vala version): unknown - how do I determine those versions?
Display Server (X/Wayland): X
HiDPI Setting (yes/no): yes. (I experienced the problem when using a laptop with HDMI and when the laptop was attached to no secondary screen.)

**Comment by fnevgeny** [comment]
There is no "scrolling" for the slides themselves. There is no scrolling for the notes as well. Choose the amount of text that fits a single notes "page" and/or adjust the font size and/or adjust the space occupied by the notes panel. Read the man pages to learn about all these options.

**Comment by LinuxOnTheDesktop** [comment]
Thank you.

I note for the following for the use of others.

- One uses a configuration file to change such things as font size and the size of the notes panel.
- Some information about the configuration file - or rather configuration files (plural) - is hidden away in `man pdfpcrc` (_sic_). That information includes the following.

```
/etc/pdfpcrc
       System-wide configuration file

   $XDG_CONFIG_HOME/pdfpc/pdfpcrc
       User configuration file (if $XDG_CONFIG_HOME is not set, $HOME/.config will be used).
```

Next: _you leave uncontested the idea that it would be better were notes to be scrollable-outside-of-editing mode_. But I suppose that here we have a feature request (and the README says people must implement new features themselves).

Now: 
> There is no "scrolling" for the slides themselves. 

I am unsure what you mean. I note though (again for the use of others) the following. Setting the configuration file option `disable scrolling` prevents the mouse wheel from switching from one slide to another.

> There is no scrolling for the notes as well.

I do not understand. Within and only within editing mode, one _can_ - if note text overflows the bottom of the screen - scroll down to that text.

**Comment by fnevgeny** [comment]
> I am unsure what you mean.

I mean that you are not expecting to scroll the slide itself, aren't you? Each slide takes the whole screen; when there is not enough space, one makes another slide (bad presenters decrease the font size...). So I see no reason why the notes for the same *single* screen ever need to be such copious as to require scrolling. If you put pages of text as "notes", these are anything but notes. What do you do with your notes? Read them aloud?

> Within and only within editing mode, one can 

In the editing mode, one enters the markup code - `Markdown`, which may further include HTML. So the markup text length can easily be large.

**Comment by LinuxOnTheDesktop** [comment]
I am indeed interested, only, in scrolling the notes (and note the slides). I wish to do so whilst delivering a presentation - and, thus, quickly and easily. Now, true: the Hi-DPI limitations of my Linux distribution make the space available somewhat small. (I have a resolution of 2560 by 1440 pixels, which is _halved_ by using a DPI setting of two. My distribution - or desktop environment - does offer fractional scaling but not of a type that performs well enough to be usable.) However,

1) _Many_ (most?) versions of Linux have the aforementioned Hi-DPI problem.

Also: sometimes I do need lengthy notes for a slide - for the following two reasons.

2) Sometimes I wish to read the notes aloud, either _verbatim_ or as a paraphrase. (For, exactness matters in my discipline.)

3) At other times I wish to be able to use (twenty or so) lines of notes as a reference.

Also

4) Being able to scroll the notes but _only in editing mode_ adds frustration to the situation.

5) You seem to say (but once again I am afraid that I have trouble understanding you) that there is another reason - to do with HTML - that notes can be long.

Shrinking the preview (a.k.a. 'next') slide is some help, but I'd rather be able to scroll the notes (without entering editing mode).

**Comment by fnevgeny** [comment]
> Being able to scroll the notes but only in editing mode adds frustration to the situation.

You consider the absence of scrolling in the normal (non-edit) mode as a bug. It isn't. It's a feature. IMO, just as a slide should be shown to the auditorium as a whole, the respective notes should fit in a single "page", too. At least as long as we're talking about typical (large) display that a presenter is using. For a small handheld or like device I accept it might be different, but then this is part of a larger ergonomics issue - adjusting the pdfpc layout for small screens.

> You seem to say (but once again I am afraid that I have trouble understanding you) that there is another reason - to do with HTML - that notes can be long.

Yes. The markup code can easily be much larger than the rendered output. E.g., `<span style="color:red">red</span>` is more than ten times lengthier than the actual output. So having scrollbars there makes sense.

**Comment by LinuxOnTheDesktop** [comment]
I seem not to be getting through to you; so - forgive me - I must now be emphatic.

> You consider the absence of scrolling in the normal (non-edit) mode as a bug. It isn't. It's a feature.

_I supplied three reasons to consider it a bug_ but seemingly you ignored those points. Your own point about markup constitutes a _fourth_ reason. Let me put my case another way.. **Some people have good reason for lengthy notes (or are you wise enough to tell all presenters how their presentation notes should be); hence, and because Hi-DPI problems, and markup, it needs to be easier to scroll the notes**.

**Comment by fnevgeny** [comment]
It just occurred to me that you use a no-idea-where-from-obtained outdated git snapshot version. If all you want is to scroll the notes using the mouse wheel, you need to disable handling of the scrolling events in the pdfpc controller. Just put `option disable-scrolling true` in pdfpcrc. And, of course, use the last officially released version.

**Comment by LinuxOnTheDesktop** [comment]
Thanks.

I obtained the git version by fetching and downloading from your git. I have an installer script (based on a library I wrote) that does that. I might alter my script to download and compile the latest official release (because you don't offer prebuilt packages, from what I can see - at least not outside of distro repositories).

You offer a way of scrolling notes - without having to enter editing mode, yes? That sounds good, but it won't change any other behaviour, will it?

**Comment by fnevgeny** [comment]
> I obtained the git version by fetching and downloading from your git. I have an installer script (based on a library I wrote) that does that.

Well, debug your script...

> You offer a way of scrolling notes - without having to enter editing mode, yes? That sounds good, but it won't change any other behaviour, will it?

What do you mean? Just try it.

**Comment by LinuxOnTheDesktop** [comment]
What I meant about my script was: it downloads the very latest version, i.e. the version that includes the very latest commits. I'd appreciate advice on how to use git to download the latest _release_.

I find that I have `option disable-scrolling true` in pdfpcrc already and that indeed I can now scroll notes when not being in edit mode. I think I must have found that option in an earlier bug report, namely #350 (which I should have found earlier).

**Comment by fnevgeny** [comment]
> I'd appreciate advice on how to use git to download the latest _release_.

You don't need git for that. https://github.com/pdfpc/pdfpc/releases/latest

**Comment by LinuxOnTheDesktop** [comment]
> You don't need git for that. https://github.com/pdfpc/pdfpc/releases/latest

Thanks, but my script - the point of which is to automate installations - uses git. I'll work out a way of doing the automation.

**Comment by LinuxOnTheDesktop** [comment]
Hmm . .

```
$ git clone --depth 1 -b latest https://github.com/pdfpc/pdfpc.git
Cloning into 'pdfpc'...
warning: Could not find remote branch latest to clone.
fatal: Remote branch latest not found in upstream origin
```
But (via [here](https://stackoverflow.com/questions/17414104/git-checkout-latest-tag))  . .

```
#!/usr/bin/env bash
git fetch --tags
latestTag=$(git describe --tags "$(git rev-list --tags --max-count=1)")
git checkout "${latestTag}"
```

But this requires that one have cloned the repository already . . (otherwise the `fetch` fails).

**Comment by LinuxOnTheDesktop** [comment]
@fnevgeny: as you advised, I switched away from the version that I was using - which I pulled from the main git branch some time ago and which identified itself as v4.5pre - and installed instead v4.5.0. _Upon so doing the following three bad things happened._

1) _The newly-installed version found multiple things it disliked in a .pdfpc file_ of mine. The first complaint here was: ' Parse error: unexpected identifier `duration', expected value
The legacy pdfpc file was saved as [. . .]' (Note also that the use of the word 'legacy' here is confusing.)

2) Something to do with DPI seems messed up: _the text size of my notes doubled_ (and I found that to be the case both with an existing pdfpc file and with a newly created one).

3) The `option disable-scrolling true` in my ~/.config/pdfpc/pdfpcrc seems now to be being ignored.

Should I file some new issue(s)?

**Comment by fnevgeny** [comment]
> Upon so doing the following three bad things happened.

To which one should be ready when working with not officially released software. Stay with releases, there will be fewer surprises.

> Note also that the use of the word 'legacy' here is confusing

What is confusing here? https://www.pcmag.com/encyclopedia/term/legacy-format

**Comment by LinuxOnTheDesktop** [comment]
'The legacy pdfpc file' is ambiguous between

1) the old version of the file

and

2) a version of the file that uses an old format.

The file in question is a 'legacy' in sense 1 but not in sense 2.

I will open a new issue (or two) about the problems I am having with v4.5.0.

**Comment by fnevgeny** [comment]
> The file in question is a 'legacy' in sense 1 but not in sense 2.

No, in both senses.
