### ISSUE TITLE
Formal documentation of the .pdfpc format

### ISSUE THREAD

**Issue by zhangchuck** [pdfpc/pdfpc#605]
**Request:**

- Documentation of the .pdfpc format
    - What JSON keys are required in a .pdfpc file?
    - What JSON keys are optional in a .pdfpc file?
    - How should slide-specific notes be stored?
    - When will the .pdfpc format change? When was the last change?
    - How does `pdfpc` interact with the associated `.pdfpc` file? Does it automatically overwrite this file?

**Motivation:**

- A clearly defined .pdfpc format (and clarity on if/when this format has changed) would allow other projects to export notes for direct notes usage with `pdfpc`. For example, I use [Marp](https://marp.app/) to generate slides. Marp allows me to write my notes in Markdown. Ideally, when Marp converts Markdown into a PDF, it would automatically generate an accompanying `.pdfpc` file with the notes included. While the export would need to be a Marp feature, to create such a feature, a clearly defined `.pdfpc` format (and guarantees or clarity about when the format changes) would be necessary.
- Currently, the .pdfpc format is documented ad-hoc (as far as I can tell):
    - Slide 18 of the demo file
    - Comments in this pull request: https://github.com/pdfpc/pdfpc/pull/556#issuecomment-739565800
    - the `man` page for pdfpc

**Comment by fnevgeny** [comment]
Documenting is not a big deal by itself, but making it an official schema description implies promises of maintaining compatibility etc. The .pdfpc format is not intended to be used by anything/anybody except `pdfpc` itself. Moreover, with a good presentation creator software there should be no reason to deal with .pdfpc files at all.

Please consider instead using the native PDF annotations; have a look at `pdfpc.sty`. I am not familiar with `Marp`, but suppose its framework should be able to produce the PDF annotations.

**Comment by MJimitater** [comment]
BTW, is it possible to just write all the notes into the `.pdfpc` file and save it, in order for pdfpc to recognize and display them during presentation? Im too lazy to write them in the black notes field while being in presentation mode..

**Comment by fnevgeny** [comment]
@MJimitater It seems to me you read neither the original post nor my reply...

**Comment by MJimitater** [comment]
@fnevgeny Yes, you are right, I hadn't read the above comments properly, sorry for that. My question is resolved, thank you.

**Comment by zhangchuck** [comment]
@fnevgeny Thanks for the response; appreciate your time and help with this. It looks like with the most recent release of Marp, support for PDF annotations was added (https://github.com/marp-team/marp-vscode/releases/tag/v1.3.0), so that's mostly solved my workflow.

---

It may still be valuable to document the *current* `.pdfpc` format for people who have a workflow where they need to migrate speaker notes from a V1 of a presentation to a V2 of a presentation. To give an example of that workflow:

1. When preparing for a presentation, I often write and edit speaker notes while practicing the presentation (e.g., when I'm using *pdfpc*). The speaker notes, therefore, are stored in the `.pdfpc` file.
2. As a part of preparing for a presentation, I may need to update the content of my slides.
    a. If I make slide updates that do not change the order of slides or the number of slides, then I can use the old `.pdfpc` file.
    b. If I change the order of slides or add/subtract slides, however, then the old `.pdfpc` file will have speaker notes assigned to the wrong slides.
3. To fix this, I will migrate those notes manually.
   a. One way to do this is to copy and paste notes inside of *pdfpc* (a bit troublesome). 
   b. Another way is to adjust the slide numbers inside of the `.pdfpc` file. (much quicker)

Just a thought --- perhaps maintainers would prefer to discourage this usage as it may cause too many troubleshooting requests.

--- 

One final thought (let me know if I should split this off into a bug report).  The `man` page suggests that the user can override "native PDF annotations" with notes written in *pdfpc*:

>  In addition,  while in the presentation mode, pressing 'Ctrl + n' will
>        allow you to take or edit notes for the current user  slide.   To  exit
>        the note editing mode, press the Escape key.  These notes are stored in
>        the .pdfpc file.  They take precedence over the native PDF annotations,
>        i.e., if a user-provided note exists for a given slide, any PDF annota‐
>        tions on that page will be silently ignored. While editing a note,  the
>        normal  keybindings  are  disabled,  e.g.,  you  are not able to change
>        slides.

On my system (*pdfpc* v4.5/Fedora 34), this doesn't seem to happen. When I press `Ctrl + n` on a slide that has PDF annotations, I get a lock in the bottom-left of the screen and cannot add notes from within *pdfpc*. (When I press `Ctrl + n` on a slide that has no PDF annotations, I can add notes and they save as normal.) 

Am I reading the documentation wrong? Is the lock expected behavior?

**Comment by fnevgeny** [comment]
> It looks like with the most recent release of Marp, support for PDF annotations was added (https://github.com/marp-team/marp-vscode/releases/tag/v1.3.0), so that's mostly solved my workflow.

Good to know.

> It may still be valuable to document the current .pdfpc format for people who have a workflow where they need to migrate speaker notes from a V1 of a presentation to a V2 of a presentation.

I don't see the point. Just migrate the notes to the PDF annotations *once*. And you're all set. Am I missing something? The virtue of PDF annotations is that they would be produced within the same workflow as the slides themselves (in the case of *TeX, one is supposed to use the `pdfpc.sty` package, or just the original beamer notes), so you don't have to worry about the synchronization at all. 

> When I press `Ctrl + n` on a slide that has PDF annotations, I get a lock in the bottom-left of the screen and cannot add notes from within pdfpc.

Yes, that's the intended behavior. First, the "precedence" didn't mean you could *override* the PDF annotation while in `pdfpc`. Rather, if a manual note already existed (entered in a previous pdfpc session), and then the PDF file was modified to have an annotation on the same page, it would have been ignored. Yes, it was confusing, and so in 4.5 the precedence was changed (but the docs weren't updated :) so it's a doc bug).

It's still quite a pain trying to support notes potentially coming from two sources. It might be better to take the either-or approach: if the PDF annotations are detected, disallow manual notes at all...

> the lock appears presumably because the native PDF annotations are supposed be read-only

Technically, it would be rather trivial to edit the PDF annotations from pdfpc. But then they would be overwritten on the next invocation of the software producing the slides... There is no silver bullet here, but IMO the best approach is to produce *both* slides and notes by the same software (within the same workflow).

**Comment by zhangchuck** [comment]
> I don't see the point. Just migrate the notes to the PDF annotations _once_. And you're all set. Am I missing something? The virtue of PDF annotations is that they would be produced within the same workflow as the slides themselves (in the case of *TeX, one is supposed to use the `pdfpc.sty` package, or just the original beamer notes), so you don't have to worry about the synchronization at all.

Just my opinion (and therefore, feel free to disregard :) ). I think that slides are often more immutable than speaker notes, so there will be many situations where you edit speaker notes but not the slides. Editing notes in *TeX and rebuilding slides is harder than editing it in pdfpc, so I naturally gravitate toward writing notes in pdfpc. However, when there *are* updates to the slides, it's troublesome to move notes around. Given this, a user has to choose one of two workflows:

- Making notes in the presentation maker, which is a worse experience when working on speaker notes, but easier to maintain
- Making notes in *pdfpc*, which is a better experience working on speaker notes, but a pain to migrate if you make changes to the slides

So, documentation of the format helps users working in the second workflow.> Yes, that's the intended behavior. First, the "precedence" didn't mean you could _override_ the PDF annotation while in `pdfpc`. Rather, if a manual note already existed (entered in a previous pdfpc session), and then the PDF file was modified to have an annotation on the same page, it would have been ignored. Yes, it was confusing, and so in 4.5 the precedence was changed (but the docs weren't updated :) so it's a doc bug).
 
> It's still quite a pain trying to support notes potentially coming from two sources. It might be better to take the either-or approach: if the PDF annotations are detected, disallow manual notes at all...

If you end up taking an either/or approach, perhaps add a switch in the command-line to choose annotations and default to pdfpc notes? 
 
> Technically, it would be rather trivial to edit the PDF annotations from pdfpc. But then they would be overwritten on the next invocation of the software producing the slides... There is no silver bullet here, but IMO the best approach is to produce _both_ slides and notes by the same software (within the same workflow).

Yeah, for maintainability, slides and notes from the same software would be ideal. I think that, from a usability standpoint, *some* users prefer to write it within pdfpc though (just a hunch).

**Comment by fnevgeny** [comment]
@zhangchuck Is #610 what you want?

**Comment by zhangchuck** [comment]
Yep. That's perfect. Thanks!

(In case it's helpful for people looking up this issue later:
https://json-schema.org/understanding-json-schema/structuring.html#defs)

**Comment by fnevgeny** [comment]
@AndreasBilke my idea was to keep this file under the main pdfpc repository, but copy to github.io with the versioned path (like https://pdfpc.github.io/schema/pdfpc/2) upon release of new pdfpc versions if the JSON format changes. What do you think?

**Comment by AndreasBilke** [comment]
@fnevgeny Maybe we can have the same mechanism like releasing (and linking) the current example slides and attach them to releases? Then you can reference them with "Latest release"/schema.

**Comment by fnevgeny** [comment]
> Then you can reference them with "Latest release"/schema.

In that case, there would be no easy way to find a specific older version of the schema.

I really doubt the .pdfpc schema will ever get any adoption except the internal use of pdfpc (which is what I said in the first comment), but if we do proceed with publishing it, let's do it according to the rules :).

**Comment by AndreasBilke** [comment]
> In that case, there would be no easy way to find a specific older version of the schema.

No but you would see which pdfpc version uses which schema version. It would also make the release process easier, since it's just another asset attached to a release :D

**Comment by AndreasBilke** [comment]
Okay, I think I got it. Writing a thing which looks like a valid URL but results in HTTP 404 is not an option, so we need to upload it to the github web repo, right (otherwise we can't have stable URLs which are not bound to a pdfpc release)?

**Comment by fnevgeny** [comment]
Right, that seems the only reasonable way. We also need to setup the "extensionless" URL's to be redirected to the respective .json file, I suppose it's possible with github.io.

**Comment by The-Compiler** [comment]
FWIW if someone wants a more human-readable representation of the data in #610, the [JSON Schema Viewer](https://json-schema.app/view/%23?url=https%3A%2F%2Fraw.githubusercontent.com%2Fpdfpc%2Fpdfpc%2Fjson-schema%2Fschema%2Fpdfpc.json) website renders it quite nicely.

**Comment by bytinbit** [comment]
I'm very glad you raised this topic, @zhangchuck because I'm having a need similar to yours: Slides made in PowerPoint (on a Windows VM), exported as pdf + highly mutable speaker notes used on a Linux host with pdfpc. I create the slides in PowerPoint with a first draft oft speaker notes, but had the issue that speaker notes are not included in the exported pdf. I've created a [tool that extracts the speaker notes](https://github.com/bytinbit/pptx2pdfpc) and creates the .pdfpc-file, but am lacking the description of all possible fields in the config file. The links posted help a lot with determining what to add as options to my tool, thanks.

**Comment by fnevgeny** [comment]
@bytinbit It seems you create the obsolete style .pdfpc files, not the current JSON-based ones. In fact, I'd rather augment the exported PDF file with native PDF annotations, which pdfpc supports. To this end, you can use the poppler module in python.

**Comment by bytinbit** [comment]
Ah, I was not aware that the .pdfpc-files were obsolete - thanks for the update! I see what I'll do with my tool then and rewrite it based on the new format or the pdf annotations.
