### ISSUE TITLE
Pointer is behind video

### ISSUE THREAD

**Issue by khdlr** [pdfpc/pdfpc#606]
First of all, pdfpc is amazing! I just discovered that it can show videos on my slides. However, I noticed a small issue with the pointer and video display (Surprisingly, the drawing tool does not exhibit any similar issues).

**Expected Behaviour**

Pointer is showing on top of a video 

**Actual Behaviour**

Pointer is hidden behind video 

**Steps to reproduce**

1. Download and extract https://pdfpc.github.io/demo/pdfpc-video-example.zip
2. Run pdfpc video-example.pdf
3. Navigate to a slide with a video
4. Activate "Laser" Pointer and move it over the video

pdfpc version: v4.5
Used Distribution (GTK version, vala version): GTK 3.24.30-2, Vala 0.52.5-1 (Arch Linux on kernel 5.13.12)
Display Server (X/Wayland): X
HiDPI Setting (yes/no): no

**Comment by fnevgeny** [comment]
@khdlr, please test #607.

**Comment by khdlr** [comment]
Works like a charm for me :+1:
