### ISSUE TITLE
Notes flag skews presentation

### ISSUE THREAD

**Issue by sesselastronaut** [pdfpc/pdfpc#608]
Compiling the `pdfpc-demo.tex` and starting it with `pdfpc pdfpc-demo.pdf` brings me the expected layout on a 2 screen desktop with preview and presenter window fully visible. However once I run the file with `pdfpc --notes=bottom pdfpc-demo.pdf`, which shows a skewed layout, and then run the same command from above again `pdfpc pdfpc-demo.pdf` the screen layout stays the same as running it with the --notes flag. See screenshot.
![Screenshot_2021-08-31_18-45-05](https://user-images.githubusercontent.com/861210/131543916-53d48755-fcd8-42c2-a070-e9597b7b22d8.png)
What do I miss at this point to get the normal layout back?

**Comment by einhander** [comment]
You can delete pdfpc-demo.pdfpc file, to revert back default settings.

**Comment by sesselastronaut** [comment]
That does the trick, many thanks!
