### ISSUE TITLE
The README and FAQ lack instructions on how to uninstall

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pdfpc/pdfpc#616]
**Expected Behaviour**

I expect the README to disclose how to uninstall the software.

**Actual Behaviour**

It doesn't.

**Steps to reproduce**

See [here (the README)](https://github.com/pdfpc/pdfpc) and [here (the FAQ](https://github.com/pdfpc/pdfpc/blob/master/FAQ.rst)).

pdfpc version: irrelevant.
Used Distribution (GTK version, vala version) :irrelevant.
Display Server (X/Wayland): irrelevant.
HiDPI Setting (yes/no): irrelevant.

**Comment by fnevgeny** [comment]
"make install"; write down the files listed; remove.

**Comment by LinuxOnTheDesktop** [comment]
Nothing save your comment contains those instructions. Also, it would be better were `make uninstall` to work.
