### ISSUE TITLE
v4.5.0: in notes, line-breaks appear only in editing mode

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pdfpc/pdfpc#617]
**Expected Behaviour**

I expect line breaks that I enter within a note to display as line-breaks not only when I am editing a note but also when I am not.

**Actual Behaviour**

Line breaks that I enter within a note display as line-breaks only when I am editing a note.

Editing mode:

![image](https://user-images.githubusercontent.com/47056543/133120906-6e148292-d30e-46e5-938a-a93c5bef8d20.png)

Non-editing mode: 

![image](https://user-images.githubusercontent.com/47056543/133120996-a35ea5f7-c4db-45f5-9a20-1f4652d2596b.png)

**Steps to reproduce**

1. Enter lines of text into a note, such that one has something like what is depicted in the first screenshot above.
2. Leave editing mode and look at the note.

pdfpc version: 4.5.0
Used Distribution (GTK version, vala version):
Linux Mint 20.2 Cinnamon
Vala 0.48.6
GTK version: unknown; how do I determine this?

Display Server (X/Wayland): X
HiDPI Setting (yes/no): no.

**Comment by LinuxOnTheDesktop** [comment]
#587 suggests that the behaviour is by design. If so, then I question that design. Here's why. Surely something that the user has entered - the line break - should not be ignored. Or rather: surely it should not _sometimes_ be ignored (namely when not in editing mode) and sometimes be heeded (namely when in editing mode)?

**Comment by fnevgeny** [comment]
Read the docs. Read the docs about Markdown.

**Comment by LinuxOnTheDesktop** [comment]
Where is the relevant document? Also, you seem to ignore that I wrote the following. '#587 suggests that the behaviour is by design. If so, then I question that design. Here's why.'
