### ISSUE TITLE
Editing externally created notes

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pdfpc/pdfpc#618]
**Only submit a feature request if you read the SUPPORT.md file**

(I cannot find that file. However, I seem to recall that it - or a similar file - says: submit support requests only if you are willing to help implement what you request. Well, my programming ability is likely not up to the job, but I do volunteer to help with testing and perhaps with documentation.)

**The feature wish description**

_The requested feature_: editing externally created notes

_Rationale for the feature_

pdfpc enables one to create and edit notes but it does those things in a rather limited way. So one might resort to other tools to create and/or edit notes. Yet, if one does that, then the notes are not editable within pdfpc. That seems a serious problem. For, one is now using at least two programs. ('At least' because one might create the slides in program P1, create the notes in program P2, and then display them in P3=pdfpc. That is my use case: I use Word - on Windows - to create the slides; I can create and edit notes in any of various programs that display PDFs; and then I use pdfpc for the presentation itself.) More: if one is short of time and/or travelling, then leaving pdfpc in order to use another program to edit notes is a more serious inconvenience.

So I submit that implementing this feature request would make pdfpc much more useful.

**Comment by fnevgeny** [comment]
It will never be implemented. Just use a smart software (e.g., LaTeX) that can do both slides and notes.

> I use Word - on Windows

Together with your nickname, it sounds like a trolling...

**Comment by LinuxOnTheDesktop** [comment]
I have the moniker 'LinuxOnTheDesktop' because I am serious about . . Linux on the desktop. As to Word: LaTex might be better, but those who use WYSIWYG editors have good reasons - unfortunately - to prefer Word to LibreOffice Writer. Why are you imputing bad faith? Is it out of defensiveness?

**Comment by LinuxOnTheDesktop** [comment]
I don't want to start a fight; rather I think that this feature request (and some other issues) have a point to them. Let's judge all those things on their merits.
