### ISSUE TITLE
Wall clock time

### ISSUE THREAD

**Issue by eletronzip** [pdfpc/pdfpc#62]
Hi, feature request. :)

Is it possible to add an option for a real time clock instead or together with the presentation timer?

Thanks.

**Comment by AndreasBilke** [comment]
Hi. What would be the benefit for having a real time clock in a
presentation program?

**Comment by arbox** [comment]
I support this request, probably not in form of both, but in form of alternative (I could select one of both variants). I feel better to have absolute times not relative because I know when I have to finish (e.g. at 5:45).

**Comment by mrueg** [comment]
Maybe add a -r cmdline option for that?

**Comment by AndreasBilke** [comment]
Ah, I probably misunderstood the request. I have thought of an extra precise
timing device instead of using the computer time.

You want to see the current time and not the amount of time which has been
ellapsed since you began your talk? That sounds like a good idea :).

**Comment by rschroll** [comment]
You may have already seen it, but the --end-time=HH:MM flag allows you 
to specify when your talk ends.  You'll get a countdown to that time 
instead of the elapsed time counter.


That said, an option to show the current time here is very reasonable.

**Comment by eletronzip** [comment]
Exactly @AndreasBilke ! My English is not the best, :). 
Thanks @arbox, you explained exactly what I feel.
I actually use the --end-time flag, but I'd rather look at an absolute clock, maybe this is the case for other people too.

**Comment by AndreasBilke** [comment]
Could some of the requestors test this feature from #70 ?

**Comment by ziotom78** [comment]
My typical usage of the program is to use it for projecting slides on the wall and use the laptop monitor to have presenter notes at hand. Occasionally I have to show animations or do interactive exercises with other programs, so I close `pdfpc`, turn on display mirroring and start the program I need. When I finish, I turn off mirroring again and restart `pdfpc`. The problem with this workflow is that the time counter is always reset to zero, so I have to keep an eye on my clock to check how much time I still have.

I am really interested in your pull request, I have downloaded and briefly tested it, and the `-C` switch seems to do exactly what I want. I'll surely test it for my next lesson, next week.

**Comment by AndreasBilke** [comment]
#70 was merged into master.

**Comment by ziotom78** [comment]
I tested this feature this afternoon in my class, and it worked flawlessly. Thanks a lot!
