### ISSUE TITLE
Optional dependency on WebKit-GTK

### ISSUE THREAD

**Issue by TheJJ** [pdfpc/pdfpc#622]
I don't have webkit-gtk installed currently, only pdfpc requires it now.

Please make the dependency to webkit-gtk optional. I see it's just for markdown support, so I'd be really glad if this can be enabled/disabled at configure time. Thanks :smiley:

**Comment by fnevgeny** [comment]
webkit-gtk is currently used to render plain text as well.

**Comment by fnevgeny** [comment]
Given the slow progress of #590 and no foreseen porting of webkit2gtk to some non-Unix OS's at all, I reopen the issue.
