### ISSUE TITLE
Add adjustable font size to timer

### ISSUE THREAD

**Issue by Gordin508** [pdfpc/pdfpc#624]
It would be very useful if the timer font size could be adjusted, specifically increased.

Currently pdfpc allows changing the note size with hotkeys, however, the timer remains unaffected. This may be a problem in certain setups as the timer becomes unreadable if the presenter is not standing directly in front of the presenter screen. This is a common scenario in my opinion as the presenter would usually move around the room a bit.

The current UI layout would allow doubling the timer size without visual interference with other UI elements.

**Comment by fnevgeny** [comment]
As a quick fix, you can put in your personal CSS file (`$XDG_CONFIG_HOME/pdfpc/pdfpc.css`) something like

```
.bottomText {
    font-size: 36px;
}
```

but this will prevent rescaling of the label upon window resize.
