### ISSUE TITLE
Presentation window out of sync if hidden (Wayland only)

### ISSUE THREAD

**Issue by ningit** [pdfpc/pdfpc#625]
**Expected Behaviour**

When shared in a videoconference system, the presentation window should be in sync with the presenter window, even if it is out of focus in the screen.

**Actual Behaviour**

The contents of the presentation window are frozen and do not reflect the changes (jumping between slides or using markers) in the presenter window unless the former is given focus.

**Steps to reproduce**

1. Run `pdfpc -w both file.pdf` for some `file.pdf`.
2. Share the presentation window in a videoconference service like Google Meet.
3. With the presenter window maximized in the presenter screen, jump between slides, or use the pointer, the pen or the spotlight while looking at the shared window in the videconference system. Nothing changes.
4. Bring the presentation window into focus (with Alt+Tab, for example). The shared screen gets updated.

This problem does not happen with X.

pdfpc version: 4.5
Used Distribution: Arch Linux (GTK 3.24.30+90+g20be04f7ac-1, Vala 0.54.3)
Display Server (X/Wayland): Wayland 
HiDPI Setting: no

**Comment by fnevgeny** [comment]
To me, it sounds like a Wayland problem. Or rather a feature - if a window is obscured by another window, it is a valid optimization strategy not to update its contents.

**Comment by ningit** [comment]
Yes, it may probably be a Wayland bug. Not repainting windows that are not visible at all would be a valid optimization, but in this case the window is being shared in the video conference and so it is visible. This problem happens with other programs too. For example, a shared Totem window playing a movie will be not be updated if it is not visible in the screen... unless in full screen mode. Moreover, calling the `hide` method of the `MetaSurfaceActorWayland` of the presentation window hides it in the screen but solves the problem in the video conference. This is probably not the right thing to do, but it seems that the final program could have some role in putting the window in sync.

I have reported the issue here because it impedes an interesting use case of pdfpc, giving a presentation through a video conference system when using Wayland.

**Comment by fnevgeny** [comment]
I'm not even sure it's a Wayland vs. X11 issue. Likely it's the WM optimization. I see the same with FVWM under X11.

> Not repainting windows that are not visible at all would be a valid optimization, but in this case the window is being shared in the video conference and so it is visible.

Do you think a video conference app has any way of informing WM that a specific window should be treated as in the visible state (in spite of being obscured by another window)?

**Comment by ningit** [comment]
> I'm not even sure it's a Wayland vs. X11 issue. Likely it's the WM optimization. I see the same with FVWM under X11.

It makes sense. I have tested it with GNOME shell, hence with Mutter, in both X11 and Wayland. However, it may behave differently in each case.

> Do you think a video conference app has any way of informing WM that a specific window should be treated as in the visible state (in spite of being obscured by another window)?

Probably not, but the safest in that case is assuming that every shared window is in the visible state. Moreover, this is usually true in video conference systems.

**Comment by fnevgeny** [comment]
> but the safest in that case is assuming that every shared window is in the visible state.

Well, that was my question - how an app can inform the WM (or whoever decides about enforcing the visibility) that a specific window is "shared"?

**Comment by ningit** [comment]
The screen-sharing mechanism must be in touch with the window manager, so it could tell whether a window is being shared and ensure that it is updated. In Gnome under Wayland, the fact that something is being shared is shown by an icon in the shell, so this information is available.

I have submitted an issue to the [xdg-desktop-portal-gtk](https://github.com/flatpak/xdg-desktop-portal-gtk) project. However, this would not solve the same problem in FVWM under X11.

**Comment by caplett** [comment]
I have a possible workaround:

Arrange the Outputs to overlap for one Pixel. 
The windows will still be rendered on one monitor so its not visible.
It feels still a little bit sluggish but works in my case.
