### ISSUE TITLE
Change ratio of area of Current slide and upcoming slide in Presenter Monitor

### ISSUE THREAD

**Issue by DDuttaGit** [pdfpc/pdfpc#626]
Hello Team,
    In the Presenter Monitor I find the area my current slide is covering, is small enough to interpret in my laptop screen. The upcoming slide is actually taking more than enough space than required.
   I like to change this ratio of area that are covered by these two slides in the Presenter Monitor.

**Comment by fnevgeny** [comment]
Please see #576.

**Comment by DDuttaGit** [comment]
@fnevgeny Thanks for your your support.

As mentioned in #576 `Shift + C` can be used to customise the GUI, I am using `pdfpc v4.3.4` but this key combination is yielding nothing here. Also the `manpage` of `pdfpc` has no reference of this

But yes, I need to customise GUI of Presenter Monitor. However that has hardly anything to do with `notes`.

**Comment by fnevgeny** [comment]
> As mentioned in #576 `Shift + C` can be used to customise the GUI, I am using `pdfpc v4.3.4` but this key combination is yielding nothing here.

Well, upgrade to the latest released version.

There are also pdfpcrc options that you may want to tune - `current-height`, `current-size`, `next-height`.

**Comment by DDuttaGit** [comment]
> > As mentioned in #576 `Shift + C` can be used to customise the GUI, I am using `pdfpc v4.3.4` but this key combination is yielding nothing here.
> 
> Well, upgrade to the latest released version.
> 
> There are also pdfpcrc options that you may want to tune - `current-height`, `current-size`, `next-height`.

Thanks Again @fnevgeny. Your solution is working when I modify the options in `pdfpcrc` file. 

However, I am using a 1920x1080 15inch screen as Presenter monitor. But once the `current-height` is made greater than 82 (default 80); the `timer` and the `pagecount` portion at bottom are going beyond the screen and hence they are disappearing.

Is there any way to lock the bottom portion of Presenter monitor containing the `timer` and `pagecount` and still increasing `current-height`?

**Comment by fnevgeny** [comment]
> once the current-height is made greater than 82 (default 80); the timer and the pagecount portion at bottom are going beyond the screen and hence they are disappearing.

Works fine for me in 4.5.0. Note also that after some point, `current-size` needs to be increased as well - the slides have their aspect ratio fixed, of course. Why are you so hesitant to try the new version?

**Comment by DDuttaGit** [comment]
As you (@fnevgeny ) suggested to upgrade, I tried it explicitly by mentioning the version name i.e 4.5. What it results is an Error. Screenshot Attached below.
![ATrytoInstall4 5Directly](https://user-images.githubusercontent.com/52165986/142768678-fce50465-b08f-488c-89ed-61f3cedd7060.png

Now I leave the responsibility completely to `apt`. It has installed `v4.3` as the newest version. Version installation has been highlighted in the below screenshot. 
![NowLeaveitToAPT](https://user-images.githubusercontent.com/52165986/142768686-0e8cbfcd-8e3a-4e91-b783-b4e772a05780.png)
)

**Comment by fnevgeny** [comment]
4.5 might be absent in the package repository of the OS you use. But we provide clear, easy-to-follow instructions on compiling pdfpc from sources - just follow [README](https://github.com/pdfpc/pdfpc#readme).

**Comment by DDuttaGit** [comment]
Though the documentation is simple but actual installation is not. That was
a whole lot of libraries to install. But then I got package xxxx is not in
VALA API Directories or in GIR Directories or something like that. Now
after a heavy search I found
https://raw.githubusercontent.com/frida/vala/master/vapi/xxxx.vapi and
copied all missing *.vapi  files in /usr/share/vala/vapi.
 However that did not rescue me as new (1393) errors while executing make
come in form:
     1. error: The symbol `Gdk' could not be found  public bool
button_press(Gdk.EventButton button) { for several files
    2. The type name `Pango.Context' in pangoccairo.vapi
Can there be any way out from this? This is too much of pre-process
installing pdpfpc.

**Comment by fnevgeny** [comment]
You never cared to name your OS, but from the mention of `apt-get` I assume it's Debian-based, in which case the _very specific_ instructions we give for Ubuntu should work as is or with minimal changes. Did you follow them? Did you read the README, again?

**Comment by DDuttaGit** [comment]
Yes Dear, I followed them. That you have so politely asked about the OS, I
really appreciate your guess. It is Ubuntu 20.

**Comment by fnevgeny** [comment]
> I followed them

Hmm, but there is nothing like a suggestion to manually copy files from an average place on the Internet - which apparently you did...

**Comment by einhander** [comment]
@DDuttaGit the provided list of packages is not complete, you'll have to find missing packages using 'apt-file search' or packages.ubuntu.com

>copied all missing *.vapi  files in /usr/share/vala/vapi.

That's a wrong decigion. It can lead to complete broken system.

**Comment by DDuttaGit** [comment]
Thanks @einhander , I'll then start afresh and try install all the dependencies.

**Comment by einhander** [comment]
@fnevgeny  Sorry, may be I'm wrong about missing packages in readme. Some time ago I updated pdfpc install to a more recent, and found missing packages. I remembered that because I have to find out that dev package I should install. But I'm pretty sure that I used copy-paste to install necessary packages.

**Comment by fnevgeny** [comment]
Well, if you find something missing next time, please file a bug report...
