### ISSUE TITLE
video doesn't playback on mouseclick nor showing the controls

### ISSUE THREAD

**Issue by sesselastronaut** [pdfpc/pdfpc#628]
**Expected Behaviour**
When "Click on the image to play/pause the video" the video should play back, moving the mouse on the bottom of the video the controls should come up.

**Actual Behaviour**
When clicking on the image of the video the presentation skips to the next slide.

**Steps to reproduce**

1. download and compile the demo example. 
2. start the presentation with `pdfpc video-example.pdf` and move to frame 5 "Example 1" showing the poster image of the video. Click on the video and next frame will be displayed. Also moving the mouse to the bottom for the controls has no effect/no controls shown.

pdfpc version: 4.5.0-2
Used Distribution (GTK version, vala version): Debian 10.5 (bullseye),  libgtk 3.24.24-4
Display Server: X
HiDPI Setting: yes

**Comment by fnevgeny** [comment]
Make sure you've read the [FAQ](https://github.com/pdfpc/pdfpc/blob/master/FAQ.rst).

**Comment by fnevgeny** [comment]
Do you click on the presenter or the presentation screen?

**Comment by sesselastronaut** [comment]
Haaa, I owe you a drink for this comment, in the presenter screen works like expected, I should have found this myself, anyway, many thanks!

**Comment by fnevgeny** [comment]
In the master branch, you can click on both. There are also other improvements related to the video playback interface.
