### ISSUE TITLE
Stretched video

### ISSUE THREAD

**Issue by GregorySchwartz** [pdfpc/pdfpc#638]
**Expected Behaviour**
Video appears in correct aspect ratio as in Okular.

**Actual Behaviour**
Video is stretched to fill the entire specified width and height specified by beamer. I understand that this behavior may be required by some, but I would like a non-stretched video.

**Steps to reproduce**

1. Include a movie in beamer: `\movie[width=\textwidth,height=0.8\textheight]{}{/path/to/movie}`
2. Press play on the pdf video in pdfpc.

pdfpc version: 4.5
Used Distribution (GTK version, vala version):  GTK
Display Server (X/Wayland): X
HiDPI Setting (yes/no): no

**Comment by fnevgeny** [comment]
From the manual of the `multimedia.sty` package:

> The aspect ratio of the movie will _not_ be corrected automatically if the dimension of the ⟨poster text⟩ box does not have the same aspect ratio.

So I believe the behavior of pdfpc is correct.

**Comment by GregorySchwartz** [comment]
Ah, then nevermind. I wonder why Okular behaves differently.
