### ISSUE TITLE
Full frame video

### ISSUE THREAD

**Issue by sesselastronaut** [pdfpc/pdfpc#639]
Previous versions came with a `pdfpc-commands.sty` which included helpful commands for instance to have a presentation with a full frame video.  I've been using this a lot and still using it copying the `pdfpc-commands.sty` into my current working folder.  This seems to have gone in the current version. It would be nice to have this back for people who are opting for some full frame features.

**Comment by fnevgeny** [comment]
We have a separate project for pdfpc-specific LaTeX stuff, https://github.com/pdfpc/latex-pdfpc, please post your suggestions there. Note though that `pdfpc-commands.sty` used the `\href` trick for embedding videos, which is strongly deprecated. Please see https://github.com/pdfpc/pdfpc/releases/latest/download/pdfpc-video-example.zip for explanations.

**Comment by sesselastronaut** [comment]
Thanks for that indication that `\href` is deprecated! For me the main thing is the full screen video feature. Which somehow works using the `\movie` command, however the video is slightly off (~1cm) on the X-Axis, using the following MWE:
```
\begin{frame}
  \movie{\includegraphics[width=\paperwidth, height=\paperheight]{apollo17.jpg}}{apollo17.avi}
\end{frame}
```
If there's a way this could be adjusted there's no need for `\href` anymore, at least from my side
