### ISSUE TITLE
When in eraser mode and entering the presenter window, the tool is automatically changed to pen mode

### ISSUE THREAD

**Issue by dov** [pdfpc/pdfpc#643]
**Expected Behaviour**

When in eraser mode and using drawing tablet (wacom) to enter the slide window, the tool should stay an eraser, so that it is possible to erase with the stylus.

**Actual Behaviour**

Currently when entereting the slide window, the tool is automatically changed to pen mode

**Steps to reproduce**

1. Open the toolbox
2. With the mouse choose the eraser tool
3. Switch to the stylus and enter the slide area. This causes the tool to change to an eraser

pdfpc version: 3310efbf87b5457cbff49076447fcf5f822c2269 (git)
Used Distribution (GTK version, vala version): Fedora 36, Gtk 3.24
Display Server (X/Wayland): X11
HiDPI Setting (yes/no): ?

**Comment by fnevgeny** [comment]
A tablet stylus itself usually has a way to switch between the pen and eraser mode, and pdfpc tries to autodetect that. You can set the `disable-input-autodetection` option in the pdfpcrc file to switch the autodetection off.

**Comment by dov** [comment]
@fnevgeny Thanks. The `disable-input-autodetection` solves the problem for me. I still don't know how to distinguish between a mouse button press and a stylus button press, to make the stylus button press turn on eraser mode. I worked around that by adding "e" in a private branch for quick toggle between pen and eraser (like in Krita).

**Comment by fnevgeny** [comment]
I don't have a stylus right now to check, but I remember its button wasn't detected as a mouse click at all, it just changed the stylus mode which pdfpc correctly detected. Which tablet/stylus do you use?

**Comment by dov** [comment]
I have a One by Wacom. All events come through as "normal" mouse events, and you have to probe the event further to figure out what its source is.

I investigated how to distinguish between a mouse event and a stylus event and found that you can do it by the following code (gtkmm syntax):

```
  bool on_button_press_event(GdkEventButton *event) override
  {
    GdkDeviceTool *tool = gdk_event_get_device_tool((GdkEvent*)event);

    // For mouse the tool isn't defined, so we set a default -1
    GdkDeviceToolType tool_type = (GdkDeviceToolType)(-1);
    if (tool)
      // true for stylus only
      tool_type = gdk_device_tool_get_tool_type (tool);

    print("button_press_notify: tool_type={}, x,y,{},{}\n",
          (int)tool_type, event->x, event->y);
    return true;
  }
```

With code like this it should be trivial to erase on motion event if the stylus button is pressed, and draw if the stylus button is not pressed. I'll add something like this to my "eraser-pen-toggle" branch.
