### ISSUE TITLE
pdfpc's documentation leave it unclear whether overlays created in PowerPoint will work

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pdfpc/pdfpc#652]
**Expected Behaviour**

The documentation should make plain the answer to the following question. _Is there a way in which overlays created in PowerPoint can be used with pdfpc?_ By 'the documentation' I understand the README (on github and within the program files) together with pdfpc's manual (that manual being the one that is available via `man pdfpc`).

**Actual Behaviour**

The matter is not made plain. I suspect that the answer to the question is as follows. _No - and no matter just how one exports to PDF within PowerPoint_.

(The user who presumes that her PowerPoint overlays cannot translate into pdfpc might try to re-create her overlays within pdfpc. As a re-creation, that would be extra work. Moreover: it seems to me that the instructions that the manual gives on the creation of overlays could be both clearer and more discoverable. More discoverable, partly just because the manual itself is not especially discoverable - at least for the user who has got used to find instructions outside of manuals - and because it is hard, at least for many users and at least if the user is in a hurry, to find any particular topic within the manual. I myself decided to cut my loses: for the presentation of mine that was at issue, I gave up upon pdfpc in favour of delivering my presentation via LibreOffice's Impress.)

**Steps to reproduce**

1. Wonder whether there a way in which overlays created in PowerPoint can be used with pdfpc.
2. Consult pdfpc documentation.
3. Fail to get an answer to the question of _1_. 
4. Either have the hard job of re-creating one's overlays, or else present one's presentation using software other than pdfpc.

pdfpc version: 4.5

Cf., within issue #554, [here ](https://github.com/pdfpc/pdfpc/issues/554#issuecomment-1245932848) and below.

**Proposed remedy**

Make it plain, in the README and the manual, whether or not overlays created in PowerPoint can be used with pdfpc.

**Comment by fnevgeny** [comment]
It's reasonable to assume that anything *not* mentioned as supported is not supported.
