### ISSUE TITLE
Pdfpc overlay-spec aware \note override, with patch included

### ISSUE THREAD

**Issue by Britaliope** [pdfpc/pdfpc#653]
Currently the overrided \note command is not overlay-aware : using \note<3-5>[item]{stuff} results in a huge mess.

Here is how to fix it
```patch
80,81c80,81
<   \renewcommand{\note}[2][]{%
<     \IfStrEq{#1}{item}%
---
>   \renewcommand<>{\note}[2][]{%
>     \only#3{\IfStrEq{#1}{item}%
84c84
<       {\pdfpcnote{#2}}%
---
>       {\pdfpcnote{#2}}}%
```

**Comment by AndreasBilke** [comment]
Could you create a PR for this?

**Comment by Britaliope** [comment]
> Could you create a PR for this? (Also for acknowledge your contribution in the commit history)

I tried when submitting this patch but was unable to find the repository. i've looked again and found it... the MR is linked
