### ISSUE TITLE
Freeze on slides with videos

### ISSUE THREAD

**Issue by einhander** [pdfpc/pdfpc#654]
**Expected Behaviour**
Plays video on click

**Actual Behaviour**

Pdfpc freeze with following log in terminal:
```
Gstreamer error from element qtdemux0: Internal data stream error.
  (debugging info: ../gst/isomp4/qtdemux.c(6752): gst_qtdemux_loop (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstQTDemux:qtdemux0:
streaming stopped, reason error (-5))
Gstreamer error from element qtdemux0: Internal data stream error.
  (debugging info: ../gst/isomp4/qtdemux.c(6752): gst_qtdemux_loop (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstQTDemux:qtdemux0:
streaming stopped, reason error (-5))
```

Tests with gst-play-1.0

`gst-play-1.0 --gst-fatal-warnings --videosink gtksink file.mp4` plays ok with following in terminal:
```
Redistribute latency...
Redistribute latency...
Redistribute latency...
Redistribute latency...
```

`gst-play-1.0 --gst-fatal-warnings --gst-debug-level=3 --videosink gtksink file.mp4` plays ok with followin warnings:
```
0:00:00.129117730 57817 0x555bd3a6db00 WARN                 basesrc gstbasesrc.c:3688:gst_base_src_start_complete:<source> pad not activated yet
0:00:00.129686675 57817 0x555bd3a6db00 WARN                 basesrc gstbasesrc.c:3688:gst_base_src_start_complete:<source> pad not activated yet
0:00:00.168425039 57817 0x555bd3c90d20 WARN                 qtdemux qtdemux_types.c:249:qtdemux_type_get: unknown QuickTime node type gsst
0:00:00.168462899 57817 0x555bd3c90d20 WARN                 qtdemux qtdemux_types.c:249:qtdemux_type_get: unknown QuickTime node type gstd
0:00:00.168538968 57817 0x555bd3c90d20 WARN                 qtdemux qtdemux.c:3121:qtdemux_parse_trex:<qtdemux0> failed to find fragment defaults for stream 1
0:00:00.168748035 57817 0x555bd3c90d20 WARN                 qtdemux qtdemux.c:3121:qtdemux_parse_trex:<qtdemux0> failed to find fragment defaults for stream 2
0:00:00.261812849 57817 0x555bd3c90d20 WARN              vaapiblend gstvaapiblend.c:184:gst_vaapi_blend_initialize:<vaapiblend0> VPP does not support global alpha blending
Redistribute latency...
0:00:00.907511674 57817 0x555bd3c90a40 WARN             vaapifilter gstvaapifilter.c:2395:gst_vaapi_filter_set_colorimetry_unlocked:<vaapifilter1> driver does not support 'bt709' input colorimetry. vpp may fail or produce unexpected results.
0:00:00.907657455 57817 0x555bd3c90a40 WARN             vaapifilter gstvaapifilter.c:2405:gst_vaapi_filter_set_colorimetry_unlocked:<vaapifilter1> driver does not support 'sRGB' output colorimetry. vpp may fail or produce unexpected results.
```

**Steps to reproduce**

Create slide with video, by any command e.g \href or \movie

pdfpc version:
Used Distribution (GTK version, vala version): Debian testing gtk=4.8.1,valac-0.56
Display Server (X/Wayland): Xserver
HiDPI Setting (yes/no): no

**Comment by fnevgeny** [comment]
Which version of pdfpc?

**Comment by fnevgeny** [comment]
BTW, just in case: does it happen also with apollo17.avi from the video demo?

**Comment by einhander** [comment]
>Which version of pdfpc?

Latest git. I've also checked debian repo version, the same result

> does it happen also with apollo17.avi

No, it's only file, that play ok. Seems gstreamer problem, but gst-play play other files without errors. 
.

**Comment by fnevgeny** [comment]
> > does it happen also with apollo17.avi
> 
> No, it's only file, that play ok. Seems gstreamer problem, but gst-play play other files without errors. .

Well, please share a problematic file.

**Comment by einhander** [comment]
Here the file, but I don't see anything special in it: 
https://dropmefiles.com/SWwgR

Is there the way to provide more verbose output from pdfpc to diagnose the problem?

**Comment by fnevgeny** [comment]
Which video card/driver do you use? `nouveau` per chance? Try uninstalling `gstreamer1.0-vaapi`.

**Comment by einhander** [comment]
>Which video card/driver do you use

I use laptop with ryzen 3 5300u, I think it uses radeon_drv_video.so for vaapi acceleration. On other software it works just fine.

>nouveau per chance?

No, nouveau works flawlessly with that video file on other PC.

**Comment by fnevgeny** [comment]
So did you try uninstalling `gstreamer1.0-vaapi`?

**Comment by einhander** [comment]
> Try uninstalling gstreamer1.0-vaapi

Yes, it's hardware acceleration after all. I uninstalled gstreamer1.0-vaapi video play ok.

**Comment by einhander** [comment]
I don't want to disable hw accel for all gstreamer programs. Is there the way to use software decoding for video in pdfpc?

**Comment by fnevgeny** [comment]
> Is there the way to use software decoding for video in pdfpc?

Define environment variable `LIBVA_DRIVERS_PATH` to point to a non-existing path. <https://gstreamer.freedesktop.org/documentation/vaapi/index.html>

**Comment by einhander** [comment]
Thank you! Has pdfpc/gstreamer supports vdpau, vdpau has better performance on my system?

**Comment by fnevgeny** [comment]
It is the responsibility of GStreamer to use VDPAU via `libva`. Or actually, it *was*. See <https://gstreamer.freedesktop.org/releases/1.18/>: "The VDPAU plugin has been unmaintained and unsupported for a very long time and does not have the feature set we expect from hardware-accelerated video decoders. It's been superseded by the nvcodec plugin leveraging NVIDIA's NVDEC API."
