### ISSUE TITLE
Jump to first overlay

### ISSUE THREAD

**Issue by bmurauer** [pdfpc/pdfpc#655]
I understand that it is a sensible setting to jump to the last overlay of a slide when using the overview or Shift+PgDown, as it will usually be the overlay that contains "all" information.

However, I have some overlays where i change the content on the slide, and I would want to jump to a specific overlay of the slide. From the documentation, I think that this is not a use case that is currently possible. Please do correct me if I'm wrong, and I'll gladly close this ticket.

I understand that choosing a specific overlay may be challenging in terms of designing the UI to be intuitive. Therefore, I have the following suggestions for a simpler solution that at least enables displaying the **first** overlay of a slide:
 - in the overview mode, when clicking on a slide using the left mouse button, the last overlay will be displayed (this is currently the case). However, when clicking with the right mouse button, the first overlay of that slide is displayed.
 - a key combination could be added to jump to the first overlay of the next user slide.
 
Let me know what you think.

**Comment by fnevgeny** [comment]
> * in the overview mode, when clicking on a slide using the left mouse button, the last overlay will be displayed (this is currently the case). However, when clicking with the right mouse button, the first overlay of that slide is displayed.

 `Shift + 1st mouse button`. Already there, please see the man page.

> * a key combination could be added to jump to the first overlay of the next user slide.

This is the default when moving to the next slide.
