### ISSUE TITLE
Request a new release

### ISSUE THREAD

**Issue by chenrui333** [pdfpc/pdfpc#656]
It has been two years since the 4.5.0 release, while [4.5.0 build does not work on the homebrew side](https://github.com/Homebrew/homebrew-core/pull/67319) due to the dependency missing issue, the [head build](https://github.com/Homebrew/homebrew-core/pull/106761) does work for us. Hence, requesting a new release! Thanks!

**Comment by fnevgeny** [comment]
I've just updated the version/copyright strings :).

**Comment by AndreasBilke** [comment]
Oh no :( Too much manual work. This sounds like CI work :)

**Comment by fnevgeny** [comment]
Right, we need to add release-specific actions. Including TeX-compiling the demos.

**Comment by ildar** [comment]
plz reopen. The new release is strongly needed esp. after https://github.com/pdfpc/pdfpc/pull/716
thank you

**Comment by fnevgeny** [comment]
Well, this specific issue was closed with the release of 4.6.0. Having said that, I agree it has, again, passed quite some time since the previous release. @AndreasBilke, do you mind going for 4.7 before the holiday season?

**Comment by AndreasBilke** [comment]
> @AndreasBilke, do you mind going for 4.7 before the holiday season?

The release is out. I had some fun with the outdated workflow dependencies :)
