### ISSUE TITLE
Switch between "full screen" and presentation mode for drawing

### ISSUE THREAD

**Issue by torwag** [pdfpc/pdfpc#658]
I recently learned about the Shift+c function to modify the position of the frames for the preview, notes and presenting frames in the presenter view. 
I tested this together with drawings and I was happy to see, that I can draw and resize the presenting frame including the drawing.

I believe from here it is rather simple to provide a hotkey, which once pressed puts the presenting screen into "full screen" mode, removing the preview, notes, and previous and next overlays.
Pressing the button again, the former frame positions get restored.

That would allow people to switch to full screen to get the maximum screen estate for drawing annotations, which potentially results in much clear handwriting and accuracy and being able to switch back to "presentation mode" after that, all without any change of the presenting window and hence without being noticed by the audience.

If this sounds like a great idea, I would try to give it a go.

**Comment by torwag** [comment]
@fnevgeny You're kidding me ;)
I know I was toying with the idea at one point. During the pandemic and online lectures, I had not much use of pdfpc as we used the usual online tools and now being back in class I noticed again how much I miss it. I have completely forgotten about it.
Thanks for reminding me.

**Comment by fnevgeny** [comment]
I just noticed that `Shift+a` wasn't mentioned in the manpage, only in the demo slides. Now fixed.
