### ISSUE TITLE
Show a translucent crosshair for the pen function

### ISSUE THREAD

**Issue by torwag** [pdfpc/pdfpc#659]
I often face the challenge to see the little dot during a presentation if I have selected the pen. Furthermore, sometimes I would like to make sure that text or drawings do align somewhat, which is often difficult on a small screen, standing in front of an audience.

I would love to add (switchable) a translucent crosshair for the pen mode, which allows me to easily find it and enables me to align e.g. the start of a drawing. This crosshair should only be visible in the presenter view, which might be challenging as for now if I see this correctly, all annotating related functions are directly mirrored to the presentation view. 

Also, here, would be looking into it if this finds approval.

**Comment by fnevgeny** [comment]
> I would love to add (switchable) a translucent crosshair for the pen mode, which allows me to easily find it and enables me to align e.g. the start of a drawing.

Actually, there is a (default) cursor, but it becomes hidden after a few seconds of inactivity. It doesn't show up again once you move the pointer though - unless you move it off the main slide view (try it), which I would call a bug.

> This crosshair should only be visible in the presenter view, which might be challenging as for now if I see this correctly, all annotating related functions are directly mirrored to the presentation view.

Not really. For example, the "little dot" you mentioned is not shown in the presentation view.
