### ISSUE TITLE
Have different title for the various windows.

### ISSUE THREAD

**Issue by PTNobel** [pdfpc/pdfpc#66]
I'm trying to write a python script that uses i3-msg to move the pdfpc windows to various outputs, however I have no way of knowing which window is which (from the script). Could you change the value of the title?

For example make one title 'pdfpc - Presenter' and 'pdfpc - Projector'. Or at least make it a command line option?

**Comment by AndreasBilke** [comment]
Both windows have a property named "role", I don't know if it is possible
to get this role from a window but if you can, you can distinguish both
windowes that way.

**Comment by rschroll** [comment]
This seems like a reasonable thing to do.  It should be easy to 
implement, and I don't see any downside.
