### ISSUE TITLE
Wrong transition for transdissolve

### ISSUE THREAD

**Issue by glemco** [pdfpc/pdfpc#670]
**Expected Behaviour**

The slide should dissolve smoothly.
[see it on Evince](https://user-images.githubusercontent.com/32201227/212277585-b423f879-0a64-49a8-9a47-d29db6c98062.webm)

**Actual Behaviour**

It rather breaks up into squares.
[see video](https://user-images.githubusercontent.com/32201227/212277601-8bd0b154-4303-4c6a-b543-6c9dcfa42c6b.webm)

**Steps to reproduce**

1. Compile a beamer presentation with the `\transdissolve` command somewhere or use the example presentation.
2. Display the transitioning slide with `pdfpc`

pdfpc version: v4.5
Used Distribution (GTK version, vala version): Bundled in Fedora 37 (gtk3 3.24.36, gtk4 4.8.2, vala 0.56.3)
Display Server (X/Wayland): Wayland
HiDPI Setting (yes/no): no

Overall a minor issue for this great presenter software!

**Comment by fnevgeny** [comment]
Basically, you say that pdfpc and evince implement the dissolve transition differently. But what makes you believe evince is right? Why not, e.g., acrobat that does it differently yet (many small squares flipped randomly)?

Moreover, what is "right"? If you have an authoritative (read: from Adobe) unambiguous *technical* description of how the "dissolve" transition should look like, please point to it.

If your presentation crucially depends on the specific implementation of the page transition, perhaps you should prepare a short animation and include it as a multimedia movie element (which pdfpc supports).

**Comment by fnevgeny** [comment]
> However in my common sense, I would call dissolve something more like the one in Evince.

Well, *my* common sense disagrees with yours. I'm a physicist, and maybe that's the reason. E.g., search for "dissolving crystal" videos (like [this one](https://www.youtube.com/watch?v=cfgPVxWJaB4)). Don't you agree it resembles the implementation in Acrobat? To my *aesthetic* taste, though, this doesn't look very attractive, so I decided to increase the size of the squares and get rid of the randomness - but still keeping in mind the physical meaning of "dissolving". Again, to the best of my knowledge, there is no concise technical description of the effect in the context of the PDF page transitions, so I believe the specific implementation in pdfpc is as "right" as anything else.

>  (and apparently also Wikipedia agrees [Dissolve_(filmmaking)](https://www.wikiwand.com/en/Dissolve_(filmmaking)))

Video editing software use a lot of pixel-level transformations/interpolations/blending anyway (this is just a variant of fade-out/in). But if you look at the *PDF* page transitions, each of them is  just a combination of geometrical  translation and patterned clipping. Adding a separate engine only for a single type of transition out of two dozen makes no (common ;)) sense to me.

**Comment by glemco** [comment]
Well, I agree with you that without a formal specification it boils down to the dev's opinion.
Since that animation is the desired effect I guess I can close the issue and use `\transfade` instead.
Thanks for your help, I completely overlooked the existence of that other transition to do what I wanted!

**Comment by fnevgeny** [comment]
Oh indeed, it has been a while since I was coding the page transitions, so I totally forgot about the "fade" transition type. In Evince, there is no difference between the two. So decide yourself who is closer to the specification...
