### ISSUE TITLE
Support for webkit2gtk-4.1

### ISSUE THREAD

**Issue by ulm** [pdfpc/pdfpc#671]
Gentoo Linux is transitioning from webkit2gtk-4.0 to 4.1, see https://bugs.gentoo.org/893668.

Would it be possible to support webkit2gtk-4.1? IIUC there should be no API differences. However, 4.1 would require libsoup-3.0 (so issue #664 would have to be reconsidered).

**Comment by fnevgeny** [comment]
I believe it should be possible to link against two libsoup API's simultaneously (provided the SONAME's are different, of course) - one (3.0) as the implicit dependence of webkit2gtk-4.1, and 2.4 as pdfpc's explicit dependence.

**Comment by ulm** [comment]
> I believe it should be possible to link against two libsoup API's simultaneously (provided the SONAME's are different, of course) - one (3.0) as the implicit dependence of webkit2gtk-4.1, and 2.4 as pdfpc's explicit dependence.

I think that's not possible. pkgconfig for webkit2gtk-4.1 will include header files for libsoup-3.0 which will cause conflicts. Even if it was possible to work around this, libsoup-2.4 and 3.0 contain a runtime check and verify that both are not loaded into the same process:
```
(process:128960): libsoup-ERROR **: 09:15:12.394: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
```

**Comment by sanjayankur31** [comment]
Just noting that Fedora will also move to webkit2gtk-4.1 soon (in August once Fedora 39 branches). More information here:

https://fedoraproject.org/wiki/Changes/Remove_webkit2gtk-4.0_API_Version

**Comment by AndreasBilke** [comment]
FTR: Debian Bookworm (will be released in june 2023) will also include webkit2gtk-4.1 (https://packages.debian.org/bookworm/libwebkit2gtk-4.1-0)

**Comment by fnevgeny** [comment]
Strictly speaking, switching to webkit2gtk-4.1 is trivial as far as one doesn't need the REST functionality (i.e., accessing the libsoup3 API). So an immediate solution might be to compile with REST=OFF. In fact, I wonder how many users are there that use the functionality. Probably on the order of unity (including me) :).

**Comment by chenrui333** [comment]
👋 Any updates on the webkit2gtk-4.1 support? Thanks!

**Comment by chenrui333** [comment]
Checkin again. Thanks!
