### ISSUE TITLE
Compilation failure using  Vala < v0.47.1

### ISSUE THREAD

**Issue by duksosleepy** [pdfpc/pdfpc#674]
**Expected Behaviour**
Compile successful
**Actual Behaviour**
/newpk/pdfpc/src/classes/action/link_action.vala:87.17-87.27: error: The type name `var' could not be found
                unowned var goto_action = (Poppler.ActionGotoDest*) mapping.action;
                ^^^^^^^^^^^

/newpk/pdfpc/src/classes/action/link_action.vala:95.17-95.27: error: The type name `var' could not be found
                unowned var movie_action = (Poppler.ActionMovie*) mapping.action;
                ^^^^^^^^^^^

/newpk/pdfpc/src/classes/action/link_action.vala:163.17-163.27: error: The type name `var' could not be found
                unowned var action = (Poppler.ActionGotoDest*) this.action;
                ^^^^^^^^^^^

/newpk/pdfpc/src/classes/action/link_action.vala:171.17-171.27: error: The type name `var' could not be found
                unowned var action = (Poppler.ActionMovie*) this.action;
                ^^^^^^^^^^^

/newpk/pdfpc/src/classes/drawings/drawing_commands.vala:144.17-144.27: error: The type name `var' could not be found
                unowned var el = this.drawing_commands.last();
                ^^^^^^^^^^^

/newpk/pdfpc/src/classes/drawings/drawing_commands.vala:161.17-161.27: error: The type name `var' could not be found
                unowned var el = this.redo_commands.last();
                ^^^^^^^^^^^

Compilation failed: 6 error(s), 0 warning(s)
make[2]: *** [src/CMakeFiles/pdfpc.dir/build.make:109: src/classes/action/action_mapping.c] Error 1
make[1]: *** [CMakeFiles/Makefile2:169: src/CMakeFiles/pdfpc.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Steps to reproduce**

1. Install all dependencies
2. cmake -DMDVIEW=OFF ..
3. make

pdfpc version: 4.6.0
Used Distribution (GTK version, vala version): Windows 10(Cygwin), gtk+-3.22.28, vala 0.38.8
Display Server (X/Wayland):
HiDPI Setting (yes/no):

**Comment by fnevgeny** [comment]
Ah yes, "unowned var" was introduced in Vala-0.47.1. Is there a specific reason you're still using the 5-year old v0.38.8?

**Comment by duksosleepy** [comment]
Oh, thank you so much !
