### ISSUE TITLE
Windows 10, Ubuntu WSL installation issue

### ISSUE THREAD

**Issue by Agusmastex** [pdfpc/pdfpc#677]
**Expected Behaviour**
pdf-presenter-console gets installed normally from an Ubuntu bash session started from Windows CMD.

**Actual Behaviour**
E: Unable to locate package pdf-presenter-console

**Steps to reproduce**
1. Install Ubuntu from cmd with 'wsl --install -d Ubuntu
2. Open Windows CMD
3. run 'bash'
4. run 'sudo apt-get install pdf-presenter-console'

I am a noob regarding software issues, I apologize if this is a simple mistake on my part.

**Comment by fnevgeny** [comment]
Please make sure you enabled the "universe" apt repository. Note that in general, we don't answer distribution-specific questions. Also, you may instead want to compile pdfpc natively under Windows, as README explains.
