### ISSUE TITLE
ability to resize the bottom region of the presenter screen

### ISSUE THREAD

**Issue by jdchristensen** [pdfpc/pdfpc#679]
The feature wish description:

I like how with shift-C one can resize the views of the slides on the presenter's screen.  But the window sizes are limited by the vertical space, and currently the bottom region (with the clock/timer and the page count) has unused vertical space.  Would it be possible to be able to resize that region (or for it to automatically be made so that the contents just fit)?

**Comment by fnevgeny** [comment]
Related to #624.
