### ISSUE TITLE
Pre-rendering is broken if option prerender-slides exceeds number of pages

### ISSUE THREAD

**Issue by Enrico204** [pdfpc/pdfpc#688]
**Expected Behaviour**

The pre-rendering should pre-render and cache the configured number of slides for all resolution used at the moment (presentation, presenter "current slide" and presenter "next slide preview", and maybe also the gallery?), except for those slides rendered in less than `cache-min-rtime`.

**Actual Behaviour**

The pre-rendering is pre-rendering and caching the configured number of slides only for some resolutions, forcing the program to render the others when the slide is first presented.

**Steps to reproduce**

1. Open a presentation, wait for pre-rendering
2. Switch to 2nd slide. If the 3rd slide rendering is slow, the delay is still noticeable.

pdfpc version: 4.6.0
Used Distribution (GTK version, Vala version): Debian 11, GTK 3.24.24
Display Server (X11/Wayland): X11
HiDPI Setting (yes/no): no

---

I noticed this behavior because I am ~~messing~~ playing with a persistent disk-based cache. The patch is not ready and not intended to be implemented (I was just experimenting an idea, I will open an issue later to propose this). Anyway, the good part is that the debug prints I added show that the `store()` function in the renderer Cache is called with different sizes:

```
PNG saved for slide 0 (576, 324)
PNG saved for slide 1 (379, 213)
PNG saved for slide 0 (960, 540)
PNG saved for slide 0 (1136, 639)
PNG saved for slide 1 (757, 426)
PNG saved for slide 0 (1883, 1059)
PNG saved for slide 1 (1136, 639)
PNG saved for slide 2 (757, 426)
PNG saved for slide 2 (1136, 639)
PNG saved for slide 1 (1883, 1059)
PNG saved for slide 3 (1136, 639)
PNG saved for slide 2 (1883, 1059)
PNG saved for slide 4 (1136, 639)
...
```

The code that is printing these lines is:

```vala
GLib.printerr("PNG saved for slide %u (%u, %u)\n", props.index, props.width, props.height);
```

As you can see, slide 0 and 1 are rendered with all resolutions, then somehow only 1883x1059 (which I think it's the presentation window) and 1136x639 (which I think is the presenter "current slide" view) are rendered. If I switch to the next slide (1), the pre-rendering kicks in and caches the slide 2 for all other resolutions.

I have attached the patch with my changes to the code. 
[add-file-cache.patch.zip](https://github.com/pdfpc/pdfpc/files/11416005/add-file-cache.patch.zip)

**Comment by fnevgeny** [comment]
There are many "knobs" to fine-tune pre-rendering & caching: `prerender-delay`, `prerender-slides`, `cache-max-rtime`, `cache-min-rtime`, `cache-max-usize`, etc. Please see the pdfpcrc man page. Depending on the configuration and screen resolution(s), not everything is slated for caching, so you don't see your debug messages.

As to the persistent caching - we've been there. Why do you need it? Is your hardware exceptionally low-end? For me, Raspberry Pi3 works just fine, not to mention modern desktop CPU's...

**Comment by Enrico204** [comment]
My `pdfpcrc` contains these options:

```
option black-on-end true
option cache-expiration 3600
option prerender-slides 99
option prerender-delay 2
option cache-max-rtime 100
option cache-min-rtime 0
option cache-max-usize 10240
```

As far as I understand by the manual, this should cache 99 slides from now (starting 2 second after switching to the next slide), caching every slide regardless on how much time is needed for rendering (`cache-min-rtime 0`), keeping all cache for slides where the rendering is > 100ms, and the cap for each cache item is 10M.

So, by using these settings, I expect `pdfpc` to pre-render and cache everything from the start. That's not the case, apparently. Also, it's pre-rendering large resolutions correctly, so I don't think that it's related to the rendering time or size.

On the persistent caching: it's not the hardware, it's the presentation somehow. I'm working on a i7-8750H (it should be fast), and there is at least 200-500ms rendering time for each slide (the presentation is an output of `pandoc`). However, the persistent caching is not the issue here - it's a workaround that I was experimenting with.

**Comment by fnevgeny** [comment]
> there is at least 200-500ms rendering time for each slide

Does it happen with a specific file or with any (e.g., the [official demo](https://github.com/pdfpc/pdfpc/releases/latest/download/pdfpc-demo.pdf))?

**Comment by Enrico204** [comment]
> > there is at least 200-500ms rendering time for each slide
> 
> Does it happen with a specific file or with any (e.g., the [official demo](https://github.com/pdfpc/pdfpc/releases/latest/download/pdfpc-demo.pdf))?

No. But still, the "next slide" image is not pre-rendered (I did some debugging).

I'm doing some tests and I see that at the line https://github.com/pdfpc/pdfpc/blob/b62ef90482103a09bb12c78a0b9e287bf6d55441/src/classes/window/presenter.vala#L580

the 4th parameter `user_slides` is set to `true`, which in turns is checked here: https://github.com/pdfpc/pdfpc/blob/b62ef90482103a09bb12c78a0b9e287bf6d55441/src/classes/view/pdf.vala#L162

If `this.user_slides` is true, then the first code block is executed, and `metadata.user_slide_to_real_slide(last_user_slide, true);` returns `-1`, which is stopping the pre-rendering here: https://github.com/pdfpc/pdfpc/blob/b62ef90482103a09bb12c78a0b9e287bf6d55441/src/classes/view/pdf.vala#L200

Is that (skipping the pre-rendering for the "next slide window") an expected behavior?

I still have issues trying to understand what "user slides" means. Is it a flag for presenter window slides?

**Comment by Enrico204** [comment]
I think I found the problem. My configuration contains the following:

```
option prerender-slides 99
```

The option asks for 99 slide to be pre-rendered. If there are less than 99 slides in total, the code for the "next slide" (`user_slides == true`) is setting `-1` in `last_slide` (due to the line `last_slide = metadata.user_slide_to_real_slide(last_user_slide, true);` in the [`css/classes/view/pdf.vala` in `prerender()` function](https://github.com/pdfpc/pdfpc/blob/b62ef90482103a09bb12c78a0b9e287bf6d55441/src/classes/view/pdf.vala#L165)) where I think it should be `this.n_slides - 1`.

Also, setting `prerender-slides` to a negative number to render all slides (the doc says that it's possible) is not working due to the same reason. And I suspect that it's not working even for other slide "views" (presentation, main presenter view, etc.) when the starting slide is not zero (because of the code in the same region of that file).

If I am not mistaken, by changing the [`if` at the next code block](https://github.com/pdfpc/pdfpc/blob/b62ef90482103a09bb12c78a0b9e287bf6d55441/src/classes/view/pdf.vala#L169) to this will fix these problem:

```c
if (last_slide >= this.n_slides || Options.prerender_slides < 0 || last_slide == -1) {
```

Rationale: the `if` is resetting `last_slide` to `this.n_slides - 1;` when one of these conditions are true:

- `last_slide` is beyond the last slide (this condition is already present in the `if` statement)
- `Options.prerender_slides` is less than zero, as per the documentation: "*set to a negative number to pre-render all at once.*"
- `last_slide` is `-1` (this occurs when rendering the "next slide" view)

What do you think? Shall I open a pull request?

---

How to "reproduce"/"see the problem": I tested both the latest version from `master` and the latest stable (v4.6.0), and I see the problem in both, with any PDF. Here some debug prints I am using: [debug_prints.diff.zip](https://github.com/pdfpc/pdfpc/files/11438782/debug_prints.diff.zip). This is the output I get:

```
$ ~/git/pdfpc-github/build/bin/pdfpc pdfpc-demo.pdf -N
Screensaver inhibited
pre-render requested for widget size (1021 766)
last slide from options
last slide reset
pre-render requested for slide 1 (1021 766)
pre-render requested for widget size (755 566)
last slide from user_slide_to_real_slide 100 (755 566)
last slide from user_slide_to_real_slide -1 (755 566)
pre-render requested for slide 2 (1021 766)
pre-render requested for slide 2 (755 566)
pre-render ended at slide 3 > -1 (755 566)
pre-render requested for slide 3 (1021 766)
pre-render requested for slide 4 (1021 766)
pre-render requested for slide 5 (1021 766)
```

In the line `pre-render ended at slide 3 > -1 (755 566)` you see that the code is terminating prematurely for the next slide view (`755x566`) due to `-1` set in `last_slide` variable.

**Comment by fnevgeny** [comment]
Good catch! `user_slide_to_real_slide` returning -1 is problematic in general, the check should be forced. I think it should either throw an exception or be modified to return `bool` indicating success/failure and the actual slide number via an `out` argument. @AndreasBilke, what's your opinion?
