### ISSUE TITLE
Pre-rendering progress bar is not visible

### ISSUE THREAD

**Issue by Enrico204** [pdfpc/pdfpc#689]
**Expected Behaviour**

In the presenter view, I expected to see a progress bar while the pre-rendering is in progress (as stated by the manual).

**Actual Behaviour**

No progress bar is shown (but the pre-rendering is working).

**Steps to reproduce**

1. Open a presentation

pdfpc version: 4.6.0
Used Distribution (GTK version, Vala version): Debian 11, GTK 3.24.24
Display Server (X11/Wayland): X11
HiDPI Setting (yes/no): no

**Comment by fnevgeny** [comment]
Ah, that's a remnant (in the man page) from old versions.
