### ISSUE TITLE
pdfpc prompts a warning if I move to the next slide

### ISSUE THREAD

**Issue by mrueg** [pdfpc/pdfpc#69]
pdfpc prompts a warning if I move to the next slide:

(pdfpc:19881): Gtk-WARNING **: Theme parsing error: gtk.css:3993:50: Missing name of pseudo-class

**Comment by AndreasBilke** [comment]
We do not ship any gtk.css with pdfpc. Is this probably a CSS file for your current GTK theme?

**Comment by mrueg** [comment]
Thanks, it could be caused by the theme I'm using ( https://github.com/dirruk1/gnome-breeze )
