### ISSUE TITLE
Can't open both windows on single-screen mode?

### ISSUE THREAD

**Issue by naps62** [pdfpc/pdfpc#690]
Question in the title

  I'm on a single-screen setup, but would still like the be able to open both windows
  
  my main use case, is that I often get on stage with my laptop already setup, and just connect the external monitor. As it stands, it seems I can only boot pdfpc once the 2nd monitor is connected.
  
  in addition, the fact that I use a tiling wm made this more confusing to understand. Earlier today I was seeing both windows, because I had a secondary monitor plugged in. but because of tiling rules, they still opened up in the same workspace. Took me a while to figure out why I was only seeing one of them now

**Comment by fnevgeny** [comment]
> I'm on a single-screen setup, but would still like the be able to open both windows

Have you read the man page? Or opened the [demo](https://github.com/pdfpc/pdfpc/releases/latest/download/pdfpc-demo.pdf)?

> my main use case, is that I often get on stage with my laptop already setup, and just connect the external monitor.

That's how it's supposed to work. In fact, it works just fine here.

**Comment by naps62** [comment]
> Have you read the man page? Or opened the [demo](https://github.com/pdfpc/pdfpc/releases/latest/download/pdfpc-demo.pdf)?

I did both of those things. and also played around with the various cli flags to see if I was missing something
went to them again now and found the "Plug and Play" section, which I had missed before. I supose that's what you're hinting at?

Gotta say, as a bit of feedback, that it seems quite an important thing to be so far down the man page, instead of, for example, the "Features" section of the website

being an old-time linux user, I'm very used to things not working on the first try. And I don't have a second monitor at my disposal until the presentation. so the idea of trusting that the tool will do this magic (when historically, dual-screen support has always been tricky, particularly with tiling wms) is very foreign to me.
having the simple ability of opening both windows and allowing me to control them manually would add some welcome predictability

**Comment by AndreasBilke** [comment]
After reading the man page, looking at the demo slides and reading the [FAQ](https://github.com/pdfpc/pdfpc/blob/master/FAQ.rst), do you still have problems configuring your setup properly?

**Comment by naps62** [comment]
@AndreasBilke As I said above, after finding the "Plug and Play" section that I had originally missed, I see the original answer to my question is "not, but it's not suposed to matter".

What I am arguing here is that, at least for me, it does matter. perhaps that's just a me problem and not worth fixing. I'm fine with that.

to your question, am I having configuration problems right now? well no, because I don't have access to a second monitor to double check my configuration, until a few hours from now when I'm actually on stage. that's what my feedback here is about
The fact that I apparently can't have to tool open both windows, and delegate to me the work of positioning them where/how I want feels unnecesssarily restrictive

there's also other use cases I haven't mentioned here, such as wanting the ability to keep another window on the same workspace as the slides, so that I can toggle between "full screen slides" and "slides on the left and a live demo on the right". This requires me to control the layout of the workspace, including the window that I currently don't have access to
