### ISSUE TITLE
Toolbox not starting minimized even when enabled

### ISSUE THREAD

**Issue by ModProg** [pdfpc/pdfpc#696]
**Expected Behaviour**
when setting `option toolbox-minimized true` in the `~/.config/pdfpc/pdfpcrc` i expect the toolbox to start minimized

**Actual Behaviour**
toolbox starts maximized:
![grafik](https://github.com/pdfpc/pdfpc/assets/11978847/bfc0e6d9-1cc5-47aa-abb4-b0149883962f)

**Steps to reproduce**

1. add `option toolbox-minimized true` in `~/.config/pdfpc/pdfpcrc`
2. open presentation and notice it is not minimized

pdfpc version: v4.6
Used Distribution (GTK version, Vala version): not sure how to detect (https://archlinux.org/packages/extra/x86_64/pdfpc/) depends on GTK though
Display Server (X11/Wayland): wayland
HiDPI Setting (yes/no): no

**NOTE**
Another solution to my problem would be to have a way to start the toolbox below the current slide as it wouldn't block any content even when starting maximized.

**Comment by fnevgeny** [comment]
Well, it's a regression from fbf790446d3d2dd75383ff53261ababc773657f4. I don't know, though, how to make it work without using (in this specific single case) [`Widget.set_child_visible()`](https://valadoc.org/gtk+-3.0/Gtk.Widget.set_child_visible.html), which says "never should be called by an application".

**Comment by ModProg** [comment]
It would have been ok for me, to be able to just have the toolbox start out at a position where it doesn't interfere with the slide.

Then again, I'm probably not going to have any presentations in the near future (maybe ever), so I'm not super pressed on having a solution ASAP.

**Comment by fnevgeny** [comment]
> It would have been ok for me, to be able to just have the toolbox start out at a position where it doesn't interfere with the slide.

It shouldn't normally, unless you resize the presenter windows. I guess you start in the windowed mode and then make it full screen, right?

**Comment by ModProg** [comment]
I kept the presenter window windowed, and had the presentation window full screen. But an issue might be that I am using a tiling window manager, that might force a resize on the window resulting in having it start out in the position in the screenshot.

**Comment by fnevgeny** [comment]
I see. Please test the PR #698.

**Comment by ModProg** [comment]
Looks good
