### ISSUE TITLE
Video not playing: Internal data stream error

### ISSUE THREAD

**Issue by MayeulC** [pdfpc/pdfpc#697]
**Expected Behaviour**
Video plays when clicking it.

**Actual Behaviour**
Video is not playing, errors are printed to `stdout`. The videos I tried work nicely with `gst-play-1.0 beamer/figures/blender/0001-0060.mp4`

However, the automatically generated preview (`poster` option) works fine.

**Steps to reproduce**

```latex
\usepackage{multimedia}
%[...]
\movie[width=3cm,height=2cm,poster]{}{beamer/figures/blender/0001-0060.mp4}
```
or:

```latex
\usepackage{pdfpc-movie}
%[...]
\pdfpcmovie[autostart, loop, width=8cm, height=4.5cm]{}{beamer/figures/blender/0001-0060.mp4}
```

<details> <summary>Tested with the two following files (second is actually an mkv/VP9)</summary>

https://github.com/pdfpc/pdfpc/assets/3952726/2cc23d9a-e8a6-4ebf-bbb4-46b3474eeb04

https://github.com/pdfpc/pdfpc/assets/3952726/fd75e85b-4aab-4b7a-97a8-a5582bb65b7a

</details>

pdfpc version: 4.6
Used Distribution (GTK version, Vala version): Arch
Display Server (X11/Wayland): sway/wayland
HiDPI Setting (yes/no): no

<details> <summary>console output (stdout or stderr)</summary>

```
Gstreamer error from element qtdemux2: Internal data stream error.
  (debugging info: ../gstreamer/subprojects/gst-plugins-good/gst/isomp4/qtdemux.c(6967): gst_qtdemux_loop (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin2/GstDecodeBin:decodebin2/GstQTDemux:qtdemux2:
streaming stopped, reason error (-5))
```

```
Gstreamer error from element matroskademux0: Internal data stream error.
  (debugging info: ../gstreamer/subprojects/gst-plugins-good/gst/matroska/matroska-demux.c(6095): gst_matroska_demux_loop (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstMatroskaDemux:matroskademux0:
streaming stopped, reason error (-5))
```

</details>

My PhD presentation is in one week, so I guess no movie for me :upside_down_face: (I don't mind too much, I wasn't convinced it was a good idea). I think I can obtain a similar result with a fade animation.

**Comment by fnevgeny** [comment]
> The videos I tried work nicely with `gst-play-1.0 beamer/figures/blender/0001-0060.mp4`

This is not the test we ask to perform. Have you read the [FAQ](https://github.com/pdfpc/pdfpc/blob/master/FAQ.rst)?

> \usepackage{pdfpc-movie}

This is a third-party package which we don't support.

Does video playback in the [official demo](https://github.com/pdfpc/pdfpc/releases/latest/download/pdfpc-video-example.zip) work?

**Comment by MayeulC** [comment]
Hello,

I did read the FAQ. I can't remember if I had tried the exact command listed there. I did try it now though (`gst-play-1.0 --gst-fatal-warnings --videosink gtksink 0001-0060.mkv`). It works fine, with no warnings or errors.

Video playback works with the official demo, both with the precompiled `pdf` and if I compile it myself. **However, if I replace the file in the example with mine (adjusting the filename), it stops working**. This happens with both `lualatex` and `pdflatex` compilations.

**Comment by fnevgeny** [comment]
Well, I cannot reproduce it. Here, both files playback just fine. What's your video card/driver?

**Comment by fnevgeny** [comment]
Also, have a look at #654.

**Comment by fnevgeny** [comment]
No response, closing.
