### ISSUE TITLE
debian packages

### ISSUE THREAD

**Issue by andybarry** [pdfpc/pdfpc#7]
Once we get everything fixed up we should package pdfpc as a .deb and get it into the repositories.  The last pdfpc package I saw was very old.

If there are other package formats folks like, mention them here.  I have worked with .deb so I can charge forward on that when we're ready.

**Comment by Beuh** [comment]
For deb packages, I was thinking about creating a PPA. At least for ubuntu users, which are a lot nowadays, this could be great.

**Comment by andybarry** [comment]
Sounds great.  Have you set one up before?  I don't have any experience with it, but it's definitely something we should do.

**Comment by AndreasBilke** [comment]
The pdfpc version in the debian repository is not that old (see https://packages.debian.org/wheezy/pdf-presenter-console). It is the latest "official" release of pdfpc (davils version). Just the package name is the old one.

In my opinion it would be better to ask the package maintainer to upload a new version to the repos, if there is one. Then ubuntu would copy it also for their next releases.

**Comment by Beuh** [comment]
Indeed, this old name trick did beat me, since I thought it was the old code behind. Makes sense to contact the maintainer when a new version is there, indeed. 

(though I really like PPAs since they allow direct update from apt-get for ubuntu users like me)

**Comment by rschroll** [comment]
I've put one project up in a PPA.  Once you have a debian source 
package, it's not too bad to do.  Making the debian source package, on 
the other hand, was an absolute pain.  But since it already exists, we 
ought to be able to update it and load it to a PPA.

But first, let's get something worthy of being uploaded. :)

**Comment by barak** [comment]
I've pushed a recent version to Debian.
The name remains ```pdf-presenter-console```, to allow for painless upgrades.
However I've added a ```Provides: pdfpc``` control field, so it shows up with a search:
````
$ apt-cache search pdfpc
pdf-presenter-console - multi-monitor presentation tool (ala Keynote) for PDF files
````
Please feel free to peruse http://bugs.debian.org/pdf-presenter-console for issue.
E.g., it has recently been reported that ```libgstreamer 0.1``` is on its way out, and packages need to switch to ```libgstreamer 1.0```.

**Comment by AndreasBilke** [comment]
So the pdfpc debian package manager appeared here and is informed about everything. I will close this issue.

**Comment by barak** [comment]
Please do let me know when it's time for me to do a point release.
The best way would be to create a tag ```v3.1.2``` and I'll be automatically notified.
But you can also feel free to drop me a note.
(I'd consider solving the gstreamer 0.1 -> 1.0 issue release-worthy, and inhibiting screen-saver as well.)
