### ISSUE TITLE
Suggested documentation hint for azerty keyboards

### ISSUE THREAD

**Issue by marc456** [pdfpc/pdfpc#702]
If you press the usual 1, 2, 3, 4, 5 keys on an azerty keyboard, you get: `& é " ' (`
To get the actual numbers you have to press also the shift key.
So the pdfpc key bindings involving these numbers do not work.

This is easily fixed in the `pdfpcrc` file:

```
bind ampersand          switchMode normal
bind eacute             switchMode pointer
bind quotedbl           switchMode pen
bind apostrophe         switchMode eraser
bind parenleft          switchMode spotlight
```

To help the user, these bindings could be mentioned in the documentation or included, as a comment, in the `pdfpcrc` file.

**Note**: for some reason, the following bindings do not work:
```
bind S+ampersand        switchMode normal
bind S+eacute           switchMode pointer
bind S+quotedbl         switchMode pen
bind S+apostrophe       switchMode eraser
bind S+parenleft        switchMode spotlight
```

But I don't think that they are needed. The user can remember that instead of typing three (shift + double quote), he has to press the key used to output three (i.e., the double quote).

**Comment by fnevgeny** [comment]
I'd rather we handle these keyboards correctly. Please try #730.
