### ISSUE TITLE
Notes are not shown

### ISSUE THREAD

**Issue by Beiri22** [pdfpc/pdfpc#703]
**Expected Behaviour**
Last year notes were shown as white text in the right bottom area of the window.

**Actual Behaviour**
not any more. It's now black. If you drag with the mouse, you see the text moving; if you let go its gone.

**Steps to reproduce**

1. use latex / pdfpc demo document with 3 slides and some note
2. open in pdfpc
3. look for notes.

pdfpc version: 4.6
Used Distribution (GTK version, Vala version): manjaro
Display Server (X11/Wayland): ?
HiDPI Setting (yes/no): ?

**Comment by fnevgeny** [comment]
> not any more

Not any more after what? After you have upgraded the OS? or pdfpc? or both?

> Used Distribution (GTK version, Vala version): manjaro

Works just fine for me from the current live Manjaro CD (Gnome version).

**Comment by Beiri22** [comment]
> > not any more
> 
> Not any more after what? After you have upgraded the OS? or pdfpc? or both?

Last year IT worked. I only use it occasionally, so I cannot say what time/change was the cause


> 
> > Used Distribution (GTK version, Vala version): manjaro
> 
> Works just fine for me from the current live Manjaro CD (Gnome version).
I'm on testing branch. Would you try this one?

**Comment by fnevgeny** [comment]
> I'm on testing branch. Would you try this one?

I'm not familiar with Manjaro. Where is the testing image downloads?

Actually, I'd suggest you to create a new user account and try running pdfpc under it.

**Comment by Beiri22** [comment]
You May have to use a default image and switch branch. I'm not sure, if this works directly from the image or if you need an installation.

See https://wiki.manjaro.org/index.php/Switching_Branches

**Comment by Beiri22** [comment]
Notes are not shown in the right bottom area:
![Bildschirmfoto vom 2023-10-25 17-04-38](https://github.com/pdfpc/pdfpc/assets/8210233/38ffb50d-96a7-41a3-ae90-6ee9a342e89c)

But, when you click and drag in this area, you select and move the note. So it does exist, but is not visible.
![Bildschirmfoto vom 2023-10-25 17-04-48](https://github.com/pdfpc/pdfpc/assets/8210233/c7b0f9d6-274c-4c88-bc2e-67962e71da6c)

any idea?

**Comment by fnevgeny** [comment]
> Actually, I'd suggest you to create a new user account and try running pdfpc under it.

@Beiri22 Have you tried it?

**Comment by Beiri22** [comment]
I just wanted to try it, but noticed that it works again on manjaro testing. I don't know if there was a direct update or if any dependency update fixed it.

**Comment by yangwenbo99** [comment]
Arch Linux user here.  I can confirm this is due to dependencies (probably webkit2gtk).  

I encountered the same issue.  Using a fresh user does not solve it.  However, the problem fixes itself after a system update.
