### ISSUE TITLE
animategraphics does not work

### ISSUE THREAD

**Issue by ssandfeld** [pdfpc/pdfpc#708]
**Expected Behaviour**
The line inside a frame
`\animategraphics[loop,autoplay, width=0.63\textwidth]{6}{frame-}{1}{10}`
is supposed to to start an "animation" where the 10 frames are shown with fps=6. 

**Actual Behaviour**
Only the first image frame-1.jpg is shown, and the animation does not automatically advance.

**Steps to reproduce**
compile the following code with pdflatex and open it in pdfpc:

```latex
\documentclass[11pt]{beamer}
\usepackage{animate}

\begin{document}
	\begin{frame}
		\animategraphics[loop,autoplay, width=0.63\textwidth]{6}{frame-}{1}{5}
	\end{frame}
\end{document}
``` 

The same works in okular.

pdfpc version: 4.6
Used Distribution (GTK version, Vala version): Fedora38
Display Server (X11/Wayland): wayland
HiDPI Setting (yes/no):

**Comment by fnevgeny** [comment]
`\animategraphics` uses JavaScript. Poppler has no support for JavaScript. So it won't work in pdfpc (for the same reason, it won't work in evince).

If all you need is an animation of a series of bitmap images, I suggest you create a video from the frames, e.g., using ffmpeg. Then use `\movie` as explained in the [demo](https://github.com/pdfpc/pdfpc/releases/latest/download/pdfpc-video-example.zip).
