### ISSUE TITLE
Allow both windows in fullscreen on single screen for screen sharing

### ISSUE THREAD

**Issue by DWIAltonaAnalytics** [pdfpc/pdfpc#709]
Sometimes, one has only one screen and shares windows with a second screen. Be this online via any of the many screen sharing apps, or even with something like clickshare to share a window with a second screen in the room (which is not recognized as a second screen).

right now, pdfpc would detect only one screen and not show the presentation unless `-w both` is provided.

This has the disadvantage that I could share the presentation window, but I would have the window-border on the shared screen and in the online conference app.

Is there a way to force both windows fullscreen, even on a single (laptop) screen? With that one could tell the screen sharing application to share the presentation window, and look at the presenter window at the same time without the window borders?

**Comment by DWIAltonaAnalytics** [comment]
Clickshare - it did share the window borders. The added complexity might come from this being WSL on windows.

But I am pretty sure if I share a window in teams (I never share the screen, to many possibilities to show more than wanted) it also shows the complete window with borders.

**Comment by fnevgeny** [comment]
Very strange. If you share a native Windows app, does it also come with the borders? If not, the problem might indeed be WSL. BTW, pdfpc now compiles natively under Windows, so I suggest you just try it.

**Comment by DWIAltonaAnalytics** [comment]
nope, if I don't full screen (F11) my browser window and share it with a colleague he can see the window borders and what ever the controls at the top right are called, too.

**Comment by DWIAltonaAnalytics** [comment]
and this was with MS teams.

**Comment by fnevgeny** [comment]
Probably a WSL bug/feature.
