### ISSUE TITLE
Indicators placed off the screen

### ISSUE THREAD

**Issue by dpthurst** [pdfpc/pdfpc#71]
Something apparently went funny with pdfpc's display size recognition,
and much of the crucial information is not visible. The image below is
a full-screen screenshot immediately after starting `pdfpc pdfpc-demo.pdf`.
Observe that

(a) the timer is partially cut off at the bottom of the screen
(b) there is an inordinate amount of blank space on the left
(c) the page counter is not visible
(d) the preview of the next page is partially cut off.

All of this looks like it thinks my laptop screen is larger than it
is. There is no second monitor, so it is running in single-screen
mode; adding the `-S` option has no effect.

Here is the output of `xrandr`:

    dpt@tulip:/tmp$ xrandr
    Screen 0: minimum 8 x 8, current 1366 x 768, maximum 32767 x 32767
    LVDS1 connected 1366x768+0+0 (normal left inverted right x axis y axis) 256mm x 144mm
       1366x768      59.97*+  39.98  
       1360x768      59.80    59.96  
       1024x768      60.00  
       800x600       60.32    56.25  
       640x480       59.94  
    DP1 disconnected (normal left inverted right x axis y axis)
    DP2 disconnected (normal left inverted right x axis y axis)
    DP3 disconnected (normal left inverted right x axis y axis)
    HDMI1 disconnected (normal left inverted right x axis y axis)
    HDMI2 disconnected (normal left inverted right x axis y axis)
    HDMI3 disconnected (normal left inverted right x axis y axis)
    VGA1 disconnected (normal left inverted right x axis y axis)
    VIRTUAL1 disconnected (normal left inverted right x axis y axis)

The physical display resolution is, in fact, 1366x768.

When I try the same thing on a two-screen setup, the presentation
slides work normally, but I get the same view on the internal laptop
display.

I am running the xfwm4 window manager, with a vertical taskbar on the
left side of the screen.

**Comment by AndreasBilke** [comment]
I can't see the your screenshot. Is this issue maybe related to #68 ?

**Comment by dpthurst** [comment]
It might be, although it's not obvious to me either way. I saw the
issues when running on my laptop with no external screen attached at
all. I've attached the screenshot.

Is there some other version you'd like me to try?

--Dylan

**Comment by AndreasBilke** [comment]
You can try pull request #37 . I played a little bit around with font
sizes, since they caused cut-offs on my setup.

**Comment by AndreasBilke** [comment]
@dpthurst can you fetch the latest master and changing the font-size in the css file to something smaller? Does this solve the issue?

**Comment by dpthurst** [comment]
I tried the latest master, and it seems to work well. I didn't try
changing the font size, it didn't seem necessary.

--Dylan

**Comment by PrivateMandella** [comment]
I'm having the same issue using an external monitor and is happens for versions 4.0.1, 4.0.2, and 4.0.8. I'm using Mac OSX version 10.9.5. Any fix?
