### ISSUE TITLE
A way to make pdfpc display current date, or fields.

### ISSUE THREAD

**Issue by Atreyagaurav** [pdfpc/pdfpc#710]
**Only submit a feature request if you read the SUPPORT.rst file**

The feature wish description:

Hi, I haven't used Vala before, so I do not know if it is possible with the way pdfpc rendering is structured. But I think this would be a nice feature. And I want to discuss it before I try to attempt it (or maybe someone else can also try, or have already tried).

And if it can be done from PDF side (maybe through forms or other tags) and pdfpc just support the insertion of current date, then that'd also work.

Otherwise, would it be possible to create something that'll always display current date/time? For example, we can have a command on the LaTeX package to insert it, and for PDF compilation, it'll compile with certain extra information as well as the placeholder date+time while compiling. And in normal cases it would fall back to it, but pdfpc can detect it and display current datetime.

I see it being useful while presenting PDF compiled from previous days without having to insert the date manually, as I start with `\today` in the date field.

And as cherry on top. I was thinking if we could even make "fields" and have the `key=value` for the fields in the `.pdfpc` file, so we can easily change those things and reuse the presentation for different purposes.

**Comment by fnevgeny** [comment]
(Re)compiling PDFs is pretty fast nowadays. So you can just add some scripting to your *TeX workflow.

**Comment by Atreyagaurav** [comment]
Recompiling it just to update the date to today seems like excessive, so a Date Field that automatically displays today's date would really be a nice feature. But understandable if you don't want to put into effort to do that for a small thing.

**Comment by fnevgeny** [comment]
> Recompiling it just to update the date to today seems like excessive

If you believe this feature can be implemented in less time than it takes to recompile a typical presentation, I agree to consider such a PR. BTW, if all you need is to update a particular string, there are various tools out there. Or just leave an empty space and overlay it using, e.g., xournal.

I really don't think pdfpc should implement an ad-hoc variant of XFA. If you think it's really important, the proper place to ask (and provide help with it) is the poppler project. Once it's there, pdfpc will support it automatically.
