### ISSUE TITLE
[Feature Request] I wonder if we can make something like the Morph transition

### ISSUE THREAD

**Issue by Atreyagaurav** [pdfpc/pdfpc#714]
**Only submit a feature request if you read the SUPPORT.rst file**

The feature wish description:

So, the morph transition that PowerPoint does, does an excellent job in changing between the slides that have a similar element. And I've seen that the manin library from 3blue1brown also has the feature to do that for simple shapes it has. I wonder if it's doable here in pdfpc. 

Using beamer, I end up making a lot of slides that have a similar element with some additions or replacement. So a transition like morph would be elegant looking.

I know it might be too much work, so I'm not asking for it, just leaving it here just in case someone that can implement it has this to see.

**Comment by fnevgeny** [comment]
It's impossible to support something in pdfpc that is not part of the PDF standard; more specifically, anything not understood by the poppler library.

If you know how to create the animation you like using manim, just embed that video in your presentation; pdfpc will show it.

**Comment by Atreyagaurav** [comment]
Hello. Thanks for the response. 

Sorry, I didn't know the slide transitions were part of the PDF standard. I thought the application could implement slide transitions, as they're just changing the way the next page is shown. As I use the transition option from the CLI.

I couldn't find the standard docs by a surface level search. So maybe people have to add it to the standard to have this. My understanding was popper is for rendering pages only, and the transition is implemented by the pdfpc (maybe the transition type is stored in the PDF, but it's just a string), so we can have other types as well.

**Comment by fnevgeny** [comment]
> My understanding was popper is for rendering pages only, and the transition is implemented by the pdfpc (maybe the transition type is stored in the PDF, but it's just a string)

Yes, it's a kind of string. But poppler will only recognize a predefined one. Further, beamer (or any other PDF creator) will also set only one from the predefined list. So a new transition type will require (i) adding it to the standard, (ii) updating poppler (and its glib and vala bindings), (iii) updating latex-beamer, and only then the turn comes to pdfpc to actually implement the effect.

I'm not sure all this is relevant, though. I'm not familiar with the manim library, but it looks like it works on math/geometric objects. How can it be translated to a page transition?

**Comment by Atreyagaurav** [comment]
Yes, it works with the objects that are in that library. I was just giving an open source example of the algorithms like that. 

For example, look at this one: https://revealjs.com/auto-animate/#how-elements-are-matched

I found it while searching for other ways to make that transition. 

So that example, and how morph basically works (in my head), is: 
1. Find similar objects in the two pages,
2. For the ones that match (exact match), do nothing,
3. For the ones that match and are in different location, scale, rotation, do that transition,
4. For new ones, make them appear, and for ones that are no longer there, make them disappear.

First step is important part of the algorithm, the link also shows the way to give "id" so that it knows which ones are the same objects. And [this link from microsoft](https://support.microsoft.com/en-us/office/use-the-morph-transition-in-powerpoint-8dd1c7b2-b935-44f5-a74c-741d8d9244ea) suggests in the powerpoint do "duplicate slide" for this sort of transition, which probably allows them to internally know which objects are similar.

So the combination of them, end up looking nice, and removes a lot of manual work from making the transitions explicit. It is specially nice for when you want to "zoom in" on a picture to focus on different aspects, or have a pointer/circle in the image in different location, the morph transition can smoothly move it between the frame. 

We can also make a flowchart, that appears one step at a time, and each time it'll shrink slightly and move to accommodate for the new step. Instead of starting with few boxes and a lot of white space for future boxes,

It seems like a really wonderful feature to me, that's why I wanted to brainstorm on it, we can make it in pdfpc, that way it'll stand out among other open source PDF presenters as well. But if the only way to add it comes after the PDF standard, then that might not go the way I planned. 

I'm not really knowledgeable about the PDF standards, I wonder if it stores identical components just onces, and uses that ID to render it in different pages. Like the frames from beamer are the same objects, a lot of the times, and storing that separately in each page seems like a waste. And if it stores the clone objects once and referes them with ID, it might make recognizing them from PDF viewer side would be at least easier. And with the page labels that pdfpc already uses, we could only run the algorithm to check for same objects in the frames of the same page (label wise).

**Comment by fnevgeny** [comment]
PS. To comment on your last paragraph: PDF is a rich language, but how it is used depends on the software that produces it: it can be anything from dumb pixmaps to sophisticated constructions reusing objects stored in dictionaries, etc. It's up to the authoring software. So if you want the morphing feature, ask the developers of your favorite authoring software to implement it. Then pdfpc will do its best to show it on the screen.

**Comment by Atreyagaurav** [comment]
Yeah, as you said, the communication between the authoring program and viewer seems to be important for this. 

But, I originally wasn't thinking of adding IDs like in the reveal.js. The way I was thinking, "the reverse engineering" was doable with the information from the PDF. As we know which frames are related to each other from page labels, and then by hashing the components, we could probably find the differences between them. But implementing might actually be hard.

Another way I'm thinking was to use the synctex (if present) to see if components from different frames lead to the same TeX code, and know those are the same components.

But as you said this might not always work, and having the ids of the objects to refer from the PDF creator will make things a lot easier.

Thank you for the discussion. I'll close the issue now. Maybe if I'm motivated enough, I can try to write a PDF to video converted to make videos from the frame and have different implementations of the transitions there.
