### ISSUE TITLE
Unknown action showQRcode every time is run

### ISSUE THREAD

**Issue by lima-limon-inc** [pdfpc/pdfpc#719]
**Expected Behaviour**
Every time I open `pdfpc`, I get an message on stdout stating: `Unknown action showQRcode`. 
**Actual Behaviour**
Is this an intended behavior? I could not find any references to QR code.

**Steps to reproduce**
1. `pdfpc` <file.pdf> (Even `pdfpc` by itself)

pdfpc version:
pdfpc v4.6
Used Distribution (GTK version, Vala version): Gentoo (gui-libs/gtk-4.12.5-r1, dev-lang/vala-0.56.16)
Display Server (X11/Wayland): X11
HiDPI Setting (yes/no): no

Thanks in advance

**Comment by AndreasBilke** [comment]
It seems your build is done with `REST=off`, right?

The key binding for `showQRCode` is always included (see https://github.com/pdfpc/pdfpc/blob/1de2963b12d16d24c6e682db2477b5bdb24b0c64/rc/pdfpcrc#L121) but the corresponding action just added if `REST=on` was set (see https://github.com/pdfpc/pdfpc/blob/1de2963b12d16d24c6e682db2477b5bdb24b0c64/src/classes/presentation_controller.vala#L1315-L1318).

@fnevgeny What do you think is the best way in dealing it? Make `pdfpcrc` preprocessed by cmake and exclude this binding?

**Comment by fnevgeny** [comment]
I think it's better to have an empty show_qrcode() if REST is off.

**Comment by lima-limon-inc** [comment]
Hello @fnevgeny @AndreasBilke ; I tried giving fixing the issue taking into account @fnevgeny approach.

It compiles and runs correctly in my machine. I added a simple print message to convey _some_ sort of information to the user. 

Would love to get some feedback. 

Cheers! :wave:
