### ISSUE TITLE
href not working

### ISSUE THREAD

**Issue by smihael** [pdfpc/pdfpc#72]
I create my presentations using LaTex's Beamer. It supports adding links to other objects (such as links to websites, to movies etc). If I open the PDF in Okular or other PDF viewer, the links open on-click just as expected, but not in pdfpc (they instead next slide will be shown). Please, add on-click handler for links.

Edit: duplicate of
https://github.com/davvil/pdfpc/issues/66 (but no error message)

**Comment by AndreasBilke** [comment]
could you test the AndreasBilke/pdfpc href branch?

**Comment by AndreasBilke** [comment]
#80 was merged into master.

**Comment by diegit** [comment]
Sadly this is not working for me. My code looks the following:
`
\href{vid/realCells/scratchAssay.mov}{
\includegraphics[width=0.9\linewidth]{vid/realCells/scratchAssay.png}
}
`
Error message: "Vorgang wird nicht unterstützt" (operation not supported). With Okular everything works as expected. Embedded videos (with run:) also work.

OS: Linux Mint 17.3
/usr/local/bin/pdfpc -v
pdfpc v4.0.2

**Comment by AndreasBilke** [comment]
Could you create a new issue and providing a complete example where you
encounter this problem?
