### ISSUE TITLE
Invisible (black) caret in the note editor

### ISSUE THREAD

**Issue by melnikovsky** [pdfpc/pdfpc#720]
Editing the notes works and one can use the arrows as well as the mouse to navigate. But I can not see the caret (text input cursor). It seems to be black, but how do I configure it? Thanks in advance

pdfpc version: pdfpc v4.6 Copyright (C) 2010-2022
Used Distribution: Arch Linux, extra/gtk3 1:3.24.42-1, extra/gtk4 1:4.14.4-1
Display Server: xorg

![2024-06-30_18-17](https://github.com/pdfpc/pdfpc/assets/43612263/38199fdf-b763-4441-abdd-fead876cc949)

**Comment by Ordoviz** [comment]
A workaround is adding this to `~/.config/pdfpc/pdfpc.css`:
 ```css
 textview * {
	caret-color: white;
}
```

**Comment by melnikovsky** [comment]
> A workaround is adding this to `~/.config/pdfpc/pdfpc.css`:
This really works, thanks!!!
Where was the wrong color inherited from? Some misconfiguration on my side?
Should I close the issue?
