### ISSUE TITLE
Incoherent note order when using pdfpc file notes

### ISSUE THREAD

**Issue by tingerrr** [pdfpc/pdfpc#727]
To preface this:
I took a look at the man page, the schema and parts of the repo which could perhaps shed some light on this, but I couldn't find a definitive explanation of the pdfpc file format, perhaps I simply didn't find it and have the wrong expectations on where the notes should be displayed (which could at least explain the off-by-one case in the first example).

I attached a PDF with and without overlays and two pdfpc files below, the `Slide <idx>` refer to absolute indices as in the `page.idx` property of the pdfpc file.

**Expected and Actual Behaviour**
For the non-overlay case, I would expect pdfpc to display the following notes:
- Slide 0: no note
- Slide 1: `Note A`
- Slide 2: `Note B`

What I actually see is:
- Slide 0: `Note A`
- Slide 1: `Note B`
- Slide 2: no note

If it was only that I could adjust my notes to be on the next page, but it gets worse with overlays.
The order becomes completely incoherent once overlays are added.

In the overlay case I expect this:
- Slide 0: no note
- Slide 1: no note
- Slide 2: `Note A`
- Slide 3: `Note A`
- Slide 4: `Note B`
- Slide 5: `Note B`

Instead, I get this:
- Slide 0: no note
- Slide 1: `Note A`
- Slide 2: `Note B`
- Slide 3: `Note A`
- Slide 4: no note
- Slide 5: `Note B`

Note the interspersed `Note B` on slide 2. Other cases include well ordered, but missing notes in ovelays and the like.

**Steps to reproduce**

1. provide a pdfpc file instead of PDF annotations

PDF Annotation seem to work fine, but I haven't tested them thoroughly as I'm still working on the slides and the PDF is regenerated each time, it's not a pleasant workflow.

pdfpc version: v4.6
Used Distribution (GTK version, Vala version): My package manager tells me the pdfpc package depends on gtk3, so I assume this is the GTK distribution, the `--version` flag should probably display this.
Display Server (X11/Wayland): wayland
HiDPI Setting (yes/no): no idea, likely not relevant

<details>
<summary>pdfpc files</summary>

Without overlay (example 1):
```json
{
  "pdfpcFormat": 2,
  "disableMarkdown": false,
  "pages": [
    {
      "idx": 0,
      "label": "0",
      "overlay": 0,
      "forcedOverlay": false,
      "hidden": false
    },
    {
      "idx": 1,
      "label": "1",
      "overlay": 0,
      "forcedOverlay": false,
      "hidden": false,
      "note": "Note A"
    },
    {
      "idx": 2,
      "label": "2",
      "overlay": 0,
      "forcedOverlay": false,
      "hidden": false,
      "note": "Note B"
    }
  ]
}
```

With overlay (Example 2):

```json
{
  "pdfpcFormat": 2,
  "disableMarkdown": false,
  "pages": [
    {
      "idx": 0,
      "label": "0",
      "overlay": 0,
      "forcedOverlay": false,
      "hidden": false
    },
    {
      "idx": 1,
      "label": "1",
      "overlay": 0,
      "forcedOverlay": false,
      "hidden": false
    },
    {
      "idx": 2,
      "label": "2",
      "overlay": 0,
      "forcedOverlay": false,
      "hidden": false,
      "note": "Note A"
    },
    {
      "idx": 3,
      "label": "2",
      "overlay": 1,
      "forcedOverlay": true,
      "hidden": false,
      "note": "Note A"
    },
    {
      "idx": 4,
      "label": "3",
      "overlay": 0,
      "forcedOverlay": false,
      "hidden": false,
      "note": "Note B"
    },
    {
      "idx": 5,
      "label": "3",
      "overlay": 1,
      "forcedOverlay": true,
      "hidden": false,
      "note": "Note B"
    }
  ]
}
```

</details>

Without overlay (Example 1):
[simple.pdf](https://github.com/user-attachments/files/17391783/simple.pdf)

With overlay (Example 2):
[overlay.pdf](https://github.com/user-attachments/files/17391782/overlay.pdf)

**Comment by fnevgeny** [comment]
The "label" fields refer to the page labels of the PDF file. You cannot just invent them. Normally, they start at 1 (which is also the case with your two files). Use, e.g., [pdfpagelabels](HeimMatthias/pdfpagelabels) to list the labels.

**Comment by tingerrr** [comment]
Ok, that sheds some light on the issue, the PDF does not contain the labels correct slide labels. It seems that it doesn't contain the `/PageLabels` entry, which is why most readers do the sensible thing of assuming arabic labels starting at 1.

Adjusting the pdfpc file to use those labels works. I'll report this with the tool I used to generate the PDF, thanks.
