### ISSUE TITLE
CLI Flag Values suggestion

### ISSUE THREAD

**Issue by JeffreyAnimal** [pdfpc/pdfpc#729]
**Expected Behaviour**

When entering a optional flag parameter e.g.: `pdfpc -w example.pdf `, without the value or a wrong one, the CLI should suggest the options for the given parameter. E.g:

```bash
$ pdfpc -w example.pdf
Unknown windowed mode "example.pdf"
Try using one of the modes: both / <option2> / <option3> / ...
```
**Actual Behaviour**

If a optional Flag parameter is not recognized, the CLI shows the standard `Application Options` or a `Unknown parameter` Message, but without giving a hint what the possible options are.

```bash
$ pdfpc -w example.pdf
Unknown windowed mode "example.pdf"
```
**Steps to reproduce**

Enter
```bash
pdfpc -w example.pdf
```

or 
```bash
pdfpc  example.pdf --presenter-screen
```

pdfpc version: v4.6
Used Distribution (GTK version, Vala version): Debian12
Display Server (X11/Wayland): Wayland
HiDPI Setting (yes/no):no

**Comment by fnevgeny** [comment]
IMO, the ability to read a manpage should still be assumed for any user considered advanced enough to risk running anything from the command line...

**Comment by AndreasBilke** [comment]
Thanks for your input, but I agree with fnevgeny such that our man pages contains all needed informations and a user can read things up there.
