### ISSUE TITLE
make homebrew recipe for pdfpc

### ISSUE THREAD

**Issue by maxheld83** [pdfpc/pdfpc#75]
the dependency hell of pdfpc is a little hard on newbies like me, but I LOVE this program (I think).

Any chance we can get homebrew recipe for this?

Someone seems to have gotten *very* close a couple of years back ... -> https://github.com/Homebrew/homebrew/issues/28963

**Comment by AndreasBilke** [comment]
You can try to write your own homebrew recipe. Without some Mac OS X it is not possible to write some and I also think it should be the job of the package maintainer to provide this.

**Comment by AndreasBilke** [comment]
Related to #74 and I think it is out of scope for pdfpc.
