### ISSUE TITLE
No gstreamer-1.0-audio and video packages in Ubuntu 14.04

### ISSUE THREAD

**Issue by zenny** [pdfpc/pdfpc#78]
Hi,

Trying to compile pdfpc in Ubuntu 14.04 and the cmake asked for two packages which is not available in ubuntu repos. it is like dependency hell! What on earth are the modules, gstreamer-{audio,video}-1.0?

-- checking for module 'gstreamer-audio-1.0'
--   package 'gstreamer-audio-1.0' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  src/CMakeLists.txt:10 (pkg_check_modules)

-- checking for module 'gstreamer-video-1.0'
--   package 'gstreamer-video-1.0' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  src/CMakeLists.txt:11 (pkg_check_modules)

-- checking for module 'gdk-x11-3.0'
--   found gdk-x11-3.0, version 3.10.8
-- Configuring incomplete, errors occurred!

/z

**Comment by zenny** [comment]
I guess all gstreamer packages were installed as of follow, but could not figure out the specified packages called, gstreamer-{audio,video}-1.0 Any help?

# $ dpkg -l | grep ii | grep gstreamer
ii  bluez-gstreamer                             4.101-0ubuntu13.1                                           amd64        Bluetooth GStreamer support
ii  gir1.2-gstreamer-0.10                       0.10.36-1.2ubuntu3                                          amd64        Description: GObject introspection data for the GStreamer library
ii  gir1.2-gstreamer-1.0                        1.2.4-0ubuntu1                                              amd64        Description: GObject introspection data for the GStreamer library
ii  gstreamer-tools                             0.10.36-1.2ubuntu3                                          amd64        Tools for use with GStreamer
ii  gstreamer0.10-ffmpeg:amd64                  0.10.13-5ubuntu1~trusty2                                    amd64        FFmpeg plugin for GStreamer
ii  gstreamer0.10-fluendo-mp3:amd64             0.10.23.debian-3                                            amd64        Fluendo mp3 decoder GStreamer 0.10 plugin
ii  gstreamer0.10-gnonlin                       0.10.17-2ubuntu1                                            amd64        non-linear editing module for GStreamer
ii  gstreamer0.10-nice:amd64                    0.1.4-1                                                     amd64        ICE library (GStreamer 0.10 plugin)
ii  gstreamer0.10-plugins-bad:amd64             0.10.23-7.2ubuntu1.1                                        amd64        GStreamer plugins from the "bad" set
ii  gstreamer0.10-plugins-bad-multiverse        0.10.21-1ubuntu3                                            amd64        GStreamer plugins from the "bad" set (Multiverse Variant)
ii  gstreamer0.10-plugins-base:amd64            0.10.36-1.1ubuntu2                                          amd64        GStreamer plugins from the "base" set
ii  gstreamer0.10-plugins-good:amd64            0.10.31-3+nmu1ubuntu5                                       amd64        GStreamer plugins from the "good" set
ii  gstreamer0.10-plugins-ugly:amd64            0.10.19-2ubuntu5                                            amd64        GStreamer plugins from the "ugly" set
ii  gstreamer0.10-pulseaudio:amd64              0.10.31-3+nmu1ubuntu5                                       amd64        GStreamer plugin for PulseAudio
ii  gstreamer0.10-tools                         0.10.36-1.2ubuntu3                                          amd64        Tools for use with GStreamer
ii  gstreamer1.0-alsa:amd64                     1.2.4-1~ubuntu1                                             amd64        GStreamer plugin for ALSA
ii  gstreamer1.0-fluendo-mp3:amd64              0.10.23.debian-3                                            amd64        Fluendo mp3 decoder GStreamer 1.0 plugin
ii  gstreamer1.0-gnonlin                        1.2.0-1                                                     amd64        non-linear editing module for GStreamer
ii  gstreamer1.0-libav:amd64                    1.2.4-1~ubuntu1                                             amd64        libav plugin for GStreamer
ii  gstreamer1.0-plugins-bad:amd64              1.2.4-1~ubuntu1                                             amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.0-plugins-bad-faad:amd64         1.2.4-1~ubuntu1                                             amd64        GStreamer faad plugin from the "bad" set
ii  gstreamer1.0-plugins-bad-videoparsers:amd64 1.2.4-1~ubuntu1                                             amd64        GStreamer videoparsers plugin from the "bad" set
ii  gstreamer1.0-plugins-base:amd64             1.2.4-1~ubuntu1                                             amd64        GStreamer plugins from the "base" set
ii  gstreamer1.0-plugins-good:amd64             1.2.4-1~ubuntu1                                             amd64        GStreamer plugins from the "good" set
ii  gstreamer1.0-plugins-ugly:amd64             1.2.3-2build1                                               amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.0-pulseaudio:amd64               1.2.4-1~ubuntu1                                             amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.0-tools                          1.2.4-0ubuntu1                                              amd64        Tools for use with GStreamer
ii  gstreamer1.0-x:amd64                        1.2.4-1~ubuntu1                                             amd64        GStreamer plugins for X11 and Pango
ii  libgstreamer-plugins-bad0.10-0:amd64        0.10.23-7.2ubuntu1.1                                        amd64        GStreamer shared libraries from the "bad" set
ii  libgstreamer-plugins-bad1.0-0:amd64         1.2.4-1~ubuntu1                                             amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base0.10-0:amd64       0.10.36-1.1ubuntu2                                          amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base0.10-0:i386        0.10.36-1.1ubuntu2                                          i386         GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base0.10-dev           0.10.36-1.1ubuntu2                                          amd64        GStreamer development files for libraries from the "base" set
ii  libgstreamer-plugins-base1.0-0:amd64        1.2.4-1~ubuntu1                                             amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.0-0:i386         1.2.4-1~ubuntu1                                             i386         GStreamer libraries from the "base" set
ii  libgstreamer-plugins-good1.0-0:amd64        1.2.4-1~ubuntu1                                             amd64        GStreamer development files for libraries from the "good" set
ii  libgstreamer0.10-0:amd64                    0.10.36-1.2ubuntu3                                          amd64        Core GStreamer libraries and elements
ii  libgstreamer0.10-0:i386                     0.10.36-1.2ubuntu3                                          i386         Core GStreamer libraries and elements
ii  libgstreamer0.10-dev                        0.10.36-1.2ubuntu3                                          amd64        GStreamer core development files
ii  libgstreamer1.0-0:amd64                     1.2.4-0ubuntu1                                              amd64        Core GStreamer libraries and elements
ii  libgstreamer1.0-0:i386                      1.2.4-0ubuntu1                                              i386         Core GStreamer libraries and elements
ii  libgstreamer1.0-dev                         1.2.4-0ubuntu1                                              amd64        GStreamer core development files
ii  libreoffice-avmedia-backend-gstreamer       1:4.2.8-0ubuntu2                                            amd64        GStreamer backend for LibreOffice
ii  phonon-backend-gstreamer:amd64              4:4.7.80-0ubuntu2~ubuntu14.04                               amd64        Phonon GStreamer 1.0.x backend
ii  phonon-backend-gstreamer-common:amd64       4:4.7.80-0ubuntu2~ubuntu14.04                               amd64        Phonon GStreamer 1.0.x backend icons
ii  phonon-backend-gstreamer1.0                 4:4.7.80-0ubuntu2~ubuntu14.04                               all          transitional package

**Comment by AndreasBilke** [comment]
Could you try installing `libgstreamer-plugins-base1.0-dev` ? For all
dependencies, you need always the corresponding -dev package as well.

**Comment by AndreasBilke** [comment]
It is not a pdfpc problem.
