### ISSUE TITLE
Presenter issues with tiling window manager (awesome)

### ISSUE THREAD

**Issue by samueltardieu** [pdfpc/pdfpc#79]
See https://github.com/davvil/pdfpc/issues/98

**Comment by samueltardieu** [comment]
(confirmed with latest git version b7b9751c92189de9f9c19bbb3ae7c4c90287d4f5)

**Comment by einhander** [comment]
I've created rule for pdfpc. It makes presentation window fullscreen and move to external monitor.

**Comment by samueltardieu** [comment]
I noticed that I can get pdfpc to work if I move my mouse to the external screen just before the pdfpc "public" window appears. If I can get the mouse there in time, then the presentation will work flawlessly, otherwise it won't advance.

**Comment by samueltardieu** [comment]
@einhander What do you mean? Where did you create such a rule? In pdfpc or in awesome? Is it included by default? If yes, starting from which version?

**Comment by samueltardieu** [comment]
(cc @Knaldgas)

**Comment by einhander** [comment]
The rule for awesome wm.

**Comment by Knaldgas** [comment]
@einhander, can you share that rule please?

**Comment by einhander** [comment]
````
   { rule = { class = "Pdfpc-git", role = "presentation" },
   properties = {opacity = 1 }, 
   callback = function(c) 
	--awful.client.movetoscreen
	awful.client.movetotag(tags[1][9],
	c)
	awful.client.movetoscreen(c) 
	end},
   
--presenter console 
   { rule = { class = "Pdfpc-git", role = "presenter" },
   properties = { tag = tags[1][9], switchtotag = true, opacity = 1} },
````

Tag 9 is fullscreen for both monitors.

**Comment by AndreasBilke** [comment]
Could someone extend the README troubleshooting section and create a pull request? Also if you have fun fixing this in the source code you are also welcome!

It seems that this is (so far) an awesome issue. I use xmonad tilling window manager and it does behave correctly for me.
