### ISSUE TITLE
[Organizational] Releasing v4.0.1?

### ISSUE THREAD

**Issue by AndreasBilke** [pdfpc/pdfpc#85]
Since v4.0.0 we have the following changes:
- fixing movie aspect ratio problems (#44) 
- key bindings for note text size scaling (#32)
- open hyperlinks in browser (#72)
- clock instead of countdowns in presenter view (#62)
- start/stop, noaudio attributes for movies (#42)
- command line options to change the size of current/next view in presenter view (#84)

Is this enough to have a new minor release for pdfpc? Should we tackle #71, #68, #64 first before releasing 4.0.1 or can we do this in 4.0.2? These three (probably related issues) were already present in 4.0.0 so we don't release something with new known bugs.

**Comment by rschroll** [comment]
Andreas, thanks for all the work you've been doing on the project.  I'm 
sorry I haven't had time to sit down and help out.  My theory on 
releases is, the more the merrier.  If the current master is better 
than 4.0.0, let's get it out as 4.0.1.  And if we get those other bugs 
fixed soon, we can release 4.0.2.

I'll play around with the current master a bit just to sanity check 
everything, but I don't anticipate any problems.

**Comment by AndreasBilke** [comment]
I would wait until #94 is fixed, since this was introduced after 4.0.0 (and it is some kind of show stopper, since it is really nasty to find the problem for an end user).

**Comment by AndreasBilke** [comment]
I created for pdfpc and the pdfpc web site a v4.0.1 branch. If we think everything is fine we can merge both branches and make the v4.0.1 active.

**Comment by rschroll** [comment]
If #96 solves #94, then I'll be go for the release.  If not, let's discuss on #94 what to do.

We can look at #47 to remember all the things that need to be done.  You've already taken care of updating the version number and the website. (Thanks!)  Does any documentation need to be updated?  We should also check if any copyright statements should be updated.  I'll try to find the script I used to check them before and push a commit to the 4.0.1 branch.

**Comment by AndreasBilke** [comment]
We could create a new man page to explain the possibility to modify font sizes in the css file.

**Comment by rschroll** [comment]
I just pushed a commit to the release branch with updated copyright statements.

For the record, here's the script I used to generate them: https://gist.github.com/rschroll/33c6dc52d38d42f1117b

**Comment by AndreasBilke** [comment]
I pushed v4.0.1 for pdfpc and the website.

**Comment by mrueg** [comment]
Thanks for the release, this might be a little bit late, but is this PR still relevant? https://github.com/jakobwesthoff/Vala_CMake/pull/9

**Comment by AndreasBilke** [comment]
Thank you for pointing to some updates in the vala cmake module. But I
think your PR does not affect pdfpc.
