### ISSUE TITLE
Clock and slide progress not rendered properly on high-dpi display

### ISSUE THREAD

**Issue by oskar456** [pdfpc/pdfpc#89]
I'm having an issue with time and slide progress display – the font is too big for its area.
![pdfpc-highdpi-problem](https://cloud.githubusercontent.com/assets/816717/10863174/bf74ecfe-7fc4-11e5-813b-3070227ae59d.png)

The reason is probably that my screen has a density of 158 ppi, therefore pixel size of rendered fonts is bigger than same font rendered on common 96 ppi screen. Is there any way I can work around this?

**Comment by AndreasBilke** [comment]
Could you test pull request #95 and play around with font sizes?

**Comment by oskar456** [comment]
Thanks for the patch! All texts are now fully visible with one exception – slide counter last digit on slide number bigger than 9:
![pdfpc-font-sizes-slidecounter](https://cloud.githubusercontent.com/assets/816717/10963153/492becae-839e-11e5-8707-aa44e4e91d8d.png)

**Comment by AndreasBilke** [comment]
Okay, could you try to modify the font size according to your needs (In the
css file)? If this works for you, you can copy the global pdfpc.css to

$XDG_CONFIG_HOME/pdfpc.css

and make local changes.

**Comment by oskar456** [comment]
Changing `font-size` in the `.informationWidget` to 3em fixes the slide counter going off screen, however it also reduces the size of the clock. Is it possible to control the sizes separately?

**Comment by AndreasBilke** [comment]
I updated the branch. You can now change the timer label with

#timer {
    font-size: 4em;
}

and the slide progress with

#slideProgress {
...
}

The default value for the font is 5em via .informationWidget

**Comment by oskar456** [comment]
Thanks, this works perfectly. I lowered just he `#slideProgress` font size and now everything is on screen.
