### ISSUE TITLE
Fails to open presentation with a .pdfpc file in another directory

### ISSUE THREAD

**Issue by rschroll** [pdfpc/pdfpc#94]
If you try to open a presentation stored in another directory that has a .pdfpc file, pdfpc will fail.  The problem seems to be that it reads the file name from the .pdfpc file and the looks for it relative to the current directory, rather than relative to the .pdfpc file.  This problem was introduced in 5a429bcc.

**Comment by AndreasBilke** [comment]
Did somebody remember why there is a [file] section in the pdfpc file? If I
understand it correctly, you always start pdfpc with a pdf file, then,
pdfpc tries to find the .pdfpc (by appending pdfpc to the basename) and
then reads again the file path for some PDF.

Is there some use case why we need something like this? Could we completely
remove the [file] section from the pdfpc file?

**Comment by rschroll** [comment]
I don't know the historical reasons behind this.  There are many things 
in the code base that seem overengineered.  Perhaps this represents 
long-term plans that were never realized.

That said, this does have an impact right now.  You can launch pdfpc 
with a .pdfpc file directly.  We could get the PDF file name by 
changing the extension back to pdf, but "explicit is better than 
implicit," so having the file name explicitly in the .pdfpc file 
strikes me as a good idea.  You could use this to reference a PDF file 
in another directory.  I'm not sure *why* you would want to do this, 
but it is something we currently support, and I'd be hesitant to remove 
it from a point release.

**Comment by AndreasBilke** [comment]
Okay I forgot that you can launch pdfpc via

$ pdfpc path/something.pdfpc # directly specify the pdfpc file

In this case the bug should be fixed, but actually I am not convinced
that somebody uses this.

Shall I fix the bug or do we remove the possibility to call pdfpc with a
.pdfpc file? For me it is counter intuitive to have some [file] section if
it is not used (and lead to bugs :)).

**Comment by AndreasBilke** [comment]
I suggest to remove the [file] section completely and compute all paths from the path passed via command line.
I see two cases when a user invokes pdfpc
- pdfpc &lt;path&gt;/file.pdf
    - we have the full/relativ path to the pdf. If we cut of the .pdf extension, we can easily find the .pdfpc file and read config instructions from there
   - we don't care about relativ or full paths, because finding the .pdfpc is just a matter of string manipulation
- pdfpc &lt;path&gt;/file.pdfpc
   - again, we find the pdf file via string manipulation

This change is more or less backwards compatible, since (if the user does not modify the pdfpc content) the basename of .pdf/.pdfpc file is always the same, so we find the corresponding part via string manipulation.
The only use case where we broke something is, that a user changes the pdf file name (moving the pdf to another directory) and change this manually in the .pdfpc [file] section.

**Comment by AndreasBilke** [comment]
I removed the [file] section from .pdfpc. This should also work if we apply #96 first.

**Comment by rschroll** [comment]
The string construction of the PDF file name will fail if the PDF file 
doesn't have a .pdf extension.  This is surely not a big concern, and 
likely no one will notice.  But if we eventually decide to support 
another file type, this will become important again.

If we were starting from scratch, I wouldn't miss the [file] section.  
For that matter, I wouldn't miss the ability to launch via the .pdfpc 
file.  But, given that we have it and with a little care we can keep it 
working, I don't really see the advantage in removing it.

But you've been putting more work into the project than I have, so if 
you want it gone, go ahead.

**Comment by AndreasBilke** [comment]
The [file] section is probably one of this over engineered parts in the
code. I think this is more confusing than anything other.

Actually, calling pdfpc with the .pdfpc file is a hidden feature. It is
never mentioned in the documentation nor does any error message could give
hints about it.

We always say "launch via pdfpc <file>.pdf" or error messages keep telling
you about non existent pdf files.

I see this as a code base cleanup. As you mentioned often, the code is not
straight forward in many areas if you just want to show a pdf.

As a suggestion: you can merge your CWD pull request into master, and we
can release v4.0.1.

If we remove the [file] section is a question for the next release :).
