### ISSUE TITLE
Analog clock

### ISSUE THREAD

**Issue by dpthurst** [pdfpc/pdfpc#98]
Would it be possible to have an option for an analog clock? I personally find it much easier to intuitively judge how much time is left with an analog display rather than a digital display.

(I also find displays that show (digital) seconds distracting during a presentation, the constant large movement draws the eye. Analog second hands are less distracting.)

**Comment by AndreasBilke** [comment]
On Sat Nov 07, 2015 at 01:40:01AM -0800, dpthurst wrote:
> Would it be possible to have an option for an analog clock? I personally find it much easier to intuitively judge how much time is left with an analog display rather than a digital display.

Everything(tm) is possible, but I think the space at the bottom for an
analog clock is too small.

> 
> (I also find displays that show (digital) seconds distracting during a presentation, the constant large movement draws the eye. Analog second hands are less distracting.)

So you would not display seconds in general or just if you display the
current time?

**Comment by dpthurst** [comment]
On Sat, Nov 07, 2015 at 01:57:17AM -0800, Andreas Bilke wrote:
> On Sat Nov 07, 2015 at 01:40:01AM -0800, dpthurst wrote:
> > Would it be possible to have an option for an analog clock? I personally find
> it much easier to intuitively judge how much time is left with an analog
> display rather than a digital display.
> 
> Everything(tm) is possible, but I think the space at the bottom for an
> analog clock is too small.

A progress bar would be another option. But I also think it wouldn't
be hard to make room. The clock probably wouldn't fit within the
current strip allocated, but overall there's lots of blank space in
the default view (at least on reasonably simple presentations).

> >
> > (I also find displays that show (digital) seconds distracting during a
> presentation, the constant large movement draws the eye. Analog second hands
> are less distracting.)
> 
> So you would not display seconds in general or just if you display the
> current time?

This is actually an argument for an analog view, where the movement is
less distracting. In a digital view, I would suggest making the
seconds smaller and/or dimmer rather than suppressing them entirely.

--Dylan

**Comment by AndreasBilke** [comment]
Your ideas sounds reasonable. Could you code something and show us your results?

**Comment by dpthurst** [comment]
On Mon, Nov 09, 2015 at 12:31:10AM -0800, Andreas Bilke wrote:
> Your ideas sounds reasonable. Could you code something and show us your
> results?

It will take me a little bit, as I am not familiar with vala, but yes,
I'll try.

--Dylan

**Comment by AndreasBilke** [comment]
Please re-open if you made some progress.
