### ISSUE TITLE
Web page http://pdfpc.github.io/pdfpc contains old informations

### ISSUE THREAD

**Issue by AndreasBilke** [pdfpc/pdfpc#99]
If you enter http://pdfpc.github.io/pdfpc some old information about pdfpc. My guess is, that http://pdfpc.github.io/pdfpc is the project based web page served from the gh-pages branch of our pdfpc repo.

During the v4.0 release, we deleted the gh-branch. Maybe github has some old cached content of it. A quick fix for this behaviour may be to re-create the gh-pages branch and have just a redirect to http://pdfpc.github.io/ 

Actually I don't know what happens if we create a pdfpc/ directory in our pdfpc.github.io repo.

**Comment by AndreasBilke** [comment]
Okay, now I get a HTTP 404. I don't know what happened before, may be my cache tricked me.

**Comment by rschroll** [comment]
I saw the problem back after you pointed it out, and I was just as 
confused as you.  Looks like it was a Github hiccup.
